// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 convert fvar cert).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;

#[test]
fn test_convert_fvar_cert_to_bvar_multiple_fvars() {
    // This test uses two different FVars and converts only one of them.
    // Mutation: id == fvar_id -> true would convert BOTH FVars to BVars

    use crate::cert::ProofCert;

    // Create two different FVars
    let fvar1 = FVarId(100);
    let fvar2 = FVarId(200);

    // Create an App cert: (FVar1 FVar2)
    // The function is FVar1, argument is FVar2
    let app_cert = ProofCert::App {
        fn_cert: Box::new(ProofCert::FVar {
            id: fvar1,
            type_: Box::new(Expr::pi(BinderInfo::Default, Expr::prop(), Expr::prop())),
        }),
        fn_type: Box::new(Expr::pi(BinderInfo::Default, Expr::prop(), Expr::prop())),
        arg_cert: Box::new(ProofCert::FVar {
            id: fvar2,
            type_: Box::new(Expr::prop()),
        }),
        result_type: Box::new(Expr::prop()),
    };

    // Convert only fvar1 to a BVar at depth 0
    let result = convert_fvar_cert_to_bvar(app_cert, fvar1, 0);

    // The fn_cert should be BVar(0), but arg_cert should still be FVar(200)
    match &result {
        ProofCert::App {
            fn_cert, arg_cert, ..
        } => {
            // fn_cert should be converted to BVar
            match fn_cert.as_ref() {
                ProofCert::BVar { idx, .. } => {
                    assert_eq!(*idx, 0, "FVar1 should convert to BVar(0)");
                }
                ProofCert::FVar { id, .. } => {
                    panic!("FVar1 should have been converted, got FVar({})", id.0);
                }
                _ => panic!("Expected BVar or FVar for fn_cert"),
            }

            // arg_cert should NOT be converted (different FVar)
            match arg_cert.as_ref() {
                ProofCert::FVar { id, .. } => {
                    assert_eq!(
                        id.0, 200,
                        "FVar2 should remain as FVar(200), got FVar({})",
                        id.0
                    );
                }
                ProofCert::BVar { idx, .. } => {
                    panic!("FVar2 should NOT have been converted to BVar, got BVar({idx})");
                }
                _ => panic!("Expected FVar or BVar for arg_cert"),
            }
        }
        _ => panic!("Expected App"),
    }
}

// =========================================================================
// Kill: tc.rs:542 - replace + with - or * in convert_fvar_cert_to_bvar (Pi body depth)
// =========================================================================

#[test]
fn test_convert_fvar_cert_pi_body_depth() {
    // Tests that Pi body correctly increments depth by 1
    // Mutation: depth + 1 -> depth - 1 or depth * 1 would break nested conversion

    use crate::cert::ProofCert;

    let fvar = FVarId(42);

    // Create a Pi cert: ∀ (x : Prop). FVar42
    // The FVar42 in the body should become BVar(1) when converting at depth 0
    // Because: under the Pi binder, depth is 1
    let pi_cert = ProofCert::Pi {
        binder_info: BinderInfo::Default,
        arg_type_cert: Box::new(ProofCert::Sort {
            level: Level::zero(),
        }),
        arg_level: Level::succ(Level::zero()),
        body_type_cert: Box::new(ProofCert::FVar {
            id: fvar,
            type_: Box::new(Expr::prop()),
        }),
        body_level: Level::succ(Level::zero()),
    };

    // Convert fvar at depth 0
    // In the body, depth should be 1, so fvar -> BVar(1)
    let result = convert_fvar_cert_to_bvar(pi_cert, fvar, 0);

    match &result {
        ProofCert::Pi { body_type_cert, .. } => {
            match body_type_cert.as_ref() {
                ProofCert::BVar { idx, .. } => {
                    // With correct depth + 1: fvar at body depth 1 -> BVar(1)
                    // With depth - 1: would be depth -1, wrong
                    // With depth * 1: would be depth 0, giving BVar(0)
                    assert_eq!(
                        *idx, 1,
                        "FVar in Pi body should become BVar(1) at depth 1, got BVar({idx})"
                    );
                }
                ProofCert::FVar { id, .. } => {
                    panic!("FVar should have been converted, got FVar({})", id.0);
                }
                _ => panic!("Expected BVar or FVar for body_type_cert"),
            }
        }
        _ => panic!("Expected Pi"),
    }
}

// =========================================================================
// Kill: tc.rs:716, tc.rs:761 - indexed inductive iota reduction tests
// These mutants can only be killed with an indexed inductive (num_indices > 0)
// =========================================================================
