// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 defeq literals).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;

#[test]
fn test_is_def_eq_literals() {
    // Kill mutant at line 867: delete match arm (Expr::from_kind(ExprKind::Lit(l1)), Expr::from_kind(ExprKind::Lit(l2)))
    // Without this arm, Lit falls through to `_ => false`
    use crate::expr::{BigNat, Literal};

    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Same nat literals should be def_eq
    let nat42_a = Expr::from_kind(ExprKind::Lit(Literal::Nat(BigNat::Small(42))));
    let nat42_b = Expr::from_kind(ExprKind::Lit(Literal::Nat(BigNat::Small(42))));
    assert!(
        tc.is_def_eq(&nat42_a, &nat42_b),
        "Lit(42) should be def_eq to Lit(42)"
    );

    // Different nat literals should not be def_eq
    let nat43 = Expr::from_kind(ExprKind::Lit(Literal::Nat(BigNat::Small(43))));
    assert!(
        !tc.is_def_eq(&nat42_a, &nat43),
        "Lit(42) should NOT be def_eq to Lit(43)"
    );

    // Same string literals should be def_eq
    let str_a = Expr::from_kind(ExprKind::Lit(Literal::String(std::sync::Arc::from(
        "hello",
    ))));
    let str_b = Expr::from_kind(ExprKind::Lit(Literal::String(std::sync::Arc::from(
        "hello",
    ))));
    assert!(
        tc.is_def_eq(&str_a, &str_b),
        "Lit(\"hello\") should be def_eq to Lit(\"hello\")"
    );

    // Different string literals should not be def_eq
    let str_c = Expr::from_kind(ExprKind::Lit(Literal::String(std::sync::Arc::from(
        "world",
    ))));
    assert!(
        !tc.is_def_eq(&str_a, &str_c),
        "Lit(\"hello\") should NOT be def_eq to Lit(\"world\")"
    );
}

// =========================================================================
// Kill: tc.rs:42:22, 56:22 - += to -= in LocalContext::push/push_let
// =========================================================================
