// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 local context).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;

#[test]
fn test_local_context_fvarid_increment() {
    // Tests that FVarIds are monotonically increasing
    // Mutation: += to -= would cause IDs to decrease

    let mut ctx = LocalContext::new();

    // Push several bindings and verify IDs are increasing
    let id1 = ctx.push(Name::anon(), Expr::prop(), BinderInfo::Default);
    let id2 = ctx.push(Name::anon(), Expr::prop(), BinderInfo::Default);
    let id3 = ctx.push_let(Name::anon(), Expr::prop(), Expr::prop());

    // IDs should be monotonically increasing
    assert!(id2.0 > id1.0, "id2 should be greater than id1");
    assert!(id3.0 > id2.0, "id3 should be greater than id2");

    // Verify we can look them up
    let _b1 = ctx.get(id1).expect("id1 should be in context");
    let _b2 = ctx.get(id2).expect("id2 should be in context");
    let _b3 = ctx.get(id3).expect("id3 should be in context");

    // With -= mutation, id2.0 would be id1.0 - 1, causing lookup issues
}

// =========================================================================
// Kill: tc.rs:98:33 - + to - in LocalContext::push_with_id
// =========================================================================

#[test]
fn test_local_context_push_with_id_updates_next_id() {
    // Tests that push_with_id correctly updates next_id to avoid collisions
    // Mutation: id.0 + 1 -> id.0 - 1 would cause next_id to underflow

    let mut ctx = LocalContext::new();

    // Push with a specific ID
    ctx.push_with_id(FVarId(100), Name::anon(), Expr::prop(), BinderInfo::Default);

    // Now push a regular binding - should get ID > 100
    let id = ctx.push(Name::anon(), Expr::prop(), BinderInfo::Default);
    assert!(
        id.0 > 100,
        "New ID should be greater than 100, got {}",
        id.0
    );

    // With - mutation, next_id would be 99, causing ID collision
}

#[test]
#[should_panic(expected = "reused popped FVarId")]
fn test_local_context_push_with_id_rejects_reused_popped_id_without_clear() {
    let mut ctx = LocalContext::new();
    let reused = FVarId(7);

    ctx.push_with_id(reused, Name::anon(), Expr::prop(), BinderInfo::Default);
    let popped = ctx.pop().expect("explicit FVar should be present");
    assert_eq!(popped.id, reused);

    ctx.push_with_id(reused, Name::anon(), Expr::type_(), BinderInfo::Default);
}

#[test]
#[should_panic(expected = "reused popped FVarId")]
fn test_local_context_push_let_with_id_rejects_reused_popped_id_without_clear() {
    let mut ctx = LocalContext::new();
    let reused = FVarId(9);

    ctx.push_let_with_id(reused, Name::anon(), Expr::prop(), Expr::type_());
    let popped = ctx
        .pop()
        .expect("explicit let-bound FVar should be present");
    assert_eq!(popped.id, reused);

    ctx.push_let_with_id(reused, Name::anon(), Expr::type_(), Expr::prop());
}

#[test]
fn test_local_context_mut_clears_reuse_history_for_explicit_ids() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);
    let reused = FVarId(11);

    {
        let ctx = tc.local_context_mut();
        ctx.push_with_id(reused, Name::anon(), Expr::prop(), BinderInfo::Default);
        let popped = ctx.pop().expect("explicit FVar should be present");
        assert_eq!(popped.id, reused);
    }

    let ctx = tc.local_context_mut();
    ctx.push_with_id(reused, Name::anon(), Expr::type_(), BinderInfo::Default);
    let decl = ctx
        .get(reused)
        .expect("cache-cleared TypeChecker should allow safe explicit-id reuse");
    assert_eq!(decl.type_, Expr::type_());
}

#[test]
fn test_local_context_mut_clears_reuse_history_for_explicit_let_ids() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);
    let reused = FVarId(12);
    let first_value = Expr::type_();
    let second_value = Expr::prop();

    {
        let ctx = tc.local_context_mut();
        ctx.push_let_with_id(reused, Name::anon(), Expr::prop(), first_value.clone());
        let popped = ctx
            .pop()
            .expect("explicit let-bound FVar should be present");
        assert_eq!(popped.id, reused);
        assert_eq!(popped.value.as_ref(), Some(&first_value));
    }

    let ctx = tc.local_context_mut();
    ctx.push_let_with_id(reused, Name::anon(), Expr::type_(), second_value.clone());
    let decl = ctx
        .get(reused)
        .expect("cache-cleared TypeChecker should allow safe explicit let-id reuse");
    assert_eq!(decl.type_, Expr::type_());
    assert_eq!(decl.value.as_ref(), Some(&second_value));
}

#[test]
fn test_local_context_push_let_with_id_preserves_value_and_next_id() {
    let mut ctx = LocalContext::new();
    let value = Expr::type_();

    ctx.push_let_with_id(FVarId(100), Name::anon(), Expr::prop(), value.clone());

    let decl = ctx
        .get(FVarId(100))
        .expect("push_let_with_id should register the supplied FVarId");
    assert_eq!(decl.value.as_ref(), Some(&value));

    let next = ctx.push(Name::anon(), Expr::prop(), BinderInfo::Default);
    assert!(
        next.0 > 100,
        "next fresh FVarId should advance past an explicit let-binding id, got {}",
        next.0
    );
}

// =========================================================================
// Kill: tc.rs:1035:54, 1040:54 - + to - in lift_expr (Pi body, Let body)
// =========================================================================

#[test]
fn test_local_context_push_let_id_positive() {
    // Tests that push_let generates positive, increasing IDs
    // Mutation: += to -= would cause IDs to become negative/decreasing

    let mut ctx = LocalContext::new();

    // Push only let bindings
    let id1 = ctx.push_let(Name::anon(), Expr::prop(), Expr::prop());
    let id2 = ctx.push_let(Name::anon(), Expr::type_(), Expr::type_());
    let id3 = ctx.push_let(
        Name::anon(),
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::zero()))),
        Expr::type_(),
    );

    // IDs should be reasonable (not wrapped around from underflow)
    // If -= mutation happens: 0 - 1 = u64::MAX in wrapping
    assert!(
        id1.0 < u64::MAX / 2,
        "id1 should be small, got {} (underflow?)",
        id1.0
    );
    assert!(
        id2.0 < u64::MAX / 2,
        "id2 should be small, got {} (underflow?)",
        id2.0
    );
    assert!(
        id3.0 < u64::MAX / 2,
        "id3 should be small, got {} (underflow?)",
        id3.0
    );

    // IDs should be strictly increasing
    assert!(id2.0 > id1.0, "id2 ({}) should be > id1 ({})", id2.0, id1.0);
    assert!(id3.0 > id2.0, "id3 ({}) should be > id2 ({})", id3.0, id2.0);

    // With -= mutation, after first push_let at id=0:
    // next_id becomes 0 - 1 = u64::MAX (wrapping)
    // Second push_let would get id = u64::MAX
    // So id2 would NOT be > id1
}

#[test]
fn test_local_context_lookup_scaling() {
    let _serial = crate::test_utils::serial_test_guard();
    use std::hint::black_box;
    use std::time::Instant;

    fn build_context(size: usize) -> (LocalContext, Vec<FVarId>) {
        let mut ctx = LocalContext::new();
        let mut ids = Vec::with_capacity(size);
        for _ in 0..size {
            let id = ctx.push(Name::anon(), Expr::prop(), BinderInfo::Default);
            ids.push(id);
        }
        (ctx, ids)
    }

    // Sizes selected to check scaling without long test runtime.
    let sizes = [200usize, 2000, 20000];
    let lookups = 100_000usize;
    let mut per_op_ns = Vec::with_capacity(sizes.len());

    for &size in &sizes {
        let (ctx, ids) = build_context(size);
        let start = Instant::now();
        for i in 0..lookups {
            let id = ids[i % ids.len()];
            black_box(ctx.get(id));
        }
        let elapsed = start.elapsed().as_nanos() as f64;
        per_op_ns.push(elapsed / lookups as f64);
    }

    if per_op_ns[0] > 1.0 {
        let ratio = per_op_ns[2] / per_op_ns[0];
        // For O(1) with 100x input, ratio should be ≈1. O(log n) gives ≈2.
        // Threshold 5.0 rejects O(√n) (ratio=10); see #1871.
        assert!(
            ratio < 5.0,
            "LocalContext::get scaling regression: per-op ratio {ratio:.2}x for 100x size \
             (threshold: 5x, O(√n) = 10x). sizes: {sizes:?}, per_op_ns: {per_op_ns:?}"
        );
    }
}

#[test]
fn test_local_context_push_scaling() {
    let _serial = crate::test_utils::serial_test_guard();
    use std::time::Instant;

    let sizes = [200usize, 2000, 20000];
    let mut per_op_ns = Vec::with_capacity(sizes.len());

    for &size in &sizes {
        let mut ctx = LocalContext::new();
        let start = Instant::now();
        for _ in 0..size {
            ctx.push(Name::anon(), Expr::prop(), BinderInfo::Default);
        }
        let elapsed = start.elapsed().as_nanos() as f64;
        per_op_ns.push(elapsed / size as f64);
    }

    if per_op_ns[0] > 1.0 {
        let ratio = per_op_ns[2] / per_op_ns[0];
        // For O(1) with 100x input, ratio should be ≈1. O(log n) gives ≈2.
        // Threshold 5.0 rejects O(√n) (ratio=10); see #1871.
        assert!(
            ratio < 5.0,
            "LocalContext::push scaling regression: per-op ratio {ratio:.2}x for 100x size \
             (threshold: 5x, O(√n) = 10x). sizes: {sizes:?}, per_op_ns: {per_op_ns:?}"
        );
    }
}

// =========================================================================
// Recursor reduction tests with recursive fields
// =========================================================================
