// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 proof irrelevance).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;

#[test]
fn test_try_proof_irrel_eq_both_in_prop() {
    // Kill mutant at line 900: replace && with ||
    // Both types must be in Prop for proof irrelevance

    use crate::env::Declaration;
    let mut env = Environment::new();

    // Add an axiom of type Prop
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("p"),
        level_params: vec![],
        type_: Expr::prop(), // p : Prop
    })
    .unwrap();

    // Add a proof of p
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("proof1"),
        level_params: vec![],
        type_: Expr::const_(Name::from_string("p"), vec![]), // proof1 : p
    })
    .unwrap();

    env.add_decl(Declaration::Axiom {
        name: Name::from_string("proof2"),
        level_params: vec![],
        type_: Expr::const_(Name::from_string("p"), vec![]), // proof2 : p
    })
    .unwrap();

    // Add a term in Type (not Prop)
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("t"),
        level_params: vec![],
        type_: Expr::type_(), // t : Type
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    let proof1 = Expr::const_(Name::from_string("proof1"), vec![]);
    let proof2 = Expr::const_(Name::from_string("proof2"), vec![]);
    let t = Expr::const_(Name::from_string("t"), vec![]);

    // Two proofs of the same proposition SHOULD be proof-irrelevant equal
    // This is the case where both are in Prop
    assert_eq!(
        tc.is_def_eq_proof_irrel(&proof1, &proof2),
        Some(true),
        "Two proofs of same Prop should be proof-irrelevant equal"
    );

    // A proof vs a non-proof term should NOT be proof-irrelevant equal.
    // proof1 : p (a Prop), t : Type. is_prop(p) = true, so we proceed to compare.
    // is_def_eq(p, Type) = false → Some(false).
    assert_eq!(
        tc.is_def_eq_proof_irrel(&proof1, &t),
        Some(false),
        "A proof vs a Type term: types differ so proof irrelevance returns false"
    );
}

#[test]
fn test_is_type_in_prop_sort_universe_check() {
    // Kill mutant at line 947: delete match arm ExprKind::Sort(_) => false
    // Additional test for sort universe checking

    // A Sort is a TYPE, not a proof. is_type_in_prop should return false for Sort.
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Sort(0) = Prop, but Prop itself is not "in Prop" (it's a type universe)
    assert!(
        !tc.is_type_in_prop(&Expr::prop()),
        "Prop (Sort 0) is not in Prop - it IS Prop, not a term in Prop"
    );

    // Type = Sort(1) is also not in Prop
    assert!(
        !tc.is_type_in_prop(&Expr::type_()),
        "Type (Sort 1) is not in Prop"
    );

    // Higher universes also not in Prop
    assert!(
        !tc.is_type_in_prop(&Expr::from_kind(ExprKind::Sort(Level::succ(Level::succ(
            Level::zero()
        ))))),
        "Sort 2 is not in Prop"
    );
}
