// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 rec on).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;
use crate::inductive::RecursorArgOrder;

#[test]
fn test_rec_on_type_structure() {
    // Verify that recOn type has correct structure: {motive} → major → minors → result
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    let nat = Name::from_string("Nat");
    let nat_ref = Expr::const_(nat.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat.clone(),
            type_: Expr::from_kind(ExprKind::Sort(Level::succ(Level::zero()))), // Type 1
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(BinderInfo::Default, nat_ref.clone(), nat_ref.clone()),
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Verify recOn is created
    let rec_on_val = env
        .get_recursor(&Name::from_string("Nat.recOn"))
        .expect("Nat.recOn should exist");

    assert_eq!(rec_on_val.name, Name::from_string("Nat.recOn"));
    assert_eq!(rec_on_val.num_params, 0);
    assert_eq!(rec_on_val.num_motives, 1);
    assert_eq!(rec_on_val.num_minors, 2); // zero and succ

    // Verify type structure: {motive} → major → minor_zero → minor_succ → motive major
    // Count Pi binders
    let mut pi_count = 0;
    let mut ty = &rec_on_val.type_;
    while let ExprKind::Pi(_, _, body) = &ty.kind {
        pi_count += 1;
        ty = body;
    }
    assert_eq!(pi_count, 4); // motive, major, minor_zero, minor_succ

    // Compare with rec type structure
    let rec_val = env
        .get_recursor(&Name::from_string("Nat.rec"))
        .expect("Nat.rec should exist");

    let mut rec_pi_count = 0;
    let mut rec_ty = &rec_val.type_;
    while let ExprKind::Pi(_, _, body) = &rec_ty.kind {
        rec_pi_count += 1;
        rec_ty = body;
    }
    assert_eq!(rec_pi_count, 4); // Both have same number of Pi binders

    // The difference is in argument order, not count
}

#[test]
fn test_rec_on_iota_reduction_zero() {
    // recOn should reduce with the major premise before minors
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    let nat = Name::from_string("Nat");
    let nat_ref = Expr::const_(nat.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::arrow(nat_ref.clone(), nat_ref.clone()),
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    let rec_val = env
        .get_recursor(&Name::from_string("Nat.recOn"))
        .expect("Nat.recOn should exist");
    assert_eq!(
        rec_val.arg_order,
        RecursorArgOrder::MajorAfterMotive,
        "recOn should position major before minors"
    );

    let tc = TypeChecker::new(&env);

    let rec_on = Expr::const_(Name::from_string("Nat.recOn"), vec![Level::zero()]);
    let motive = Expr::lam(BinderInfo::Default, nat_ref.clone(), Expr::prop());
    let zero_case = Expr::const_(Name::from_string("ZeroResult"), vec![]);
    let succ_case = Expr::lam(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::prop(),
            Expr::const_(Name::from_string("SuccResult"), vec![]),
        ),
    );

    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);

    // Order: motive, major, minor_zero, minor_succ
    let app = Expr::app(
        Expr::app(
            Expr::app(Expr::app(rec_on, motive), zero.clone()),
            zero_case.clone(),
        ),
        succ_case,
    );

    let result = tc.whnf(&app);
    assert_eq!(
        result, zero_case,
        "recOn should reduce to zero_case when major = Nat.zero"
    );
}

#[test]
fn test_rec_on_iota_reduction_succ() {
    // recOn must supply an induction hypothesis even with major-before-minors layout
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    let nat = Name::from_string("Nat");
    let nat_ref = Expr::const_(nat.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::arrow(nat_ref.clone(), nat_ref.clone()),
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    let rec_on = Expr::const_(Name::from_string("Nat.recOn"), vec![Level::zero()]);
    let motive = Expr::lam(BinderInfo::Default, nat_ref.clone(), Expr::prop());
    let zero_case = Expr::const_(Name::from_string("ZeroCase"), vec![]);
    // succ_case returns the IH to expose whether it was supplied
    let succ_case = Expr::lam(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::prop(),
            Expr::from_kind(ExprKind::BVar(0)),
        ),
    );

    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let one = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        zero.clone(),
    );

    // Order: motive, major, minor_zero, minor_succ
    let app = Expr::app(
        Expr::app(
            Expr::app(Expr::app(rec_on, motive.clone()), one),
            zero_case.clone(),
        ),
        succ_case,
    );

    let result = tc.whnf(&app);
    assert_eq!(
        result, zero_case,
        "recOn should pass IH and reduce recursive call on Nat.zero"
    );
}

#[test]
fn test_rec_on_exists_for_enum() {
    // Test recOn for a simple enumeration
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    let bool_name = Name::from_string("MyBool");
    let bool_ref = Expr::const_(bool_name.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: bool_name.clone(),
            type_: Expr::from_kind(ExprKind::Sort(Level::succ(Level::zero()))), // Type 1
            constructors: vec![
                Constructor {
                    name: Name::from_string("MyBool.false"),
                    type_: bool_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("MyBool.true"),
                    type_: bool_ref.clone(),
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Verify all three eliminators exist
    assert!(
        env.get_recursor(&Name::from_string("MyBool.rec")).is_some(),
        "MyBool.rec should exist"
    );
    assert!(
        env.get_recursor(&Name::from_string("MyBool.casesOn"))
            .is_some(),
        "MyBool.casesOn should exist"
    );
    assert!(
        env.get_recursor(&Name::from_string("MyBool.recOn"))
            .is_some(),
        "MyBool.recOn should exist"
    );
}

#[test]
fn test_rec_on_parametric_list() {
    // Test recOn for parametric type
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();

    let u = Name::from_string("u");
    let list = Name::from_string("List");

    // List : Type u → Type u
    let list_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
    );

    // List A (with BVar 0 for parameter A)
    let list_a = Expr::app(
        Expr::const_(list.clone(), vec![Level::param(u.clone())]),
        Expr::bvar(0),
    );

    // nil : (A : Type u) → List A
    let nil_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
        list_a.clone(),
    );

    // cons : (A : Type u) → A → List A → List A
    let cons_body = Expr::pi(
        BinderInfo::Default,
        Expr::bvar(0), // A
        Expr::pi(
            BinderInfo::Default,
            Expr::app(
                Expr::const_(list.clone(), vec![Level::param(u.clone())]),
                Expr::bvar(1), // A (now at depth 1)
            ),
            Expr::app(
                Expr::const_(list.clone(), vec![Level::param(u.clone())]),
                Expr::bvar(2), // A (now at depth 2)
            ),
        ),
    );
    let cons_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
        cons_body,
    );

    let decl = InductiveDecl {
        level_params: vec![u.clone()],
        num_params: 1,
        types: vec![InductiveType {
            name: list.clone(),
            type_: list_type,
            constructors: vec![
                Constructor {
                    name: Name::from_string("List.nil"),
                    type_: nil_type,
                },
                Constructor {
                    name: Name::from_string("List.cons"),
                    type_: cons_type,
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Verify recOn is created and has correct structure
    let rec_on_val = env
        .get_recursor(&Name::from_string("List.recOn"))
        .expect("List.recOn should exist");

    assert_eq!(rec_on_val.num_params, 1); // A is a parameter
    assert_eq!(rec_on_val.num_minors, 2); // nil and cons cases
    assert_eq!(rec_on_val.rules.len(), 2);
}

/// D6: Test recOn iota reduction with an indexed inductive type (#1406).
///
/// The `MajorAfterMotive` arg order path for indexed inductives places
/// indices between motive and major, then minors after major. This tests
/// that the index handling in `tc/mod.rs` lines 2899-2902 works correctly
/// for the recOn layout (as opposed to the standard rec layout).
#[test]
fn test_rec_on_indexed_inductive_reduction() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();
    let nat = Name::from_string("Nat");
    let nat_ref = Expr::const_(nat.clone(), vec![]);
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::arrow(nat_ref.clone(), nat_ref.clone()),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    // Fin : Nat → Type, Fin.mk : (n : Nat) → Fin (succ n)
    // Non-fixed index prevents fixedIndicesToParams promotion.
    let fin_name = Name::from_string("Fin");
    let fin_type = Expr::pi(BinderInfo::Default, nat_ref.clone(), Expr::type_());
    let fin_mk_type = Expr::pi(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::app(
            Expr::const_(fin_name.clone(), vec![]),
            Expr::app(
                Expr::const_(Name::from_string("Nat.succ"), vec![]),
                Expr::bvar(0),
            ),
        ),
    );
    let fin_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: fin_name.clone(),
            type_: fin_type,
            constructors: vec![Constructor {
                name: Name::from_string("Fin.mk"),
                type_: fin_mk_type,
            }],
        }],
    };
    env.add_inductive(fin_decl).unwrap();

    // Verify recOn has the MajorAfterMotive order
    let rec_on_val = env
        .get_recursor(&Name::from_string("Fin.recOn"))
        .expect("Fin.recOn should exist");
    assert_eq!(
        rec_on_val.arg_order,
        RecursorArgOrder::MajorAfterMotive,
        "Fin.recOn should use MajorAfterMotive ordering"
    );
    assert_eq!(rec_on_val.num_indices, 1, "Fin has 1 index");
    assert_eq!(rec_on_val.num_params, 0);
    assert_eq!(rec_on_val.num_minors, 1); // only Fin.mk

    let tc = TypeChecker::new(&env);

    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let fin_mk = Expr::const_(Name::from_string("Fin.mk"), vec![]);
    let succ_zero = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        zero.clone(),
    );

    // Fin.mk 0 : Fin (succ 0)
    let major = Expr::app(fin_mk, zero.clone());

    // Fin.recOn : {motive : (n : Nat) → Fin n → Sort u}
    //           → (n : Nat) → (t : Fin n) → ((n : Nat) → motive n (Fin.mk n))
    //           → motive n t
    // Arg order for MajorAfterMotive: motive, index(n), major, minor
    let rec_on = Expr::const_(Name::from_string("Fin.recOn"), vec![Level::zero()]);

    // motive: λ (n : Nat) (_ : Fin n) => Nat
    let motive = Expr::lam(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::app(
                Expr::const_(fin_name.clone(), vec![]),
                Expr::from_kind(ExprKind::BVar(0)),
            ),
            nat_ref.clone(),
        ),
    );

    // minor (mk_case): λ (n : Nat) => Nat.succ n
    let mk_case = Expr::lam(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::app(
            Expr::const_(Name::from_string("Nat.succ"), vec![]),
            Expr::bvar(0),
        ),
    );

    // Build: Fin.recOn motive index(=succ 0) major(=Fin.mk 0) mk_case
    let app = Expr::app(
        Expr::app(Expr::app(Expr::app(rec_on, motive), succ_zero), major),
        mk_case,
    );

    let result = tc.whnf(&app);

    // mk_case applied to 0 should give Nat.succ Nat.zero
    let expected = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        zero.clone(),
    );
    assert!(
        tc.is_def_eq(&result, &expected),
        "D6: Fin.recOn with MajorAfterMotive on indexed inductive must reduce \
         correctly; expected Nat.succ Nat.zero, got: {:?}",
        result
    );
}
