// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 recursor).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;

#[test]
fn test_recursor_type_structure() {
    // Verify that the generated recursor type has correct structure
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    let nat = Name::from_string("Nat");
    let nat_ref = Expr::const_(nat.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::arrow(nat_ref.clone(), nat_ref.clone()),
                },
            ],
        }],
    };
    env.add_inductive(decl).unwrap();

    let rec_val = env.get_recursor(&Name::from_string("Nat.rec")).unwrap();

    // Recursor should have: motive universe param
    assert!(rec_val.level_params.contains(&Name::from_string("u")));

    // Check recursor type is a Pi type
    // Should be: {motive : Nat → Sort u} → ... → (t : Nat) → motive t
    match &rec_val.type_.kind {
        ExprKind::Pi(bi, _, _) => {
            // First parameter should be implicit (motive)
            assert_eq!(bi.info, BinderInfo::Implicit);
        }
        _ => panic!("Recursor type should be a Pi type"),
    }

    // Check metadata
    assert_eq!(rec_val.num_params, 0);
    assert_eq!(rec_val.num_motives, 1);
    assert_eq!(rec_val.num_minors, 2); // zero and succ cases
    assert_eq!(rec_val.num_indices, 0);
}

#[test]
fn test_parametric_recursor_list() {
    // Test recursor for parametric inductive type (List)
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();

    let u = Name::from_string("u");
    let list = Name::from_string("List");

    // List.{u} : Type u → Type u
    let list_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
    );

    // List A (with BVar 0 for parameter A)
    let list_a = Expr::app(
        Expr::const_(list.clone(), vec![Level::param(u.clone())]),
        Expr::bvar(0),
    );

    // nil : (A : Type u) → List A
    let nil_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
        list_a.clone(),
    );

    // cons : (A : Type u) → A → List A → List A
    let cons_body = Expr::pi(
        BinderInfo::Default,
        Expr::bvar(0), // A
        Expr::pi(
            BinderInfo::Default,
            Expr::app(
                Expr::const_(list.clone(), vec![Level::param(u.clone())]),
                Expr::bvar(1), // A (now at depth 1)
            ),
            Expr::app(
                Expr::const_(list.clone(), vec![Level::param(u.clone())]),
                Expr::bvar(2), // A (now at depth 2)
            ),
        ),
    );
    let cons_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone())))),
        cons_body,
    );

    let decl = InductiveDecl {
        level_params: vec![u.clone()],
        num_params: 1, // A is a parameter
        types: vec![InductiveType {
            name: list.clone(),
            type_: list_type,
            constructors: vec![
                Constructor {
                    name: Name::from_string("List.nil"),
                    type_: nil_type,
                },
                Constructor {
                    name: Name::from_string("List.cons"),
                    type_: cons_type,
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Verify both rec and casesOn are created
    let rec_val = env
        .get_recursor(&Name::from_string("List.rec"))
        .expect("List.rec should exist");
    let cases_val = env
        .get_recursor(&Name::from_string("List.casesOn"))
        .expect("List.casesOn should exist");

    // Both should have 1 type parameter
    assert_eq!(rec_val.num_params, 1);
    assert_eq!(cases_val.num_params, 1);

    // Both should have 2 minor premises (nil and cons cases)
    assert_eq!(rec_val.num_minors, 2);
    assert_eq!(cases_val.num_minors, 2);

    // rec should have recursive field marked for cons (the List A argument)
    assert_eq!(rec_val.rules.len(), 2);
    let cons_rule = &rec_val.rules[1]; // cons is second constructor
                                       // cons has 2 fields: the element (A) and the tail (List A)
                                       // The tail (List A) is recursive
    assert_eq!(cons_rule.num_fields, 2);
    assert_eq!(cons_rule.recursive_fields.len(), 2);
    assert!(
        !cons_rule.recursive_fields[0],
        "First field (element) is not recursive"
    );
    assert!(
        cons_rule.recursive_fields[1],
        "Second field (tail) IS recursive"
    );

    // casesOn should have NO recursive fields
    let cases_cons_rule = &cases_val.rules[1];
    assert!(
        cases_cons_rule.recursive_fields.iter().all(|&b| !b),
        "casesOn should have no recursive fields"
    );
}

/// Regression test for #1393/#1394: Eq recursor metadata consistency after init_eq
/// parameter promotion (a from index to rec-parameter).
#[test]
fn test_eq_recursor_metadata_consistency() {
    use crate::inductive::RecursorArgOrder;
    let mut env = Environment::new();
    env.init_eq().expect("init_eq should succeed");

    // Eq.rec: num_params=2 (α, a), num_indices=1 (b), num_motives=1, num_minors=1
    let eq_rec = env
        .get_recursor(&Name::from_string("Eq.rec"))
        .expect("Eq.rec should exist");
    assert_eq!(eq_rec.num_params, 2, "Eq.rec num_params");
    assert_eq!(eq_rec.num_indices, 1, "Eq.rec num_indices");
    assert_eq!(eq_rec.num_motives, 1, "Eq.rec num_motives");
    assert_eq!(eq_rec.num_minors, 1, "Eq.rec num_minors");
    assert!(eq_rec.is_k, "Eq.rec should be K-like");

    // The Eq.refl rule should have num_fields=0 after init_eq promotes `a`
    // to a rec-parameter. Before the fix (#1393), this was stale at 1.
    assert_eq!(eq_rec.rules.len(), 1, "Eq has one constructor (refl)");
    let refl_rule = &eq_rec.rules[0];
    assert_eq!(
        refl_rule.constructor_name,
        Name::from_string("Eq.refl"),
        "rule is for Eq.refl"
    );
    assert_eq!(
        refl_rule.num_fields, 0,
        "Eq.refl has 0 fields from recursor's perspective after parameter promotion"
    );
    assert!(
        refl_rule.recursive_fields.is_empty(),
        "Eq.refl has no recursive fields"
    );

    // Cross-table metadata validation should pass.
    env.validate_recursor_metadata(&Name::from_string("Eq.rec"))
        .expect("Eq.rec metadata should be consistent");

    // Eq.casesOn: same metadata structure
    let eq_cases = env
        .get_recursor(&Name::from_string("Eq.casesOn"))
        .expect("Eq.casesOn should exist");
    assert_eq!(eq_cases.num_params, 2);
    assert_eq!(eq_cases.num_indices, 1);
    assert_eq!(eq_cases.rules[0].num_fields, 0);
    // Eq.casesOn's repaired type is `{α}{a}{motive}{b}(h)(minor) → motive b h`:
    // the major premise `h` (and its index `b`) precede the minor premise, which
    // is Lean 4's `MajorAfterMotive` argument order. The `arg_order` metadata
    // must agree with that type, otherwise iota reduction and match lowering
    // place the minor and major in swapped positions (Track C dependent-elim).
    assert_eq!(
        eq_cases.arg_order,
        RecursorArgOrder::MajorAfterMotive,
        "Eq.casesOn must use MajorAfterMotive arg order to match its repaired type"
    );
    env.validate_recursor_metadata(&Name::from_string("Eq.casesOn"))
        .expect("Eq.casesOn metadata should be consistent");

    // Eq.recOn: same metadata structure
    let eq_rec_on = env
        .get_recursor(&Name::from_string("Eq.recOn"))
        .expect("Eq.recOn should exist");
    assert_eq!(eq_rec_on.num_params, 2);
    assert_eq!(eq_rec_on.num_indices, 1);
    assert_eq!(eq_rec_on.rules[0].num_fields, 0);
    env.validate_recursor_metadata(&Name::from_string("Eq.recOn"))
        .expect("Eq.recOn metadata should be consistent");
}

/// Regression test for #1393: Eq.rec iota reduction should not over-apply fields.
/// With the old code, `Eq.rec motive minor (Eq.refl α a)` would extract `a` as a
/// field and apply `minor a`, but the minor expects 0 field arguments.
#[test]
fn test_eq_rec_iota_no_field_over_application() {
    let mut env = Environment::new();
    env.init_eq().expect("init_eq should succeed");
    let tc = TypeChecker::new(&env);

    // Build: Eq.rec.{1, 1} {Nat} {0} (λ x h => Nat) zero {0} (Eq.refl Nat 0)
    // This should reduce to just 42 (the minor), not `42 0`.
    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);

    let eq_rec = Expr::const_(
        Name::from_string("Eq.rec"),
        vec![Level::succ(Level::zero()), Level::succ(Level::zero())],
    );

    // motive: λ (x : Nat) (h : Eq Nat 0 x) => Nat
    let eq_const = Expr::const_(Name::from_string("Eq"), vec![Level::succ(Level::zero())]);
    let motive = Expr::lam(
        BinderInfo::Default,
        nat.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::app(
                Expr::app(Expr::app(eq_const.clone(), nat.clone()), zero.clone()),
                Expr::bvar(0),
            ),
            nat.clone(),
        ),
    );

    // minor: 42 (represented as Nat.succ^42(Nat.zero), but for simplicity just use zero)
    let minor = zero.clone();

    // major: Eq.refl Nat 0
    let refl = Expr::const_(
        Name::from_string("Eq.refl"),
        vec![Level::succ(Level::zero())],
    );
    let major = Expr::app(Expr::app(refl, nat.clone()), zero.clone());

    // Eq.rec {Nat} {0} {motive} minor {0} major
    let app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_rec, nat.clone()), zero.clone()),
                    motive,
                ),
                minor.clone(),
            ),
            zero.clone(),
        ),
        major,
    );

    let result = tc.whnf(&app);

    // Result should be `minor` (= zero), NOT `minor zero` (= App(zero, zero))
    assert_eq!(
        result, minor,
        "Eq.rec iota reduction should return minor with 0 field applications"
    );
}

/// Regression test for #1394: Eq.casesOn and Eq.recOn should share the same
/// no-over-application behavior as Eq.rec for Eq.refl iota reduction.
#[test]
fn test_eq_cases_on_and_rec_on_iota_no_field_over_application() {
    let mut env = Environment::new();
    env.init_eq().expect("init_eq should succeed");
    let tc = TypeChecker::new(&env);

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let minor = zero.clone();

    // motive: λ (x : Nat) (h : Eq Nat 0 x) => Nat
    let eq_const = Expr::const_(Name::from_string("Eq"), vec![Level::succ(Level::zero())]);
    let motive = Expr::lam(
        BinderInfo::Default,
        nat.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::app(
                Expr::app(Expr::app(eq_const.clone(), nat.clone()), zero.clone()),
                Expr::bvar(0),
            ),
            nat.clone(),
        ),
    );

    let refl = Expr::const_(
        Name::from_string("Eq.refl"),
        vec![Level::succ(Level::zero())],
    );
    let major = Expr::app(Expr::app(refl, nat.clone()), zero.clone());

    let levels = vec![Level::succ(Level::zero()), Level::succ(Level::zero())];

    // Eq.casesOn {Nat} {0} {motive} {0} (Eq.refl Nat 0) minor
    // casesOn ordering follows Lean 4: params → motive → indices → major →
    // minors (RecursorArgOrder::MajorAfterMotive). The major premise `h` and
    // its index `b` therefore precede the minor premise.
    let eq_cases_on = Expr::const_(Name::from_string("Eq.casesOn"), levels.clone());
    let cases_app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_cases_on, nat.clone()), zero.clone()),
                    motive.clone(),
                ),
                zero.clone(),
            ),
            major.clone(),
        ),
        minor.clone(),
    );
    assert_eq!(
        tc.whnf(&cases_app),
        minor,
        "Eq.casesOn should reduce to the minor premise for Eq.refl without applying extra fields"
    );

    // Eq.recOn {Nat} {0} {motive} {0} (Eq.refl Nat 0) minor
    // recOn ordering is params → motive → indices → major → minors.
    let eq_rec_on = Expr::const_(Name::from_string("Eq.recOn"), levels);
    let rec_on_app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_rec_on, nat.clone()), zero.clone()),
                    motive,
                ),
                zero.clone(),
            ),
            major,
        ),
        zero.clone(),
    );
    assert_eq!(
        tc.whnf(&rec_on_app),
        zero,
        "Eq.recOn should reduce to the minor premise for Eq.refl without applying extra fields"
    );
}

/// Regression test for #1394: Eq.ndrec and Eq.ndrecOn must reduce consistently
/// with Eq.rec metadata after fixed-index parameter promotion.
#[test]
fn test_eq_ndrec_and_ndrec_on_reduction_outcomes() {
    let mut env = Environment::new();
    env.init_eq().expect("init_eq should succeed");
    let tc = TypeChecker::new(&env);

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let refl = Expr::const_(
        Name::from_string("Eq.refl"),
        vec![Level::succ(Level::zero())],
    );
    let h = Expr::app(Expr::app(refl, nat.clone()), zero.clone());

    // motive: λ _ : Nat => Nat
    let motive = Expr::lam(BinderInfo::Default, nat.clone(), nat.clone());
    let levels = vec![Level::succ(Level::zero()), Level::succ(Level::zero())];

    // Eq.ndrec {Nat} {0} motive 0 {0} (Eq.refl Nat 0)
    let eq_ndrec = Expr::const_(Name::from_string("Eq.ndrec"), levels.clone());
    let ndrec_app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_ndrec, nat.clone()), zero.clone()),
                    motive.clone(),
                ),
                zero.clone(),
            ),
            zero.clone(),
        ),
        h.clone(),
    );
    assert_eq!(
        tc.whnf(&ndrec_app),
        zero,
        "Eq.ndrec should reduce to the base motive value on Eq.refl"
    );

    // Eq.ndrecOn {Nat} {0} motive {0} (Eq.refl Nat 0) 0
    let eq_ndrec_on = Expr::const_(Name::from_string("Eq.ndrecOn"), levels);
    let ndrec_on_app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_ndrec_on, nat.clone()), zero.clone()),
                    motive,
                ),
                zero.clone(),
            ),
            h,
        ),
        zero.clone(),
    );
    assert_eq!(
        tc.whnf(&ndrec_on_app),
        zero,
        "Eq.ndrecOn should reduce to the base motive value on Eq.refl"
    );
}

// ================================================================
// infer_implicit gap tests
//
// Lean 4's kernel applies `infer_implicit(rec_ty, true)` as a post-processing
// pass on every recursor type (inductive.cpp:767). This walks the Pi chain
// and marks explicit binders as Implicit when their bound variable appears
// in a subsequent Pi domain (strict mode: only in Pi domains, not the result).
//
// clean does NOT implement infer_implicit. These tests document the expected
// Lean 4 behavior so the gap is visible and can be tracked.
// ================================================================

/// Helper: extract binder info sequence from a Pi-chain.
pub(super) fn collect_binder_infos(mut ty: &Expr) -> Vec<BinderInfo> {
    let mut infos = Vec::new();
    loop {
        match &ty.kind {
            ExprKind::Pi(bi, _, body) => {
                infos.push(bi.info);
                ty = body.as_ref();
            }
            _ => return infos,
        }
    }
}

/// Eq.rec binder info matches Lean 4 — init_eq manually overrides {a} and {b} as Implicit.
///
/// Lean 4 Eq.rec type:
///   {α : Sort u} → {a : α} → {motive : (x : α) → @Eq α a x → Sort v} →
///   motive a (Eq.refl α a) → {b : α} → (h : @Eq α a b) → motive b h
///
/// Expected binder info: [Implicit, Implicit, Implicit, Default, Implicit, Default]
///
/// init_eq (core.rs:206-287) manually constructs Eq.rec with correct binder infos,
/// bypassing the need for infer_implicit for this specific recursor.
///
/// Reference: lean4-ref/src/kernel/inductive.cpp:767, core.rs:216 ({a} Implicit), core.rs:260 ({b} Implicit)
#[test]
fn test_eq_rec_binder_info_infer_implicit_gap() {
    let mut env = Environment::new();
    env.init_eq().expect("init_eq");

    let eq_rec_info = env
        .get_const(&Name::from_string("Eq.rec"))
        .expect("Eq.rec should exist");

    let binder_infos = collect_binder_infos(&eq_rec_info.type_);
    assert_eq!(binder_infos.len(), 6, "Eq.rec should have 6 Pi binders");

    // Lean 4 expected behavior (type_checker.cpp, inductive.cpp):
    //   {α : Sort u} → {a : α} → {motive : ...} → (minor : ...) → {b : α} → (h : ...) → ...
    let lean4_expected = vec![
        BinderInfo::Implicit, // {α : Sort u}
        BinderInfo::Implicit, // {a : α}
        BinderInfo::Implicit, // {motive : ...}
        BinderInfo::Default,  // (minor : motive a (Eq.refl α a))
        BinderInfo::Implicit, // {b : α}
        BinderInfo::Default,  // (h : @Eq α a b)
    ];

    // clean's init_eq manually sets {a} and {b} as Implicit, achieving Lean 4
    // parity for Eq.rec without needing infer_implicit. Verified against
    // core.rs:216 ({a : α} = Implicit) and core.rs:260 ({b : α} = Implicit).
    assert_eq!(
        binder_infos, lean4_expected,
        "Eq.rec binder infos should match Lean 4 (init_eq manually sets {{a}},{{b}} Implicit)"
    );
}

/// HEq.rec binder info now matches Lean 4 after infer_implicit implementation.
///
/// Lean 4 HEq.rec type:
///   {α : Sort u} → {a : α} → {motive : {β : Sort u} → (b : β) → @HEq α a β b → Sort v} →
///   motive α a (HEq.refl α a) → {β : Sort u} → {b : β} → (h : @HEq α a β b) → motive β b h
///
/// Expected binder info (from infer_implicit):
///   [Implicit, Implicit, Implicit, Default, Implicit, Implicit, Default]
///
/// Reference: lean4-ref/src/kernel/inductive.cpp:767, lean4-ref/src/kernel/expr.cpp:480-496
/// Fixes: #1454
#[test]
fn test_heq_rec_binder_info_matches_lean4() {
    let mut env = Environment::new();
    env.init_heq().expect("init_heq");

    let heq_rec_info = env
        .get_const(&Name::from_string("HEq.rec"))
        .expect("HEq.rec should exist");

    let binder_infos = collect_binder_infos(&heq_rec_info.type_);
    assert_eq!(binder_infos.len(), 7, "HEq.rec should have 7 Pi binders");

    let lean4_expected = vec![
        BinderInfo::Implicit, // {α : Sort u}
        BinderInfo::Implicit, // {a : α} — infer_implicit
        BinderInfo::Implicit, // {motive : ...}
        BinderInfo::Default,  // (minor : motive α a (HEq.refl α a))
        BinderInfo::Implicit, // {β : Sort u} — infer_implicit
        BinderInfo::Implicit, // {b : β} — infer_implicit
        BinderInfo::Default,  // (h : @HEq α a β b)
    ];

    assert_eq!(
        binder_infos, lean4_expected,
        "HEq.rec binder info should match Lean 4 after infer_implicit"
    );
}
