// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (tests2 structure eta).
//
// Generated by splitting tc/tests2.rs into submodules for maintainability.

use super::*;

/// Test structure eta expansion: Pair.mk p.fst p.snd ≡ p
///
/// Lean 4 supports structure eta: for structure types, `s = S.mk s.1 s.2 ... s.n`
/// holds definitionally. This test verifies clean handles this correctly (#573).
#[test]
fn test_structure_eta_pair() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();
    env.init_nat().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);

    // Define: structure Pair where fst : Nat; snd : Nat
    // As an inductive: Pair : Type with Pair.mk : Nat → Nat → Pair
    let pair_name = Name::from_string("Pair");
    let pair_ref = Expr::const_(pair_name.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: pair_name.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: Expr::pi(
                    BinderInfo::Default,
                    nat.clone(),
                    Expr::pi(BinderInfo::Default, nat.clone(), pair_ref.clone()),
                ),
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Verify Pair is structure-like (single ctor, no indices, not recursive)
    let ind = env.get_inductive(&pair_name).expect("Pair should exist");
    assert_eq!(
        ind.constructor_names.len(),
        1,
        "Pair has single constructor"
    );
    assert_eq!(ind.num_indices, 0, "Pair has no indices");
    assert!(!ind.is_recursive, "Pair is not recursive");

    // Verify projection reduction works
    // Build: (Pair.mk 1 2).0 and (Pair.mk 1 2).1
    let one = Expr::const_(Name::from_string("Nat.succ"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let nat_one = Expr::app(one.clone(), zero.clone());
    let nat_two = Expr::app(one.clone(), nat_one.clone());

    let pair_val = Expr::app(
        Expr::app(
            Expr::const_(Name::from_string("Pair.mk"), vec![]),
            nat_one.clone(),
        ),
        nat_two.clone(),
    );
    let proj0 = Expr::proj(pair_name.clone(), 0, pair_val.clone());
    let proj1 = Expr::proj(pair_name.clone(), 1, pair_val.clone());

    // Reduce projections
    let proj0_whnf = tc.whnf(&proj0);
    let proj1_whnf = tc.whnf(&proj1);

    // proj0 should reduce to 1
    assert!(
        tc.is_def_eq(&proj0_whnf, &nat_one),
        "Pair.mk 1 2 . 0 should equal 1, got {:?}",
        proj0_whnf
    );

    // proj1 should reduce to 2
    assert!(
        tc.is_def_eq(&proj1_whnf, &nat_two),
        "Pair.mk 1 2 . 1 should equal 2, got {:?}",
        proj1_whnf
    );

    // Now test that reconstructed value equals original:
    // Pair.mk (Pair.mk 1 2).0 (Pair.mk 1 2).1 ≡ Pair.mk 1 2
    let reconstructed_val = Expr::app(
        Expr::app(
            Expr::const_(Name::from_string("Pair.mk"), vec![]),
            proj0.clone(),
        ),
        proj1.clone(),
    );

    assert!(
        tc.is_def_eq(&reconstructed_val, &pair_val),
        "Pair.mk (p.0) (p.1) should equal p"
    );
}

/// Test structure eta expansion for nested structures.
///
/// Verifies that structure eta works with structures containing other structures.
#[test]
fn test_structure_eta_nested() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();
    env.init_nat().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);

    // Define: structure Point where x : Nat; y : Nat
    let point_name = Name::from_string("Point");
    let point_ref = Expr::const_(point_name.clone(), vec![]);

    let point_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: point_name.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Point.mk"),
                type_: Expr::pi(
                    BinderInfo::Default,
                    nat.clone(),
                    Expr::pi(BinderInfo::Default, nat.clone(), point_ref.clone()),
                ),
            }],
        }],
    };

    env.add_inductive(point_decl).unwrap();

    // Define: structure Line where start : Point; end_ : Point
    let line_name = Name::from_string("Line");
    let line_ref = Expr::const_(line_name.clone(), vec![]);

    let line_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: line_name.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Line.mk"),
                type_: Expr::pi(
                    BinderInfo::Default,
                    point_ref.clone(),
                    Expr::pi(BinderInfo::Default, point_ref.clone(), line_ref.clone()),
                ),
            }],
        }],
    };

    env.add_inductive(line_decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build concrete values
    let one = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        Expr::const_(Name::from_string("Nat.zero"), vec![]),
    );
    let two = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        one.clone(),
    );

    // Point.mk 1 2
    let point_val = Expr::app(
        Expr::app(
            Expr::const_(Name::from_string("Point.mk"), vec![]),
            one.clone(),
        ),
        two.clone(),
    );

    // Line.mk (Point.mk 1 2) (Point.mk 1 2)
    let line_val = Expr::app(
        Expr::app(
            Expr::const_(Name::from_string("Line.mk"), vec![]),
            point_val.clone(),
        ),
        point_val.clone(),
    );

    // Test Line projection reduction
    let line_start = Expr::proj(line_name.clone(), 0, line_val.clone());
    let line_end = Expr::proj(line_name.clone(), 1, line_val.clone());

    let start_whnf = tc.whnf(&line_start);
    let end_whnf = tc.whnf(&line_end);

    assert!(
        tc.is_def_eq(&start_whnf, &point_val),
        "Line.start should reduce to the Point value"
    );
    assert!(
        tc.is_def_eq(&end_whnf, &point_val),
        "Line.end should reduce to the Point value"
    );

    // Test nested reconstruction
    // Line.mk (line.0) (line.1) ≡ line
    let reconstructed = Expr::app(
        Expr::app(
            Expr::const_(Name::from_string("Line.mk"), vec![]),
            line_start,
        ),
        line_end,
    );

    assert!(
        tc.is_def_eq(&reconstructed, &line_val),
        "Line.mk (l.0) (l.1) should equal l"
    );
}

/// Test that Prop-typed structures are excluded from eta expansion.
///
/// Lean 4 excludes Prop-typed structures from eta to avoid duplicating proof terms.
/// This is Guard 4 in `to_cnstr_when_structure`.
#[test]
fn test_structure_eta_prop_excluded() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define: structure TrueStruct : Prop where val : True
    // First define True : Prop
    let true_name = Name::from_string("True");
    let true_ref = Expr::const_(true_name.clone(), vec![]);

    let true_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: true_name.clone(),
            type_: Expr::prop(),
            constructors: vec![Constructor {
                name: Name::from_string("True.intro"),
                type_: true_ref.clone(),
            }],
        }],
    };

    env.add_inductive(true_decl).unwrap();

    // Define PropStruct : Prop (a structure in Prop)
    let prop_struct_name = Name::from_string("PropStruct");
    let prop_struct_ref = Expr::const_(prop_struct_name.clone(), vec![]);

    let prop_struct_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: prop_struct_name.clone(),
            type_: Expr::prop(),
            constructors: vec![Constructor {
                name: Name::from_string("PropStruct.mk"),
                type_: Expr::pi(
                    BinderInfo::Default,
                    true_ref.clone(),
                    prop_struct_ref.clone(),
                ),
            }],
        }],
    };

    env.add_inductive(prop_struct_decl).unwrap();

    // Verify PropStruct is structure-like
    let ind = env
        .get_inductive(&prop_struct_name)
        .expect("PropStruct should exist");
    assert_eq!(ind.constructor_names.len(), 1, "Single constructor");
    assert_eq!(ind.num_indices, 0, "No indices");
    assert!(!ind.is_recursive, "Not recursive");

    // Verify the type is Prop
    assert!(
        ind.type_.is_prop(),
        "PropStruct should be Prop-typed, got {:?}",
        ind.type_
    );

    // Note: The structure eta exclusion for Prop happens in try_eta_struct
    // based on the type of the type (type_of_type.is_prop()).
    // With proof irrelevance, p = q for any p, q : PropStruct,
    // so eta expansion is unnecessary for correctness.
}
