#!/usr/bin/env bash
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the AArch64 FP16 (binary16, ARMv8.2-FP16) on-chip differential
# proofs/aarch64_fp16_chip.lean from the real Apple Silicon CPU, then
# `clean check` it.
#
# INDEPENDENT ORACLE for proofs/aarch64_fp16.lean (the FP16 family: widen
# f16->f32 / f16->f64 exact, narrow f32->f16 / f64->f16 RNE with overflow->Inf /
# underflow->subnormal/0 / NaN, scalar FADD.h / FMUL.h RNE). Runs each real
# ARMv8.2-FP16 instruction (fcvt h<->s, h<->d via fmov GPR<->h ; fadd/fmul .h) on
# this chip via std::arch::asm! over a rounding-EXERCISING + special grid (narrow
# ties both directions, guard/round/sticky, overflow/underflow/subnormal,
# NaN widen/narrow, signed zero), emits one `<op> <bits_in> [<bits_in>] =
# <chip_out> := rfl` theorem per sampled input against the Clean defs, and
# concatenates the defs ahead of them into a single self-contained file (the
# clean checker is single-file). `clean check` passes IFF every Clean def reduces
# to the chip's actual output. If a theorem FAILS, the Clean DEF is unfaithful:
# fix the def, never the chip.
#
# Requires: Apple Silicon (darwin arm64). macOS has no `timeout` (none needed).
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS_DIR="$REPO/scripts/isa_harness"
DEF="$REPO/proofs/aarch64_fp16.lean"
OUT="$REPO/proofs/aarch64_fp16_chip.lean"
GEN="$(mktemp -t fp16_theorems.XXXXXX.lean)"
CLEAN_BIN="$REPO/target/release/clean"

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "ERROR: the on-chip oracle requires Apple Silicon (arm64); got $(uname -m)" >&2
  exit 1
fi

echo "[1/4] building on-chip FP16 harness..."
( cd "$HARNESS_DIR" && cargo build --release --bin fp16_harness )

echo "[2/4] running real ARMv8.2-FP16 fcvt/fadd/fmul .h on this chip..."
"$HARNESS_DIR/target/release/fp16_harness" "$GEN"

echo "[3/4] assembling self-contained FP16 differential into $OUT ..."
{
  echo "-- Copyright 2026 Andrew Yates"
  echo "-- SPDX-License-Identifier: Apache-2.0"
  echo "--"
  echo "-- ============================================================================"
  echo "--  ON-CHIP FP16 DIFFERENTIAL for the AArch64 binary16 defs (GENERATED)."
  echo "-- ============================================================================"
  echo "--"
  echo "--  Defs from aarch64_fp16.lean + theorems GENERATED by the on-chip FP16"
  echo "--  harness: each \`<op> <bits_in> [<bits_in>] = <chip_out> := rfl\` asserts a"
  echo "--  Clean def reduces to the REAL Apple Silicon (M4) ARMv8.2-FP16 output for"
  echo "--  that bit-pattern input. Self-contained (single-file checker). Regenerate:"
  echo "--  scripts/isa_harness/fp16_regen.sh  (DO NOT edit by hand)."
  echo ""
  awk 'NR==FNR{if($0=="end AArch64FP16") last=FNR; next} FNR<last' "$DEF" "$DEF"
  echo ""
  echo "-- ==== BEGIN GENERATED ON-CHIP FP16 THEOREMS (do not edit by hand) ===="
  echo ""
  grep -E '^theorem h16_' "$GEN"
  echo ""
  echo "end AArch64FP16"
} > "$OUT"
rm -f "$GEN"

echo "[4/4] clean check $OUT ..."
"$CLEAN_BIN" check "$OUT" | tail -3

echo "done."
