#!/usr/bin/env bash
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the AArch64 FP-ARITHMETIC on-chip differential
# proofs/aarch64_fp_arith_chip.lean from the real Apple Silicon CPU, then
# `clean check` it.
#
# This is the INDEPENDENT ORACLE for proofs/aarch64_fp_arith.lean (the RNE
# rounding arithmetic tier: FADD32/FADD64 + FMUL32/FMUL64). It runs each real
# AArch64 fadd/fmul instruction (.s single and .d double) on this chip via
# std::arch::asm! over a CURATED rounding-EXERCISING + special-case grid (ties
# both directions, guard/round/sticky, subnormal/overflow, NaN q/s propagation,
# +-Inf, Inf-Inf, Inf*0, +-0, cancellation x+(-x)), emits one
# `<op> <bits_a> <bits_b> = <chip_result_bits> := rfl` theorem per sampled
# input against the Clean defs, and concatenates the defs ahead of them into a
# single self-contained file (the clean checker is single-file). `clean check`
# passes IFF every Clean def reduces to the chip's actual RNE-rounded output --
# a genuine hardware differential. If a theorem FAILS, the Clean DEF is
# unfaithful: fix the def, never the chip value.
#
# DEFERRED (NOT covered here): FDIV/FSQRT/FCVT and non-RNE rounding modes.
#
# Requires: Apple Silicon (darwin arm64). macOS has no `timeout` (none needed).
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS_DIR="$REPO/scripts/isa_harness"
DEF="$REPO/proofs/aarch64_fp_arith.lean"
OUT="$REPO/proofs/aarch64_fp_arith_chip.lean"
GEN="$(mktemp -t fp_arith_theorems.XXXXXX.lean)"
CLEAN_BIN="$REPO/target/release/clean"

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "ERROR: the on-chip oracle requires Apple Silicon (arm64); got $(uname -m)" >&2
  exit 1
fi

echo "[1/4] building on-chip FP-arith harness..."
( cd "$HARNESS_DIR" && cargo build --release --bin fp_arith_harness )

echo "[2/4] running real AArch64 fadd/fmul on this chip..."
"$HARNESS_DIR/target/release/fp_arith_harness" "$GEN"

echo "[3/4] assembling self-contained FP-arith differential into $OUT ..."
{
  echo "-- Copyright 2026 Andrew Yates"
  echo "-- SPDX-License-Identifier: Apache-2.0"
  echo "--"
  echo "-- ============================================================================"
  echo "--  ON-CHIP FP-ARITH DIFFERENTIAL for the AArch64 FADD/FMUL defs (GENERATED)."
  echo "-- ============================================================================"
  echo "--"
  echo "--  Defs from aarch64_fp_arith.lean + theorems GENERATED by the on-chip FP-arith"
  echo "--  harness: each \`<op> <bits_a> <bits_b> = <chip_result_bits> := rfl\` asserts a"
  echo "--  Clean def reduces to the REAL Apple Silicon fadd/fmul (RNE) output bits for"
  echo "--  that bit-pattern input. Self-contained (single-file checker). Regenerate:"
  echo "--  scripts/isa_harness/fp_arith_regen.sh  (DO NOT edit by hand)."
  echo ""
  # defs body, minus its trailing `end AArch64FPArith`
  awk 'NR==FNR{if($0=="end AArch64FPArith") last=FNR; next} FNR<last' "$DEF" "$DEF"
  echo ""
  echo "-- ==== BEGIN GENERATED ON-CHIP FP-ARITH THEOREMS (do not edit by hand) ===="
  echo ""
  grep -E '^theorem (fa32|fm32|fa64|fm64)_' "$GEN"
  echo ""
  echo "end AArch64FPArith"
} > "$OUT"
rm -f "$GEN"

echo "[4/4] clean check $OUT ..."
"$CLEAN_BIN" check "$OUT" | tail -3

echo "done."
