#!/usr/bin/env bash
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the AArch64 FP-CONVERSION on-chip differential
# proofs/aarch64_fp_cvt_chip.lean from the real Apple Silicon CPU, then
# `clean check` it.
#
# INDEPENDENT ORACLE for proofs/aarch64_fp_cvt.lean (the FCVT family: widen
# f32->f64 exact, narrow f64->f32 RNE, FCVTZS/ZU/NS/NU f->int with
# round-to-zero / round-to-nearest + saturation + NaN->0, SCVTF/UCVTF int->f
# RNE). Runs each real AArch64 conversion instruction (fcvt s<->d, fcvtz*/
# fcvtn* s/d -> w/x, scvtf/ucvtf w/x -> s/d) on this chip via std::arch::asm!
# over a rounding-EXERCISING + saturation + special grid (ties both directions,
# guard/round/sticky, overflow/underflow/subnormal, out-of-range saturation,
# NaN->0, +-Inf, +-0), emits one `<op> <bits_in> = <chip_out> := rfl` theorem
# per sampled input against the Clean defs, and concatenates the defs ahead of
# them into a single self-contained file (the clean checker is single-file).
# `clean check` passes IFF every Clean def reduces to the chip's actual output.
# If a theorem FAILS, the Clean DEF is unfaithful: fix the def, never the chip.
#
# Requires: Apple Silicon (darwin arm64). macOS has no `timeout` (none needed).
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS_DIR="$REPO/scripts/isa_harness"
DEF="$REPO/proofs/aarch64_fp_cvt.lean"
OUT="$REPO/proofs/aarch64_fp_cvt_chip.lean"
GEN="$(mktemp -t fp_cvt_theorems.XXXXXX.lean)"
CLEAN_BIN="$REPO/target/release/clean"

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "ERROR: the on-chip oracle requires Apple Silicon (arm64); got $(uname -m)" >&2
  exit 1
fi

echo "[1/4] building on-chip FP-conversion harness..."
( cd "$HARNESS_DIR" && cargo build --release --bin fp_cvt_harness )

echo "[2/4] running real AArch64 fcvt/fcvtz*/fcvtn*/scvtf/ucvtf on this chip..."
"$HARNESS_DIR/target/release/fp_cvt_harness" "$GEN"

echo "[3/4] assembling self-contained FP-conversion differential into $OUT ..."
{
  echo "-- Copyright 2026 Andrew Yates"
  echo "-- SPDX-License-Identifier: Apache-2.0"
  echo "--"
  echo "-- ============================================================================"
  echo "--  ON-CHIP FP-CONVERSION DIFFERENTIAL for the AArch64 FCVT defs (GENERATED)."
  echo "-- ============================================================================"
  echo "--"
  echo "--  Defs from aarch64_fp_cvt.lean + theorems GENERATED by the on-chip FP-cvt"
  echo "--  harness: each \`<op> <bits_in> = <chip_out> := rfl\` asserts a Clean def"
  echo "--  reduces to the REAL Apple Silicon conversion output for that bit-pattern /"
  echo "--  integer input. Self-contained (single-file checker). Regenerate:"
  echo "--  scripts/isa_harness/fp_cvt_regen.sh  (DO NOT edit by hand)."
  echo ""
  awk 'NR==FNR{if($0=="end AArch64FPCvt") last=FNR; next} FNR<last' "$DEF" "$DEF"
  echo ""
  echo "-- ==== BEGIN GENERATED ON-CHIP FP-CONVERSION THEOREMS (do not edit by hand) ===="
  echo ""
  grep -E '^theorem cv_' "$GEN"
  echo ""
  echo "end AArch64FPCvt"
} > "$OUT"
rm -f "$GEN"

echo "[4/4] clean check $OUT ..."
"$CLEAN_BIN" check "$OUT" | tail -3

echo "done."
