#!/usr/bin/env bash
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the AArch64 FDIV/FSQRT on-chip differential
# proofs/aarch64_fp_divsqrt_chip.lean from the real Apple Silicon CPU, then
# `clean check` it.
#
# INDEPENDENT ORACLE for proofs/aarch64_fp_divsqrt.lean (FDIV via long division +
# sticky + RNE ; FSQRT digit-by-digit + RNE). Runs each real AArch64 fdiv/fsqrt
# instruction (.s single and .d double) on this chip via std::arch::asm! over a
# rounding-EXERCISING + special grid (non-terminating quotients with
# guard/round/sticky, non-perfect-square radicands, +-Inf, +-0, NaN(q/s),
# Inf/Inf->qNaN, 0/0->qNaN, x/0->Inf, negative-sqrt->qNaN, overflow/underflow),
# emits one `<op> <bits> = <chip_out> := rfl` theorem per sampled input against
# the Clean defs, and concatenates the defs ahead of them into a single
# self-contained file. `clean check` passes IFF every Clean def reduces to the
# chip's actual RNE output. If a theorem FAILS, the Clean DEF is unfaithful: fix
# the def, never the chip value.
#
# NOTE: the 64-bit div/sqrt theorems are costly to reduce (the bit-by-bit
# recursors run ~110 / ~58 digit steps on closed BigNats); the f64 grid is a
# curated edge set (the f32 grid carries the dense rounding coverage), mirroring
# the FADD/FMUL chip convention.
#
# Requires: Apple Silicon (darwin arm64). macOS has no `timeout` (none needed).
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS_DIR="$REPO/scripts/isa_harness"
DEF="$REPO/proofs/aarch64_fp_divsqrt.lean"
OUT="$REPO/proofs/aarch64_fp_divsqrt_chip.lean"
GEN="$(mktemp -t fp_divsqrt_theorems.XXXXXX.lean)"
CLEAN_BIN="$REPO/target/release/clean"

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "ERROR: the on-chip oracle requires Apple Silicon (arm64); got $(uname -m)" >&2
  exit 1
fi

echo "[1/4] building on-chip FP-divsqrt harness..."
( cd "$HARNESS_DIR" && cargo build --release --bin fp_cvt_harness )

echo "[2/4] running real AArch64 fdiv/fsqrt on this chip..."
"$HARNESS_DIR/target/release/fp_cvt_harness" "$GEN" --divsqrt

echo "[3/4] assembling self-contained FDIV/FSQRT differential into $OUT ..."
{
  echo "-- Copyright 2026 Andrew Yates"
  echo "-- SPDX-License-Identifier: Apache-2.0"
  echo "--"
  echo "-- ============================================================================"
  echo "--  ON-CHIP FDIV/FSQRT DIFFERENTIAL for the AArch64 div/sqrt defs (GENERATED)."
  echo "-- ============================================================================"
  echo "--"
  echo "--  Defs from aarch64_fp_divsqrt.lean + theorems GENERATED by the on-chip"
  echo "--  harness: each \`<op> <bits> = <chip_out> := rfl\` asserts a Clean def"
  echo "--  reduces to the REAL Apple Silicon fdiv/fsqrt (RNE) output for that"
  echo "--  bit-pattern input. Self-contained (single-file checker). Regenerate:"
  echo "--  scripts/isa_harness/fp_divsqrt_regen.sh  (DO NOT edit by hand)."
  echo ""
  awk 'NR==FNR{if($0=="end AArch64FPDivSqrt") last=FNR; next} FNR<last' "$DEF" "$DEF"
  echo ""
  echo "-- ==== BEGIN GENERATED ON-CHIP FDIV/FSQRT THEOREMS (do not edit by hand) ===="
  echo ""
  grep -E '^theorem (dv32|dv64|sq32|sq64)_' "$GEN"
  echo ""
  echo "end AArch64FPDivSqrt"
} > "$OUT"
rm -f "$GEN"

echo "[4/4] clean check $OUT ..."
"$CLEAN_BIN" check "$OUT" | tail -3

echo "done."
