#!/usr/bin/env bash
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the AArch64 FP on-chip differential proofs/aarch64_fp_chip.lean
# from the real Apple Silicon CPU, then `clean check` it.
#
# This is the INDEPENDENT ORACLE for proofs/aarch64_fp.lean (the NO-ROUNDING FP
# subset: FABS/FNEG, classify, FCMP->NZCV, FMIN/FMAX/FMINNM/FMAXNM, binary32 AND
# binary64). It runs each real AArch64 FP instruction on this chip via
# std::arch::asm! over the IEEE edge grid crossed with itself, emits one
# `<def> <bits_a> [<bits_b>] = <chip_bits_or_bool> := rfl` theorem per sampled
# input against the Clean defs, and concatenates the defs ahead of them into a
# single self-contained file (the clean checker is single-file). `clean check`
# passes IFF every Clean def reduces to the chip's actual output -- a genuine
# hardware differential including the NaN-propagation / sNaN-quieting /
# signed-zero edges. If a theorem FAILS, the Clean DEF is unfaithful: fix the
# def, never the chip value.
#
# DEFERRED (need IEEE-754 rounding, NOT covered here): FADD/FMUL/FDIV/FSQRT/FCVT.
#
# Requires: Apple Silicon (darwin arm64). macOS has no `timeout` (none needed).
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS_DIR="$REPO/scripts/isa_harness"
DEF="$REPO/proofs/aarch64_fp.lean"
OUT="$REPO/proofs/aarch64_fp_chip.lean"
GEN="$(mktemp -t fp_chip_theorems.XXXXXX.lean)"
CLEAN_BIN="$REPO/target/release/clean"

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "ERROR: the on-chip oracle requires Apple Silicon (arm64); got $(uname -m)" >&2
  exit 1
fi

echo "[1/4] building on-chip FP harness..."
( cd "$HARNESS_DIR" && cargo build --release --bin fp_harness )

echo "[2/4] running real AArch64 FP instructions on this chip..."
"$HARNESS_DIR/target/release/fp_harness" "$GEN"

echo "[3/4] assembling self-contained FP differential into $OUT ..."
{
  echo "-- Copyright 2026 Andrew Yates"
  echo "-- SPDX-License-Identifier: Apache-2.0"
  echo "--"
  echo "-- ============================================================================"
  echo "--  ON-CHIP FP DIFFERENTIAL for the AArch64 FP defs (SELF-CONTAINED, GENERATED)."
  echo "-- ============================================================================"
  echo "--"
  echo "--  Defs from aarch64_fp.lean + theorems GENERATED by the on-chip FP harness:"
  echo "--  each \`<def> <bits_a> [<bits_b>] = <chip_bits_or_bool> := rfl\` asserts a"
  echo "--  Clean def reduces to the REAL Apple Silicon FP instruction's output bits"
  echo "--  (or NZCV bool) for that bit-pattern input. Self-contained (single-file"
  echo "--  checker). Regenerate: scripts/isa_harness/fp_regen.sh  (DO NOT edit by hand)."
  echo ""
  # defs body, minus its trailing `end AArch64FP`
  awk 'NR==FNR{if($0=="end AArch64FP") last=FNR; next} FNR<last' "$DEF" "$DEF"
  echo ""
  echo "-- ==== BEGIN GENERATED ON-CHIP FP THEOREMS (do not edit by hand) ===="
  echo ""
  grep -E '^theorem (fpd|fps)_' "$GEN"
  echo ""
  echo "end AArch64FP"
} > "$OUT"
rm -f "$GEN"

echo "[4/4] clean check $OUT ..."
"$CLEAN_BIN" check "$OUT" | tail -3

echo "done."
