#!/usr/bin/env bash
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the AArch64 on-chip differential proofs/aarch64_isa_chip.lean from
# the real Apple Silicon CPU, then `clean check` it.
#
# This is the INDEPENDENT ORACLE for proofs/aarch64_isa.lean: it runs each real
# AArch64 64-bit integer instruction on this chip via std::arch::asm! over the
# deterministic edge/shift sweep + a fixed-seed random spread, emits one
# `<op>Spec a b = <chip_result> := rfl` theorem per sampled input against the
# Clean defs, and concatenates the defs ahead of them into a single self-
# contained file (the clean checker is single-file). `clean check` passes IFF
# every Clean def reduces to the chip's actual output -- a genuine hardware
# differential. If a theorem FAILS, the Clean DEF is unfaithful: fix the def,
# never the chip value.
#
# Requires: Apple Silicon (darwin arm64). macOS has no `timeout` (none needed).
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARNESS_DIR="$REPO/scripts/isa_harness"
DEF="$REPO/proofs/aarch64_isa.lean"
OUT="$REPO/proofs/aarch64_isa_chip.lean"
GEN="$(mktemp -t isa_chip_theorems.XXXXXX.lean)"
CLEAN_BIN="$REPO/target/debug/clean"

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "ERROR: the on-chip oracle requires Apple Silicon (arm64); got $(uname -m)" >&2
  exit 1
fi

echo "[1/4] building on-chip harness..."
( cd "$HARNESS_DIR" && cargo build --release )

echo "[2/4] running real AArch64 instructions on this chip..."
"$HARNESS_DIR/target/release/isa_harness" "$GEN"

echo "[3/4] assembling self-contained differential into $OUT ..."
{
  echo "-- Copyright 2026 Andrew Yates"
  echo "-- SPDX-License-Identifier: Apache-2.0"
  echo "--"
  echo "-- ============================================================================"
  echo "--  ON-CHIP DIFFERENTIAL for the AArch64 ISA defs (SELF-CONTAINED, GENERATED)."
  echo "-- ============================================================================"
  echo "--"
  echo "--  Defs from aarch64_isa.lean + theorems GENERATED by the on-chip harness:"
  echo "--  each \`<op>Spec a b = <chip_result> := rfl\` asserts a Clean def reduces to"
  echo "--  the REAL Apple Silicon instruction's output for that sampled input."
  echo "--  Self-contained because the clean checker is single-file."
  echo "--  Regenerate: scripts/isa_harness/regen.sh   (DO NOT edit by hand)."
  echo ""
  # defs body, minus its trailing `end AArch64`
  awk 'NR==FNR{if($0=="end AArch64") last=FNR; next} FNR<last' "$DEF" "$DEF"
  echo ""
  echo "-- ==== BEGIN GENERATED ON-CHIP THEOREMS (do not edit by hand) ===="
  echo ""
  grep '^theorem chip_' "$GEN"
  echo ""
  echo "end AArch64"
} > "$OUT"
rm -f "$GEN"

echo "[4/4] clean check $OUT ..."
"$CLEAN_BIN" check "$OUT" | tail -3

echo "done."
