// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Generate an Isabelle session `ROOT` file from a capture-chain [`Segment`].
//!
//! The emitted stanza matches the hand-written `zp_lib3*` ROOTs' shape: an
//! auto-generated header comment, a `session "<s>" = "<parent>" +` line, the
//! `options [quick_and_dirty = false, record_proofs = <n>, parallel_limit = 200]`
//! line, a `sessions` import block (derived from the theory qualifiers), and a
//! `theories` block. record_proofs is the segment's own value, so a proofless
//! bake (record_proofs=2) regenerates a proofless ROOT by construction.

use super::spec::Segment;

/// The `sessions` import block for a segment: the unique session qualifiers of
/// its fully-qualified theory names (`HOL-Library.Interval` → `HOL-Library`),
/// in first-appearance order. Theory names without a dot import no cross-session
/// heap and are skipped.
#[must_use]
pub fn import_sessions(seg: &Segment) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for thy in &seg.theories {
        if let Some((session, _rest)) = thy.split_once('.') {
            if !out.iter().any(|s| s == session) {
                out.push(session.to_string());
            }
        }
    }
    out
}

/// The description line for a segment's ROOT stanza.
fn description(seg: &Segment) -> String {
    let base = if seg.record_proofs <= 2 {
        format!(
            "capture-chain proofless heap-bake of {} (record_proofs={}, chained on {}).",
            seg.session, seg.record_proofs, seg.parent
        )
    } else {
        format!(
            "capture-chain segment {} (record_proofs={}, chained on {}).",
            seg.session, seg.record_proofs, seg.parent
        )
    };
    match &seg.note {
        Some(note) if !note.is_empty() => format!("{base} {note}"),
        _ => base,
    }
}

/// Render the full `ROOT` file text for one segment.
#[must_use]
pub fn segment_root_text(seg: &Segment) -> String {
    let sessions_block = import_sessions(seg)
        .iter()
        .map(|s| format!("    \"{s}\""))
        .collect::<Vec<_>>()
        .join("\n");
    let theories_block = seg
        .theories
        .iter()
        .map(|t| format!("    \"{t}\""))
        .collect::<Vec<_>>()
        .join("\n");
    let proofless_note = if seg.record_proofs <= 2 {
        "   record_proofs=2 keeps zproof recording OFF (proofless heap-bake): the theory\n   \
         imports proofless but is baked into the heap so successors never re-elaborate it\n   \
         under recording.\n"
    } else {
        ""
    };
    format!(
        "(* auto-generated by clean mathverse isabelle-capture-chain. DO NOT EDIT BY HAND.\n   \
         Re-elaborates {session}'s theories on the captured heap {parent} under\n   \
         record_proofs={rp} and heap-saves (-b) so the chain never re-elaborates a\n   \
         predecessor. Lib3-lesson checkpointing: one Poly/ML process per segment (RSS\n   \
         resets at each session boundary). See docs/analysis/zproof-v3-backfill.md.\n{proofless_note}*)\n\
         session \"{session}\" = \"{parent}\" +\n  \
         description \"{desc}\"\n  \
         options [quick_and_dirty = false, record_proofs = {rp}, parallel_limit = 200]\n  \
         sessions\n{sessions_block}\n  \
         theories\n{theories_block}\n",
        session = seg.session,
        parent = seg.parent,
        rp = seg.record_proofs,
        desc = description(seg),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn seg(session: &str, parent: &str, rp: u32, theories: &[&str]) -> Segment {
        Segment {
            session: session.to_string(),
            dir: format!("dir_{session}").into(),
            theories: theories.iter().map(|t| (*t).to_string()).collect(),
            parent: parent.to_string(),
            record_proofs: rp,
            note: None,
        }
    }

    #[test]
    fn test_import_sessions_dedup_first_appearance_order() {
        let s = seg(
            "ZP-X",
            "ZP-Base",
            4,
            &[
                "HOL-Library.Float",
                "HOL-Library.Interval",
                "HOL-Analysis.Foo",
            ],
        );
        assert_eq!(import_sessions(&s), vec!["HOL-Library", "HOL-Analysis"]);
    }

    #[test]
    fn test_root_text_matches_handwritten_lib3c2i_shape() {
        // Reproduces scripts/isabelle/zp_lib3_split2_ROOT.lib3c2i's shape: the
        // Interval proofless heap-bake at record_proofs=2.
        let mut s = seg("ZP-Lib3c2i", "ZP-Lib3c2", 2, &["HOL-Library.Interval"]);
        s.note = Some("Interval proofless bake (line-567 by-proof OOMs even serialized).".into());
        let text = segment_root_text(&s);

        assert!(
            text.starts_with(
                "(* auto-generated by clean mathverse isabelle-capture-chain. DO NOT EDIT BY HAND."
            ),
            "has the auto-generated header"
        );
        assert!(
            text.contains("session \"ZP-Lib3c2i\" = \"ZP-Lib3c2\" +"),
            "session line matches: {text}"
        );
        assert!(
            text.contains(
                "options [quick_and_dirty = false, record_proofs = 2, parallel_limit = 200]"
            ),
            "options line matches the hand-written record_proofs=2 shape"
        );
        assert!(
            text.contains("  sessions\n    \"HOL-Library\"\n"),
            "sessions block imports HOL-Library"
        );
        assert!(
            text.contains("  theories\n    \"HOL-Library.Interval\"\n"),
            "theories block lists the qualified theory"
        );
        assert!(
            text.contains("proofless heap-bake"),
            "proofless bake is noted"
        );
        assert!(text.ends_with("    \"HOL-Library.Interval\"\n"));
    }

    #[test]
    fn test_root_text_record_proofs_4_is_not_proofless() {
        let s = seg(
            "ZP-Lib3c2",
            "ZP-Lib3c1",
            4,
            &["HOL-Library.Float", "HOL-Library.Going_To_Filter"],
        );
        let text = segment_root_text(&s);
        assert!(text.contains("record_proofs = 4, parallel_limit = 200"));
        assert!(
            !text.contains("proofless"),
            "record_proofs=4 ROOT is not marked proofless"
        );
        assert!(text.contains("    \"HOL-Library.Float\"\n    \"HOL-Library.Going_To_Filter\"\n"));
    }
}
