// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
//
//! De Bruijn closedness bundle (census-11 drain, Stage 2A).
//!
//! Ports the PROVED closedness bundle from
//! `scratch/aristotle-debruijn-lt/DeBruijnLt.lean` (real `Lt`/`Le` vocabulary)
//! as explicit Clean `value_src` terms:
//!
//!   * `is_closed_at_lam_body` / `is_closed_at_pi_body` — the body-component
//!     inversions (the `_type` companions already live in
//!     `implementation_soundness_admissibility.rs`; the body inversions were
//!     missing and are added here).
//!   * `lift_preserves_closed`          — lift-closedness sublemma (Target 1).
//!   * `instantiate_preserves_closed`   — depth-separated M3 (Target 2), the
//!     long pole gating the `tc_infer_soundness` drain.
//!   * `beta_reduces_preserves_closed`  — closedness under `beta_reduces`
//!     (Target 3); the 10 non-iota arms are unconditional, the iota arm is
//!     conditional on the explicit `hiota` hypothesis.
//!
//! Every term kernel-verifies with an EMPTY (foundational-only) axiom closure:
//! the proofs use only the in-tree `Lt`/`Le` arithmetic lemmas (the Clean
//! equivalent of the Lean mirror's `omega`-bridge) plus the reduction/injection
//! lemmas already registered in `core_spec`. There is no `Nat.lt` in the Clean
//! spec — the custom `Lt`/`Le` inductives ARE the ordering — so the Lean
//! mirror's four `lt_to_nat`/`nat_to_lt`/`le_to_nat`/`nat_to_le` omega bridges
//! collapse to direct use of `nat_lt_le_dichotomy` / `nat_trichotomy` /
//! `lt_add_weaken_right` / `le_sub_zero` / … here.

use std::collections::HashSet;

use crate::spec::definition::SpecDefinition;
use crate::spec::error::SpecError;
use crate::spec::types::{AxiomCategory, ProofStatus};

/// Inline KExpr.rec discriminator: non-Lam -> Nat, Lam -> Empty.
const KEXPR_NOT_LAM_INLINE: &str = concat!(
    "(KExpr.rec (fun (_ : KExpr) => Type) ",
    "(fun (_ : Level) => Nat) ",
    "(fun (_ : Nat) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Empty) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : Name) (_ : ListType Level) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : Type) => Nat) ",
    "(fun (_ : Nat) => Nat))"
);

/// Inline KExpr.rec discriminator: non-Pi -> Nat, Pi -> Empty.
const KEXPR_NOT_PI_INLINE: &str = concat!(
    "(KExpr.rec (fun (_ : KExpr) => Type) ",
    "(fun (_ : Level) => Nat) ",
    "(fun (_ : Nat) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Empty) ",
    "(fun (_ : Name) (_ : ListType Level) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : Type) => Nat) ",
    "(fun (_ : Nat) => Nat))"
);

/// Inline KExpr.rec discriminator: non-Let -> Nat, Let -> Empty.
const KEXPR_NOT_LET_INLINE: &str = concat!(
    "(KExpr.rec (fun (_ : KExpr) => Type) ",
    "(fun (_ : Level) => Nat) ",
    "(fun (_ : Nat) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : Name) (_ : ListType Level) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) (_ : Type) => Empty) ",
    "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : Type) => Nat) ",
    "(fun (_ : Nat) => Nat))"
);

/// Inline KExpr.rec discriminator: non-Proj -> Nat, Proj -> Empty.
const CB_KEXPR_NOT_PROJ: &str = concat!(
    "(KExpr.rec (fun (_ : KExpr) => Type) ",
    "(fun (_ : Level) => Nat) ",
    "(fun (_ : Nat) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : Name) (_ : ListType Level) => Nat) ",
    "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : Type) (_ : Type) (_ : Type) => Nat) ",
    "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : Type) => Empty) ",
    "(fun (_ : Nat) => Nat))"
);

impl crate::spec::Specification {
    pub(super) fn add_closedness_bundle(&mut self) -> Result<(), SpecError> {
        // ================================================================
        // Body-component inversions for is_closed_at (the missing twins of
        // is_closed_at_lam_type / is_closed_at_pi_type in
        // implementation_soundness_admissibility.rs).
        // ================================================================

        // is_closed_at_lam_body: is_closed_at (lam A body) d -> is_closed_at body (succ d).
        self.add_definition(SpecDefinition {
            name: "is_closed_at_lam_body".to_string(),
            type_src: "forall (A : KExpr) (body : KExpr) (d : Nat), is_closed_at (KExpr.lam A body) d -> is_closed_at body (Nat.succ d)".to_string(),
            value_src: Some(format!(concat!(
                "fun (A : KExpr) (body : KExpr) (d : Nat) ",
                "(h : is_closed_at (KExpr.lam A body) d) => ",
                "is_closed_at.rec ",
                "(fun (e : KExpr) (depth : Nat) (_hc : is_closed_at e depth) => ",
                "Eq KExpr e (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(fun (n : Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.sort n) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.sort n) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (i : Nat) (depth : Nat) (_hlt : Lt i depth) ",
                "(eq : Eq KExpr (KExpr.bvar i) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.bvar i) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (f : KExpr) (a : KExpr) (depth : Nat) ",
                "(_hf : is_closed_at f depth) (_ha : is_closed_at a depth) ",
                "(_ihf : Eq KExpr f (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_iha : Eq KExpr a (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.app f a) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.app f a) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.lam A body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.lam A0 body0) (KExpr.lam A body)) => ",
                "Eq.substType KExpr (fun (x : KExpr) => is_closed_at x (Nat.succ depth)) ",
                "body0 body (lam_inj_snd A0 body0 A body eq) hbody0) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.lam A body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.pi A0 body0) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.pi A0 body0) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (n : Name) (us : ListType Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.const n us) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.const n us) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (ty0 : KExpr) (val0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hty0 : is_closed_at ty0 depth) (_hval0 : is_closed_at val0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihty0 : Eq KExpr ty0 (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihval0 : Eq KExpr val0 (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.lam A body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.let_ ty0 val0 body0) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.let_ ty0 val0 body0) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (s : Name) (i : Nat) (sub : KExpr) (depth : Nat) ",
                "(_hsub : is_closed_at sub depth) ",
                "(_ihsub : Eq KExpr sub (KExpr.lam A body) -> is_closed_at body (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.proj s i sub) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.proj s i sub) (KExpr.lam A body) eq Nat.zero)) ",
                "(fun (v : Nat) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.lit v) (KExpr.lam A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lit v) (KExpr.lam A body) eq Nat.zero)) ",
                "(KExpr.lam A body) d h (Eq.refl KExpr (KExpr.lam A body))"
            ), discr = KEXPR_NOT_LAM_INLINE)),
            is_axiom: false,
            description: "Closed lambda terms have closed bodies (at succ depth): invert is_closed_at.lam constructively via is_closed_at.rec + Lam body injectivity (lam_inj_snd). The body twin of is_closed_at_lam_type. DerivedProved, zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at.rec".to_string(),
                "lam_inj_snd".to_string(),
                "Eq.substType".to_string(),
                "Eq.refl".to_string(),
                "KExpr.rec".to_string(),
                "Empty.rec".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // is_closed_at_pi_body: is_closed_at (pi A body) d -> is_closed_at body (succ d).
        self.add_definition(SpecDefinition {
            name: "is_closed_at_pi_body".to_string(),
            type_src: "forall (A : KExpr) (body : KExpr) (d : Nat), is_closed_at (KExpr.pi A body) d -> is_closed_at body (Nat.succ d)".to_string(),
            value_src: Some(format!(concat!(
                "fun (A : KExpr) (body : KExpr) (d : Nat) ",
                "(h : is_closed_at (KExpr.pi A body) d) => ",
                "is_closed_at.rec ",
                "(fun (e : KExpr) (depth : Nat) (_hc : is_closed_at e depth) => ",
                "Eq KExpr e (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(fun (n : Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.sort n) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.sort n) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (i : Nat) (depth : Nat) (_hlt : Lt i depth) ",
                "(eq : Eq KExpr (KExpr.bvar i) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.bvar i) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (f : KExpr) (a : KExpr) (depth : Nat) ",
                "(_hf : is_closed_at f depth) (_ha : is_closed_at a depth) ",
                "(_ihf : Eq KExpr f (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_iha : Eq KExpr a (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.app f a) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.app f a) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.pi A body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.lam A0 body0) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lam A0 body0) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.pi A body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.pi A0 body0) (KExpr.pi A body)) => ",
                "Eq.substType KExpr (fun (x : KExpr) => is_closed_at x (Nat.succ depth)) ",
                "body0 body (pi_inj_snd A0 body0 A body eq) hbody0) ",
                "(fun (n : Name) (us : ListType Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.const n us) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.const n us) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (ty0 : KExpr) (val0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hty0 : is_closed_at ty0 depth) (_hval0 : is_closed_at val0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihty0 : Eq KExpr ty0 (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihval0 : Eq KExpr val0 (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.pi A body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.let_ ty0 val0 body0) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.let_ ty0 val0 body0) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (s : Name) (i : Nat) (sub : KExpr) (depth : Nat) ",
                "(_hsub : is_closed_at sub depth) ",
                "(_ihsub : Eq KExpr sub (KExpr.pi A body) -> is_closed_at body (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.proj s i sub) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.proj s i sub) (KExpr.pi A body) eq Nat.zero)) ",
                "(fun (v : Nat) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.lit v) (KExpr.pi A body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lit v) (KExpr.pi A body) eq Nat.zero)) ",
                "(KExpr.pi A body) d h (Eq.refl KExpr (KExpr.pi A body))"
            ), discr = KEXPR_NOT_PI_INLINE)),
            is_axiom: false,
            description: "Closed Pi terms have closed bodies (at succ depth): invert is_closed_at.pi constructively via is_closed_at.rec + Pi body injectivity (pi_inj_snd). The body twin of is_closed_at_pi_type. DerivedProved, zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at.rec".to_string(),
                "pi_inj_snd".to_string(),
                "Eq.substType".to_string(),
                "Eq.refl".to_string(),
                "KExpr.rec".to_string(),
                "Empty.rec".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // ================================================================
        // let_ component inversions for is_closed_at (the three-field twins of
        // is_closed_at_lam_type / is_closed_at_lam_body, for the genuine let_
        // constructor). Each inverts is_closed_at (let_ ty val body) d via
        // is_closed_at.rec: the six non-let arms are absurd (discharged by the
        // NOT_LET discriminator no-confusion), the matching let_ arm transports
        // the stored component proof along a field-projector injectivity (Eq.cong
        // through an inline KExpr.rec projector, the lam_inj_fst technique).
        // Consumed by beta_reduces_preserves_closed's zeta/let_ty/let_val/let_body
        // arms. Part of the let-promotion surgery (task #28).
        // ================================================================

        // is_closed_at_let_ty: is_closed_at (let_ ty val body) d -> is_closed_at ty d.
        self.add_definition(SpecDefinition {
            name: "is_closed_at_let_ty".to_string(),
            type_src: "forall (ty : KExpr) (val : KExpr) (body : KExpr) (d : Nat), is_closed_at (KExpr.let_ ty val body) d -> is_closed_at ty d".to_string(),
            value_src: Some(format!(concat!(
                "fun (ty : KExpr) (val : KExpr) (body : KExpr) (d : Nat) ",
                "(h : is_closed_at (KExpr.let_ ty val body) d) => ",
                "is_closed_at.rec ",
                "(fun (e : KExpr) (depth : Nat) (_hc : is_closed_at e depth) => ",
                "Eq KExpr e (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(fun (n : Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.sort n) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.sort n) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (i : Nat) (depth : Nat) (_hlt : Lt i depth) ",
                "(eq : Eq KExpr (KExpr.bvar i) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.bvar i) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (f : KExpr) (a : KExpr) (depth : Nat) ",
                "(_hf : is_closed_at f depth) (_ha : is_closed_at a depth) ",
                "(_ihf : Eq KExpr f (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(_iha : Eq KExpr a (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(eq : Eq KExpr (KExpr.app f a) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.app f a) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at ty (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.lam A0 body0) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lam A0 body0) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at ty (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.pi A0 body0) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.pi A0 body0) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (n : Name) (us : ListType Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.const n us) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.const n us) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (ty0 : KExpr) (val0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(hty0 : is_closed_at ty0 depth) (_hval0 : is_closed_at val0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihty0 : Eq KExpr ty0 (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(_ihval0 : Eq KExpr val0 (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at ty (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.let_ ty0 val0 body0) (KExpr.let_ ty val body)) => ",
                "Eq.substType KExpr (fun (x : KExpr) => is_closed_at x depth) ty0 ty ",
                "(Eq.cong KExpr KExpr ",
                "(fun (e : KExpr) => KExpr.rec (fun (_ : KExpr) => KExpr) ",
                "(fun (_ : Level) => ty0) ",
                "(fun (_ : Nat) => ty0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => ty0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => ty0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => ty0) ",
                "(fun (_ : Name) (_ : ListType Level) => ty0) ",
                "(fun (t : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => t) ",
                "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : KExpr) => ty0) ",
                "(fun (_ : Nat) => ty0) ",
                "e) ",
                "(KExpr.let_ ty0 val0 body0) (KExpr.let_ ty val body) eq) ",
                "hty0) ",
                "(fun (s : Name) (i : Nat) (sub : KExpr) (depth : Nat) ",
                "(_hsub : is_closed_at sub depth) ",
                "(_ihsub : Eq KExpr sub (KExpr.let_ ty val body) -> is_closed_at ty depth) ",
                "(eq : Eq KExpr (KExpr.proj s i sub) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.proj s i sub) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (v : Nat) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.lit v) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at ty depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lit v) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(KExpr.let_ ty val body) d h (Eq.refl KExpr (KExpr.let_ ty val body))"
            ), discr = KEXPR_NOT_LET_INLINE)),
            is_axiom: false,
            description: "Closed let_ terms have closed value-type components: invert is_closed_at.let_ constructively via is_closed_at.rec + let_ first-field injectivity. Part of the let-promotion surgery (task #28). DerivedProved, zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at.rec".to_string(),
                "Eq.substType".to_string(),
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
                "KExpr.rec".to_string(),
                "Empty.rec".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // is_closed_at_let_val: is_closed_at (let_ ty val body) d -> is_closed_at val d.
        self.add_definition(SpecDefinition {
            name: "is_closed_at_let_val".to_string(),
            type_src: "forall (ty : KExpr) (val : KExpr) (body : KExpr) (d : Nat), is_closed_at (KExpr.let_ ty val body) d -> is_closed_at val d".to_string(),
            value_src: Some(format!(concat!(
                "fun (ty : KExpr) (val : KExpr) (body : KExpr) (d : Nat) ",
                "(h : is_closed_at (KExpr.let_ ty val body) d) => ",
                "is_closed_at.rec ",
                "(fun (e : KExpr) (depth : Nat) (_hc : is_closed_at e depth) => ",
                "Eq KExpr e (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(fun (n : Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.sort n) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.sort n) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (i : Nat) (depth : Nat) (_hlt : Lt i depth) ",
                "(eq : Eq KExpr (KExpr.bvar i) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.bvar i) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (f : KExpr) (a : KExpr) (depth : Nat) ",
                "(_hf : is_closed_at f depth) (_ha : is_closed_at a depth) ",
                "(_ihf : Eq KExpr f (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(_iha : Eq KExpr a (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(eq : Eq KExpr (KExpr.app f a) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.app f a) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at val (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.lam A0 body0) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lam A0 body0) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at val (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.pi A0 body0) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.pi A0 body0) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (n : Name) (us : ListType Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.const n us) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.const n us) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (ty0 : KExpr) (val0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hty0 : is_closed_at ty0 depth) (hval0 : is_closed_at val0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihty0 : Eq KExpr ty0 (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(_ihval0 : Eq KExpr val0 (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at val (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.let_ ty0 val0 body0) (KExpr.let_ ty val body)) => ",
                "Eq.substType KExpr (fun (x : KExpr) => is_closed_at x depth) val0 val ",
                "(Eq.cong KExpr KExpr ",
                "(fun (e : KExpr) => KExpr.rec (fun (_ : KExpr) => KExpr) ",
                "(fun (_ : Level) => val0) ",
                "(fun (_ : Nat) => val0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => val0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => val0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => val0) ",
                "(fun (_ : Name) (_ : ListType Level) => val0) ",
                "(fun (_ : KExpr) (v : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => v) ",
                "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : KExpr) => val0) ",
                "(fun (_ : Nat) => val0) ",
                "e) ",
                "(KExpr.let_ ty0 val0 body0) (KExpr.let_ ty val body) eq) ",
                "hval0) ",
                "(fun (s : Name) (i : Nat) (sub : KExpr) (depth : Nat) ",
                "(_hsub : is_closed_at sub depth) ",
                "(_ihsub : Eq KExpr sub (KExpr.let_ ty val body) -> is_closed_at val depth) ",
                "(eq : Eq KExpr (KExpr.proj s i sub) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.proj s i sub) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (v : Nat) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.lit v) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at val depth) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lit v) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(KExpr.let_ ty val body) d h (Eq.refl KExpr (KExpr.let_ ty val body))"
            ), discr = KEXPR_NOT_LET_INLINE)),
            is_axiom: false,
            description: "Closed let_ terms have closed values: invert is_closed_at.let_ constructively via is_closed_at.rec + let_ second-field injectivity. Part of the let-promotion surgery (task #28). DerivedProved, zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at.rec".to_string(),
                "Eq.substType".to_string(),
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
                "KExpr.rec".to_string(),
                "Empty.rec".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // is_closed_at_let_body: is_closed_at (let_ ty val body) d -> is_closed_at body (succ d).
        self.add_definition(SpecDefinition {
            name: "is_closed_at_let_body".to_string(),
            type_src: "forall (ty : KExpr) (val : KExpr) (body : KExpr) (d : Nat), is_closed_at (KExpr.let_ ty val body) d -> is_closed_at body (Nat.succ d)".to_string(),
            value_src: Some(format!(concat!(
                "fun (ty : KExpr) (val : KExpr) (body : KExpr) (d : Nat) ",
                "(h : is_closed_at (KExpr.let_ ty val body) d) => ",
                "is_closed_at.rec ",
                "(fun (e : KExpr) (depth : Nat) (_hc : is_closed_at e depth) => ",
                "Eq KExpr e (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(fun (n : Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.sort n) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.sort n) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (i : Nat) (depth : Nat) (_hlt : Lt i depth) ",
                "(eq : Eq KExpr (KExpr.bvar i) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.bvar i) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (f : KExpr) (a : KExpr) (depth : Nat) ",
                "(_hf : is_closed_at f depth) (_ha : is_closed_at a depth) ",
                "(_ihf : Eq KExpr f (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(_iha : Eq KExpr a (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.app f a) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.app f a) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.lam A0 body0) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lam A0 body0) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (A0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hA0 : is_closed_at A0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihA0 : Eq KExpr A0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.pi A0 body0) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.pi A0 body0) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (n : Name) (us : ListType Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.const n us) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.const n us) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (ty0 : KExpr) (val0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hty0 : is_closed_at ty0 depth) (_hval0 : is_closed_at val0 depth) (hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihty0 : Eq KExpr ty0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihval0 : Eq KExpr val0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ (Nat.succ depth))) ",
                "(eq : Eq KExpr (KExpr.let_ ty0 val0 body0) (KExpr.let_ ty val body)) => ",
                "Eq.substType KExpr (fun (x : KExpr) => is_closed_at x (Nat.succ depth)) body0 body ",
                "(Eq.cong KExpr KExpr ",
                "(fun (e : KExpr) => KExpr.rec (fun (_ : KExpr) => KExpr) ",
                "(fun (_ : Level) => body0) ",
                "(fun (_ : Nat) => body0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => body0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => body0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => body0) ",
                "(fun (_ : Name) (_ : ListType Level) => body0) ",
                "(fun (_ : KExpr) (_ : KExpr) (bb : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => bb) ",
                "(fun (_ : Name) (_ : Nat) (_ : KExpr) (_ : KExpr) => body0) ",
                "(fun (_ : Nat) => body0) ",
                "e) ",
                "(KExpr.let_ ty0 val0 body0) (KExpr.let_ ty val body) eq) ",
                "hbody0) ",
                "(fun (s : Name) (i : Nat) (sub : KExpr) (depth : Nat) ",
                "(_hsub : is_closed_at sub depth) ",
                "(_ihsub : Eq KExpr sub (KExpr.let_ ty val body) -> is_closed_at body (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.proj s i sub) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.proj s i sub) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(fun (v : Nat) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.lit v) (KExpr.let_ ty val body)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at body (Nat.succ depth)) ",
                "(Eq.substType KExpr {discr} ",
                "(KExpr.lit v) (KExpr.let_ ty val body) eq Nat.zero)) ",
                "(KExpr.let_ ty val body) d h (Eq.refl KExpr (KExpr.let_ ty val body))"
            ), discr = KEXPR_NOT_LET_INLINE)),
            is_axiom: false,
            description: "Closed let_ terms have closed bodies (at succ depth): invert is_closed_at.let_ constructively via is_closed_at.rec + let_ third-field injectivity. Part of the let-promotion surgery (task #28). DerivedProved, zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at.rec".to_string(),
                "Eq.substType".to_string(),
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
                "KExpr.rec".to_string(),
                "Empty.rec".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // ================================================================
        // Target 1: lift_preserves_closed.
        // Induction on the is_closed_at derivation (is_closed_at.rec); the
        // depth transforms uniformly n -> n + amount. The bvar arm decides
        // i < cutoff (lift keeps i) vs cutoff <= i (lift shifts to i+amount)
        // via nat_lt_le_dichotomy; app/lam/pi/sort/const arms reassemble.
        // ================================================================
        self.add_definition(SpecDefinition {
            name: "lift_preserves_closed".to_string(),
            type_src: concat!(
                "forall (e : KExpr) (n : Nat) (cutoff : Nat) (amount : Nat), ",
                "is_closed_at e n -> is_closed_at (lift_at e cutoff amount) (Nat.add n amount)"
            )
            .to_string(),
            value_src: Some(
                concat!(
                    "fun (e : KExpr) (n : Nat) (cutoff : Nat) (amount : Nat) (h : is_closed_at e n) => ",
                    "is_closed_at.rec ",
                    "(fun (e0 : KExpr) (D : Nat) (_hc : is_closed_at e0 D) => ",
                    "forall (cf : Nat) (am : Nat), is_closed_at (lift_at e0 cf am) (Nat.add D am)) ",
                    // sort
                    "(fun (nn : Level) (D : Nat) => fun (cf : Nat) (am : Nat) => ",
                    "is_closed_at.sort nn (Nat.add D am)) ",
                    // bvar
                    "(fun (i : Nat) (D : Nat) (hlt : Lt i D) => fun (cf : Nat) (am : Nat) => ",
                    "NatLtLeDichotomy.rec i cf ",
                    "(fun (_d : NatLtLeDichotomy i cf) => is_closed_at (lift_at (KExpr.bvar i) cf am) (Nat.add D am)) ",
                    "(fun (hic : Lt i cf) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add D am)) ",
                    "(KExpr.bvar i) (lift_at (KExpr.bvar i) cf am) ",
                    "(Eq.symm KExpr (lift_at (KExpr.bvar i) cf am) (KExpr.bvar i) ",
                    "(lift_at_bvar_lt i cf am hic)) ",
                    "(is_closed_at.bvar i (Nat.add D am) (lt_add_weaken_right i D am hlt))) ",
                    "(fun (hci : Le cf i) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add D am)) ",
                    "(KExpr.bvar (Nat.add i am)) (lift_at (KExpr.bvar i) cf am) ",
                    "(Eq.symm KExpr (lift_at (KExpr.bvar i) cf am) (KExpr.bvar (Nat.add i am)) ",
                    "(lift_at_bvar_geq i cf am (le_sub_zero cf i hci))) ",
                    "(is_closed_at.bvar (Nat.add i am) (Nat.add D am) (lt_add_right_mono i D am hlt))) ",
                    "(nat_lt_le_dichotomy i cf)) ",
                    // app
                    "(fun (f : KExpr) (g : KExpr) (D : Nat) (_hf : is_closed_at f D) (_hg : is_closed_at g D) ",
                    "(ihf : forall (cf : Nat) (am : Nat), is_closed_at (lift_at f cf am) (Nat.add D am)) ",
                    "(ihg : forall (cf : Nat) (am : Nat), is_closed_at (lift_at g cf am) (Nat.add D am)) => ",
                    "fun (cf : Nat) (am : Nat) => ",
                    "is_closed_at.app (lift_at f cf am) (lift_at g cf am) (Nat.add D am) ",
                    "(ihf cf am) (ihg cf am)) ",
                    // lam
                    "(fun (ty : KExpr) (body : KExpr) (D : Nat) (_hty : is_closed_at ty D) (_hbody : is_closed_at body (Nat.succ D)) ",
                    "(ihty : forall (cf : Nat) (am : Nat), is_closed_at (lift_at ty cf am) (Nat.add D am)) ",
                    "(ihbody : forall (cf : Nat) (am : Nat), is_closed_at (lift_at body cf am) (Nat.add (Nat.succ D) am)) => ",
                    "fun (cf : Nat) (am : Nat) => ",
                    "is_closed_at.lam (lift_at ty cf am) (lift_at body (Nat.succ cf) am) (Nat.add D am) ",
                    "(ihty cf am) ",
                    "(Eq.substType Nat (fun (t : Nat) => is_closed_at (lift_at body (Nat.succ cf) am) t) ",
                    "(Nat.add (Nat.succ D) am) (Nat.succ (Nat.add D am)) (nat_succ_add D am) ",
                    "(ihbody (Nat.succ cf) am))) ",
                    // pi
                    "(fun (ty : KExpr) (body : KExpr) (D : Nat) (_hty : is_closed_at ty D) (_hbody : is_closed_at body (Nat.succ D)) ",
                    "(ihty : forall (cf : Nat) (am : Nat), is_closed_at (lift_at ty cf am) (Nat.add D am)) ",
                    "(ihbody : forall (cf : Nat) (am : Nat), is_closed_at (lift_at body cf am) (Nat.add (Nat.succ D) am)) => ",
                    "fun (cf : Nat) (am : Nat) => ",
                    "is_closed_at.pi (lift_at ty cf am) (lift_at body (Nat.succ cf) am) (Nat.add D am) ",
                    "(ihty cf am) ",
                    "(Eq.substType Nat (fun (t : Nat) => is_closed_at (lift_at body (Nat.succ cf) am) t) ",
                    "(Nat.add (Nat.succ D) am) (Nat.succ (Nat.add D am)) (nat_succ_add D am) ",
                    "(ihbody (Nat.succ cf) am))) ",
                    // const
                    "(fun (nm : Name) (us : ListType Level) (D : Nat) => fun (cf : Nat) (am : Nat) => ",
                    "is_closed_at.const nm us (Nat.add D am)) ",
                    // let_
                    "(fun (ty : KExpr) (val : KExpr) (body : KExpr) (D : Nat) (_hty : is_closed_at ty D) (_hval : is_closed_at val D) (_hbody : is_closed_at body (Nat.succ D)) ",
                    "(ihty : forall (cf : Nat) (am : Nat), is_closed_at (lift_at ty cf am) (Nat.add D am)) ",
                    "(ihval : forall (cf : Nat) (am : Nat), is_closed_at (lift_at val cf am) (Nat.add D am)) ",
                    "(ihbody : forall (cf : Nat) (am : Nat), is_closed_at (lift_at body cf am) (Nat.add (Nat.succ D) am)) => ",
                    "fun (cf : Nat) (am : Nat) => ",
                    "is_closed_at.let_ (lift_at ty cf am) (lift_at val cf am) (lift_at body (Nat.succ cf) am) (Nat.add D am) ",
                    "(ihty cf am) ",
                    "(ihval cf am) ",
                    "(Eq.substType Nat (fun (t : Nat) => is_closed_at (lift_at body (Nat.succ cf) am) t) ",
                    "(Nat.add (Nat.succ D) am) (Nat.succ (Nat.add D am)) (nat_succ_add D am) ",
                    "(ihbody (Nat.succ cf) am))) ",
                    // proj: lift_at (proj s i sub) = proj s i (lift_at sub); rebuild via is_closed_at.proj + ihsub.
                    "(fun (s : Name) (i : Nat) (sub : KExpr) (D : Nat) (_hsub : is_closed_at sub D) ",
                    "(ihsub : forall (cf : Nat) (am : Nat), is_closed_at (lift_at sub cf am) (Nat.add D am)) => ",
                    "fun (cf : Nat) (am : Nat) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add D am)) ",
                    "(KExpr.proj s i (lift_at sub cf am)) (lift_at (KExpr.proj s i sub) cf am) ",
                    "(Eq.symm KExpr (lift_at (KExpr.proj s i sub) cf am) (KExpr.proj s i (lift_at sub cf am)) ",
                    "(lift_at_proj s i sub cf am)) ",
                    "(is_closed_at.proj s i (lift_at sub cf am) (Nat.add D am) (ihsub cf am))) ",
                    // lit: lift_at (lit v) = lit v; is_closed_at.lit is depth-agnostic.
                    "(fun (v : Nat) (D : Nat) => fun (cf : Nat) (am : Nat) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add D am)) ",
                    "(KExpr.lit v) (lift_at (KExpr.lit v) cf am) ",
                    "(Eq.symm KExpr (lift_at (KExpr.lit v) cf am) (KExpr.lit v) (lift_at_lit v cf am)) ",
                    "(is_closed_at.lit v (Nat.add D am))) ",
                    "e n h cutoff amount"
                )
                .to_string(),
            ),
            is_axiom: false,
            description: "lift_preserves_closed (DeBruijnLt Target 1): is_closed_at e n -> is_closed_at (lift_at e cutoff amount) (n+amount). DerivedProved via is_closed_at.rec; bvar decides i<cutoff (keep) vs cutoff<=i (shift) via nat_lt_le_dichotomy + lt_add_weaken_right / lt_add_right_mono; lam/pi shift the body depth via nat_succ_add. Zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at".to_string(),
                "is_closed_at.rec".to_string(),
                "is_closed_at.proj".to_string(),
                "is_closed_at.lit".to_string(),
                "lift_at".to_string(),
                "lift_at_proj".to_string(),
                "lift_at_lit".to_string(),
                "NatLtLeDichotomy".to_string(),
                "NatLtLeDichotomy.rec".to_string(),
                "nat_lt_le_dichotomy".to_string(),
                "lift_at_bvar_lt".to_string(),
                "lift_at_bvar_geq".to_string(),
                "lt_add_weaken_right".to_string(),
                "lt_add_right_mono".to_string(),
                "le_sub_zero".to_string(),
                "nat_succ_add".to_string(),
                "Eq.substType".to_string(),
                "Eq.symm".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // ================================================================
        // Target 2: instantiate_preserves_closed (depth-separated M3).
        // Induction on the is_closed_at derivation with an equation-carrying
        // motive (the substitution depth j is decoupled from the closed-value
        // depth d). The bvar arm trichotomizes i vs j; the i==j arm uses
        // lift_preserves_closed; app/lam/pi reassemble (d + succ j reduces to
        // succ (d+j) definitionally).
        // ================================================================
        self.add_definition(SpecDefinition {
            name: "instantiate_preserves_closed".to_string(),
            type_src: concat!(
                "forall (b : KExpr) (a : KExpr) (d : Nat) (j : Nat), ",
                "is_closed_at b (Nat.succ (Nat.add d j)) -> is_closed_at a d -> ",
                "is_closed_at (instantiate_at b a j) (Nat.add d j)"
            )
            .to_string(),
            value_src: Some(
                concat!(
                    "fun (b : KExpr) (a : KExpr) (d : Nat) (j : Nat) ",
                    "(hb : is_closed_at b (Nat.succ (Nat.add d j))) (ha : is_closed_at a d) => ",
                    "is_closed_at.rec ",
                    "(fun (b0 : KExpr) (D : Nat) (_hc : is_closed_at b0 D) => ",
                    "forall (aa : KExpr) (dd : Nat) (jj : Nat), ",
                    "Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> ",
                    "is_closed_at (instantiate_at b0 aa jj) (Nat.add dd jj)) ",
                    // sort
                    "(fun (nn : Level) (D : Nat) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (_heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (_haa : is_closed_at aa dd) => ",
                    "is_closed_at.sort nn (Nat.add dd jj)) ",
                    // bvar
                    "(fun (i : Nat) (D : Nat) (hlt : Lt i D) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (haa : is_closed_at aa dd) => ",
                    "NatTrichotomy.rec i jj ",
                    "(fun (_t : NatTrichotomy i jj) => is_closed_at (instantiate_at (KExpr.bvar i) aa jj) (Nat.add dd jj)) ",
                    // i < jj: instantiate keeps bvar i
                    "(fun (hij : Lt i jj) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add dd jj)) ",
                    "(KExpr.bvar i) (instantiate_at (KExpr.bvar i) aa jj) ",
                    "(Eq.symm KExpr (instantiate_at (KExpr.bvar i) aa jj) (KExpr.bvar i) ",
                    "(Eq.trans KExpr (instantiate_at (KExpr.bvar i) aa jj) (instantiate_bvar_at i jj aa) (KExpr.bvar i) ",
                    "(instantiate_at_bvar i aa jj) ",
                    "(instantiate_bvar_at_below i jj aa (lt_sub_succ i jj hij)))) ",
                    "(is_closed_at.bvar i (Nat.add dd jj) ",
                    "(lt_of_lt_of_le i jj (Nat.add dd jj) hij (le_add_self_right dd jj)))) ",
                    // i == jj: instantiate lifts aa by jj
                    "(fun (heqij : Eq Nat i jj) => ",
                    "Eq.substType Nat (fun (z : Nat) => is_closed_at (instantiate_at (KExpr.bvar z) aa jj) (Nat.add dd jj)) ",
                    "jj i (Eq.symm Nat i jj heqij) ",
                    "(Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add dd jj)) ",
                    "(lift_at aa Nat.zero jj) (instantiate_at (KExpr.bvar jj) aa jj) ",
                    "(Eq.symm KExpr (instantiate_at (KExpr.bvar jj) aa jj) (lift_at aa Nat.zero jj) ",
                    "(Eq.trans KExpr (instantiate_at (KExpr.bvar jj) aa jj) (instantiate_bvar_at jj jj aa) (lift_at aa Nat.zero jj) ",
                    "(instantiate_at_bvar jj aa jj) ",
                    "(instantiate_bvar_at_eq jj aa))) ",
                    "(lift_preserves_closed aa dd Nat.zero jj haa))) ",
                    // i > jj: instantiate decrements to bvar (i-1)
                    "(fun (hgt : Lt jj i) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add dd jj)) ",
                    "(KExpr.bvar (Nat.sub i (Nat.succ Nat.zero))) (instantiate_at (KExpr.bvar i) aa jj) ",
                    "(Eq.symm KExpr (instantiate_at (KExpr.bvar i) aa jj) (KExpr.bvar (Nat.sub i (Nat.succ Nat.zero))) ",
                    "(Eq.trans KExpr (instantiate_at (KExpr.bvar i) aa jj) (instantiate_bvar_at i jj aa) (KExpr.bvar (Nat.sub i (Nat.succ Nat.zero))) ",
                    "(instantiate_at_bvar i aa jj) ",
                    "(instantiate_bvar_at_above i jj aa (le_sub_zero jj i (lt_implies_le jj i hgt)) (lt_sub_succ jj i hgt)))) ",
                    "(is_closed_at.bvar (Nat.sub i (Nat.succ Nat.zero)) (Nat.add dd jj) ",
                    "(lt_of_lt_of_le (Nat.sub i (Nat.succ Nat.zero)) i (Nat.add dd jj) ",
                    "(Eq.substType Nat (fun (t : Nat) => Lt (Nat.sub i (Nat.succ Nat.zero)) t) ",
                    "(Nat.succ (Nat.sub i (Nat.succ Nat.zero))) i (nat_succ_sub1_of_lt jj i hgt) ",
                    "(lt_succ_self (Nat.sub i (Nat.succ Nat.zero)))) ",
                    "(lt_succ_to_le i (Nat.add dd jj) ",
                    "(Eq.substType Nat (fun (t : Nat) => Lt i t) D (Nat.succ (Nat.add dd jj)) heq hlt))))) ",
                    "(nat_trichotomy i jj)) ",
                    // app
                    "(fun (f : KExpr) (g : KExpr) (D : Nat) (_hf : is_closed_at f D) (_hg : is_closed_at g D) ",
                    "(ihf : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at f aa jj) (Nat.add dd jj)) ",
                    "(ihg : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at g aa jj) (Nat.add dd jj)) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (haa : is_closed_at aa dd) => ",
                    "is_closed_at.app (instantiate_at f aa jj) (instantiate_at g aa jj) (Nat.add dd jj) ",
                    "(ihf aa dd jj heq haa) (ihg aa dd jj heq haa)) ",
                    // lam
                    "(fun (ty : KExpr) (body : KExpr) (D : Nat) (_hty : is_closed_at ty D) (_hbody : is_closed_at body (Nat.succ D)) ",
                    "(ihty : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at ty aa jj) (Nat.add dd jj)) ",
                    "(ihbody : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat (Nat.succ D) (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at body aa jj) (Nat.add dd jj)) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (haa : is_closed_at aa dd) => ",
                    "is_closed_at.lam (instantiate_at ty aa jj) (instantiate_at body aa (Nat.succ jj)) (Nat.add dd jj) ",
                    "(ihty aa dd jj heq haa) ",
                    "(ihbody aa dd (Nat.succ jj) (Eq.cong Nat Nat Nat.succ D (Nat.succ (Nat.add dd jj)) heq) haa)) ",
                    // pi
                    "(fun (ty : KExpr) (body : KExpr) (D : Nat) (_hty : is_closed_at ty D) (_hbody : is_closed_at body (Nat.succ D)) ",
                    "(ihty : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at ty aa jj) (Nat.add dd jj)) ",
                    "(ihbody : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat (Nat.succ D) (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at body aa jj) (Nat.add dd jj)) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (haa : is_closed_at aa dd) => ",
                    "is_closed_at.pi (instantiate_at ty aa jj) (instantiate_at body aa (Nat.succ jj)) (Nat.add dd jj) ",
                    "(ihty aa dd jj heq haa) ",
                    "(ihbody aa dd (Nat.succ jj) (Eq.cong Nat Nat Nat.succ D (Nat.succ (Nat.add dd jj)) heq) haa)) ",
                    // const
                    "(fun (nm : Name) (us : ListType Level) (D : Nat) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (_heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (_haa : is_closed_at aa dd) => ",
                    "is_closed_at.const nm us (Nat.add dd jj)) ",
                    // let_
                    "(fun (ty : KExpr) (val : KExpr) (body : KExpr) (D : Nat) (_hty : is_closed_at ty D) (_hval : is_closed_at val D) (_hbody : is_closed_at body (Nat.succ D)) ",
                    "(ihty : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at ty aa jj) (Nat.add dd jj)) ",
                    "(ihval : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at val aa jj) (Nat.add dd jj)) ",
                    "(ihbody : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat (Nat.succ D) (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at body aa jj) (Nat.add dd jj)) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (haa : is_closed_at aa dd) => ",
                    "is_closed_at.let_ (instantiate_at ty aa jj) (instantiate_at val aa jj) (instantiate_at body aa (Nat.succ jj)) (Nat.add dd jj) ",
                    "(ihty aa dd jj heq haa) ",
                    "(ihval aa dd jj heq haa) ",
                    "(ihbody aa dd (Nat.succ jj) (Eq.cong Nat Nat Nat.succ D (Nat.succ (Nat.add dd jj)) heq) haa)) ",
                    // proj: instantiate_at (proj s i sub) = proj s i (instantiate_at sub); rebuild via is_closed_at.proj.
                    "(fun (s : Name) (i : Nat) (sub : KExpr) (D : Nat) (_hsub : is_closed_at sub D) ",
                    "(ihsub : forall (aa : KExpr) (dd : Nat) (jj : Nat), Eq Nat D (Nat.succ (Nat.add dd jj)) -> is_closed_at aa dd -> is_closed_at (instantiate_at sub aa jj) (Nat.add dd jj)) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (haa : is_closed_at aa dd) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add dd jj)) ",
                    "(KExpr.proj s i (instantiate_at sub aa jj)) (instantiate_at (KExpr.proj s i sub) aa jj) ",
                    "(Eq.symm KExpr (instantiate_at (KExpr.proj s i sub) aa jj) (KExpr.proj s i (instantiate_at sub aa jj)) ",
                    "(instantiate_at_proj s i sub aa jj)) ",
                    "(is_closed_at.proj s i (instantiate_at sub aa jj) (Nat.add dd jj) (ihsub aa dd jj heq haa))) ",
                    // lit: instantiate_at (lit v) = lit v; is_closed_at.lit is depth-agnostic.
                    "(fun (v : Nat) (D : Nat) => ",
                    "fun (aa : KExpr) (dd : Nat) (jj : Nat) (_heq : Eq Nat D (Nat.succ (Nat.add dd jj))) (_haa : is_closed_at aa dd) => ",
                    "Eq.substType KExpr (fun (w : KExpr) => is_closed_at w (Nat.add dd jj)) ",
                    "(KExpr.lit v) (instantiate_at (KExpr.lit v) aa jj) ",
                    "(Eq.symm KExpr (instantiate_at (KExpr.lit v) aa jj) (KExpr.lit v) (instantiate_at_lit v aa jj)) ",
                    "(is_closed_at.lit v (Nat.add dd jj))) ",
                    "b (Nat.succ (Nat.add d j)) hb a d j (Eq.refl Nat (Nat.succ (Nat.add d j))) ha"
                )
                .to_string(),
            ),
            is_axiom: false,
            description: "instantiate_preserves_closed (DeBruijnLt Target 2, depth-separated M3): is_closed_at b (succ(d+j)) -> is_closed_at a d -> is_closed_at (instantiate_at b a j) (d+j). The long pole gating the tc_infer_soundness census-11 drain. DerivedProved via is_closed_at.rec with an equation-carrying motive; bvar trichotomizes i vs j (i==j uses lift_preserves_closed); lam/pi rely on d + succ j reducing to succ(d+j). Zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at".to_string(),
                "is_closed_at.rec".to_string(),
                "is_closed_at.proj".to_string(),
                "is_closed_at.lit".to_string(),
                "instantiate_at".to_string(),
                "instantiate_at_proj".to_string(),
                "instantiate_at_lit".to_string(),
                "lift_preserves_closed".to_string(),
                "NatTrichotomy".to_string(),
                "NatTrichotomy.rec".to_string(),
                "nat_trichotomy".to_string(),
                "instantiate_at_bvar".to_string(),
                "instantiate_bvar_at_below".to_string(),
                "instantiate_bvar_at_eq".to_string(),
                "instantiate_bvar_at_above".to_string(),
                "lt_sub_succ".to_string(),
                "lt_of_lt_of_le".to_string(),
                "le_add_self_right".to_string(),
                "le_sub_zero".to_string(),
                "lt_implies_le".to_string(),
                "nat_succ_sub1_of_lt".to_string(),
                "lt_succ_self".to_string(),
                "lt_succ_to_le".to_string(),
                "Eq.substType".to_string(),
                "Eq.symm".to_string(),
                "Eq.trans".to_string(),
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // is_closed_at_proj_sub: is_closed_at (proj s i sub) d -> is_closed_at sub d.
        // Inverts is_closed_at.proj via is_closed_at.rec: the eight non-proj arms are
        // absurd (NOT_PROJ discriminator no-confusion), the proj arm transports the
        // stored sub-closedness along the sub-field projector (the lam_inj_fst technique).
        self.add_definition(SpecDefinition {
            name: "is_closed_at_proj_sub".to_string(),
            type_src: "forall (s : Name) (i : Nat) (sub : KExpr) (d : Nat), is_closed_at (KExpr.proj s i sub) d -> is_closed_at sub d".to_string(),
            value_src: Some(format!(concat!(
                "fun (s : Name) (i : Nat) (sub : KExpr) (d : Nat) ",
                "(h : is_closed_at (KExpr.proj s i sub) d) => ",
                "is_closed_at.rec ",
                "(fun (e : KExpr) (depth : Nat) (_hc : is_closed_at e depth) => ",
                "Eq KExpr e (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(fun (n : Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.sort n) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.sort n) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (i0 : Nat) (depth : Nat) (_hlt : Lt i0 depth) ",
                "(eq : Eq KExpr (KExpr.bvar i0) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.bvar i0) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (f : KExpr) (a : KExpr) (depth : Nat) ",
                "(_hf : is_closed_at f depth) (_ha : is_closed_at a depth) ",
                "(_ihf : Eq KExpr f (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(_iha : Eq KExpr a (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(eq : Eq KExpr (KExpr.app f a) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.app f a) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (A : KExpr) (body : KExpr) (depth : Nat) ",
                "(_hA : is_closed_at A depth) (_hbody : is_closed_at body (Nat.succ depth)) ",
                "(_ihA : Eq KExpr A (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(_ihbody : Eq KExpr body (KExpr.proj s i sub) -> is_closed_at sub (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.lam A body) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.lam A body) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (A : KExpr) (body : KExpr) (depth : Nat) ",
                "(_hA : is_closed_at A depth) (_hbody : is_closed_at body (Nat.succ depth)) ",
                "(_ihA : Eq KExpr A (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(_ihbody : Eq KExpr body (KExpr.proj s i sub) -> is_closed_at sub (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.pi A body) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.pi A body) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (n : Name) (us : ListType Level) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.const n us) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.const n us) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (ty0 : KExpr) (val0 : KExpr) (body0 : KExpr) (depth : Nat) ",
                "(_hty0 : is_closed_at ty0 depth) (_hval0 : is_closed_at val0 depth) (_hbody0 : is_closed_at body0 (Nat.succ depth)) ",
                "(_ihty0 : Eq KExpr ty0 (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(_ihval0 : Eq KExpr val0 (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(_ihbody0 : Eq KExpr body0 (KExpr.proj s i sub) -> is_closed_at sub (Nat.succ depth)) ",
                "(eq : Eq KExpr (KExpr.let_ ty0 val0 body0) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.let_ ty0 val0 body0) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(fun (s0 : Name) (i0 : Nat) (sub0 : KExpr) (depth : Nat) ",
                "(hsub0 : is_closed_at sub0 depth) ",
                "(_ihsub0 : Eq KExpr sub0 (KExpr.proj s i sub) -> is_closed_at sub depth) ",
                "(eq : Eq KExpr (KExpr.proj s0 i0 sub0) (KExpr.proj s i sub)) => ",
                "Eq.substType KExpr (fun (x : KExpr) => is_closed_at x depth) sub0 sub ",
                "(Eq.cong KExpr KExpr ",
                "(fun (e : KExpr) => KExpr.rec (fun (_ : KExpr) => KExpr) ",
                "(fun (_ : Level) => sub0) (fun (_ : Nat) => sub0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => sub0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => sub0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => sub0) ",
                "(fun (_ : Name) (_ : ListType Level) => sub0) ",
                "(fun (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) (_ : KExpr) => sub0) ",
                "(fun (_ : Name) (_ : Nat) (psub : KExpr) (_ : KExpr) => psub) ",
                "(fun (_ : Nat) => sub0) e) ",
                "(KExpr.proj s0 i0 sub0) (KExpr.proj s i sub) eq) ",
                "hsub0) ",
                "(fun (v : Nat) (depth : Nat) ",
                "(eq : Eq KExpr (KExpr.lit v) (KExpr.proj s i sub)) => ",
                "Empty.rec (fun (_ : Empty) => is_closed_at sub depth) ",
                "(Eq.substType KExpr {discr} (KExpr.lit v) (KExpr.proj s i sub) eq Nat.zero)) ",
                "(KExpr.proj s i sub) d h (Eq.refl KExpr (KExpr.proj s i sub))"
            ), discr = CB_KEXPR_NOT_PROJ)),
            is_axiom: false,
            description: "Closed proj terms have closed subexpressions: invert is_closed_at.proj constructively via is_closed_at.rec + proj sub-field injectivity. Part of the proj/lit rung. DerivedProved, zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at.rec".to_string(),
                "Eq.substType".to_string(),
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
                "KExpr.rec".to_string(),
                "Empty.rec".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // ================================================================
        // Target 3: beta_reduces_preserves_closed.
        // Induction on the beta_reduces derivation. The 13 non-iota arms are
        // unconditional (congruence + the helper lemmas; the zeta/let_ arms use
        // the is_closed_at_let_ty/val/body inversions + instantiate_preserves_closed
        // on the zeta redex); the iota arm is discharged by the EXPLICIT hiota
        // hypothesis (Stage 2B supplies it from the_red_env's carried
        // RecEnvClosed / RecEnvLiftClosed facts).
        // ================================================================
        self.add_definition(SpecDefinition {
            name: "beta_reduces_preserves_closed".to_string(),
            type_src: concat!(
                "forall (hiota : forall (e : KExpr) (e' : KExpr) (d : Nat), iota_reduces e e' -> is_closed_at e d -> is_closed_at e' d) ",
                "(e : KExpr) (e' : KExpr), beta_reduces e e' -> ",
                "forall (d : Nat), is_closed_at e d -> is_closed_at e' d"
            )
            .to_string(),
            value_src: Some(
                concat!(
                    "fun (hiota : forall (e : KExpr) (e' : KExpr) (d : Nat), iota_reduces e e' -> is_closed_at e d -> is_closed_at e' d) ",
                    "(e : KExpr) (e' : KExpr) (h : beta_reduces e e') => ",
                    "beta_reduces.rec ",
                    "(fun (e0 : KExpr) (e0' : KExpr) (_hb : beta_reduces e0 e0') => ",
                    "forall (d : Nat), is_closed_at e0 d -> is_closed_at e0' d) ",
                    // beta: (lam A body) arg -> instantiate body arg
                    "(fun (A : KExpr) (body : KExpr) (arg : KExpr) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.app (KExpr.lam A body) arg) d) => ",
                    "instantiate_preserves_closed body arg d Nat.zero ",
                    "(is_closed_at_lam_body A body d (is_closed_at_app_fun (KExpr.lam A body) arg d hc)) ",
                    "(is_closed_at_app_arg (KExpr.lam A body) arg d hc)) ",
                    // app_left
                    "(fun (f : KExpr) (f2 : KExpr) (a : KExpr) (_hr : beta_reduces f f2) ",
                    "(ih : forall (d : Nat), is_closed_at f d -> is_closed_at f2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.app f a) d) => ",
                    "is_closed_at.app f2 a d (ih d (is_closed_at_app_fun f a d hc)) (is_closed_at_app_arg f a d hc)) ",
                    // app_right
                    "(fun (f : KExpr) (a : KExpr) (a2 : KExpr) (_hr : beta_reduces a a2) ",
                    "(ih : forall (d : Nat), is_closed_at a d -> is_closed_at a2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.app f a) d) => ",
                    "is_closed_at.app f a2 d (is_closed_at_app_fun f a d hc) (ih d (is_closed_at_app_arg f a d hc))) ",
                    // lam_ty
                    "(fun (ty : KExpr) (ty2 : KExpr) (body : KExpr) (_hr : beta_reduces ty ty2) ",
                    "(ih : forall (d : Nat), is_closed_at ty d -> is_closed_at ty2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.lam ty body) d) => ",
                    "is_closed_at.lam ty2 body d (ih d (is_closed_at_lam_type ty body d hc)) (is_closed_at_lam_body ty body d hc)) ",
                    // lam_body
                    "(fun (ty : KExpr) (body : KExpr) (body2 : KExpr) (_hr : beta_reduces body body2) ",
                    "(ih : forall (d : Nat), is_closed_at body d -> is_closed_at body2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.lam ty body) d) => ",
                    "is_closed_at.lam ty body2 d (is_closed_at_lam_type ty body d hc) (ih (Nat.succ d) (is_closed_at_lam_body ty body d hc))) ",
                    // pi_dom
                    "(fun (dom : KExpr) (dom2 : KExpr) (body : KExpr) (_hr : beta_reduces dom dom2) ",
                    "(ih : forall (d : Nat), is_closed_at dom d -> is_closed_at dom2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.pi dom body) d) => ",
                    "is_closed_at.pi dom2 body d (ih d (is_closed_at_pi_type dom body d hc)) (is_closed_at_pi_body dom body d hc)) ",
                    // pi_cod
                    "(fun (dom : KExpr) (body : KExpr) (body2 : KExpr) (_hr : beta_reduces body body2) ",
                    "(ih : forall (d : Nat), is_closed_at body d -> is_closed_at body2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.pi dom body) d) => ",
                    "is_closed_at.pi dom body2 d (is_closed_at_pi_type dom body d hc) (ih (Nat.succ d) (is_closed_at_pi_body dom body d hc))) ",
                    // forall_congr_dom (forall_ is the reducible pi alias)
                    "(fun (dom : KExpr) (dom2 : KExpr) (body : KExpr) (_hr : beta_reduces dom dom2) ",
                    "(ih : forall (d : Nat), is_closed_at dom d -> is_closed_at dom2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.forall_ dom body) d) => ",
                    "is_closed_at.pi dom2 body d (ih d (is_closed_at_pi_type dom body d hc)) (is_closed_at_pi_body dom body d hc)) ",
                    // forall_congr_cod
                    "(fun (dom : KExpr) (body : KExpr) (body2 : KExpr) (_hr : beta_reduces body body2) ",
                    "(ih : forall (d : Nat), is_closed_at body d -> is_closed_at body2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.forall_ dom body) d) => ",
                    "is_closed_at.pi dom body2 d (is_closed_at_pi_type dom body d hc) (ih (Nat.succ d) (is_closed_at_pi_body dom body d hc))) ",
                    // zeta: (let_ ty val body) -> instantiate body val (top-level let unfolding).
                    // Same substitution-closedness lemma the beta redex uses: body is
                    // closed at succ d, val is closed at d.
                    "(fun (ty : KExpr) (val : KExpr) (body : KExpr) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.let_ ty val body) d) => ",
                    "instantiate_preserves_closed body val d Nat.zero ",
                    "(is_closed_at_let_body ty val body d hc) ",
                    "(is_closed_at_let_val ty val body d hc)) ",
                    // let_ty: congruence on the let value-type component.
                    "(fun (ty : KExpr) (ty2 : KExpr) (val : KExpr) (body : KExpr) (_hr : beta_reduces ty ty2) ",
                    "(ih : forall (d : Nat), is_closed_at ty d -> is_closed_at ty2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.let_ ty val body) d) => ",
                    "is_closed_at.let_ ty2 val body d ",
                    "(ih d (is_closed_at_let_ty ty val body d hc)) ",
                    "(is_closed_at_let_val ty val body d hc) ",
                    "(is_closed_at_let_body ty val body d hc)) ",
                    // let_val: congruence on the let value component.
                    "(fun (ty : KExpr) (val : KExpr) (val2 : KExpr) (body : KExpr) (_hr : beta_reduces val val2) ",
                    "(ih : forall (d : Nat), is_closed_at val d -> is_closed_at val2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.let_ ty val body) d) => ",
                    "is_closed_at.let_ ty val2 body d ",
                    "(is_closed_at_let_ty ty val body d hc) ",
                    "(ih d (is_closed_at_let_val ty val body d hc)) ",
                    "(is_closed_at_let_body ty val body d hc)) ",
                    // let_body: congruence on the let body component (under one binder).
                    "(fun (ty : KExpr) (val : KExpr) (body : KExpr) (body2 : KExpr) (_hr : beta_reduces body body2) ",
                    "(ih : forall (d : Nat), is_closed_at body d -> is_closed_at body2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.let_ ty val body) d) => ",
                    "is_closed_at.let_ ty val body2 d ",
                    "(is_closed_at_let_ty ty val body d hc) ",
                    "(is_closed_at_let_val ty val body d hc) ",
                    "(ih (Nat.succ d) (is_closed_at_let_body ty val body d hc))) ",
                    // iota
                    "(fun (ee : KExpr) (ee2 : KExpr) (hstep : iota_reduces ee ee2) => ",
                    "fun (d : Nat) (hc : is_closed_at ee d) => hiota ee ee2 d hstep hc) ",
                    // proj: congruence on the sub-expression (invert closedness, recurse, rebuild).
                    "(fun (s : Name) (i : Nat) (sub : KExpr) (sub2 : KExpr) (_hr : beta_reduces sub sub2) ",
                    "(ih : forall (d : Nat), is_closed_at sub d -> is_closed_at sub2 d) => ",
                    "fun (d : Nat) (hc : is_closed_at (KExpr.proj s i sub) d) => ",
                    "is_closed_at.proj s i sub2 d (ih d (is_closed_at_proj_sub s i sub d hc))) ",
                    "e e' h"
                )
                .to_string(),
            ),
            is_axiom: false,
            description: "beta_reduces_preserves_closed (DeBruijnLt Target 3): closedness is preserved by a single beta_reduces step, GIVEN closedness-preservation for the iota substep (the explicit hiota hypothesis). DerivedProved via beta_reduces.rec; the 13 non-iota arms use congruence + is_closed_at_{app,lam,pi}_{fun,arg,type,body} and is_closed_at_let_{ty,val,body} inversions + instantiate_preserves_closed on the beta/zeta redexes; the iota arm defers to hiota. Zero axiom_deps.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "is_closed_at".to_string(),
                "beta_reduces".to_string(),
                "beta_reduces.rec".to_string(),
                "iota_reduces".to_string(),
                "instantiate_preserves_closed".to_string(),
                "is_closed_at_app_fun".to_string(),
                "is_closed_at_app_arg".to_string(),
                "is_closed_at_lam_type".to_string(),
                "is_closed_at_lam_body".to_string(),
                "is_closed_at_pi_type".to_string(),
                "is_closed_at_pi_body".to_string(),
                "is_closed_at_let_ty".to_string(),
                "is_closed_at_let_val".to_string(),
                "is_closed_at_let_body".to_string(),
                "is_closed_at_proj_sub".to_string(),
                "is_closed_at.proj".to_string(),
                "is_closed_at.app".to_string(),
                "is_closed_at.lam".to_string(),
                "is_closed_at.pi".to_string(),
                "is_closed_at.let_".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        Ok(())
    }
}
