// Copyright 2026 Andrew Yates.0
// Author: Andrew Yates <andrewyates.name@gmail.com>
//
//! Substitution-lift interchange: full KExpr.rec proof at arbitrary cutoff.
//!
//! Contains:
//!   - subst_lift_interchange_gen: structural induction over KExpr
//!     proving inst(lift(e, c, sd), w, sd+(c+od)) = lift(inst(e, w, c+od), c, sd).
//!
//! The bvar case delegates to subst_lift_interchange_bvar_gen (DerivedProved in
//! expr_model_subst_lift_interchange_bvar.rs). All cases are fully constructive.

use std::collections::HashSet;

use crate::spec::definition::SpecDefinition;
use crate::spec::error::SpecError;
use crate::spec::types::{AxiomCategory, ProofStatus};
use crate::spec::Specification;

impl Specification {
    pub(super) fn add_expr_model_subst_lift_interchange_gen(&mut self) -> Result<(), SpecError> {
        // subst_lift_interchange_gen: full KExpr.rec proof at arbitrary cutoff.
        //
        // Statement:
        //   inst(lift(e, c, sd), w, add(sd, add(c, od)))
        //   = lift(inst(e, w, add(c, od)), c, sd)
        //
        // Proof by KExpr.rec with motive universalizing w, c, sd, od.
        //   sort: Eq.refl (both sides = sort sv).
        //   bvar: delegates to subst_lift_interchange_bvar_gen.
        //   app: unfold lift_at_app, unfold instantiate_at_app, IH on f and a,
        //        fold back via Eq.symm of lift_at_app and instantiate_at_app.
        //   lam/pi: unfold lift_at_lam/pi + instantiate_at_lam/pi, IH on ty
        //        at (c, sd, od), IH on body at (succ c, sd, od) with arithmetic
        //        transport succ(sd+(c+od)) = sd+(succ(c)+od), fold back.
        // Part of #461, #464.
        self.add_definition_structural(SpecDefinition {
            name: "subst_lift_interchange_gen".to_string(),
            type_src: concat!(
                "forall (e : KExpr) (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                "Eq KExpr ",
                "(instantiate_at (lift_at e c sd) w (Nat.add sd (Nat.add c od))) ",
                "(lift_at (instantiate_at e w (Nat.add c od)) c sd)",
            )
            .to_string(),
            value_src: Some(
                concat!(
                    "fun (e : KExpr) (w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "KExpr.rec ",
                    // motive
                    "(fun (expr : KExpr) => forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr ",
                    "(instantiate_at (lift_at expr c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at expr w (Nat.add c od)) c sd)) ",
                    // ── sort ──
                    "(fun (sv : Level) (w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "Eq.refl KExpr (KExpr.sort sv)) ",
                    // ── bvar ──
                    "(fun (i : Nat) (w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "subst_lift_interchange_bvar_gen i w c sd od) ",
                    // ── app ──
                    "(fun (f : KExpr) (a : KExpr) ",
                    "(ih_f : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at f c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at f w (Nat.add c od)) c sd)) ",
                    "(ih_a : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at a w (Nat.add c od)) c sd)) ",
                    "(w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "Eq.trans KExpr ",
                    "(instantiate_at (lift_at (KExpr.app f a) c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (KExpr.app (lift_at f c sd) (lift_at a c sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at (KExpr.app f a) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => instantiate_at x w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (KExpr.app f a) c sd) ",
                    "(KExpr.app (lift_at f c sd) (lift_at a c sd)) ",
                    "(lift_at_app f a c sd)) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (KExpr.app (lift_at f c sd) (lift_at a c sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(KExpr.app (instantiate_at (lift_at f c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od)))) ",
                    "(lift_at (instantiate_at (KExpr.app f a) w (Nat.add c od)) c sd) ",
                    "(instantiate_at_app (lift_at f c sd) (lift_at a c sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.app (instantiate_at (lift_at f c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od)))) ",
                    "(KExpr.app (lift_at (instantiate_at f w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od)))) ",
                    "(lift_at (instantiate_at (KExpr.app f a) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.app x ",
                    "(instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od)))) ",
                    "(instantiate_at (lift_at f c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at f w (Nat.add c od)) c sd) ",
                    "(ih_f w c sd od)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.app (lift_at (instantiate_at f w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od)))) ",
                    "(KExpr.app (lift_at (instantiate_at f w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at a w (Nat.add c od)) c sd)) ",
                    "(lift_at (instantiate_at (KExpr.app f a) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.app ",
                    "(lift_at (instantiate_at f w (Nat.add c od)) c sd) x) ",
                    "(instantiate_at (lift_at a c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at a w (Nat.add c od)) c sd) ",
                    "(ih_a w c sd od)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.app (lift_at (instantiate_at f w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at a w (Nat.add c od)) c sd)) ",
                    "(lift_at (KExpr.app (instantiate_at f w (Nat.add c od)) ",
                    "(instantiate_at a w (Nat.add c od))) c sd) ",
                    "(lift_at (instantiate_at (KExpr.app f a) w (Nat.add c od)) c sd) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.app (instantiate_at f w (Nat.add c od)) ",
                    "(instantiate_at a w (Nat.add c od))) c sd) ",
                    "(KExpr.app (lift_at (instantiate_at f w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at a w (Nat.add c od)) c sd)) ",
                    "(lift_at_app (instantiate_at f w (Nat.add c od)) ",
                    "(instantiate_at a w (Nat.add c od)) c sd)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x c sd) ",
                    "(KExpr.app (instantiate_at f w (Nat.add c od)) ",
                    "(instantiate_at a w (Nat.add c od))) ",
                    "(instantiate_at (KExpr.app f a) w (Nat.add c od)) ",
                    "(Eq.symm KExpr ",
                    "(instantiate_at (KExpr.app f a) w (Nat.add c od)) ",
                    "(KExpr.app (instantiate_at f w (Nat.add c od)) ",
                    "(instantiate_at a w (Nat.add c od))) ",
                    "(instantiate_at_app f a w (Nat.add c od))))))))) ",
                    // ── lam ──
                    "(fun (ty : KExpr) (body : KExpr) ",
                    "(ih_ty : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd)) ",
                    "(ih_body : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at body c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at body w (Nat.add c od)) c sd)) ",
                    "(w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    // step 1: unfold lift_at_lam inside inst
                    "Eq.trans KExpr ",
                    "(instantiate_at (lift_at (KExpr.lam ty body) c sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (KExpr.lam (lift_at ty c sd) (lift_at body (Nat.succ c) sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at (KExpr.lam ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => instantiate_at x w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (KExpr.lam ty body) c sd) ",
                    "(KExpr.lam (lift_at ty c sd) (lift_at body (Nat.succ c) sd)) ",
                    "(lift_at_lam ty body c sd)) ",
                    // step 2: unfold instantiate_at_lam
                    "(Eq.trans KExpr ",
                    "(instantiate_at (KExpr.lam (lift_at ty c sd) (lift_at body (Nat.succ c) sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(KExpr.lam (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.lam ty body) w (Nat.add c od)) c sd) ",
                    "(instantiate_at_lam (lift_at ty c sd) (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    // step 3: IH on ty
                    "(Eq.trans KExpr ",
                    "(KExpr.lam (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.lam (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.lam ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.lam x ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(ih_ty w c sd od)) ",
                    // step 4: IH on body with arithmetic transport
                    "(Eq.trans KExpr ",
                    "(KExpr.lam (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.lam (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at (instantiate_at (KExpr.lam ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.lam ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd) x) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od)))) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    // body chain: transport LHS depth, IH, transport RHS depth
                    "(Eq.trans KExpr ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od)))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od))) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    // transport succ(sd+(c+od)) → sd+(succ(c)+od)
                    "(Eq.cong Nat KExpr ",
                    "(fun (d : Nat) => instantiate_at (lift_at body (Nat.succ c) sd) w d) ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od)) ",
                    "(Eq.trans Nat ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(Nat.add sd (Nat.succ (Nat.add c od))) ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od)) ",
                    "(Eq.symm Nat (Nat.add sd (Nat.succ (Nat.add c od))) ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(nat_add_succ_right sd (Nat.add c od))) ",
                    "(Eq.cong Nat Nat (fun (x : Nat) => Nat.add sd x) ",
                    "(Nat.succ (Nat.add c od)) (Nat.add (Nat.succ c) od) ",
                    "(Eq.symm Nat (Nat.add (Nat.succ c) od) (Nat.succ (Nat.add c od)) ",
                    "(nat_succ_add c od))))) ",
                    // apply IH, then transport inner depth
                    "(Eq.trans KExpr ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od))) ",
                    "(lift_at (instantiate_at body w (Nat.add (Nat.succ c) od)) (Nat.succ c) sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(ih_body w (Nat.succ c) sd od) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (d : Nat) => lift_at (instantiate_at body w d) (Nat.succ c) sd) ",
                    "(Nat.add (Nat.succ c) od) (Nat.succ (Nat.add c od)) ",
                    "(nat_succ_add c od))))) ",
                    // step 5: fold back via Eq.symm lift_at_lam + inst_at_lam
                    "(Eq.trans KExpr ",
                    "(KExpr.lam (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at (KExpr.lam (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) c sd) ",
                    "(lift_at (instantiate_at (KExpr.lam ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.lam (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) c sd) ",
                    "(KExpr.lam (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at_lam (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od))) c sd)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x c sd) ",
                    "(KExpr.lam (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) ",
                    "(instantiate_at (KExpr.lam ty body) w (Nat.add c od)) ",
                    "(Eq.symm KExpr ",
                    "(instantiate_at (KExpr.lam ty body) w (Nat.add c od)) ",
                    "(KExpr.lam (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) ",
                    "(instantiate_at_lam ty body w (Nat.add c od))))))))) ",
                    // ── pi ── (same structure as lam with KExpr.pi)
                    "(fun (ty : KExpr) (body : KExpr) ",
                    "(ih_ty : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd)) ",
                    "(ih_body : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at body c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at body w (Nat.add c od)) c sd)) ",
                    "(w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "Eq.trans KExpr ",
                    "(instantiate_at (lift_at (KExpr.pi ty body) c sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (KExpr.pi (lift_at ty c sd) (lift_at body (Nat.succ c) sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at (KExpr.pi ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => instantiate_at x w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (KExpr.pi ty body) c sd) ",
                    "(KExpr.pi (lift_at ty c sd) (lift_at body (Nat.succ c) sd)) ",
                    "(lift_at_pi ty body c sd)) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (KExpr.pi (lift_at ty c sd) (lift_at body (Nat.succ c) sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(KExpr.pi (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.pi ty body) w (Nat.add c od)) c sd) ",
                    "(instantiate_at_pi (lift_at ty c sd) (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.pi (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.pi (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.pi ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.pi x ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(ih_ty w c sd od)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.pi (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.pi (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at (instantiate_at (KExpr.pi ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.pi ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd) x) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od)))) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od)))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od))) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (d : Nat) => instantiate_at (lift_at body (Nat.succ c) sd) w d) ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od)) ",
                    "(Eq.trans Nat ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(Nat.add sd (Nat.succ (Nat.add c od))) ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od)) ",
                    "(Eq.symm Nat (Nat.add sd (Nat.succ (Nat.add c od))) ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(nat_add_succ_right sd (Nat.add c od))) ",
                    "(Eq.cong Nat Nat (fun (x : Nat) => Nat.add sd x) ",
                    "(Nat.succ (Nat.add c od)) (Nat.add (Nat.succ c) od) ",
                    "(Eq.symm Nat (Nat.add (Nat.succ c) od) (Nat.succ (Nat.add c od)) ",
                    "(nat_succ_add c od))))) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od))) ",
                    "(lift_at (instantiate_at body w (Nat.add (Nat.succ c) od)) (Nat.succ c) sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(ih_body w (Nat.succ c) sd od) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (d : Nat) => lift_at (instantiate_at body w d) (Nat.succ c) sd) ",
                    "(Nat.add (Nat.succ c) od) (Nat.succ (Nat.add c od)) ",
                    "(nat_succ_add c od))))) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.pi (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at (KExpr.pi (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) c sd) ",
                    "(lift_at (instantiate_at (KExpr.pi ty body) w (Nat.add c od)) c sd) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.pi (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) c sd) ",
                    "(KExpr.pi (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at_pi (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od))) c sd)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x c sd) ",
                    "(KExpr.pi (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) ",
                    "(instantiate_at (KExpr.pi ty body) w (Nat.add c od)) ",
                    "(Eq.symm KExpr ",
                    "(instantiate_at (KExpr.pi ty body) w (Nat.add c od)) ",
                    "(KExpr.pi (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) ",
                    "(instantiate_at_pi ty body w (Nat.add c od))))))))) ",
                    // const
                    "(fun (nm : Name) (us : ListType Level) ",
                    "(w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "Eq.refl KExpr (KExpr.const nm us)) ",
                    // ── let_ ── (ty and val recurse at (c,sd,od), body at (succ c,sd,od))
                    "(fun (ty : KExpr) (val : KExpr) (body : KExpr) ",
                    "(ih_ty : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd)) ",
                    "(ih_val : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd)) ",
                    "(ih_body : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), ",
                    "Eq KExpr (instantiate_at (lift_at body c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at body w (Nat.add c od)) c sd)) ",
                    "(w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "Eq.trans KExpr ",
                    "(instantiate_at (lift_at (KExpr.let_ ty val body) c sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (KExpr.let_ (lift_at ty c sd) (lift_at val c sd) (lift_at body (Nat.succ c) sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => instantiate_at x w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (KExpr.let_ ty val body) c sd) ",
                    "(KExpr.let_ (lift_at ty c sd) (lift_at val c sd) (lift_at body (Nat.succ c) sd)) ",
                    "(lift_at_let_ ty val body c sd)) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (KExpr.let_ (lift_at ty c sd) (lift_at val c sd) (lift_at body (Nat.succ c) sd)) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(KExpr.let_ (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) c sd) ",
                    "(instantiate_at_let_ (lift_at ty c sd) (lift_at val c sd) (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add c od))) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.let_ x ",
                    "(instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(instantiate_at (lift_at ty c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(ih_ty w c sd od)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(lift_at (instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) x ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(instantiate_at (lift_at val c sd) w (Nat.add sd (Nat.add c od))) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) ",
                    "(ih_val w c sd od)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))))) ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at (instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) c sd) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.let_ ",
                    "(lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) x) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od)))) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.succ (Nat.add sd (Nat.add c od)))) ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od))) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (d : Nat) => instantiate_at (lift_at body (Nat.succ c) sd) w d) ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od)) ",
                    "(Eq.trans Nat ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(Nat.add sd (Nat.succ (Nat.add c od))) ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od)) ",
                    "(Eq.symm Nat (Nat.add sd (Nat.succ (Nat.add c od))) ",
                    "(Nat.succ (Nat.add sd (Nat.add c od))) ",
                    "(nat_add_succ_right sd (Nat.add c od))) ",
                    "(Eq.cong Nat Nat (fun (x : Nat) => Nat.add sd x) ",
                    "(Nat.succ (Nat.add c od)) (Nat.add (Nat.succ c) od) ",
                    "(Eq.symm Nat (Nat.add (Nat.succ c) od) (Nat.succ (Nat.add c od)) ",
                    "(nat_succ_add c od))))) ",
                    "(Eq.trans KExpr ",
                    "(instantiate_at (lift_at body (Nat.succ c) sd) w ",
                    "(Nat.add sd (Nat.add (Nat.succ c) od))) ",
                    "(lift_at (instantiate_at body w (Nat.add (Nat.succ c) od)) (Nat.succ c) sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd) ",
                    "(ih_body w (Nat.succ c) sd od) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (d : Nat) => lift_at (instantiate_at body w d) (Nat.succ c) sd) ",
                    "(Nat.add (Nat.succ c) od) (Nat.succ (Nat.add c od)) ",
                    "(nat_succ_add c od))))) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at (KExpr.let_ (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at val w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) c sd) ",
                    "(lift_at (instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) c sd) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.let_ (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at val w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) c sd) ",
                    "(KExpr.let_ (lift_at (instantiate_at ty w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at val w (Nat.add c od)) c sd) ",
                    "(lift_at (instantiate_at body w (Nat.succ (Nat.add c od))) (Nat.succ c) sd)) ",
                    "(lift_at_let_ (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at val w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od))) c sd)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x c sd) ",
                    "(KExpr.let_ (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at val w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) ",
                    "(instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) ",
                    "(Eq.symm KExpr ",
                    "(instantiate_at (KExpr.let_ ty val body) w (Nat.add c od)) ",
                    "(KExpr.let_ (instantiate_at ty w (Nat.add c od)) ",
                    "(instantiate_at val w (Nat.add c od)) ",
                    "(instantiate_at body w (Nat.succ (Nat.add c od)))) ",
                    "(instantiate_at_let_ ty val body w (Nat.add c od)))))))))) ",
                    // proj: 1-child node; lift_at + instantiate_at reduce through proj, ih_sub cong.
                    "(fun (s : Name) (i : Nat) (sub : KExpr) ",
                    "(ih_sub : forall (w : KExpr) (c : Nat) (sd : Nat) (od : Nat), Eq KExpr (instantiate_at (lift_at sub c sd) w (Nat.add sd (Nat.add c od))) (lift_at (instantiate_at sub w (Nat.add c od)) c sd)) ",
                    "(w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => ",
                    "Eq.cong KExpr KExpr (fun (x : KExpr) => KExpr.proj s i x) (instantiate_at (lift_at sub c sd) w (Nat.add sd (Nat.add c od))) (lift_at (instantiate_at sub w (Nat.add c od)) c sd) (ih_sub w c sd od)) ",
                    // lit: leaf.
                    "(fun (litn : Nat) (w : KExpr) (c : Nat) (sd : Nat) (od : Nat) => Eq.refl KExpr (KExpr.lit litn)) ",
                    // apply to original arguments
                    "e w c sd od",
                )
                .to_string(),
            ),
            is_axiom: false,
            description: concat!(
                "Generalized subst/lift interchange at arbitrary cutoff: ",
                "inst(lift(e, c, sd), w, sd+(c+od)) = lift(inst(e, w, c+od), c, sd). ",
                "DerivedProved via KExpr.rec with bvar case delegated to ",
                "subst_lift_interchange_bvar_gen (DerivedProved). ",
                "Part of #461, #464.",
            )
            .to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
                "Eq.symm".to_string(),
                "Eq.trans".to_string(),
                "KExpr.rec".to_string(),
                "instantiate_at_app".to_string(),
                "instantiate_at_lam".to_string(),
                "instantiate_at_let_".to_string(),
                "instantiate_at_pi".to_string(),
                "lift_at_app".to_string(),
                "lift_at_lam".to_string(),
                "lift_at_let_".to_string(),
                "lift_at_pi".to_string(),
                "nat_add_succ_right".to_string(),
                "nat_succ_add".to_string(),
                "subst_lift_interchange_bvar_gen".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::spec::types::ProofStatus;

    #[test]
    fn test_interchange_gen_is_fully_constructive() {
        let spec = crate::test_utils::build_substitution_spec_with_stack();

        let gen_def = spec
            .definitions()
            .get("subst_lift_interchange_gen")
            .expect("subst_lift_interchange_gen should exist");
        assert!(gen_def.value_src.is_some(), "gen should have a proof term");
        assert!(!gen_def.is_axiom, "gen should not be an axiom");
        assert_eq!(gen_def.proof_status, ProofStatus::DerivedProved);
        assert!(
            gen_def.axiom_deps.is_empty(),
            "gen should have no axiom deps (bvar_gen is now DerivedProved)"
        );
    }

    #[test]
    fn test_interchange_bridge_is_fully_derived() {
        let spec = crate::test_utils::build_substitution_spec_with_stack();

        let interchange = spec
            .definitions()
            .get("subst_lift_interchange")
            .expect("subst_lift_interchange should exist");
        assert!(interchange.value_src.is_some(), "should have a proof term");
        assert!(!interchange.is_axiom, "should no longer be a HelperAxiom");
        assert_eq!(interchange.proof_status, ProofStatus::DerivedProved);
        assert!(
            interchange.axiom_deps.is_empty(),
            "should have no axiom deps (bvar_gen is now DerivedProved): {:?}",
            interchange.axiom_deps
        );
    }
}
