// Copyright 2026 Andrew Yates.0
// Author: Andrew Yates <andrewyates.name@gmail.com>
//
//! Full-expression cross-cutoff lift composition for substitution/lift proofs.

use std::collections::HashSet;

use crate::spec::definition::SpecDefinition;
use crate::spec::error::SpecError;
use crate::spec::types::{AxiomCategory, ProofStatus};
use crate::spec::Specification;

impl Specification {
    pub(super) fn add_expr_model_subst_lift_cross_compose(&mut self) -> Result<(), SpecError> {
        // lift_at_cross_compose: cross-cutoff lift composition for all KExpr.
        //
        // Statement: lift_at(lift_at(e, c0, n), add(c0, gap), m) =
        //            lift_at(e, c0, add(n, m))
        //   when gap ≤ n (i.e. sub(gap, n) = 0).
        //
        // Proof by KExpr.rec with motive universalizing c0, n, gap, m, and
        // the constraint witness.
        //   sort: trivial (Eq.refl).
        //   bvar: delegate to lift_at_cross_compose_bvar.
        //   app: unfold via lift_at_app, apply IH to f and a.
        //   lam/pi: unfold via lift_at_lam/pi. Type component uses IH at (c0, gap).
        //     Body uses IH at (succ c0, gap). The outer cutoff
        //     succ(add(c0,gap)) = add(succ c0, gap) via Eq.symm nat_succ_add.
        // Part of #461, #464.
        self.add_definition_structural(SpecDefinition {
            name: "lift_at_cross_compose".to_string(),
            type_src: concat!(
                "forall (e : KExpr) (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                "Eq KExpr ",
                "(lift_at (lift_at e c0 n) (Nat.add c0 gap) m) ",
                "(lift_at e c0 (Nat.add n m))",
            )
            .to_string(),
            value_src: Some(
                concat!(
                    "fun (e : KExpr) (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(h_gn : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "KExpr.rec ",
                    "(fun (expr : KExpr) => forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr ",
                    "(lift_at (lift_at expr c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at expr c0 (Nat.add n m))) ",
                    "(fun (sv : Level) (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(_ : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.refl KExpr (KExpr.sort sv)) ",
                    "(fun (j : Nat) (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(h1 : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "lift_at_cross_compose_bvar j c0 n gap m h1) ",
                    "(fun (f : KExpr) (a : KExpr) ",
                    "(ih_f : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at f c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at f c0 (Nat.add n m))) ",
                    "(ih_a : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at a c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at a c0 (Nat.add n m))) ",
                    "(c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(h1 : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.trans KExpr ",
                    "(lift_at (lift_at (KExpr.app f a) c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.app (lift_at f c0 n) (lift_at a c0 n)) (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.app f a) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.app f a) c0 n) ",
                    "(KExpr.app (lift_at f c0 n) (lift_at a c0 n)) ",
                    "(lift_at_app f a c0 n)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (KExpr.app (lift_at f c0 n) (lift_at a c0 n)) (Nat.add c0 gap) m) ",
                    "(KExpr.app (lift_at (lift_at f c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at a c0 n) (Nat.add c0 gap) m)) ",
                    "(lift_at (KExpr.app f a) c0 (Nat.add n m)) ",
                    "(lift_at_app (lift_at f c0 n) (lift_at a c0 n) (Nat.add c0 gap) m) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.app (lift_at (lift_at f c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at a c0 n) (Nat.add c0 gap) m)) ",
                    "(KExpr.app (lift_at f c0 (Nat.add n m)) ",
                    "(lift_at (lift_at a c0 n) (Nat.add c0 gap) m)) ",
                    "(lift_at (KExpr.app f a) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.app x ",
                    "(lift_at (lift_at a c0 n) (Nat.add c0 gap) m)) ",
                    "(lift_at (lift_at f c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at f c0 (Nat.add n m)) ",
                    "(ih_f c0 n gap m h1)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.app (lift_at f c0 (Nat.add n m)) ",
                    "(lift_at (lift_at a c0 n) (Nat.add c0 gap) m)) ",
                    "(KExpr.app (lift_at f c0 (Nat.add n m)) ",
                    "(lift_at a c0 (Nat.add n m))) ",
                    "(lift_at (KExpr.app f a) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.app (lift_at f c0 (Nat.add n m)) x) ",
                    "(lift_at (lift_at a c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at a c0 (Nat.add n m)) ",
                    "(ih_a c0 n gap m h1)) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.app f a) c0 (Nat.add n m)) ",
                    "(KExpr.app (lift_at f c0 (Nat.add n m)) ",
                    "(lift_at a c0 (Nat.add n m))) ",
                    "(lift_at_app f a c0 (Nat.add n m))))))) ",
                    "(fun (ty : KExpr) (body : KExpr) ",
                    "(ih_ty : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at ty c0 (Nat.add n m))) ",
                    "(ih_body : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at body c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at body c0 (Nat.add n m))) ",
                    "(c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(h1 : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.trans KExpr ",
                    "(lift_at (lift_at (KExpr.lam ty body) c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.lam (lift_at ty c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.lam ty body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.lam ty body) c0 n) ",
                    "(KExpr.lam (lift_at ty c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(lift_at_lam ty body c0 n)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (KExpr.lam (lift_at ty c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(Nat.add c0 gap) m) ",
                    "(KExpr.lam (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.lam ty body) c0 (Nat.add n m)) ",
                    "(lift_at_lam (lift_at ty c0 n) (lift_at body (Nat.succ c0) n) ",
                    "(Nat.add c0 gap) m) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.lam (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.lam (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.lam ty body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.lam x ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at ty c0 (Nat.add n m)) ",
                    "(ih_ty c0 n gap m h1)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.lam (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.lam (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m))) ",
                    "(lift_at (KExpr.lam ty body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.lam (lift_at ty c0 (Nat.add n m)) x) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.add (Nat.succ c0) gap) m) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m)) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (x : Nat) => lift_at (lift_at body (Nat.succ c0) n) x m) ",
                    "(Nat.succ (Nat.add c0 gap)) (Nat.add (Nat.succ c0) gap) ",
                    "(Eq.symm Nat (Nat.add (Nat.succ c0) gap) (Nat.succ (Nat.add c0 gap)) ",
                    "(nat_succ_add c0 gap))) ",
                    "(ih_body (Nat.succ c0) n gap m h1))) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.lam ty body) c0 (Nat.add n m)) ",
                    "(KExpr.lam (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m))) ",
                    "(lift_at_lam ty body c0 (Nat.add n m))))))) ",
                    "(fun (ty : KExpr) (body : KExpr) ",
                    "(ih_ty : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at ty c0 (Nat.add n m))) ",
                    "(ih_body : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at body c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at body c0 (Nat.add n m))) ",
                    "(c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(h1 : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.trans KExpr ",
                    "(lift_at (lift_at (KExpr.pi ty body) c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.pi (lift_at ty c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.pi ty body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.pi ty body) c0 n) ",
                    "(KExpr.pi (lift_at ty c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(lift_at_pi ty body c0 n)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (KExpr.pi (lift_at ty c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(Nat.add c0 gap) m) ",
                    "(KExpr.pi (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.pi ty body) c0 (Nat.add n m)) ",
                    "(lift_at_pi (lift_at ty c0 n) (lift_at body (Nat.succ c0) n) ",
                    "(Nat.add c0 gap) m) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.pi (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.pi (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.pi ty body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.pi x ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at ty c0 (Nat.add n m)) ",
                    "(ih_ty c0 n gap m h1)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.pi (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.pi (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m))) ",
                    "(lift_at (KExpr.pi ty body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.pi (lift_at ty c0 (Nat.add n m)) x) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.add (Nat.succ c0) gap) m) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m)) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (x : Nat) => lift_at (lift_at body (Nat.succ c0) n) x m) ",
                    "(Nat.succ (Nat.add c0 gap)) (Nat.add (Nat.succ c0) gap) ",
                    "(Eq.symm Nat (Nat.add (Nat.succ c0) gap) (Nat.succ (Nat.add c0 gap)) ",
                    "(nat_succ_add c0 gap))) ",
                    "(ih_body (Nat.succ c0) n gap m h1))) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.pi ty body) c0 (Nat.add n m)) ",
                    "(KExpr.pi (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m))) ",
                    "(lift_at_pi ty body c0 (Nat.add n m))))))) ",
                    "(fun (nm : Name) (us : ListType Level) ",
                    "(c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(_ : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.refl KExpr (KExpr.const nm us)) ",
                    "(fun (ty : KExpr) (val : KExpr) (body : KExpr) ",
                    "(ih_ty : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at ty c0 (Nat.add n m))) ",
                    "(ih_val : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at val c0 (Nat.add n m))) ",
                    "(ih_body : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), ",
                    "Eq Nat (Nat.sub gap n) Nat.zero -> ",
                    "Eq KExpr (lift_at (lift_at body c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at body c0 (Nat.add n m))) ",
                    "(c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) ",
                    "(h1 : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.trans KExpr ",
                    "(lift_at (lift_at (KExpr.let_ ty val body) c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.let_ (lift_at ty c0 n) (lift_at val c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.let_ ty val body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr (fun (x : KExpr) => lift_at x (Nat.add c0 gap) m) ",
                    "(lift_at (KExpr.let_ ty val body) c0 n) ",
                    "(KExpr.let_ (lift_at ty c0 n) (lift_at val c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(lift_at_let_ ty val body c0 n)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (KExpr.let_ (lift_at ty c0 n) (lift_at val c0 n) (lift_at body (Nat.succ c0) n)) ",
                    "(Nat.add c0 gap) m) ",
                    "(KExpr.let_ (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.let_ ty val body) c0 (Nat.add n m)) ",
                    "(lift_at_let_ (lift_at ty c0 n) (lift_at val c0 n) (lift_at body (Nat.succ c0) n) ",
                    "(Nat.add c0 gap) m) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.let_ (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.let_ ty val body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.let_ x ",
                    "(lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (lift_at ty c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at ty c0 (Nat.add n m)) ",
                    "(ih_ty c0 n gap m h1)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.let_ (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at val c0 (Nat.add n m)) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (KExpr.let_ ty val body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.let_ (lift_at ty c0 (Nat.add n m)) x ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(lift_at (lift_at val c0 n) (Nat.add c0 gap) m) ",
                    "(lift_at val c0 (Nat.add n m)) ",
                    "(ih_val c0 n gap m h1)) ",
                    "(Eq.trans KExpr ",
                    "(KExpr.let_ (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at val c0 (Nat.add n m)) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m)) ",
                    "(KExpr.let_ (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at val c0 (Nat.add n m)) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m))) ",
                    "(lift_at (KExpr.let_ ty val body) c0 (Nat.add n m)) ",
                    "(Eq.cong KExpr KExpr ",
                    "(fun (x : KExpr) => KExpr.let_ (lift_at ty c0 (Nat.add n m)) (lift_at val c0 (Nat.add n m)) x) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m)) ",
                    "(Eq.trans KExpr ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.succ (Nat.add c0 gap)) m) ",
                    "(lift_at (lift_at body (Nat.succ c0) n) (Nat.add (Nat.succ c0) gap) m) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m)) ",
                    "(Eq.cong Nat KExpr ",
                    "(fun (x : Nat) => lift_at (lift_at body (Nat.succ c0) n) x m) ",
                    "(Nat.succ (Nat.add c0 gap)) (Nat.add (Nat.succ c0) gap) ",
                    "(Eq.symm Nat (Nat.add (Nat.succ c0) gap) (Nat.succ (Nat.add c0 gap)) ",
                    "(nat_succ_add c0 gap))) ",
                    "(ih_body (Nat.succ c0) n gap m h1))) ",
                    "(Eq.symm KExpr ",
                    "(lift_at (KExpr.let_ ty val body) c0 (Nat.add n m)) ",
                    "(KExpr.let_ (lift_at ty c0 (Nat.add n m)) ",
                    "(lift_at val c0 (Nat.add n m)) ",
                    "(lift_at body (Nat.succ c0) (Nat.add n m))) ",
                    "(lift_at_let_ ty val body c0 (Nat.add n m)))))))) ",
                    // proj branch: 1-child node; ih_sub congruence (lift_at reduces through proj).
                    "(fun (s : Name) (i : Nat) (sub : KExpr) ",
                    "(ih_sub : forall (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat), Eq Nat (Nat.sub gap n) Nat.zero -> Eq KExpr (lift_at (lift_at sub c0 n) (Nat.add c0 gap) m) (lift_at sub c0 (Nat.add n m))) ",
                    "(c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) (h : Eq Nat (Nat.sub gap n) Nat.zero) => ",
                    "Eq.cong KExpr KExpr (fun (x : KExpr) => KExpr.proj s i x) (lift_at (lift_at sub c0 n) (Nat.add c0 gap) m) (lift_at sub c0 (Nat.add n m)) (ih_sub c0 n gap m h)) ",
                    // lit branch: leaf.
                    "(fun (litn : Nat) (c0 : Nat) (n : Nat) (gap : Nat) (m : Nat) (_ : Eq Nat (Nat.sub gap n) Nat.zero) => Eq.refl KExpr (KExpr.lit litn)) ",
                    "e c0 n gap m h_gn",
                )
                .to_string(),
            ),
            is_axiom: false,
            description: concat!(
                "Cross-cutoff lift composition: ",
                "lift(lift(e, c0, n), add(c0,gap), m) = lift(e, c0, n+m) ",
                "when gap ≤ n. DerivedProved via KExpr.rec with cutoff-universalized motive. ",
                "Part of #461, #464.",
            )
            .to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "Eq.cong".to_string(),
                "Eq.refl".to_string(),
                "Eq.symm".to_string(),
                "Eq.trans".to_string(),
                "KExpr.rec".to_string(),
                "lift_at_app".to_string(),
                "lift_at_cross_compose_bvar".to_string(),
                "lift_at_lam".to_string(),
                "lift_at_let_".to_string(),
                "lift_at_pi".to_string(),
                "nat_succ_add".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::spec::types::ProofStatus;
    use crate::test_utils::build_spec_with_stack;

    #[test]
    fn test_cross_compose_family_is_constructive() {
        let spec = build_spec_with_stack();

        for name in [
            "nat_sub_zero_trans",
            "lift_at_cross_compose_bvar",
            "lift_at_cross_compose",
        ] {
            let def = spec
                .definitions()
                .get(name)
                .unwrap_or_else(|| panic!("Missing {name}"));
            assert!(def.value_src.is_some(), "{name} should have a proof term");
            assert!(!def.is_axiom, "{name} should not be an axiom");
            assert_eq!(
                def.proof_status,
                ProofStatus::DerivedProved,
                "{name} should be DerivedProved"
            );
            assert!(
                def.axiom_deps.is_empty(),
                "{name} should have no remaining helper blockers: {:?}",
                def.axiom_deps
            );
        }
    }
}
