// Copyright 2026 Andrew Yates.0
// Author: Andrew Yates <andrewyates.name@gmail.com>
//
//! Nested substitution commutation theorem and corollaries (PART 11a continued).
//! Split from substitution_commutation.rs for file-size compliance.
//!
//! Contains:
//! - `instantiate_at_nested_commutes`: binder-aware KExpr.rec proof
//! - `instantiate_at_zero_commutes`: depth-zero specialization
//! - `instantiate_nested_commutes_zero_subst`: depth-aware specialization at subst_depth=0
//! - `instantiate_app_lam_eq`: app/lam instantiation
//! - `instantiate_subst_commutes_eq`: instantiate commutation corollary

use std::collections::HashSet;

use crate::spec::definition::SpecDefinition;
use crate::spec::error::SpecError;
use crate::spec::types::{AxiomCategory, ProofStatus};
use crate::Specification;

impl Specification {
    pub(super) fn add_substitution_commutation_nested_lemmas(&mut self) -> Result<(), SpecError> {
        self.add_definition(SpecDefinition {
            name: "instantiate_at_nested_commutes".to_string(),
            type_src: "forall (body : KExpr) (arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat), Eq KExpr (instantiate_at (instantiate_at body arg subst_depth) w (Nat.add subst_depth outer_depth)) (instantiate_at (instantiate_at body w (Nat.succ (Nat.add subst_depth outer_depth))) (instantiate_at arg w outer_depth) subst_depth)".to_string(),
            value_src: Some(concat!(
                "fun (body : KExpr) (arg : KExpr) (w : KExpr) ",
                "(subst_depth : Nat) (outer_depth : Nat) => ",
                "KExpr.rec ",
                "instantiate_at_nested_commutes_goal ",
                "(fun (n : Level) (_arg : KExpr) (_w : KExpr) (_subst_depth : Nat) (_outer_depth : Nat) => ",
                "Eq.refl KExpr (KExpr.sort n)) ",
                "(fun (i : Nat) (arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => ",
                "instantiate_at_nested_commutes_bvar i arg w subst_depth outer_depth) ",
                "(fun (f : KExpr) (a : KExpr) ",
                "(ih_f : instantiate_at_nested_commutes_goal f) ",
                "(ih_a : instantiate_at_nested_commutes_goal a) ",
                "(arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => ",
                "Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.app f a) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.app ",
                "(instantiate_at (instantiate_at f w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at a arg subst_depth) w (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at (KExpr.app f a) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.app x ",
                "(instantiate_at (instantiate_at a arg subst_depth) w (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at f arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at f w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_f arg w subst_depth outer_depth)) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.app ",
                "(instantiate_at (instantiate_at f w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) x) ",
                "(instantiate_at (instantiate_at a arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at a w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_a arg w subst_depth outer_depth))) ",
                "(fun (ty : KExpr) (body : KExpr) ",
                "(ih_ty : instantiate_at_nested_commutes_goal ty) ",
                "(ih_body : instantiate_at_nested_commutes_goal body) ",
                "(arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => ",
                "Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.lam ty body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(instantiate_at (instantiate_at (KExpr.lam ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.lam ty body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.lam ty body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (KExpr.lam (instantiate_at ty arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth))) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => instantiate_at x w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (KExpr.lam ty body) arg subst_depth) ",
                "(KExpr.lam (instantiate_at ty arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth))) ",
                "(instantiate_at_lam ty body arg subst_depth)) ",
                "(instantiate_at_lam (instantiate_at ty arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth)) w (Nat.add subst_depth outer_depth))) ",
                "(Eq.trans KExpr ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.lam x ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_ty arg w subst_depth outer_depth)) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) x) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w d) ",
                "(Nat.add (Nat.succ subst_depth) outer_depth) ",
                "(Nat.succ (Nat.add subst_depth outer_depth)) ",
                "(nat_succ_add subst_depth outer_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.add (Nat.succ subst_depth) outer_depth))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(ih_body arg w (Nat.succ subst_depth) outer_depth) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body w d) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Nat.succ (Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(Eq.cong Nat Nat (Nat.succ) ",
                "(Nat.add (Nat.succ subst_depth) outer_depth) ",
                "(Nat.succ (Nat.add subst_depth outer_depth)) ",
                "(nat_succ_add subst_depth outer_depth)))))))) ",
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate_at (KExpr.lam ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.lam ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (KExpr.lam ",
                "(instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(KExpr.lam ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => instantiate_at x (instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (KExpr.lam ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(KExpr.lam (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))))) ",
                "(instantiate_at_lam ty body w (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at_lam ",
                "(instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) subst_depth)))) ",
                "(fun (ty : KExpr) (body : KExpr) ",
                "(ih_ty : instantiate_at_nested_commutes_goal ty) ",
                "(ih_body : instantiate_at_nested_commutes_goal body) ",
                "(arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => ",
                "Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.pi ty body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(instantiate_at (instantiate_at (KExpr.pi ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.pi ty body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.pi ty body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (KExpr.pi (instantiate_at ty arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth))) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => instantiate_at x w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (KExpr.pi ty body) arg subst_depth) ",
                "(KExpr.pi (instantiate_at ty arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth))) ",
                "(instantiate_at_pi ty body arg subst_depth)) ",
                "(instantiate_at_pi (instantiate_at ty arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth)) w (Nat.add subst_depth outer_depth))) ",
                "(Eq.trans KExpr ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.pi x ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_ty arg w subst_depth outer_depth)) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) x) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w d) ",
                "(Nat.add (Nat.succ subst_depth) outer_depth) ",
                "(Nat.succ (Nat.add subst_depth outer_depth)) ",
                "(nat_succ_add subst_depth outer_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.add (Nat.succ subst_depth) outer_depth))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(ih_body arg w (Nat.succ subst_depth) outer_depth) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body w d) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Nat.succ (Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(Eq.cong Nat Nat (Nat.succ) ",
                "(Nat.add (Nat.succ subst_depth) outer_depth) ",
                "(Nat.succ (Nat.add subst_depth outer_depth)) ",
                "(nat_succ_add subst_depth outer_depth)))))))) ",
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate_at (KExpr.pi ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.pi ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (KExpr.pi ",
                "(instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(KExpr.pi ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => instantiate_at x (instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (KExpr.pi ty body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(KExpr.pi (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))))) ",
                "(instantiate_at_pi ty body w (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at_pi ",
                "(instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) subst_depth)))) ",
                "(fun (nm : Name) (us : ListType Level) ",
                "(_arg : KExpr) (_w : KExpr) (_subst_depth : Nat) (_outer_depth : Nat) => ",
                "Eq.refl KExpr (KExpr.const nm us)) ",
                "(fun (ty : KExpr) (val : KExpr) (body : KExpr) ",
                "(ih_ty : instantiate_at_nested_commutes_goal ty) ",
                "(ih_val : instantiate_at_nested_commutes_goal val) ",
                "(ih_body : instantiate_at_nested_commutes_goal body) ",
                "(arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => ",
                "Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.let_ ty val body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(instantiate_at (instantiate_at (KExpr.let_ ty val body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.let_ ty val body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.let_ ty val body) arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (KExpr.let_ (instantiate_at ty arg subst_depth) ",
                "(instantiate_at val arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth))) w (Nat.add subst_depth outer_depth)) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => instantiate_at x w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (KExpr.let_ ty val body) arg subst_depth) ",
                "(KExpr.let_ (instantiate_at ty arg subst_depth) ",
                "(instantiate_at val arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth))) ",
                "(instantiate_at_let_ ty val body arg subst_depth)) ",
                "(instantiate_at_let_ (instantiate_at ty arg subst_depth) ",
                "(instantiate_at val arg subst_depth) ",
                "(instantiate_at body arg (Nat.succ subst_depth)) w (Nat.add subst_depth outer_depth))) ",
                "(Eq.trans KExpr ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.let_ x ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at (instantiate_at ty arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_ty arg w subst_depth outer_depth)) ",
                "(Eq.trans KExpr ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) x ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at (instantiate_at val arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_val arg w subst_depth outer_depth)) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) x) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w d) ",
                "(Nat.add (Nat.succ subst_depth) outer_depth) ",
                "(Nat.succ (Nat.add subst_depth outer_depth)) ",
                "(nat_succ_add subst_depth outer_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at body arg (Nat.succ subst_depth)) w ",
                "(Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.add (Nat.succ subst_depth) outer_depth))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(ih_body arg w (Nat.succ subst_depth) outer_depth) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body w d) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth)) ",
                "(Nat.succ (Nat.add (Nat.succ subst_depth) outer_depth)) ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(Eq.cong Nat Nat (Nat.succ) ",
                "(Nat.add (Nat.succ subst_depth) outer_depth) ",
                "(Nat.succ (Nat.add subst_depth outer_depth)) ",
                "(nat_succ_add subst_depth outer_depth))))))))) ",
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate_at (KExpr.let_ ty val body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate_at (KExpr.let_ ty val body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (KExpr.let_ ",
                "(instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(KExpr.let_ ",
                "(instantiate_at (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (instantiate_at body w ",
                "(Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) (Nat.succ subst_depth))) ",
                "(Eq.cong KExpr KExpr ",
                "(fun (x : KExpr) => instantiate_at x (instantiate_at arg w outer_depth) subst_depth) ",
                "(instantiate_at (KExpr.let_ ty val body) w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(KExpr.let_ (instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth))))) ",
                "(instantiate_at_let_ ty val body w (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at_let_ ",
                "(instantiate_at ty w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at val w (Nat.succ (Nat.add subst_depth outer_depth))) ",
                "(instantiate_at body w (Nat.succ (Nat.succ (Nat.add subst_depth outer_depth)))) ",
                "(instantiate_at arg w outer_depth) subst_depth)))) ",
                // proj: 1-child; instantiate_at reduces through proj; ih_sub cong.
                "(fun (s : Name) (i : Nat) (sub : KExpr) (ih_sub : instantiate_at_nested_commutes_goal sub) (arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => ",
                "Eq.cong KExpr KExpr (fun (x : KExpr) => KExpr.proj s i x) ",
                "(instantiate_at (instantiate_at sub arg subst_depth) w (Nat.add subst_depth outer_depth)) ",
                "(instantiate_at (instantiate_at sub w (Nat.succ (Nat.add subst_depth outer_depth))) (instantiate_at arg w outer_depth) subst_depth) ",
                "(ih_sub arg w subst_depth outer_depth)) ",
                // lit: leaf.
                "(fun (m : Nat) (arg : KExpr) (w : KExpr) (subst_depth : Nat) (outer_depth : Nat) => Eq.refl KExpr (KExpr.lit m)) ",
                "body arg w subst_depth outer_depth",
            ).to_string()),
            is_axiom: false,
            description: "Binder-aware nested substitution commutation. DerivedProved by KExpr.rec — all cases constructive including the generalized bvar case. Specializes to instantiate_at_zero_commutes and the arbitrary-depth beta substitution bridge. Part of #464.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "Eq.cong".to_string(),
                "Eq.symm".to_string(),
                "Eq.refl".to_string(),
                "Eq.trans".to_string(),
                "KExpr.rec".to_string(),
                "instantiate_at_lam".to_string(),
                "instantiate_at_let_".to_string(),
                "instantiate_at_nested_commutes_bvar".to_string(),
                "instantiate_at_nested_commutes_goal".to_string(),
                "instantiate_at_pi".to_string(),
                "nat_succ_add".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        self.add_definition(SpecDefinition {
            name: "instantiate_at_zero_commutes".to_string(),
            type_src: "forall (body : KExpr) (arg : KExpr) (w : KExpr), Eq KExpr (instantiate_at (instantiate_at body arg Nat.zero) w Nat.zero) (instantiate_at (instantiate_at body w (Nat.succ Nat.zero)) (instantiate_at arg w Nat.zero) Nat.zero)".to_string(),
            value_src: Some("fun (body : KExpr) (arg : KExpr) (w : KExpr) => instantiate_at_nested_commutes body arg w Nat.zero Nat.zero".to_string()),
            is_axiom: false,
            description: "Depth-zero substitution commutation (MetaCoq distr_subst). DerivedProved by specializing the binder-aware nested commutation theorem at subst_depth=0 and outer_depth=0. Part of #661, #461, #464.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "instantiate_at_nested_commutes".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // Depth-aware substitution commutation: specializes instantiate_at_nested_commutes
        // at subst_depth=0 for arbitrary outer_depth, then rewrites Nat.add Nat.zero depth
        // to depth using nat_add_zero + Eq.cong chains. Part of #464.
        self.add_definition(SpecDefinition {
            name: "instantiate_nested_commutes_zero_subst".to_string(),
            type_src: "forall (body : KExpr) (arg : KExpr) (val : KExpr) (depth : Nat), Eq KExpr (instantiate_at (instantiate body arg) val depth) (instantiate_at (instantiate_at body val (Nat.succ depth)) (instantiate_at arg val depth) Nat.zero)".to_string(),
            value_src: Some(concat!(
                "fun (body : KExpr) (arg : KExpr) (val : KExpr) (depth : Nat) => ",
                "Eq.trans KExpr ",
                "(instantiate_at (instantiate body arg) val depth) ",
                "(instantiate_at (instantiate body arg) val (Nat.add Nat.zero depth)) ",
                "(instantiate_at (instantiate_at body val (Nat.succ depth)) ",
                "(instantiate_at arg val depth) Nat.zero) ",
                // step 1: depth → Nat.add 0 depth (backwards via Eq.symm of Eq.cong)
                "(Eq.symm KExpr ",
                "(instantiate_at (instantiate body arg) val (Nat.add Nat.zero depth)) ",
                "(instantiate_at (instantiate body arg) val depth) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate body arg) val d) ",
                "(Nat.add Nat.zero depth) ",
                "depth ",
                "(nat_add_zero depth))) ",
                // step 2: chain nested_commutes + rhs cong (Nat.succ (Nat.add 0 d) → Nat.succ d)
                "(Eq.trans KExpr ",
                "(instantiate_at (instantiate body arg) val (Nat.add Nat.zero depth)) ",
                "(instantiate_at (instantiate_at body val (Nat.succ (Nat.add Nat.zero depth))) ",
                "(instantiate_at arg val depth) Nat.zero) ",
                "(instantiate_at (instantiate_at body val (Nat.succ depth)) ",
                "(instantiate_at arg val depth) Nat.zero) ",
                "(instantiate_at_nested_commutes body arg val Nat.zero depth) ",
                "(Eq.cong Nat KExpr ",
                "(fun (d : Nat) => instantiate_at (instantiate_at body val d) ",
                "(instantiate_at arg val depth) Nat.zero) ",
                "(Nat.succ (Nat.add Nat.zero depth)) ",
                "(Nat.succ depth) ",
                "(Eq.cong Nat Nat (Nat.succ) (Nat.add Nat.zero depth) depth ",
                "(nat_add_zero depth))))",
            ).to_string()),
            is_axiom: false,
            description: "Depth-aware nested substitution commutation at subst_depth=0. DerivedProved: rewrites Nat.add 0 depth -> depth via nat_add_zero. Part of #464.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "Eq.cong".to_string(),
                "Eq.symm".to_string(),
                "Eq.trans".to_string(),
                "instantiate_at_nested_commutes".to_string(),
                "nat_add_zero".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // Helper: instantiate (app (lam A body) arg) w = app (lam A' body') arg'
        // Now DerivedProved since instantiate_at_app and instantiate_at_lam are
        // DerivedProved. Eq.cong/Eq.trans are FoundationalRules, not HelperAxioms.
        self.add_definition(SpecDefinition {
            name: "instantiate_app_lam_eq".to_string(),
            type_src: "forall (A : KExpr) (body : KExpr) (arg : KExpr) (w : KExpr), Eq KExpr (instantiate (KExpr.app (KExpr.lam A body) arg) w) (KExpr.app (KExpr.lam (instantiate_at A w Nat.zero) (instantiate_at body w (Nat.succ Nat.zero))) (instantiate_at arg w Nat.zero))".to_string(),
            value_src: Some(
                "fun (A : KExpr) (body : KExpr) (arg : KExpr) (w : KExpr) => Eq.trans KExpr (instantiate (KExpr.app (KExpr.lam A body) arg) w) (KExpr.app (instantiate_at (KExpr.lam A body) w Nat.zero) (instantiate_at arg w Nat.zero)) (KExpr.app (KExpr.lam (instantiate_at A w Nat.zero) (instantiate_at body w (Nat.succ Nat.zero))) (instantiate_at arg w Nat.zero)) (instantiate_at_app (KExpr.lam A body) arg w Nat.zero) (Eq.cong KExpr KExpr (fun (x : KExpr) => KExpr.app x (instantiate_at arg w Nat.zero)) (instantiate_at (KExpr.lam A body) w Nat.zero) (KExpr.lam (instantiate_at A w Nat.zero) (instantiate_at body w (Nat.succ Nat.zero))) (instantiate_at_lam A body w Nat.zero))"
                    .to_string(),
            ),
            is_axiom: false,
            description: "instantiate (app (lam A body) arg) w = app (lam (inst A w 0) (inst body w 1)) (inst arg w 0). DerivedProved. Part of #661, #461.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "Eq.cong".to_string(),
                "Eq.trans".to_string(),
                "instantiate_at_app".to_string(),
                "instantiate_at_lam".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        // Helper: instantiate (instantiate body arg) w via instantiate_at_zero_commutes.
        self.add_definition(SpecDefinition {
            name: "instantiate_subst_commutes_eq".to_string(),
            type_src: "forall (body : KExpr) (arg : KExpr) (w : KExpr), Eq KExpr (instantiate (instantiate body arg) w) (instantiate (instantiate_at body w (Nat.succ Nat.zero)) (instantiate_at arg w Nat.zero))".to_string(),
            value_src: Some(
                "fun (body : KExpr) (arg : KExpr) (w : KExpr) => instantiate_at_zero_commutes body arg w".to_string()
            ),
            is_axiom: false,
            description: "Substitution commutation for instantiate. DerivedProved corollary of instantiate_at_zero_commutes. Part of #661.".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "instantiate_at_zero_commutes".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })?;

        Ok(())
    }
}
