// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! `clean vendor` — manage vendored crate sources for offline / reproducible builds.
//!
//! The external crate sources (`cargo vendor` output — ~583M uncompressed, mostly
//! cfg-gated `windows`/`wasm` bindings) are deliberately **NOT committed to git**.
//! They are published as a compressed `vendor.tar.zst` GitHub Release artifact —
//! the same pattern the `.mathverse` shards use — and fetched on demand. Default
//! reproducibility comes from `Cargo.lock` + `--locked`; this command adds the
//! offline tier.
//!
//! - `clean vendor fetch`   — download + extract the artifact and write an
//!   (untracked) `.cargo/vendor.toml` source-replacement config.
//! - `clean vendor package` — `cargo vendor` + compress to a `vendor.tar.zst`
//!   artifact (the maintainer side: produce what `fetch` consumes).
//! - `clean vendor status`  — report whether the vendor tier is set up + the
//!   `Cargo.lock` fingerprint it should correspond to.
//! - `clean vendor clean`   — remove `vendor/` and `.cargo/vendor.toml`.
//!
//! Internal repos (`ay`, `trust`, `trust-ir`) are path-dep submodules and are
//! never vendored — only external crates.io/git deps are. Replaces the former
//! `scripts/fetch_vendor.sh`.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, bail, Context};
use clap::Subcommand;
use clean_features::{Category, Example, FeatureDescriptor, RefKind, Reference, Stability};

/// Default GitHub repo hosting the vendor release artifact.
const DEFAULT_REPO: &str = "alabsystems/clean";
/// Default release tag carrying the `vendor.tar.zst` asset.
const DEFAULT_TAG: &str = "vendor-latest";
/// Release asset name.
const VENDOR_ASSET: &str = "vendor.tar.zst";
/// Vendored-sources directory (workspace-root-relative).
const VENDOR_DIR: &str = "vendor";
/// Untracked cargo source-replacement config written by `fetch`.
const VENDOR_CONFIG_REL: &str = ".cargo/vendor.toml";

/// Canonical cargo source-replacement config. Mirrors `cargo vendor`'s printed
/// stanza for this workspace; `package` re-derives it and warns on drift (e.g. a
/// changed git-source rev), so this constant stays the single source of truth.
const VENDOR_CONFIG_TOML: &str = r#"# Generated by `clean vendor fetch` — DO NOT COMMIT (gitignored).
# Source-replaces crates.io + git deps with the vendored copies under vendor/.
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/ufmg-smite/carcara?rev=fecb4224def3c26f93a5d4f1804ecf58eb979650"]
git = "https://github.com/ufmg-smite/carcara"
rev = "fecb4224def3c26f93a5d4f1804ecf58eb979650"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
"#;

const VENDOR_DESIGN_REF: Reference = Reference {
    kind: RefKind::Doc,
    label: "Vendoring via release artifact (CLAUDE.md / .mathverse shard pattern)",
    target: "CLAUDE.md",
};

const CLI_CRATE_REF: Reference = Reference {
    kind: RefKind::Crate,
    label: "clean-cli",
    target: "clean-cli",
};

/// Feature descriptors surfaced by the `clean vendor` verb tree (one per leaf;
/// registered in `crate::registry::all_features` and gated by the
/// `feature_coverage` drift test).
pub(crate) const FEATURES: &[FeatureDescriptor] = &[
    FeatureDescriptor {
        path: &["vendor", "fetch"],
        summary: "Download + extract vendored crate sources for offline builds",
        description: "\
Downloads the `vendor.tar.zst` release artifact, extracts it to `vendor/`, and \
writes an untracked `.cargo/vendor.toml` source-replacement config. Afterwards, \
build fully offline with `cargo <cmd> --offline --config .cargo/vendor.toml`. \
Vendored sources are not committed to git (they are large and mostly cfg-gated \
windows/wasm bindings); this is the on-demand offline tier over `Cargo.lock` + \
`--locked`.",
        category: Category::Build,
        stability: Stability::Building,
        examples: &[Example {
            cmd: "clean vendor fetch",
            what: "set up vendor/ + .cargo/vendor.toml from the vendor-latest release",
        }],
        see_also: &["vendor package", "vendor status", "vendor clean"],
        references: &[VENDOR_DESIGN_REF, CLI_CRATE_REF],
        domain_root: Some("vendor"),
        alternative_forms: &[],
        feature_gate: None,
    },
    FeatureDescriptor {
        path: &["vendor", "package"],
        summary: "Produce the vendor.tar.zst artifact (cargo vendor + compress)",
        description: "\
Runs `cargo vendor` and compresses the result into a `vendor.tar.zst` artifact \
(default `target/vendor.tar.zst`) for upload to the `vendor-latest` release. The \
maintainer side of the workflow: produces exactly what `clean vendor fetch` \
consumes. Warns if `cargo vendor`'s emitted source-replacement config drifts \
from the built-in canonical config.",
        category: Category::Build,
        stability: Stability::Building,
        examples: &[Example {
            cmd: "clean vendor package --out target/vendor.tar.zst",
            what: "vendor + compress the external deps into a release artifact",
        }],
        see_also: &["vendor fetch", "vendor status"],
        references: &[VENDOR_DESIGN_REF, CLI_CRATE_REF],
        domain_root: Some("vendor"),
        alternative_forms: &[],
        feature_gate: None,
    },
    FeatureDescriptor {
        path: &["vendor", "status"],
        summary: "Report whether the offline vendor tier is set up",
        description: "\
Reports whether `vendor/` and `.cargo/vendor.toml` are present and the current \
`Cargo.lock` fingerprint the vendored sources should correspond to. Pass `--json` \
for machine-readable output.",
        category: Category::Build,
        stability: Stability::Building,
        examples: &[Example {
            cmd: "clean vendor status",
            what: "show whether offline builds are wired up and the lock fingerprint",
        }],
        see_also: &["vendor fetch", "vendor clean"],
        references: &[VENDOR_DESIGN_REF, CLI_CRATE_REF],
        domain_root: Some("vendor"),
        alternative_forms: &[],
        feature_gate: None,
    },
    FeatureDescriptor {
        path: &["vendor", "clean"],
        summary: "Remove vendor/ and .cargo/vendor.toml",
        description: "\
Tears down the offline vendor tier: removes the `vendor/` directory and the \
untracked `.cargo/vendor.toml` config, returning to plain online (registry) \
builds.",
        category: Category::Build,
        stability: Stability::Building,
        examples: &[Example {
            cmd: "clean vendor clean",
            what: "remove the vendored sources + offline config",
        }],
        see_also: &["vendor fetch"],
        references: &[VENDOR_DESIGN_REF, CLI_CRATE_REF],
        domain_root: Some("vendor"),
        alternative_forms: &[],
        feature_gate: None,
    },
];

/// `clean vendor <verb>` — vendored-sources lifecycle.
#[derive(Debug, Subcommand)]
pub(crate) enum VendorCommands {
    /// Download + extract the vendor artifact and write `.cargo/vendor.toml`.
    Fetch {
        /// Release tag carrying the `vendor.tar.zst` asset.
        #[arg(long, default_value = DEFAULT_TAG)]
        tag: String,
        /// `owner/repo` hosting the release.
        #[arg(long, default_value = DEFAULT_REPO)]
        repo: String,
        /// Re-fetch even if `vendor/` is already present.
        #[arg(long)]
        force: bool,
    },
    /// `cargo vendor` + compress into a `vendor.tar.zst` release artifact.
    Package {
        /// Output artifact path (default `target/vendor.tar.zst`).
        #[arg(long)]
        out: Option<PathBuf>,
    },
    /// Report whether the offline vendor tier is set up.
    Status {
        /// Emit machine-readable JSON.
        #[arg(long)]
        json: bool,
    },
    /// Remove `vendor/` and `.cargo/vendor.toml`.
    Clean,
}

pub(crate) fn handle_vendor_command(command: VendorCommands) -> anyhow::Result<()> {
    match command {
        VendorCommands::Fetch { tag, repo, force } => vendor_fetch(&repo, &tag, force),
        VendorCommands::Package { out } => vendor_package(out.as_deref()),
        VendorCommands::Status { json } => vendor_status(json),
        VendorCommands::Clean => vendor_clean(),
    }
}

/// Locate the cargo **workspace root** (the directory whose `Cargo.toml` declares
/// `[workspace]`) by walking up from the current directory. `vendor/` and
/// `.cargo/` live there, so every verb resolves paths against it.
fn workspace_root() -> anyhow::Result<PathBuf> {
    let start = std::env::current_dir().context("resolving current directory")?;
    for dir in start.ancestors() {
        let manifest = dir.join("Cargo.toml");
        if let Ok(text) = std::fs::read_to_string(&manifest) {
            if text.contains("[workspace]") {
                return Ok(dir.to_path_buf());
            }
        }
    }
    bail!(
        "could not find the cargo workspace root (no Cargo.toml with [workspace]) at or above {}",
        start.display()
    )
}

/// `clean vendor fetch` — download the artifact, extract `vendor/`, write config.
fn vendor_fetch(repo: &str, tag: &str, force: bool) -> anyhow::Result<()> {
    let root = workspace_root()?;
    let vendor_dir = root.join(VENDOR_DIR);
    let config_path = root.join(VENDOR_CONFIG_REL);

    if vendor_dir.is_dir() && config_path.is_file() && !force {
        println!(
            "[vendor fetch] already set up at {} (pass --force to refresh)",
            vendor_dir.display()
        );
        return Ok(());
    }

    let dl_dir = root.join("target").join("vendor-download");
    let assets =
        clean_mathverse::artifacts::download_assets(repo, tag, Some(VENDOR_ASSET), &dl_dir)
            .map_err(|e| anyhow!("downloading {VENDOR_ASSET} from {repo}@{tag}: {e}"))?;
    let archive = assets
        .into_iter()
        .find(|p| p.file_name().and_then(|n| n.to_str()) == Some(VENDOR_ASSET))
        .ok_or_else(|| anyhow!("release {repo}@{tag} has no `{VENDOR_ASSET}` asset"))?;

    // The artifact's entries are `vendor/...`, so strip 0 and extract at the root.
    if force && vendor_dir.exists() {
        std::fs::remove_dir_all(&vendor_dir)
            .with_context(|| format!("removing stale {}", vendor_dir.display()))?;
    }
    clean_mathverse::artifacts::extract_archive(&archive, &root, 0).map_err(|e| {
        anyhow!(
            "extracting {} to {}: {e}",
            archive.display(),
            root.display()
        )
    })?;

    write_vendor_config(&config_path)?;
    let _ = std::fs::remove_file(&archive);

    println!(
        "[vendor fetch] ok — extracted {} and wrote {}",
        vendor_dir.display(),
        config_path.display()
    );
    println!(
        "  offline build: cargo check --workspace --locked --offline --config {VENDOR_CONFIG_REL}"
    );
    Ok(())
}

/// Write the untracked source-replacement config, creating `.cargo/` as needed.
fn write_vendor_config(config_path: &Path) -> anyhow::Result<()> {
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(config_path, VENDOR_CONFIG_TOML)
        .with_context(|| format!("writing {}", config_path.display()))
}

/// `clean vendor package` — `cargo vendor` + compress into a `vendor.tar.zst`.
fn vendor_package(out: Option<&Path>) -> anyhow::Result<()> {
    let root = workspace_root()?;
    let out = out
        .map(Path::to_path_buf)
        .unwrap_or_else(|| root.join("target").join(VENDOR_ASSET));
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }

    println!(
        "[vendor package] running `cargo vendor {VENDOR_DIR}` in {} ...",
        root.display()
    );
    let vendored = Command::new("cargo")
        .arg("vendor")
        .arg(VENDOR_DIR)
        .current_dir(&root)
        .output()
        .context("running `cargo vendor` (is cargo on PATH?)")?;
    if !vendored.status.success() {
        bail!(
            "`cargo vendor` failed (exit {:?}): {}",
            vendored.status.code(),
            String::from_utf8_lossy(&vendored.stderr)
        );
    }
    warn_on_config_drift(&String::from_utf8_lossy(&vendored.stdout));

    println!(
        "[vendor package] compressing {VENDOR_DIR}/ -> {} ...",
        out.display()
    );
    compress_tar_zst(&root, VENDOR_DIR, &out)?;

    let size = std::fs::metadata(&out).map(|m| m.len()).unwrap_or(0);
    println!(
        "[vendor package] ok — {} ({:.1} MiB). Upload with:\n  \
         gh release upload {DEFAULT_TAG} {}#{VENDOR_ASSET} -R {DEFAULT_REPO} --clobber",
        out.display(),
        size as f64 / (1024.0 * 1024.0),
        out.display()
    );
    Ok(())
}

/// Compress `<root>/<dir>` into `out` as a zstd-compressed tar, shelling out to
/// `tar` + `zstd` (mirrors the `.mathverse` artifact pipeline's reliance on
/// system tar/zstd rather than a heavyweight in-process dependency).
fn compress_tar_zst(root: &Path, dir: &str, out: &Path) -> anyhow::Result<()> {
    // `tar --zstd` is not universally available (notably macOS bsdtar lacks the
    // flag), so pipe through `zstd` explicitly.
    let tar = Command::new("tar")
        .arg("-C")
        .arg(root)
        .arg("-cf")
        .arg("-")
        .arg(dir)
        .stdout(std::process::Stdio::piped())
        .spawn()
        .context("spawning `tar` (is tar on PATH?)")?;
    let tar_out = tar.stdout.ok_or_else(|| anyhow!("capturing tar stdout"))?;
    let zstd = Command::new("zstd")
        .arg("-19")
        .arg("-T0")
        .arg("-f")
        .arg("-o")
        .arg(out)
        .stdin(tar_out)
        .status()
        .context("running `zstd` (is zstd on PATH?)")?;
    if !zstd.success() {
        bail!("`zstd` compression failed (exit {:?})", zstd.code());
    }
    Ok(())
}

/// Warn if `cargo vendor`'s emitted source-replacement config diverges from the
/// built-in canonical one (e.g. a git-source rev changed) so the maintainer
/// updates [`VENDOR_CONFIG_TOML`].
fn warn_on_config_drift(cargo_stdout: &str) {
    // Compare the meaningful (git-source) lines, ignoring whitespace/comments.
    let cargo_git: Vec<&str> = cargo_stdout
        .lines()
        .map(str::trim)
        .filter(|l| l.starts_with("rev =") || l.starts_with("git ="))
        .collect();
    let ours_git: Vec<&str> = VENDOR_CONFIG_TOML
        .lines()
        .map(str::trim)
        .filter(|l| l.starts_with("rev =") || l.starts_with("git ="))
        .collect();
    if !cargo_git.is_empty() && cargo_git != ours_git {
        eprintln!(
            "[vendor package] ⚠ warning: `cargo vendor` emitted git sources that differ from \
             the built-in config — update VENDOR_CONFIG_TOML in cmd_vendor.rs:\n  cargo: {cargo_git:?}\n  ours:  {ours_git:?}"
        );
    }
}

/// `clean vendor status` — report setup state + lock fingerprint.
fn vendor_status(json: bool) -> anyhow::Result<()> {
    let root = workspace_root()?;
    let status = VendorStatus::probe(&root)?;
    if json {
        println!("{}", status.to_json());
    } else {
        println!("{}", status.summary());
    }
    Ok(())
}

/// `clean vendor clean` — remove `vendor/` and `.cargo/vendor.toml`.
fn vendor_clean() -> anyhow::Result<()> {
    let root = workspace_root()?;
    let vendor_dir = root.join(VENDOR_DIR);
    let config_path = root.join(VENDOR_CONFIG_REL);
    let mut removed = Vec::new();
    if vendor_dir.exists() {
        std::fs::remove_dir_all(&vendor_dir)
            .with_context(|| format!("removing {}", vendor_dir.display()))?;
        removed.push(vendor_dir.display().to_string());
    }
    if config_path.exists() {
        std::fs::remove_file(&config_path)
            .with_context(|| format!("removing {}", config_path.display()))?;
        removed.push(config_path.display().to_string());
    }
    if removed.is_empty() {
        println!("[vendor clean] nothing to remove (vendor tier not set up)");
    } else {
        println!("[vendor clean] removed: {}", removed.join(", "));
    }
    Ok(())
}

/// Offline-vendor setup state, computed from the workspace root. Pure data so
/// the renderers are unit-testable.
#[derive(Debug, PartialEq, Eq)]
struct VendorStatus {
    vendor_dir_present: bool,
    config_present: bool,
    /// First 16 hex chars of `sha256(Cargo.lock)`, if present.
    lock_fingerprint: Option<String>,
}

impl VendorStatus {
    fn probe(root: &Path) -> anyhow::Result<Self> {
        let lock_fingerprint = match std::fs::read(root.join("Cargo.lock")) {
            Ok(bytes) => Some(short_sha256(&bytes)),
            Err(_) => None,
        };
        Ok(Self {
            vendor_dir_present: root.join(VENDOR_DIR).is_dir(),
            config_present: root.join(VENDOR_CONFIG_REL).is_file(),
            lock_fingerprint,
        })
    }

    fn ready(&self) -> bool {
        self.vendor_dir_present && self.config_present
    }

    fn summary(&self) -> String {
        let mut lines = vec![format!(
            "offline vendor tier: {}",
            if self.ready() { "READY" } else { "not set up" }
        )];
        lines.push(format!(
            "  vendor/ present:        {}",
            self.vendor_dir_present
        ));
        lines.push(format!("  .cargo/vendor.toml:     {}", self.config_present));
        lines.push(format!(
            "  Cargo.lock fingerprint: {}",
            self.lock_fingerprint
                .as_deref()
                .unwrap_or("<no Cargo.lock>")
        ));
        if !self.ready() {
            lines.push("  → run `clean vendor fetch` to enable offline builds".to_string());
        }
        lines.join("\n")
    }

    fn to_json(&self) -> String {
        let report = serde_json::json!({
            "ready": self.ready(),
            "vendor_dir_present": self.vendor_dir_present,
            "config_present": self.config_present,
            "lock_fingerprint": self.lock_fingerprint,
        });
        serde_json::to_string_pretty(&report).unwrap_or_else(|_| "{}".to_string())
    }
}

/// First 16 hex chars of the SHA-256 of `bytes`.
fn short_sha256(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(bytes);
    digest.iter().take(8).map(|b| format!("{b:02x}")).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vendor_config_is_valid_toml_with_three_sources() {
        let parsed: toml::Value =
            toml::from_str(VENDOR_CONFIG_TOML).expect("vendor config must be valid TOML");
        let source = parsed.get("source").expect("a [source] table");
        assert!(source.get("crates-io").is_some(), "crates-io replacement");
        assert!(
            source.get("vendored-sources").is_some(),
            "vendored-sources dir"
        );
        // exactly one git source (carcara) + crates-io + vendored-sources
        let git_sources = source
            .as_table()
            .expect("source table")
            .keys()
            .filter(|k| k.starts_with("git+"))
            .count();
        assert_eq!(git_sources, 1, "one git source (carcara)");
    }

    #[test]
    fn test_vendor_config_directory_points_at_vendor() {
        let parsed: toml::Value = toml::from_str(VENDOR_CONFIG_TOML).unwrap();
        let dir = parsed["source"]["vendored-sources"]["directory"]
            .as_str()
            .expect("directory key");
        assert_eq!(dir, VENDOR_DIR);
    }

    #[test]
    fn test_status_summary_ready_vs_not() {
        let ready = VendorStatus {
            vendor_dir_present: true,
            config_present: true,
            lock_fingerprint: Some("deadbeefcafef00d".to_string()),
        };
        let s = ready.summary();
        assert!(s.contains("READY"), "got: {s}");
        assert!(s.contains("deadbeefcafef00d"), "got: {s}");
        assert!(
            !s.contains("run `clean vendor fetch`"),
            "ready => no hint; got: {s}"
        );

        let not = VendorStatus {
            vendor_dir_present: false,
            config_present: false,
            lock_fingerprint: None,
        };
        let s = not.summary();
        assert!(s.contains("not set up"), "got: {s}");
        assert!(s.contains("<no Cargo.lock>"), "got: {s}");
        assert!(s.contains("run `clean vendor fetch`"), "got: {s}");
    }

    #[test]
    fn test_status_json_is_valid_and_machine_readable() {
        let st = VendorStatus {
            vendor_dir_present: true,
            config_present: false,
            lock_fingerprint: Some("abc123".to_string()),
        };
        let v: serde_json::Value = serde_json::from_str(&st.to_json()).expect("valid JSON");
        assert_eq!(v["ready"], false); // dir present but config missing
        assert_eq!(v["vendor_dir_present"], true);
        assert_eq!(v["config_present"], false);
        assert_eq!(v["lock_fingerprint"], "abc123");
    }

    #[test]
    fn test_short_sha256_is_16_hex_chars() {
        let h = short_sha256(b"hello");
        assert_eq!(h.len(), 16, "16 hex chars (8 bytes)");
        assert!(h.chars().all(|c| c.is_ascii_hexdigit()), "hex only: {h}");
        // SHA-256("hello") starts with 2cf24dba...
        assert_eq!(h, "2cf24dba5fb0a30e");
    }

    #[test]
    fn test_config_drift_warning_does_not_panic_on_matching_config() {
        // Feeding our own config back must be drift-free (no panic, no false positive
        // is asserted here beyond it running cleanly).
        warn_on_config_drift(VENDOR_CONFIG_TOML);
    }
}
