// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Lean 4 source code generation from the clean kernel model.
//!
//! Generates Lean 4 `.lean` source text encoding the kernel model as Lean 4
//! inductive types and recursive functions, plus formal soundness theorem
//! statements that can be proved in Lean 4 to create the bootstrap trust chain.
//!
//! ## References
//!
//! - Carneiro, M. (2019). "The type theory of Lean". MS Thesis, CMU.
//! - de Moura, L. et al. (2021). "The Lean 4 theorem prover". CADE-28.

/// Errors from Lean 4 source emission.
#[derive(Debug, Clone, thiserror::Error)]
#[non_exhaustive]
pub enum Lean4EmitError {
    /// A referenced model type is not supported for emission.
    #[error("unsupported model type for Lean 4 emission: {0}")]
    UnsupportedType(String),
}

/// Lean 4 source code emitter for the kernel model.
///
/// Generates well-formed Lean 4 source text that encodes:
/// 1. Inductive type definitions mirroring `KernelExpr` and `KernelLevel`
/// 2. Recursive function definitions for WHNF, type inference, def-eq
/// 3. Theorem statements for type preservation, progress, and confluence
#[derive(Debug, Clone)]
pub struct Lean4Emitter {
    /// Optional namespace prefix for generated definitions.
    namespace: Option<String>,
}

impl Lean4Emitter {
    /// Create a new Lean 4 emitter with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self { namespace: None }
    }

    /// Create a new emitter that wraps output in the given namespace.
    #[must_use]
    pub fn with_namespace(namespace: &str) -> Self {
        Self {
            namespace: Some(namespace.to_string()),
        }
    }

    /// Emit Lean 4 inductive type definitions for the kernel model.
    ///
    /// Generates definitions for `Level`, `KExpr`, and supporting types
    /// (`Name`, `ListType`) that mirror the spec model types.
    #[must_use]
    pub fn emit_kernel_model(&self) -> String {
        let mut out = String::with_capacity(2048);

        out.push_str("-- Auto-generated by clean bootstrap bridge\n");
        out.push_str("-- Do not edit manually\n\n");

        if let Some(ns) = &self.namespace {
            out.push_str(&format!("namespace {ns}\n\n"));
        }

        // Universe levels
        out.push_str("inductive Level : Type where\n");
        out.push_str("  | zero : Level\n");
        out.push_str("  | succ : Level → Level\n");
        out.push_str("  | max : Level → Level → Level\n");
        out.push_str("  | imax : Level → Level → Level\n");
        out.push_str("  deriving Repr, BEq\n\n");

        // Kernel expressions
        out.push_str("inductive KExpr : Type where\n");
        out.push_str("  | sort : Nat → KExpr\n");
        out.push_str("  | bvar : Nat → KExpr\n");
        out.push_str("  | app : KExpr → KExpr → KExpr\n");
        out.push_str("  | lam : KExpr → KExpr → KExpr\n");
        out.push_str("  | pi : KExpr → KExpr → KExpr\n");
        out.push_str("  | «let» : KExpr → KExpr → KExpr → KExpr\n");
        out.push_str("  | «const» : String → ListType Level → KExpr\n");
        out.push_str("  deriving Repr, BEq\n\n");

        // Typing context
        out.push_str("abbrev Ctx := ListType KExpr\n\n");

        // Environment entry
        out.push_str("structure EnvEntry where\n");
        out.push_str("  ty : KExpr\n");
        out.push_str("  val : Option KExpr\n");
        out.push_str("  deriving Repr\n\n");

        // Environment
        out.push_str("abbrev KernelEnv := ListType (String × EnvEntry)\n\n");

        // Lift (shift) operation
        out.push_str("def liftAt (e : KExpr) (cutoff amount : Nat) : KExpr :=\n");
        out.push_str("  match e with\n");
        out.push_str("  | .sort n => .sort n\n");
        out.push_str("  | .bvar i => if i >= cutoff then .bvar (i + amount) else .bvar i\n");
        out.push_str("  | .app f a => .app (liftAt f cutoff amount) (liftAt a cutoff amount)\n");
        out.push_str(
            "  | .lam ty body => .lam (liftAt ty cutoff amount) (liftAt body (cutoff+1) amount)\n",
        );
        out.push_str(
            "  | .pi ty body => .pi (liftAt ty cutoff amount) (liftAt body (cutoff+1) amount)\n",
        );
        out.push_str("  | .let ty val body => .let (liftAt ty cutoff amount) (liftAt val cutoff amount) (liftAt body (cutoff+1) amount)\n");
        out.push_str("  | .const n ls => .const n ls\n\n");

        // Instantiate (substitution) operation
        out.push_str("def instantiateAt (body val : KExpr) (depth : Nat) : KExpr :=\n");
        out.push_str("  match body with\n");
        out.push_str("  | .sort n => .sort n\n");
        out.push_str("  | .bvar i =>\n");
        out.push_str("    if i < depth then .bvar i\n");
        out.push_str("    else if i == depth then liftAt val 0 depth\n");
        out.push_str("    else .bvar (i - 1)\n");
        out.push_str(
            "  | .app f a => .app (instantiateAt f val depth) (instantiateAt a val depth)\n",
        );
        out.push_str(
            "  | .lam ty b => .lam (instantiateAt ty val depth) (instantiateAt b val (depth+1))\n",
        );
        out.push_str(
            "  | .pi ty b => .pi (instantiateAt ty val depth) (instantiateAt b val (depth+1))\n",
        );
        out.push_str("  | .let ty v b => .let (instantiateAt ty val depth) (instantiateAt v val depth) (instantiateAt b val (depth+1))\n");
        out.push_str("  | .const n ls => .const n ls\n\n");

        out.push_str("def instantiate (body val : KExpr) : KExpr := instantiateAt body val 0\n\n");

        if let Some(ns) = &self.namespace {
            out.push_str(&format!("end {ns}\n"));
        }

        out
    }

    /// Emit Lean 4 theorem statements for kernel soundness properties.
    ///
    /// Generates `theorem` (sorry) stubs for:
    /// - **Type preservation**: if `e : T` and `e` reduces to `e'`, then `e' : T`
    /// - **Progress**: well-typed closed terms are values or can reduce
    /// - **Confluence**: if `e` reduces to `a` and `b`, there exists `c`
    ///   reachable from both
    #[must_use]
    pub fn emit_soundness_statements(&self) -> String {
        let mut out = String::with_capacity(2048);

        out.push_str("-- Soundness theorem statements for clean kernel model\n");
        out.push_str("-- Generated by clean bootstrap bridge\n\n");

        if let Some(ns) = &self.namespace {
            out.push_str(&format!("namespace {ns}\n\n"));
        }

        // Type preservation (subject reduction)
        out.push_str("/-- Type preservation (subject reduction):\n");
        out.push_str("    If `Γ ⊢ e : T` and `e ⟶β e'`, then `Γ ⊢ e' : T`.\n");
        out.push_str("    This is the fundamental soundness property of the type system. -/\n");
        out.push_str("theorem type_preservation\n");
        out.push_str("  (env : KernelEnv) (ctx : Ctx) (e e' T : KExpr)\n");
        out.push_str("  (h_type : HasType env ctx e T)\n");
        out.push_str("  (h_step : BetaStep e e')\n");
        out.push_str("  : HasType env ctx e' T := by\n");
        out.push_str("  sorry\n\n");

        // Progress
        out.push_str("/-- Progress: well-typed closed terms are values or can step.\n");
        out.push_str("    If `⊢ e : T` (empty context), then either `e` is a value\n");
        out.push_str("    or there exists `e'` such that `e ⟶β e'`. -/\n");
        out.push_str("theorem progress\n");
        out.push_str("  (env : KernelEnv) (e T : KExpr)\n");
        out.push_str("  (h_type : HasType env [] e T)\n");
        out.push_str("  : IsValue e ∨ ∃ e', BetaStep e e' := by\n");
        out.push_str("  sorry\n\n");

        // Confluence (Church-Rosser)
        out.push_str("/-- Confluence (Church-Rosser property):\n");
        out.push_str("    If `e ⟶*β a` and `e ⟶*β b`, then there exists `c`\n");
        out.push_str("    such that `a ⟶*β c` and `b ⟶*β c`. -/\n");
        out.push_str("theorem confluence\n");
        out.push_str("  (e a b : KExpr)\n");
        out.push_str("  (ha : BetaStarStep e a)\n");
        out.push_str("  (hb : BetaStarStep e b)\n");
        out.push_str("  : ∃ c, BetaStarStep a c ∧ BetaStarStep b c := by\n");
        out.push_str("  sorry\n\n");

        if let Some(ns) = &self.namespace {
            out.push_str(&format!("end {ns}\n"));
        }

        out
    }
}

impl Default for Lean4Emitter {
    fn default() -> Self {
        Self::new()
    }
}
