// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Extended C Code Emitter
//!
//! Higher-level C emission: type mapping, function declarations, body emission
//! with control flow, RC calls, closure representation, string/array literals,
//! FFI wrappers, header file generation, include guards, and statistics.
//!
//! Part of #3084 - IO/FFI/Native.

use std::fmt::Write as FmtWrite;

use crate::emit_base::EmitterBase;
use crate::ir::{FnId, IRAlt, IRArg, IRBody, IRDecl, IRExpr, IRLiteral, IRType, VarId};
use crate::ir_checker::IRError;
use crate::mangle::mangle_name;

/// Statistics collected during C emission.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct EmitStats {
    pub(crate) functions_emitted: u32,
    pub(crate) closures_emitted: u32,
    pub(crate) ffi_wrappers_emitted: u32,
    pub(crate) rc_ops_emitted: u32,
    pub(crate) string_literals_emitted: u32,
    pub(crate) array_literals_emitted: u32,
}

/// Configuration for the extended C emitter.
#[derive(Debug, Clone)]
pub(crate) struct CExtEmitConfig {
    pub(crate) module_name: String,
    pub(crate) debug: bool,
    pub(crate) indent: String,
}

impl Default for CExtEmitConfig {
    fn default() -> Self {
        Self {
            module_name: "clean_module".to_string(),
            debug: false,
            indent: "  ".to_string(),
        }
    }
}

/// FFI function descriptor for extern "C" wrapper generation.
#[derive(Debug, Clone)]
pub(crate) struct FfiFunc {
    pub(crate) lean_name: String,
    pub(crate) c_name: String,
    pub(crate) param_types: Vec<IRType>,
    pub(crate) return_type: IRType,
}

/// Extended C code emitter with statistics and header generation.
pub(crate) struct CExtEmitter {
    base: EmitterBase,
    config: CExtEmitConfig,
    stats: EmitStats,
}

impl CExtEmitter {
    pub(crate) fn new() -> Self {
        Self::with_config(CExtEmitConfig::default())
    }

    pub(crate) fn with_config(config: CExtEmitConfig) -> Self {
        Self {
            base: EmitterBase::new(config.indent.clone()),
            config,
            stats: EmitStats::default(),
        }
    }

    pub(crate) fn finish(self) -> String {
        self.base.finish()
    }
    pub(crate) fn stats(&self) -> &EmitStats {
        &self.stats
    }

    fn writeln(&mut self, s: &str) {
        self.base.writeln(s);
    }
    fn indent(&mut self) {
        self.base.indent();
    }
    fn dedent(&mut self) {
        self.base.dedent();
    }

    // ── Type mapping ──

    pub(crate) fn map_type(ty: &IRType) -> &'static str {
        match ty {
            IRType::Bool | IRType::UInt8 => "uint8_t",
            IRType::UInt16 => "uint16_t",
            IRType::UInt32 => "uint32_t",
            IRType::UInt64 => "uint64_t",
            IRType::USize => "size_t",
            IRType::Float32 => "float",
            IRType::Float64 => "double",
            IRType::Object
            | IRType::TObject
            | IRType::Struct(_)
            | IRType::Union(_)
            | IRType::Erased => "lean_object*",
            IRType::Void => "void",
        }
    }

    fn emit_type(&self, ty: &IRType) -> &'static str {
        Self::map_type(ty)
    }
    fn emit_fn_name(&self, name: &clean_kernel::Name) -> String {
        mangle_name(name)
    }
    fn emit_var(&self, var: VarId) -> String {
        self.base.emit_var(var)
    }
    fn emit_arg(&self, arg: &IRArg) -> String {
        self.base.emit_arg(arg)
    }

    fn format_params(&self, params: &[(VarId, IRType)]) -> String {
        if params.is_empty() {
            return "void".to_string();
        }
        params
            .iter()
            .map(|(var, ty)| format!("{} {}", self.emit_type(ty), self.emit_var(*var)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    // ── Include guard and header management ──

    pub(crate) fn emit_source_header(&mut self) {
        self.writeln(&format!(
            "// Generated by clean compiler — module: {}",
            self.config.module_name
        ));
        self.writeln("// Do not edit manually");
        self.writeln("");
        for h in &["stdint.h", "stddef.h", "stdbool.h", "string.h"] {
            self.writeln(&format!("#include <{}>", h));
        }
        self.writeln("#include \"lean_runtime.h\"");
        self.writeln("");
    }

    pub(crate) fn emit_header_file(&mut self, decls: &[IRDecl]) {
        self.writeln("#pragma once");
        self.writeln("");
        self.writeln("// Generated by clean compiler (extended C backend)");
        self.writeln("// Do not edit manually");
        self.writeln("");
        for h in &["stdint.h", "stddef.h"] {
            self.writeln(&format!("#include <{}>", h));
        }
        self.writeln("#include \"lean_runtime.h\"");
        self.writeln("");
        for decl in decls {
            self.emit_forward_decl(decl);
        }
    }

    fn emit_forward_decl(&mut self, decl: &IRDecl) {
        let (fn_name, ret_ty, params) = (
            self.emit_fn_name(&decl.name),
            self.emit_type(&decl.return_type),
            self.format_params(&decl.params),
        );
        self.writeln(&format!("{} {}({});", ret_ty, fn_name, params));
    }

    // ── Function emission ──

    pub(crate) fn emit_function(&mut self, decl: &IRDecl) -> Result<(), IRError> {
        let (fn_name, ret_ty, params) = (
            self.emit_fn_name(&decl.name),
            self.emit_type(&decl.return_type),
            self.format_params(&decl.params),
        );
        self.writeln(&format!("{} {}({}) {{", ret_ty, fn_name, params));
        self.indent();
        self.emit_body(&decl.body)?;
        self.dedent();
        self.writeln("}");
        self.writeln("");
        self.stats.functions_emitted += 1;
        Ok(())
    }

    pub(crate) fn emit_functions(&mut self, decls: &[IRDecl]) -> Result<(), IRError> {
        for decl in decls {
            self.emit_forward_decl(decl);
        }
        self.writeln("");
        for decl in decls {
            self.emit_function(decl)?;
        }
        Ok(())
    }

    // ── Body emission ──

    fn emit_body(&mut self, body: &IRBody) -> Result<(), IRError> {
        match body {
            IRBody::VDecl {
                var,
                ty,
                value,
                rest,
            } => {
                let (ty_s, var_s, val_s) = (
                    self.emit_type(ty),
                    self.emit_var(*var),
                    self.emit_expr(value)?,
                );
                self.writeln(&format!("{} {} = {};", ty_s, var_s, val_s));
                self.emit_body(rest)?;
            }
            IRBody::JDecl {
                jp,
                params,
                body: jp_body,
                rest,
            } => {
                for (var, ty) in params {
                    self.writeln(&format!("{} {};", self.emit_type(ty), self.emit_var(*var)));
                }
                self.emit_body(rest)?;
                self.writeln(&format!("_jp{}:", jp.0));
                self.indent();
                self.emit_body(jp_body)?;
                self.dedent();
            }
            IRBody::Inc { var, n, rest } => {
                let v = self.emit_var(*var);
                if *n == 1 {
                    self.writeln(&format!("lean_inc_ref({});", v));
                } else {
                    self.writeln(&format!("lean_inc_ref_n({}, {});", v, n));
                }
                self.stats.rc_ops_emitted += 1;
                self.emit_body(rest)?;
            }
            IRBody::Dec { var, rest } => {
                self.writeln(&format!("lean_dec_ref({});", self.emit_var(*var)));
                self.stats.rc_ops_emitted += 1;
                self.emit_body(rest)?;
            }
            IRBody::Set {
                var,
                idx,
                value,
                rest,
            } => {
                let (v, val) = (self.emit_var(*var), self.emit_var(*value));
                self.writeln(&format!("lean_ctor_set({}, {}, {});", v, idx, val));
                self.emit_body(rest)?;
            }
            IRBody::SetTag { var, tag, rest } => {
                self.writeln(&format!(
                    "lean_ctor_set_tag({}, {});",
                    self.emit_var(*var),
                    tag
                ));
                self.emit_body(rest)?;
            }
            IRBody::USet {
                var,
                idx,
                value,
                rest,
            } => {
                let (v, val) = (self.emit_var(*var), self.emit_var(*value));
                self.writeln(&format!("lean_ctor_set_usize({}, {}, {});", v, idx, val));
                self.emit_body(rest)?;
            }
            IRBody::SSet {
                var,
                n,
                offset,
                value,
                ty,
                rest,
            } => {
                let byte_off = (*n as usize) * size_of::<usize>() + (*offset as usize);
                self.writeln(&format!(
                    "{}({}, {}, {});",
                    scalar_setter_name(ty),
                    self.emit_var(*var),
                    byte_off,
                    self.emit_var(*value)
                ));
                self.emit_body(rest)?;
            }
            IRBody::Case {
                scrutinee,
                alts,
                default,
            } => {
                self.emit_case(*scrutinee, alts, default.as_deref())?;
            }
            IRBody::Jmp { jp, args } => {
                for (i, arg) in args.iter().enumerate() {
                    self.writeln(&format!("_jp{}_arg{} = {};", jp.0, i, self.emit_arg(arg)));
                }
                self.writeln(&format!("goto _jp{};", jp.0));
            }
            IRBody::Ret(arg) => {
                self.writeln(&format!("return {};", self.emit_arg(arg)));
            }
            IRBody::Unreachable => {
                if self.config.debug {
                    self.writeln("lean_panic(\"unreachable\");");
                } else {
                    self.writeln("__builtin_unreachable();");
                }
            }
        }
        Ok(())
    }

    fn emit_case(
        &mut self,
        scrutinee: VarId,
        alts: &[IRAlt],
        default: Option<&IRBody>,
    ) -> Result<(), IRError> {
        self.writeln(&format!(
            "switch (lean_obj_tag({})) {{",
            self.emit_var(scrutinee)
        ));
        self.indent();
        for alt in alts {
            self.writeln(&format!("case {}: {{", alt.ctor.tag));
            self.indent();
            self.emit_body(&alt.body)?;
            self.writeln("break;");
            self.dedent();
            self.writeln("}");
        }
        if let Some(def) = default {
            self.writeln("default: {");
            self.indent();
            self.emit_body(def)?;
            self.writeln("break;");
            self.dedent();
            self.writeln("}");
        }
        self.dedent();
        self.writeln("}");
        Ok(())
    }

    // ── Expression emission ──

    fn emit_expr(&mut self, expr: &IRExpr) -> Result<String, IRError> {
        Ok(match expr {
            IRExpr::Ctor { info, args } => {
                let a = self.base.emit_args_joined(args);
                if args.is_empty() && info.scalar_size() == 0 {
                    format!("lean_box({})", info.tag)
                } else if args.is_empty() {
                    format!("lean_alloc_ctor({}, 0, {})", info.tag, info.scalar_size())
                } else {
                    format!(
                        "lean_alloc_ctor({}, {}, {}, {})",
                        info.tag,
                        info.num_objects,
                        info.scalar_size(),
                        a
                    )
                }
            }
            IRExpr::Proj { idx, ty, arg } => {
                let g = match ty {
                    IRType::UInt8 => "lean_ctor_get_uint8",
                    IRType::UInt16 => "lean_ctor_get_uint16",
                    IRType::UInt32 => "lean_ctor_get_uint32",
                    IRType::UInt64 => "lean_ctor_get_uint64",
                    IRType::USize => "lean_ctor_get_usize",
                    IRType::Float64 => "lean_ctor_get_float",
                    IRType::Float32 => "lean_ctor_get_float32",
                    _ => "lean_ctor_get",
                };
                format!("{}({}, {})", g, self.emit_arg(arg), idx)
            }
            IRExpr::Tag(arg) => format!("lean_obj_tag({})", self.emit_arg(arg)),
            IRExpr::Box { ty, arg } => match ty {
                IRType::UInt64 => format!("lean_box_uint64({})", self.emit_arg(arg)),
                IRType::UInt32 => format!("lean_box_uint32({})", self.emit_arg(arg)),
                IRType::Float64 => format!("lean_box_float({})", self.emit_arg(arg)),
                _ => format!("lean_box((size_t){})", self.emit_arg(arg)),
            },
            IRExpr::Unbox { ty, arg } => match ty {
                IRType::Float64 => format!("lean_unbox_float({})", self.emit_arg(arg)),
                IRType::UInt64 => format!("lean_unbox_uint64({})", self.emit_arg(arg)),
                IRType::UInt32 => format!("lean_unbox_uint32({})", self.emit_arg(arg)),
                _ => format!("lean_unbox({})", self.emit_arg(arg)),
            },
            IRExpr::Lit(lit) => emit_c_literal(lit),
            IRExpr::Apply { fn_id, args } => {
                format!(
                    "{}({})",
                    self.base.emit_fn_id(fn_id),
                    self.base.emit_args_joined(args)
                )
            }
            IRExpr::PartialApply { fn_id, arity, args } => {
                self.stats.closures_emitted += 1;
                self.emit_closure_alloc(fn_id, *arity, args)
            }
            IRExpr::ClosureApply { closure, args } => self.emit_closure_apply(closure, args),
            IRExpr::UProj { idx, var } => {
                format!("lean_ctor_get_usize({}, {})", self.emit_var(*var), idx)
            }
            IRExpr::SProj { n, offset, var, ty } => {
                let byte_off = (*n as usize) * size_of::<usize>() + (*offset as usize);
                format!(
                    "{}({}, {})",
                    scalar_getter_name(ty),
                    self.emit_var(*var),
                    byte_off
                )
            }
            IRExpr::IsShared(var) => format!("!lean_is_exclusive({})", self.emit_var(*var)),
            IRExpr::String(s) => {
                self.stats.string_literals_emitted += 1;
                format!("lean_mk_string({})", escape_c_string(s))
            }
            IRExpr::Reset(var) => format!("lean_reset({})", self.emit_var(*var)),
            IRExpr::Reuse { var, ctor, args } => {
                let a = self.base.emit_args_joined(args);
                if args.is_empty() {
                    format!(
                        "lean_reuse({}, {}, 0, {})",
                        self.emit_var(*var),
                        ctor.tag,
                        ctor.scalar_size()
                    )
                } else {
                    format!(
                        "lean_reuse({}, {}, {}, {}, {})",
                        self.emit_var(*var),
                        ctor.tag,
                        ctor.num_objects,
                        ctor.scalar_size(),
                        a
                    )
                }
            }
        })
    }

    // ── Closure representation ──

    fn emit_closure_alloc(&self, fn_id: &FnId, arity: u16, args: &[IRArg]) -> String {
        let (name, a) = (
            self.base.emit_fn_id(fn_id),
            self.base.emit_args_joined(args),
        );
        if args.is_empty() {
            format!("lean_alloc_closure((void*){}, {}, 0)", name, arity)
        } else {
            format!(
                "lean_alloc_closure((void*){}, {}, {}, {})",
                name,
                arity,
                args.len(),
                a
            )
        }
    }

    fn emit_closure_apply(&self, closure: &IRArg, args: &[IRArg]) -> String {
        let n = args.len();
        if n <= 16 {
            let mut ca = vec![self.emit_arg(closure)];
            ca.extend(args.iter().map(|a| self.emit_arg(a)));
            format!("lean_apply_{}({})", n, ca.join(", "))
        } else {
            format!(
                "lean_apply_n({}, {}, (lean_object*[]){{{}}})",
                self.emit_arg(closure),
                n,
                self.base.emit_args_joined(args)
            )
        }
    }

    // ── Array literal emission ──

    pub(crate) fn emit_array_literal(&mut self, var: VarId, elements: &[IRArg]) -> String {
        self.stats.array_literals_emitted += 1;
        let var_str = self.emit_var(var);
        let mut out = String::new();
        let _ = writeln!(
            out,
            "lean_object* {} = lean_alloc_array({}, {});",
            var_str,
            elements.len(),
            elements.len()
        );
        for (i, elem) in elements.iter().enumerate() {
            let _ = writeln!(
                out,
                "lean_array_set_core({}, {}, {});",
                var_str,
                i,
                self.emit_arg(elem)
            );
        }
        out
    }

    // ── FFI wrapper generation ──

    pub(crate) fn emit_extern_c_decl(&mut self, func: &FfiFunc) {
        let params = if func.param_types.is_empty() {
            "void".to_string()
        } else {
            func.param_types
                .iter()
                .map(|ty| Self::map_type(ty).to_string())
                .collect::<Vec<_>>()
                .join(", ")
        };
        self.writeln(&format!(
            "extern {} {}({});",
            Self::map_type(&func.return_type),
            func.c_name,
            params
        ));
    }

    pub(crate) fn emit_ffi_wrapper(&mut self, func: &FfiFunc) {
        let ret_ty = Self::map_type(&func.return_type);
        let wrapper_name = format!("l_{}", func.c_name);
        let params: Vec<String> = func
            .param_types
            .iter()
            .enumerate()
            .map(|(i, ty)| format!("{} _a{}", Self::map_type(ty), i))
            .collect();
        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        self.writeln(&format!("{} {}({}) {{", ret_ty, wrapper_name, params_str));
        self.indent();
        let call_args: Vec<String> = (0..func.param_types.len())
            .map(|i| format!("_a{}", i))
            .collect();
        if func.return_type == IRType::Void {
            self.writeln(&format!("{}({});", func.c_name, call_args.join(", ")));
        } else {
            self.writeln(&format!(
                "return {}({});",
                func.c_name,
                call_args.join(", ")
            ));
        }
        self.dedent();
        self.writeln("}");
        self.writeln("");
        self.stats.ffi_wrappers_emitted += 1;
    }

    // ── Full module emission ──

    pub(crate) fn emit_module(
        &mut self,
        decls: &[IRDecl],
        ffi_funcs: &[FfiFunc],
    ) -> Result<(), IRError> {
        self.emit_source_header();
        if !ffi_funcs.is_empty() {
            self.writeln("/* ── Extern (FFI) declarations ── */");
            self.writeln("");
            for func in ffi_funcs {
                self.emit_extern_c_decl(func);
            }
            self.writeln("");
        }
        self.emit_functions(decls)?;
        if !ffi_funcs.is_empty() {
            self.writeln("/* ── FFI wrappers ── */");
            self.writeln("");
            for func in ffi_funcs {
                self.emit_ffi_wrapper(func);
            }
        }
        Ok(())
    }
}

impl Default for CExtEmitter {
    fn default() -> Self {
        Self::new()
    }
}

// ── Free functions ──

fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => {
                for byte in c.to_string().as_bytes() {
                    let _ = write!(out, "\\x{:02x}", byte);
                }
            }
        }
    }
    out.push('"');
    out
}

fn emit_c_literal(lit: &IRLiteral) -> String {
    match lit {
        IRLiteral::Bool(b) => if *b { "1" } else { "0" }.to_string(),
        IRLiteral::UInt8(n) => format!("UINT8_C({})", n),
        IRLiteral::UInt16(n) => format!("UINT16_C({})", n),
        IRLiteral::UInt32(n) => format!("UINT32_C({})", n),
        IRLiteral::UInt64(n) => format!("UINT64_C({})", n),
        IRLiteral::USize(n) => format!("(size_t){}", n),
        IRLiteral::NatBig(v) => format!(
            "clean_nat_big(UINT64_C({}), UINT64_C({}))",
            *v as u64,
            (*v >> 64) as u64
        ),
        IRLiteral::Float32(f) => format!("{}f", f),
        IRLiteral::Float64(f) => format!("{}", f),
    }
}

fn scalar_getter_name(ty: &IRType) -> &'static str {
    match ty {
        IRType::UInt8 | IRType::Bool => "lean_ctor_get_uint8",
        IRType::UInt16 => "lean_ctor_get_uint16",
        IRType::UInt32 => "lean_ctor_get_uint32",
        IRType::UInt64 => "lean_ctor_get_uint64",
        IRType::Float32 => "lean_ctor_get_float32",
        IRType::Float64 => "lean_ctor_get_float",
        IRType::USize => "lean_ctor_get_usize",
        _ => "lean_ctor_get",
    }
}

fn scalar_setter_name(ty: &IRType) -> &'static str {
    match ty {
        IRType::UInt8 | IRType::Bool => "lean_ctor_set_uint8",
        IRType::UInt16 => "lean_ctor_set_uint16",
        IRType::UInt32 => "lean_ctor_set_uint32",
        IRType::UInt64 => "lean_ctor_set_uint64",
        IRType::Float32 => "lean_ctor_set_float32",
        IRType::Float64 => "lean_ctor_set_float",
        IRType::USize => "lean_ctor_set_usize",
        _ => "lean_ctor_set",
    }
}
