/*
 * clean C FFI Bindings
 * Copyright 2026 Andrew Yates
 * Author: Andrew Yates <andrewyates.name@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * Auto-generated header file. Do not edit manually.
 * Regenerate with: cbindgen --config cbindgen.toml -o include/clean.h
 */


#ifndef CLEAN_H
#define CLEAN_H

/* Generated with cbindgen:0.27.0 */

/* Warning: this file was auto-generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque environment handle.
 */
typedef struct cleanEnv cleanEnv;

/**
 * Opaque error handle.
 */
typedef struct cleanError cleanError;

/**
 * Opaque expression handle.
 */
typedef struct cleanExpr cleanExpr;

/**
 * Opaque type checker handle.
 */
typedef struct cleanTypeChecker cleanTypeChecker;

/**
 * Create a new empty environment.
 *
 * NOTE: Aborts the process on allocation failure (standard Rust OOM behavior).
 */
struct cleanEnv *clean_env_new(void);

/**
 * Create an environment with the Lean4 Init module loaded.
 *
 * If `path` is non-NULL, it is treated as an additional search path for .olean files.
 * If `path` is NULL, only the default search paths are used:
 * 1. `MATHLIB_PATH` environment variable entries (if set)
 * 2. `LEAN_PATH` environment variable entries
 * 3. `~/.elan/toolchains/<version>/lib/lean`
 *
 * Returns NULL on error and sets `err_out` if provided.
 *
 * # Safety
 *
 * If `path` is not NULL, it must be a valid null-terminated C string.
 */
struct cleanEnv *clean_env_with_init(const char *path, struct cleanError **err_out);

/**
 * Free an environment.
 *
 * # Safety
 *
 * `env` must be a valid pointer from `clean_env_new` or NULL.
 */
void clean_env_free(struct cleanEnv *env);

/**
 * Create a new type checker for the given environment.
 *
 * The type checker borrows the environment - the environment must outlive
 * the type checker.
 *
 * # Safety
 *
 * `env` must be a valid pointer to a `cleanEnv`.
 */
struct cleanTypeChecker *clean_tc_new(const struct cleanEnv *env);

/**
 * Free a type checker.
 *
 * # Safety
 *
 * `tc` must be a valid pointer from `clean_tc_new` or NULL.
 */
void clean_tc_free(struct cleanTypeChecker *tc);

/**
 * Infer the type of an expression.
 *
 * Returns the inferred type, or NULL on error. If `err_out` is not NULL,
 * sets it to the error on failure.
 *
 * # Safety
 *
 * - `tc` must be a valid pointer to a `cleanTypeChecker`
 * - `expr` must be a valid pointer to a `cleanExpr`
 */
struct cleanExpr *clean_infer_type(struct cleanTypeChecker *tc,
                                   const struct cleanExpr *expr,
                                   struct cleanError **err_out);

/**
 * Check if two expressions are definitionally equal.
 *
 * # Safety
 *
 * - `tc` must be a valid pointer to a `cleanTypeChecker`
 * - `a` and `b` must be valid pointers to `cleanExpr`
 */
bool clean_is_def_eq(struct cleanTypeChecker *tc,
                     const struct cleanExpr *a,
                     const struct cleanExpr *b);

/**
 * Reduce an expression to weak head normal form.
 *
 * Returns the reduced expression. Returns NULL if `tc` or `expr` is NULL.
 *
 * # Safety
 *
 * If non-NULL, `tc` and `expr` must be valid pointers.
 */
struct cleanExpr *clean_whnf(struct cleanTypeChecker *tc, const struct cleanExpr *expr);

/**
 * Create a constant expression from a name string.
 *
 * # Safety
 *
 * `name` must be a valid null-terminated C string.
 */
struct cleanExpr *clean_expr_const(const char *name);

/**
 * Create an application expression: `f a`.
 *
 * # Safety
 *
 * `f` and `a` must be valid pointers to `cleanExpr`.
 */
struct cleanExpr *clean_expr_app(const struct cleanExpr *f, const struct cleanExpr *a);

/**
 * Create a lambda expression: `λ x : ty. body`.
 *
 * The body should use BVar(0) to refer to the bound variable.
 *
 * # Safety
 *
 * `ty` and `body` must be valid pointers to `cleanExpr`.
 */
struct cleanExpr *clean_expr_lam(const struct cleanExpr *ty, const struct cleanExpr *body);

/**
 * Create a pi (forall) expression: `∀ x : ty. body`.
 *
 * The body should use BVar(0) to refer to the bound variable.
 *
 * # Safety
 *
 * `ty` and `body` must be valid pointers to `cleanExpr`.
 */
struct cleanExpr *clean_expr_pi(const struct cleanExpr *ty, const struct cleanExpr *body);

/**
 * Create a natural number literal expression.
 */
struct cleanExpr *clean_expr_nat(uint64_t n);

/**
 * Create the Prop sort expression (Sort 0).
 */
struct cleanExpr *clean_expr_prop(void);

/**
 * Create the Type sort expression (Sort 1).
 */
struct cleanExpr *clean_expr_type(void);

/**
 * Create a Sort expression at the given level.
 */
struct cleanExpr *clean_expr_sort(uint32_t level);

/**
 * Create a bound variable expression.
 *
 * De Bruijn index 0 refers to the innermost binder.
 */
struct cleanExpr *clean_expr_bvar(uint32_t idx);

/**
 * Free an expression.
 *
 * # Safety
 *
 * `expr` must be a valid pointer from an expression constructor or NULL.
 */
void clean_expr_free(struct cleanExpr *expr);

/**
 * Get the error message as a C string.
 *
 * The returned pointer is valid until `clean_error_free` is called.
 *
 * # Safety
 *
 * `err` must be a valid pointer to a `cleanError`.
 */
const char *clean_error_message(const struct cleanError *err);

/**
 * Free an error.
 *
 * # Safety
 *
 * `err` must be a valid pointer from error output or NULL.
 */
void clean_error_free(struct cleanError *err);

/**
 * Get the version string of the clean library.
 *
 * Returns the Cargo package version (from `CARGO_PKG_VERSION`).
 */
const char *clean_version(void);

#endif  /* CLEAN_H */
