// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (basics).
//
// Generated by splitting tc/tests.rs into submodules for maintainability.

use super::*;

#[test]
fn test_infer_sort() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Type of Prop is Type 1
    let prop = Expr::prop();
    let ty = tc.infer_type(&prop).unwrap();
    assert!(matches!(&ty.kind, ExprKind::Sort(_)));
}

#[test]
fn test_infer_sort_type_family_fvar() {
    use crate::level::Level;

    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    let u = Name::from_string("u");
    let v = Name::from_string("v");
    let alpha_sort = Expr::from_kind(ExprKind::Sort(Level::param(u.clone())));
    let alpha = tc.ctx_push(Name::from_string("alpha"), alpha_sort, BinderInfo::Implicit);
    let beta_type = Expr::pi(
        BinderInfo::Default,
        Expr::from_kind(ExprKind::FVar(alpha)),
        Expr::from_kind(ExprKind::Sort(Level::param(v.clone()))),
    );
    let beta = tc.ctx_push(Name::from_string("beta"), beta_type, BinderInfo::Implicit);

    let beta_expr = Expr::from_kind(ExprKind::FVar(beta));
    let beta_sort = tc.infer_sort(&beta_expr).unwrap();
    let expected = Level::imax(Level::param(u), Level::succ(Level::param(v)));
    assert_eq!(beta_sort, expected);
}

#[test]
fn test_infer_sort_squash_prop_returns_zero_level() {
    use crate::level::Level;

    let env = Environment::with_mode(CleanMode::Impredicative);
    let tc = TypeChecker::with_mode(&env, CleanMode::Impredicative);
    let squash_prop = Expr::from_kind(ExprKind::Squash(std::sync::Arc::new(Expr::prop())));

    let level = tc
        .infer_sort(&squash_prop)
        .expect("infer_sort should accept Squash(Prop) via SProp");

    assert_eq!(level, Level::zero());
}

#[test]
fn test_whnf_beta() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // (λ x. x) y should reduce to y
    let id_fn = Expr::lam(
        BinderInfo::Default,
        Expr::prop(), // dummy type
        Expr::bvar(0),
    );
    let arg = Expr::prop();
    let app = Expr::app(id_fn, arg.clone());

    let result = tc.whnf(&app);
    assert_eq!(result, arg);
}

#[test]
fn test_literal_types() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Natural number literal should have type Nat
    let nat_lit = Expr::nat_lit(42);
    let ty = tc.infer_type(&nat_lit).unwrap();
    assert_eq!(ty, Expr::const_(Name::from_string("Nat"), vec![]));

    // String literal should have type String
    let str_lit = Expr::str_lit("hello");
    let ty = tc.infer_type(&str_lit).unwrap();
    assert_eq!(ty, Expr::const_(Name::from_string("String"), vec![]));
}

#[test]
fn test_infer_pi() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // (x : Prop) → Prop should have type Type 1
    let pi = Expr::pi(BinderInfo::Default, Expr::prop(), Expr::prop());
    let ty = tc.infer_type(&pi).unwrap();
    // Type of (x : Prop) → Prop is Sort(imax(0, 0)) = Sort(0) = Prop
    assert!(ty.is_sort());
}

#[test]
fn test_infer_lambda() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // λ (x : Prop). x should have type Prop → Prop
    let lam = Expr::lam(BinderInfo::Default, Expr::prop(), Expr::bvar(0));
    let ty = tc.infer_type(&lam).unwrap();

    // Should be Pi(Default, Prop, Prop)
    match &ty.kind {
        ExprKind::Pi(_, arg_ty, body_ty) => {
            assert!(arg_ty.is_prop());
            assert!(body_ty.is_prop());
        }
        _ => panic!("Expected Pi type, got {ty:?}"),
    }
}

#[test]
fn test_infer_app_simple() {
    use crate::env::Declaration;

    let mut env = Environment::new();

    // Add a simple non-polymorphic identity: idProp : Prop → Prop
    let id_type = Expr::pi(BinderInfo::Default, Expr::prop(), Expr::prop());
    let id_value = Expr::lam(BinderInfo::Default, Expr::prop(), Expr::bvar(0));
    env.add_decl(Declaration::Definition {
        name: Name::from_string("idProp"),
        level_params: vec![],
        type_: id_type,
        value: id_value,
        is_reducible: true,
    })
    .unwrap();

    // Add a simple Prop inhabitant: p : Prop
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("p"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    // Apply idProp to p
    // idProp p : Prop
    let id_const = Expr::const_(Name::from_string("idProp"), vec![]);
    let p = Expr::const_(Name::from_string("p"), vec![]);
    let app = Expr::app(id_const, p);

    let ty = tc.infer_type(&app).unwrap();
    assert!(ty.is_prop());
}

#[test]
fn test_infer_app_universe_poly() {
    use crate::env::Declaration;
    use crate::level::Level;

    let mut env = Environment::new();

    // Add id : {A : Sort u} → A → A (universe polymorphic)
    // Note: Sort u, not Type u, so it works for Prop too
    let u = Name::from_string("u");
    let id_type = Expr::pi(
        BinderInfo::Implicit,
        Expr::from_kind(ExprKind::Sort(Level::param(u.clone()))), // Sort u - accepts Prop (Sort 0) or Type u-1
        Expr::pi(BinderInfo::Default, Expr::bvar(0), Expr::bvar(1)),
    );
    let id_value = Expr::lam(
        BinderInfo::Implicit,
        Expr::from_kind(ExprKind::Sort(Level::param(u.clone()))),
        Expr::lam(BinderInfo::Default, Expr::bvar(0), Expr::bvar(0)),
    );
    env.add_decl(Declaration::Definition {
        name: Name::from_string("id"),
        level_params: vec![u.clone()],
        type_: id_type,
        value: id_value,
        is_reducible: true,
    })
    .unwrap();

    // Add a Prop axiom
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("P"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    // Apply id.{1} to Prop (at level 1, first arg has type Sort 1 = Type)
    // id.{1} : {A : Sort 1} → A → A
    //        = {A : Type} → A → A
    // Prop : Sort 1 = Type ✓
    // id.{1} Prop : Prop → Prop
    let one = Level::succ(Level::zero());
    let id_const = Expr::const_(Name::from_string("id"), vec![one]);
    let app1 = Expr::app(id_const, Expr::prop()); // id.{1} Prop : Prop → Prop

    let p = Expr::const_(Name::from_string("P"), vec![]);
    let app2 = Expr::app(app1, p); // id.{1} Prop P : Prop

    let ty = tc.infer_type(&app2).unwrap();
    assert!(ty.is_prop());
}

#[test]
fn test_infer_let() {
    use crate::env::Declaration;

    let mut env = Environment::new();

    // Add P : Prop
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("P"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    // let x : Prop := P in x
    // x has type Prop, so the whole expression has type Prop
    let p_const = Expr::const_(Name::from_string("P"), vec![]);
    let let_expr = Expr::let_named(Name::anon(), Expr::prop(), p_const, Expr::bvar(0), false);

    let ty = tc.infer_type(&let_expr).unwrap();
    assert!(ty.is_prop());
}

#[test]
fn test_infer_let_body_type_depends_on_bound_var() {
    // Regression test for FVar escape in Let type inference.
    // Without abstract_fvar before instantiate, the body type retains
    // dangling FVar references instead of substituting the let value.
    //
    // Lean 4 equivalent: `let x : Type := Prop in (fun (a : x) => a)`
    // Expected type: Prop → Prop
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // let x : Type := Prop in (λ (a : x), a)
    //   BVar(0) in lambda type = let-bound x
    //   BVar(0) in lambda body = lambda-bound a
    let let_expr = Expr::let_named(
        Name::anon(),
        Expr::type_(),                                                // x : Type
        Expr::prop(),                                                 // x := Prop
        Expr::lam(BinderInfo::Default, Expr::bvar(0), Expr::bvar(0)), // λ (a : x), a
        false,
    );

    let ty = tc.infer_type(&let_expr).unwrap();
    // After instantiation: Prop → Prop = Pi(Default, Prop, Prop)
    match &ty.kind {
        ExprKind::Pi(_, domain, codomain) => {
            assert!(domain.is_prop(), "domain should be Prop, got {domain:?}");
            assert!(
                codomain.is_prop(),
                "codomain should be Prop, got {codomain:?}"
            );
        }
        _ => panic!("Expected Pi type (Prop → Prop), got {ty:?}"),
    }
}

#[test]
fn test_infer_let_identity_non_dependent_body() {
    // Simpler Let case: body type does NOT depend on the let-bound variable.
    // let x : Type := Prop in x  →  type is Type
    // This complements test_infer_let_body_type_depends_on_bound_var above.
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    let let_expr = Expr::let_named(
        Name::anon(),
        Expr::type_(), // x : Type
        Expr::prop(),  // x := Prop
        Expr::bvar(0), // body = x
        false,
    );

    let ty = tc.infer_type(&let_expr).unwrap();
    // The body is x, whose declared type is Type.
    // abstract_fvar + instantiate on Type (no FVars) = Type.
    // Type = Sort(1). The body's type doesn't depend on x, so no FVar issue.
    match &ty.kind {
        ExprKind::Sort(l) => assert!(!l.is_zero(), "Expected Type (Sort 1+), got Prop"),
        _ => panic!("let x : Type := Prop in x should have type Type (Sort), got {ty:?}"),
    }
}

#[test]
fn test_whnf_let() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // let x := Prop in x should reduce to Prop
    let let_expr = Expr::let_named(
        Name::anon(),
        Expr::type_(),
        Expr::prop(),
        Expr::bvar(0),
        false,
    );
    let result = tc.whnf(&let_expr);
    assert!(result.is_prop());
}

#[test]
fn test_whnf_delta() {
    use crate::env::Declaration;

    let mut env = Environment::new();

    // Define myProp := Prop
    env.add_decl(Declaration::Definition {
        name: Name::from_string("myProp"),
        level_params: vec![],
        type_: Expr::type_(),
        value: Expr::prop(),
        is_reducible: true,
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    // myProp should reduce to Prop
    let const_expr = Expr::const_(Name::from_string("myProp"), vec![]);
    let result = tc.whnf(&const_expr);
    assert!(result.is_prop());
}

#[test]
fn test_def_eq_levels() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Sort(0) == Sort(0)
    assert!(tc.is_def_eq(&Expr::prop(), &Expr::prop()));

    // Sort(1) == Sort(1)
    assert!(tc.is_def_eq(&Expr::type_(), &Expr::type_()));

    // Sort(0) != Sort(1)
    assert!(!tc.is_def_eq(&Expr::prop(), &Expr::type_()));

    // Sort(max(0, 0)) == Sort(0)
    use crate::level::Level;
    let max_00 = Level::max(Level::zero(), Level::zero());
    assert!(tc.is_def_eq(&Expr::from_kind(ExprKind::Sort(max_00)), &Expr::prop()));
}

#[test]
fn test_def_eq_beta() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // (λ x. x) Prop == Prop
    let id_lam = Expr::lam(BinderInfo::Default, Expr::type_(), Expr::bvar(0));
    let app = Expr::app(id_lam, Expr::prop());
    assert!(tc.is_def_eq(&app, &Expr::prop()));
}

#[test]
fn test_check_type_ok() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Check that Prop : Type
    tc.check_type(&Expr::prop(), &Expr::type_())
        .expect("Prop : Type should type-check");
}

#[test]
fn test_check_type_error() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Check that Prop : Prop should fail
    let err = tc
        .check_type(&Expr::prop(), &Expr::prop())
        .expect_err("Prop : Prop must fail type checking");
    assert!(
        matches!(err, TypeError::TypeMismatch { .. }),
        "expected TypeMismatch, got {err:?}"
    );
}

#[test]
fn test_nested_lambda() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // λ (A : Type) (x : A). x
    // This has type (A : Type) → A → A
    let inner_lam = Expr::lam(BinderInfo::Default, Expr::bvar(0), Expr::bvar(0));
    let outer_lam = Expr::lam(BinderInfo::Default, Expr::type_(), inner_lam);

    let ty = tc.infer_type(&outer_lam).unwrap();
    match &ty.kind {
        ExprKind::Pi(_, outer_ty, inner) => {
            assert!(matches!(&outer_ty.as_ref().kind, ExprKind::Sort(_)));
            match &inner.as_ref().kind {
                ExprKind::Pi(_, _, _) => {} // OK
                _ => panic!("Expected nested Pi type"),
            }
        }
        _ => panic!("Expected Pi type"),
    }
}

#[test]
fn test_environment_duplicate() {
    use crate::env::Declaration;

    let mut env = Environment::new();

    env.add_decl(Declaration::Axiom {
        name: Name::from_string("A"),
        level_params: vec![],
        type_: Expr::type_(),
    })
    .unwrap();

    // Adding same name again should fail
    let err = env
        .add_decl(Declaration::Axiom {
            name: Name::from_string("A"),
            level_params: vec![],
            type_: Expr::type_(),
        })
        .expect_err("adding duplicate constant name must fail");
    assert!(
        matches!(err, crate::EnvError::DuplicateName(ref name) if *name == Name::from_string("A")),
        "expected duplicate A error, got {err:?}"
    );
}

#[test]
fn test_whnf_iota_simple() {
    // Test iota reduction: Nat.rec on Nat.zero should reduce to the zero case
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define Nat
    let nat = Name::from_string("Nat");
    let nat_ref = Expr::const_(nat.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_ref.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::arrow(nat_ref.clone(), nat_ref.clone()),
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build: Nat.rec motive zero_case succ_case Nat.zero
    // Should reduce to zero_case

    // For simplicity, use dummy values for motive and cases
    let motive = Expr::lam(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::prop(), // motive : Nat → Prop
    );
    let zero_case = Expr::const_(Name::from_string("P"), vec![]); // some prop P
    let succ_case = Expr::lam(
        BinderInfo::Default,
        nat_ref.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::prop(), // IH
            Expr::prop(), // result
        ),
    );
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);

    // Build Nat.rec application
    // Nat.rec : {motive : Nat → Sort u} → motive zero → ((n : Nat) → motive n → motive (succ n)) → (n : Nat) → motive n
    // So args are: motive, zero_case, succ_case, major
    let rec = Expr::const_(Name::from_string("Nat.rec"), vec![Level::zero()]);
    let app1 = Expr::app(rec, motive);
    let app2 = Expr::app(app1, zero_case.clone());
    let app3 = Expr::app(app2, succ_case);
    let app4 = Expr::app(app3, zero);

    // Reduce to WHNF - should get zero_case
    let result = tc.whnf(&app4);

    // The result should be zero_case (P)
    // Note: This depends on the recursor structure we generate
    // Our simplified implementation may not fully reduce, but should at least compile
    // For now, just verify it doesn't panic and returns something
    assert!(!matches!(&result.kind, ExprKind::BVar(_))); // Should be a valid expression
}

/// Regression: dependent Let must not leak FVars into the result type.
///
/// `let x : Type 1 := Type 0 in (fun (y : x) => y)` should have type
/// `Prop → Prop`. The body `fun (y : x) => y` has type `Pi(y : x, x)`.
/// After open_bvar, the type checker replaces x with FVar(fvar_id). The
/// resulting body_type Pi(FVar(fvar_id), FVar(fvar_id)) must have the FVar
/// substituted with the Let value (Prop) before returning. If abstract_fvar
/// is not called before instantiate, escaped FVars will appear in the type.
///
/// Lean 4 reference: type_checker.cpp infer_let (line 216-218) uses
/// lctx.mk_pi which calls abstract() first, then reconstructs bindings.
#[test]
fn test_dependent_let_no_fvar_escape() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // let x : Type 1 := Prop in (fun (y : x) => y)
    // In de Bruijn:
    //   Let(ty=Sort(1), val=Sort(0), body=Lam(domain=BVar(0), body=BVar(0)))
    // BVar(0) in the lambda domain refers to the let-bound x
    // BVar(0) in the lambda body refers to the lambda-bound y
    let inner_lam = Expr::lam(BinderInfo::Default, Expr::bvar(0), Expr::bvar(0));
    let let_expr = Expr::let_named(
        Name::anon(),
        Expr::sort(Level::succ(Level::zero())), // x : Type 1
        Expr::prop(),                           // x := Prop (= Sort(0))
        inner_lam,
        false,
    );

    let ty = tc.infer_type(&let_expr).unwrap();

    // The type must not contain any FVars — they should have been substituted.
    assert!(
        !ty.has_fvar_quick(),
        "Dependent let type contains escaped FVars: {ty:?}"
    );

    // The type should be Pi(Prop, Prop) = Prop → Prop.
    match &ty.kind {
        ExprKind::Pi(_bi, domain, body) => {
            // Domain should be Prop (no FVars)
            assert!(
                !domain.has_fvar_quick(),
                "Pi domain contains escaped FVars: {domain:?}"
            );
            assert!(
                domain.is_prop(),
                "Expected domain to be Prop, got {domain:?}"
            );
            // Body (codomain) should be Prop (no FVars)
            assert!(
                !body.has_fvar_quick(),
                "Pi body contains escaped FVars: {body:?}"
            );
        }
        _ => panic!("Expected Pi type for identity lambda, got {ty:?}"),
    }
}

/// Regression: nested dependent Let must not leak FVars across nesting levels.
///
/// `let x : Type 1 := Prop in let y : Type 1 := (x → x) in (fun (z : y) => z)`
/// should have type `(Prop → Prop) → (Prop → Prop)`.
#[test]
fn test_nested_dependent_let_no_fvar_escape() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Inner lambda: fun (z : y) => z  where y is let-bound at depth 0
    // BVar(0) in domain = the innermost let-bound y
    // BVar(0) in body = the lambda-bound z
    let inner_lam = Expr::lam(BinderInfo::Default, Expr::bvar(0), Expr::bvar(0));

    // Inner let: let y : Type 1 := (x → x) in <inner_lam>
    // BVar(0) in the pi domain refers to outer let-bound x (shifted by 0 since
    // we are at depth 0 relative to the inner let's value position)
    // After the pi's domain binder, BVar(1) refers to outer let-bound x
    let x_to_x = Expr::pi(BinderInfo::Default, Expr::bvar(0), Expr::bvar(1));
    let inner_let = Expr::let_named(
        Name::anon(),
        Expr::sort(Level::succ(Level::zero())), // y : Type 1
        x_to_x,                                 // y := x → x
        inner_lam,
        false,
    );

    // Outer let: let x : Type 1 := Prop in <inner_let>
    let outer_let = Expr::let_named(
        Name::anon(),
        Expr::sort(Level::succ(Level::zero())), // x : Type 1
        Expr::prop(),                           // x := Prop
        inner_let,
        false,
    );

    let ty = tc.infer_type(&outer_let).unwrap();

    // The result type must not contain FVars.
    assert!(
        !ty.has_fvar_quick(),
        "Nested dependent let type contains escaped FVars: {ty:?}"
    );
}
