// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (cache).
//
// Generated by splitting tc/tests.rs into submodules for maintainability.

use super::*;

#[test]
fn test_type_cache_enable_disable() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);

    // Cache starts disabled
    assert!(!tc.type_cache_enabled());
    assert!(
        tc.type_cache_stats().is_none(),
        "disabled cache should return None stats, got {:?}",
        tc.type_cache_stats()
    );

    // Enable cache
    tc.enable_type_cache();
    assert!(tc.type_cache_enabled());
    let _stats = tc
        .type_cache_stats()
        .expect("enabled cache should return Some stats");

    // Disable cache
    tc.disable_type_cache();
    assert!(!tc.type_cache_enabled());
    assert!(
        tc.type_cache_stats().is_none(),
        "re-disabled cache should return None stats, got {:?}",
        tc.type_cache_stats()
    );
}

/// Test that the type cache produces hits on repeated queries.
///
/// Note: Cache integration is only active in release builds. In debug builds,
/// the cache exists but lookups are not wired in (infer_type uses cert path).
/// This test simply verifies the cache API works - actual hit rate verification
/// would require release mode testing.
#[test]
fn test_type_cache_hit_rate() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);

    // Enable cache
    tc.enable_type_cache();

    // Infer type of Prop multiple times — Prop : Type (Sort 1)
    let prop = Expr::prop();
    let prop_ty = tc.infer_type(&prop).unwrap();
    assert!(
        matches!(&prop_ty.kind, ExprKind::Sort(..)),
        "type of Prop should be Sort, got {:?}",
        prop_ty.kind
    );
    let prop_ty2 = tc.infer_type(&prop).unwrap();
    assert_eq!(
        prop_ty, prop_ty2,
        "repeated infer_type should return same result"
    );
    let prop_ty3 = tc.infer_type(&prop).unwrap();
    assert_eq!(
        prop_ty, prop_ty3,
        "repeated infer_type should return same result"
    );

    // Also check a literal — nat_lit(42) : Nat
    let nat_lit = Expr::nat_lit(42);
    let nat_ty = tc.infer_type(&nat_lit).unwrap();
    let nat_ty2 = tc.infer_type(&nat_lit).unwrap();
    assert_eq!(
        nat_ty, nat_ty2,
        "repeated infer_type on nat_lit should return same result"
    );

    // Get stats
    let stats = tc.type_cache_stats().expect("Cache should be enabled");

    // Note: In debug builds, cache entries will be 0 because infer_type
    // uses the cert-generating path which doesn't integrate with the cache.
    // In release builds, we'd expect entries > 0 and hits > 0.
    //
    // This test just verifies the API works correctly - actual cache
    // effectiveness would be measured in release mode benchmarks.
    let hit_rate = stats.hit_rate();
    assert!(
        (0.0..=100.0).contains(&hit_rate),
        "Hit rate should be between 0 and 100"
    );
}

#[test]
fn test_type_cache_correctness() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);

    // Disable cache and get type
    let prop = Expr::prop();
    let ty_without_cache = tc.infer_type(&prop).unwrap();

    // Enable cache and get type again
    tc.enable_type_cache();
    let ty_first = tc.infer_type(&prop).unwrap();
    let ty_second = tc.infer_type(&prop).unwrap();

    // All types should be identical
    assert_eq!(
        ty_without_cache, ty_first,
        "Cached result should match non-cached"
    );
    assert_eq!(ty_first, ty_second, "Repeated cached lookups should match");
}

/// Test: environment generation counter tracks mutations (#1279)
///
/// The env hash (used for cache invalidation) must change when the
/// environment is mutated, even if the constant count stays the same.
/// Previously, `compute_env_hash` used only `constant_count()`, so
/// replacing a constant with another (same count) wouldn't invalidate.
#[test]
fn test_env_generation_increments_on_mutation() {
    use crate::env::{Declaration, Reducibility};

    let mut env = Environment::new();
    // Environment::new() calls init_sorry() which adds the sorry axiom,
    // so generation starts at 1, not 0.
    let gen_initial = env.generation();
    assert!(
        gen_initial > 0,
        "fresh env has generation > 0 from init_sorry"
    );

    // add_decl bumps generation
    let name_a = Name::from_string("A");
    env.add_decl(Declaration::Axiom {
        name: name_a.clone(),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();
    let gen_after_add = env.generation();
    assert!(
        gen_after_add > gen_initial,
        "generation must increase after add_decl"
    );

    // add_decl_unchecked bumps generation
    let name_b = Name::from_string("B");
    env.add_decl_unchecked(Declaration::Axiom {
        name: name_b.clone(),
        level_params: vec![],
        type_: Expr::prop(),
    });
    assert!(
        env.generation() > gen_after_add,
        "generation must increase after add_decl_unchecked"
    );

    // set_reducibility bumps generation
    let gen_before_reduce = env.generation();
    env.set_reducibility(&name_a, Reducibility::Irreducible);
    assert!(
        env.generation() > gen_before_reduce,
        "generation must increase after set_reducibility"
    );

    // register_inductive bumps generation
    let gen_before_ind = env.generation();
    let ind_val = crate::inductive::InductiveVal {
        name: Name::from_string("TestInd"),
        level_params: vec![],
        type_: Expr::from_kind(ExprKind::Sort(Level::succ(Level::Zero))),
        num_params: 0,
        num_indices: 0,
        all_names: vec![Name::from_string("TestInd")],
        constructor_names: vec![],
        is_recursive: false,
        is_reflexive: false,
        is_large_elim: false,
        is_nested: false,
    };
    env.register_inductive(ind_val);
    assert!(
        env.generation() > gen_before_ind,
        "generation must increase after register_inductive"
    );

    // extend_constants_unchecked bumps generation
    let gen_before_ext = env.generation();
    let extra_const =
        crate::env::ConstantInfo::new(Name::from_string("C"), vec![], Expr::prop(), None, false);
    env.extend_constants_unchecked(std::iter::once(extra_const));
    assert!(
        env.generation() > gen_before_ext,
        "generation must increase after extend_constants_unchecked"
    );
}

/// Test: two environments with same constant count but different mutations
/// produce different generation values (#1279)
#[test]
fn test_env_generation_differs_for_same_count_different_content() {
    use crate::env::Declaration;

    let mut env1 = Environment::new();
    let mut env2 = Environment::new();

    // Both envs: add one axiom, then add another (count = 2 for both)
    env1.add_decl(Declaration::Axiom {
        name: Name::from_string("X"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();
    env1.add_decl(Declaration::Axiom {
        name: Name::from_string("Y"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();

    env2.add_decl(Declaration::Axiom {
        name: Name::from_string("A"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();
    env2.add_decl(Declaration::Axiom {
        name: Name::from_string("B"),
        level_params: vec![],
        type_: Expr::prop(),
    })
    .unwrap();

    // Same constant count
    assert_eq!(env1.num_constants(), env2.num_constants());

    // Same generation (both did 2 add_decl calls from generation 0)
    assert_eq!(env1.generation(), env2.generation());

    // Now mutate only env1 — generation diverges
    env1.set_reducibility(
        &Name::from_string("X"),
        crate::env::Reducibility::Irreducible,
    );
    assert_ne!(
        env1.generation(),
        env2.generation(),
        "generation must diverge after one env is mutated"
    );

    // The generation difference means compute_env_hash() (which returns
    // env.generation()) will differ for TypeCheckers built on these envs,
    // so cache entries from env2 won't be reused for env1.
}

#[test]
fn test_cache_eviction_trims_at_threshold() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);
    // Set a low threshold so we can exercise eviction quickly.
    tc.set_max_cache_entries(50);

    // Fill whnf_cache by calling whnf on many distinct expressions.
    // Each unique Sort(Succ^n(Zero)) goes through whnf → caches the identity.
    for i in 0..100u32 {
        let mut level = Level::zero();
        for _ in 0..i {
            level = Level::succ(level);
        }
        let expr = Expr::sort(level);
        let whnf_result = tc.whnf(&expr);
        // Sort expressions are already in WHNF — result should remain Sort
        assert!(
            matches!(&whnf_result.kind, ExprKind::Sort(..)),
            "whnf of Sort should return Sort, got {:?}",
            whnf_result.kind
        );
    }

    // Sliding window: when current exceeds threshold, current→previous and a fresh
    // current starts. len() = current + previous, so max is ~2x threshold + 1.
    // With threshold=50 and 100 inserts: previous≤51, current≤49, total≤100.
    // The key invariant is that current never exceeds threshold+1 at any point.
    // Total len() is bounded at 2*threshold + 1 (both generations).
    assert!(
        tc.whnf_cache_entries() <= 101,
        "whnf cache should be bounded by sliding window (~2x threshold), got {}",
        tc.whnf_cache_entries()
    );

    // Verify type checking still works after eviction — correctness is preserved.
    // Prop (Sort 0) has type Type (Sort 1).
    let prop = Expr::sort(Level::zero());
    let ty = tc
        .infer_type(&prop)
        .expect("type checking must work correctly after cache eviction");
    assert!(
        matches!(&ty.kind, ExprKind::Sort(..)),
        "type of Prop should be Sort after cache eviction, got {:?}",
        ty.kind
    );
}

#[test]
fn test_cache_metrics_complete() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // All cache metrics should start at 0.
    assert_eq!(tc.whnf_cache_entries(), 0);
    assert_eq!(tc.whnf_core_cache_entries(), 0);
    assert_eq!(tc.def_eq_cache_entries(), 0);
    assert_eq!(tc.proj_type_cache_entries(), 0);
    assert_eq!(tc.equiv_manager_entries(), 0);
    assert_eq!(tc.max_cache_entries(), 100_000);
}

#[test]
fn test_def_eq_cache_eviction() {
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);
    tc.set_max_cache_entries(20);

    // Generate many distinct is_def_eq comparisons.
    // Each Sort(Succ^n) vs Sort(Succ^n) is trivially true, populating cache.
    for i in 0..50u32 {
        let mut level = Level::zero();
        for _ in 0..i {
            level = Level::succ(level);
        }
        let a = Expr::sort(level.clone());
        let b = Expr::sort(level);
        assert!(tc.is_def_eq(&a, &b));
    }

    // def_eq cache should be trimmed.
    assert!(
        tc.def_eq_cache_entries() <= 21,
        "def_eq cache should be trimmed, got {}",
        tc.def_eq_cache_entries()
    );
}
