// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (projection).
//
// Generated by splitting tc/tests.rs into submodules for maintainability.

use super::*;

#[test]
fn test_whnf_proj() {
    // Test projection reduction
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define a simple pair type
    let pair = Name::from_string("Pair");

    // Pair : Type → Type → Type
    let pair_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(),
        Expr::pi(BinderInfo::Default, Expr::type_(), Expr::type_()),
    );

    // mk : (A B : Type) → A → B → Pair A B
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(), // A
        Expr::pi(
            BinderInfo::Default,
            Expr::type_(), // B
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(1), // A
                Expr::pi(
                    BinderInfo::Default,
                    Expr::bvar(1), // B
                    Expr::app(
                        Expr::app(Expr::const_(pair.clone(), vec![]), Expr::bvar(3)),
                        Expr::bvar(2),
                    ),
                ),
            ),
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 2, // A and B are parameters
        types: vec![InductiveType {
            name: pair.clone(),
            type_: pair_type,
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build Pair.mk Nat Nat 1 2
    let nat_type = Expr::type_(); // using Type as a stand-in for Nat
    let val1 = Expr::nat_lit(1);
    let val2 = Expr::nat_lit(2);

    let mk = Expr::const_(Name::from_string("Pair.mk"), vec![]);
    let pair_val = Expr::app(
        Expr::app(
            Expr::app(Expr::app(mk, nat_type.clone()), nat_type),
            val1.clone(),
        ),
        val2.clone(),
    );

    // Project the first field: Pair.1 should give val1
    let proj0 = Expr::proj(pair.clone(), 0, pair_val.clone());
    let result0 = tc.whnf(&proj0);

    // Project the second field: Pair.2 should give val2
    let proj1 = Expr::proj(pair, 1, pair_val);
    let result1 = tc.whnf(&proj1);

    // Verify projections
    assert_eq!(result0, val1);
    assert_eq!(result1, val2);
}

#[test]
fn test_proj_type_inference() {
    // Test projection type inference for a simple Pair type
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define Pair : Type → Type → Type
    let pair = Name::from_string("Pair");

    let pair_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(),
        Expr::pi(BinderInfo::Default, Expr::type_(), Expr::type_()),
    );

    // mk : (A B : Type) → A → B → Pair A B
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(), // A
        Expr::pi(
            BinderInfo::Default,
            Expr::type_(), // B
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(1), // A
                Expr::pi(
                    BinderInfo::Default,
                    Expr::bvar(1), // B
                    Expr::app(
                        Expr::app(Expr::const_(pair.clone(), vec![]), Expr::bvar(3)),
                        Expr::bvar(2),
                    ),
                ),
            ),
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 2, // A and B are parameters
        types: vec![InductiveType {
            name: pair.clone(),
            type_: pair_type,
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Add Nat to the environment (it's needed for nat literals)
    use crate::inductive::Constructor as IndCtor;
    let nat_name = Name::from_string("Nat");
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![
                IndCtor {
                    name: Name::from_string("Nat.zero"),
                    type_: Expr::const_(nat_name.clone(), vec![]),
                },
                IndCtor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(
                        BinderInfo::Default,
                        Expr::const_(nat_name.clone(), vec![]),
                        Expr::const_(nat_name.clone(), vec![]),
                    ),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build Pair.mk Nat Nat 1 2 (pair of nats)
    let nat_type = Expr::const_(nat_name.clone(), vec![]);
    let val1 = Expr::nat_lit(1);
    let val2 = Expr::nat_lit(2);

    let mk = Expr::const_(Name::from_string("Pair.mk"), vec![]);
    // Pair.mk Nat Nat 1 2 : Pair Nat Nat
    let pair_val = Expr::app(
        Expr::app(
            Expr::app(Expr::app(mk, nat_type.clone()), nat_type.clone()),
            val1.clone(),
        ),
        val2.clone(),
    );

    // The type of pair_val is: Pair Nat Nat
    let pair_val_type = tc.infer_type(&pair_val).unwrap();
    let pair_val_type_whnf = tc.whnf(&pair_val_type);

    // Should be App(App(Const(Pair), Nat), Nat)
    assert!(matches!(&pair_val_type_whnf.get_app_fn().kind, ExprKind::Const(n, _) if n == &pair));

    // Project the first field: Pair.0 should have type Nat
    let proj0 = Expr::proj(pair.clone(), 0, pair_val.clone());
    let proj0_type = tc.infer_type(&proj0).unwrap();

    // The first field type should be Nat (the first type argument)
    assert_eq!(proj0_type, nat_type);

    // Project the second field: Pair.1 should have type Nat
    let proj1 = Expr::proj(pair.clone(), 1, pair_val);
    let proj1_type = tc.infer_type(&proj1).unwrap();

    // The second field type should be Nat
    assert_eq!(proj1_type, nat_type);
}

#[test]
fn test_proj_type_inference_dependent_field() {
    // Test projection type inference for dependent fields (like Sigma/PSigma)
    // structure DepPair where
    //   fst : Type
    //   snd : fst  -- depends on fst (snd has type equal to the VALUE of fst)
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // DepPair : Sort(2) = Type 1. Field fst : Type needs Sort(2) result.
    let dep_pair = Name::from_string("DepPair");
    let dep_pair_type = Expr::from_kind(ExprKind::Sort(Level::succ(Level::succ(Level::zero()))));

    // DepPair.mk : (fst : Type) -> (snd : fst) -> DepPair
    // Constructor: Pi(fst : Type, Pi(snd : BVar 0, DepPair))
    //   - BVar 0 in "snd : BVar 0" refers to fst
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(), // fst : Type (field 0)
        Expr::pi(
            BinderInfo::Default,
            Expr::bvar(0), // snd : fst = BVar 0 (field 1, depends on field 0)
            Expr::const_(dep_pair.clone(), vec![]), // result: DepPair
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0, // no parameters, both are fields
        types: vec![InductiveType {
            name: dep_pair.clone(),
            type_: dep_pair_type,
            constructors: vec![Constructor {
                name: Name::from_string("DepPair.mk"),
                type_: mk_type,
            }],
        }],
    };
    env.add_inductive(decl).unwrap();

    // Add Nat for testing
    let nat_name = Name::from_string("Nat");
    let nat_type = Expr::const_(nat_name.clone(), vec![]);
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Nat.zero"),
                type_: nat_type.clone(),
            }],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Create a concrete value: DepPair.mk Nat Nat.zero
    // This represents a DepPair where fst=Nat, snd=0:Nat
    let mk = Expr::const_(Name::from_string("DepPair.mk"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let dp_val = Expr::app(Expr::app(mk, nat_type.clone()), zero.clone());

    // Project fst (field 0): should have type Type
    let proj_fst = Expr::proj(dep_pair.clone(), 0, dp_val.clone());
    let proj_fst_type = tc.infer_type(&proj_fst).unwrap();
    assert_eq!(
        proj_fst_type,
        Expr::type_(),
        "fst field should have type Type"
    );

    // Project snd (field 1): should have type (DepPair.fst dp_val) = Proj(DepPair, 0, dp_val)
    // Since fst = Nat, the type of snd should be Nat (but represented as the projection)
    let proj_snd = Expr::proj(dep_pair.clone(), 1, dp_val.clone());
    let proj_snd_type = tc.infer_type(&proj_snd).unwrap();

    // The expected type is: Proj(DepPair, 0, dp_val)
    // This represents "the first field of dp_val", which is Nat
    let expected_snd_type = Expr::proj(dep_pair.clone(), 0, dp_val.clone());

    assert_eq!(
        proj_snd_type, expected_snd_type,
        "snd field should have type (proj 0 dp_val), got: {:?}",
        proj_snd_type
    );
}

#[test]
fn test_proj_type_inference_no_params() {
    // Test projection on a type with num_params = 0 but with fields
    // This catches mutants that change `num_params > 0` to `num_params >= 0`
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // First add Nat to the environment
    let nat_name = Name::from_string("Nat");
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: Expr::const_(nat_name.clone(), vec![]),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(
                        BinderInfo::Default,
                        Expr::const_(nat_name.clone(), vec![]),
                        Expr::const_(nat_name.clone(), vec![]),
                    ),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    // Define Point : Type with two Nat fields
    // Point.mk : Nat → Nat → Point
    let point_name = Name::from_string("Point");
    let nat_ty = Expr::const_(nat_name.clone(), vec![]);

    let point_mk_type = Expr::pi(
        BinderInfo::Default,
        nat_ty.clone(), // x : Nat
        Expr::pi(
            BinderInfo::Default,
            nat_ty.clone(), // y : Nat
            Expr::const_(point_name.clone(), vec![]),
        ),
    );

    let point_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0, // No type parameters
        types: vec![InductiveType {
            name: point_name.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Point.mk"),
                type_: point_mk_type,
            }],
        }],
    };

    env.add_inductive(point_decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build Point.mk 1 2
    let mk = Expr::const_(Name::from_string("Point.mk"), vec![]);
    let point_val = Expr::app(Expr::app(mk, Expr::nat_lit(1)), Expr::nat_lit(2));

    // The type of point_val should be Point
    let point_val_type = tc.infer_type(&point_val).unwrap();
    assert!(matches!(&point_val_type.get_app_fn().kind, ExprKind::Const(n, _) if n == &point_name));

    // Project the first field: Point.0 should have type Nat
    let proj0 = Expr::proj(point_name.clone(), 0, point_val.clone());
    let proj0_type = tc.infer_type(&proj0).unwrap();
    assert_eq!(proj0_type, nat_ty, "First field of Point should be Nat");

    // Project the second field: Point.1 should have type Nat
    let proj1 = Expr::proj(point_name, 1, point_val);
    let proj1_type = tc.infer_type(&proj1).unwrap();
    assert_eq!(proj1_type, nat_ty, "Second field of Point should be Nat");
}

#[test]
fn test_proj_type_inference_index_out_of_bounds() {
    // Test that projection with invalid index returns an error
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define Unit : Type with single constructor unit
    let unit = Name::from_string("Unit");
    let unit_type = Expr::type_();
    let unit_mk_type = Expr::const_(unit.clone(), vec![]);

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: unit.clone(),
            type_: unit_type,
            constructors: vec![Constructor {
                name: Name::from_string("Unit.unit"),
                type_: unit_mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build Unit.unit
    let unit_val = Expr::const_(Name::from_string("Unit.unit"), vec![]);

    // Try to project from Unit, which has 0 fields
    let proj0 = Expr::proj(unit, 0, unit_val);
    let result = tc.infer_type(&proj0);

    // Should fail because Unit has no fields
    assert!(
        matches!(result, Err(TypeError::InvalidProjIndexOutOfBounds(0, 0))),
        "expected InvalidProjIndexOutOfBounds(0, 0), got: {result:?}"
    );
}

#[test]
fn test_proj_type_inference_not_unique_constructor() {
    // Test that projection on a type with multiple constructors fails
    // (structures must have exactly one constructor)
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Add Nat which has two constructors (zero and succ)
    let nat_name = Name::from_string("Nat");
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: Expr::const_(nat_name.clone(), vec![]),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(
                        BinderInfo::Default,
                        Expr::const_(nat_name.clone(), vec![]),
                        Expr::const_(nat_name.clone(), vec![]),
                    ),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    let tc = TypeChecker::new(&env);

    let nat_val = Expr::nat_lit(42);

    // Try to project from Nat
    let proj = Expr::proj(nat_name, 0, nat_val);
    let result = tc.infer_type(&proj);

    // Should fail because Nat has two constructors
    assert!(
        matches!(result, Err(TypeError::InvalidProjNotUniqueConstructor(_))),
        "expected InvalidProjNotUniqueConstructor, got: {result:?}"
    );
}

#[test]
fn test_proj_type_inference_under_applied() {
    // Test that projection on an under-applied struct type fails
    // e.g., projecting from `Pair Nat` instead of `Pair Nat Nat`
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define Pair : Type → Type → Type (has 2 parameters)
    let pair = Name::from_string("Pair");
    let pair_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(),
        Expr::pi(BinderInfo::Default, Expr::type_(), Expr::type_()),
    );

    // mk : (A B : Type) → A → B → Pair A B
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(), // A
        Expr::pi(
            BinderInfo::Default,
            Expr::type_(), // B
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(1), // A
                Expr::pi(
                    BinderInfo::Default,
                    Expr::bvar(1), // B
                    Expr::app(
                        Expr::app(Expr::const_(pair.clone(), vec![]), Expr::bvar(3)),
                        Expr::bvar(2),
                    ),
                ),
            ),
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 2, // A and B are parameters
        types: vec![InductiveType {
            name: pair.clone(),
            type_: pair_type,
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Add Nat to the environment
    let nat_name = Name::from_string("Nat");
    let nat_type = Expr::const_(nat_name.clone(), vec![]);
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_type.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(BinderInfo::Default, nat_type.clone(), nat_type.clone()),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    let mut tc = TypeChecker::new(&env);

    // Create a malformed expression: pretend something has type `Pair Nat` (under-applied)
    // We'll use an FVar and register it with an under-applied type
    let under_applied_type = Expr::app(Expr::const_(pair.clone(), vec![]), nat_type.clone());
    let fvar_id = tc.local_context_mut().push(
        Name::from_string("x"),
        under_applied_type,
        BinderInfo::Default,
    );

    let fvar = Expr::fvar(fvar_id);

    // Try to project from the FVar with under-applied type
    let proj = Expr::proj(pair, 0, fvar);
    let result = tc.infer_type(&proj);

    // Should fail with InvalidProjWrongArgCount error
    // Pair has 2 params, 0 indices, so expected = 2
    assert!(
        matches!(result, Err(TypeError::InvalidProjWrongArgCount { got: 1, expected: 2, num_params: 2, num_indices: 0 })),
        "Expected InvalidProjWrongArgCount {{ got: 1, expected: 2, num_params: 2, num_indices: 0 }}, got {:?}",
        result
    );
}

/// Create an environment with Nat, returning (env, nat_type).
fn make_nat_env_for_proj() -> (Environment, Expr) {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    let mut env = Environment::new();
    let nat_name = Name::from_string("Nat");
    let nat_type = Expr::const_(nat_name.clone(), vec![]);
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_type.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(BinderInfo::Default, nat_type.clone(), nat_type.clone()),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();
    (env, nat_type)
}

/// Test that projection rejects indexed inductives with missing indices
/// Per Lean 4 (type_checker.cpp:237-238), args.size() must equal nparams + nindices
#[test]
fn test_proj_type_inference_missing_indices() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    // Create indexed inductive: Idx : Nat → Type with num_params = 0, num_indices = 1
    // Structure: Idx.mk : (n : Nat) → (val : Nat) → Idx (Nat.succ n)
    // Index is succ(n), NOT a bare BVar, so fixedIndicesToParams won't promote it.
    let (mut env, nat_type) = make_nat_env_for_proj();

    // Create Idx : Nat → Type
    // This has num_params = 0 (no parameters) and num_indices = 1 (the Nat argument)
    let idx_name = Name::from_string("Idx");
    // Idx : Nat → Type
    let idx_type = Expr::pi(BinderInfo::Default, nat_type.clone(), Expr::type_());
    // Idx.mk : (n : Nat) → (val : Nat) → Idx (Nat.succ n)
    // Constructor uses succ(n) as the index, preventing fixedIndicesToParams promotion.
    let idx_mk_type = Expr::pi(
        BinderInfo::Default,
        nat_type.clone(), // n : Nat
        Expr::pi(
            BinderInfo::Default,
            nat_type.clone(), // val : Nat
            Expr::app(
                Expr::const_(idx_name.clone(), vec![]),
                Expr::app(
                    Expr::const_(Name::from_string("Nat.succ"), vec![]),
                    Expr::bvar(1),
                ),
            ), // Idx (Nat.succ n)
        ),
    );

    // num_params = 0 for this indexed inductive
    let idx_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: idx_name.clone(),
            type_: idx_type,
            constructors: vec![Constructor {
                name: Name::from_string("Idx.mk"),
                type_: idx_mk_type,
            }],
        }],
    };
    env.add_inductive(idx_decl).unwrap();

    // Verify num_indices was set
    let idx_info = env.get_inductive(&idx_name).unwrap();
    assert_eq!(idx_info.num_indices, 1, "Idx should have 1 index");

    let mut tc = TypeChecker::new(&env);

    // Create a malformed expression: something has type `Idx` (missing index)
    // type_args.len() = 0, but expected = num_params + num_indices = 0 + 1 = 1
    let under_applied_type = Expr::const_(idx_name.clone(), vec![]);
    let fvar_id = tc.local_context_mut().push(
        Name::from_string("x"),
        under_applied_type,
        BinderInfo::Default,
    );
    let fvar = Expr::fvar(fvar_id);

    // Try to project from the FVar with missing index
    let proj = Expr::proj(idx_name, 0, fvar);
    let result = tc.infer_type(&proj);

    // Should fail with InvalidProjWrongArgCount: got 0, expected 1 (0 params + 1 index)
    assert!(
        matches!(
            result,
            Err(TypeError::InvalidProjWrongArgCount {
                got: 0,
                expected: 1,
                num_params: 0,
                num_indices: 1
            })
        ),
        "Expected InvalidProjWrongArgCount {{ got: 0, expected: 1, num_params: 0, num_indices: 1 }}, got {:?}",
        result
    );
}

/// Test that projection rejects indexed inductives when params are present but indices are missing
/// Per Lean 4 (type_checker.cpp:237-238), args.size() must equal nparams + nindices
#[test]
fn test_proj_type_inference_missing_indices_with_params() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    // Create indexed inductive: VecLike : Type → Nat → Type with num_params = 1, num_indices = 1
    // Structure: VecLike.mk : (A : Type) → (n : Nat) → (val : A) → VecLike A (Nat.succ n)
    let (mut env, nat_type) = make_nat_env_for_proj();

    let vec_name = Name::from_string("VecLike");
    let vec_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(),                                                  // A : Type
        Expr::pi(BinderInfo::Default, nat_type.clone(), Expr::type_()), // n : Nat
    );
    // VecLike.mk : (A : Type) → (n : Nat) → (val : A) → VecLike A (Nat.succ n)
    // Index is succ(n), NOT a bare BVar, so fixedIndicesToParams won't promote it.
    let vec_mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(), // A
        Expr::pi(
            BinderInfo::Default,
            nat_type.clone(), // n
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(1), // val : A
                Expr::app(
                    Expr::app(Expr::const_(vec_name.clone(), vec![]), Expr::bvar(2)),
                    Expr::app(
                        Expr::const_(Name::from_string("Nat.succ"), vec![]),
                        Expr::bvar(1),
                    ),
                ), // VecLike A (Nat.succ n)
            ),
        ),
    );

    let vec_decl = InductiveDecl {
        level_params: vec![],
        num_params: 1,
        types: vec![InductiveType {
            name: vec_name.clone(),
            type_: vec_type,
            constructors: vec![Constructor {
                name: Name::from_string("VecLike.mk"),
                type_: vec_mk_type,
            }],
        }],
    };
    env.add_inductive(vec_decl).unwrap();

    let vec_info = env.get_inductive(&vec_name).unwrap();
    assert_eq!(vec_info.num_indices, 1, "VecLike should have 1 index");

    let mut tc = TypeChecker::new(&env);

    // Missing index: VecLike Nat (only param supplied)
    let under_applied_type = Expr::app(Expr::const_(vec_name.clone(), vec![]), nat_type);
    let fvar_id = tc.local_context_mut().push(
        Name::from_string("x"),
        under_applied_type,
        BinderInfo::Default,
    );
    let fvar = Expr::fvar(fvar_id);

    let proj = Expr::proj(vec_name, 0, fvar);
    let result = tc.infer_type(&proj);

    // Should fail with InvalidProjWrongArgCount: got 1, expected 2 (1 param + 1 index)
    assert!(
        matches!(
            result,
            Err(TypeError::InvalidProjWrongArgCount {
                got: 1,
                expected: 2,
                num_params: 1,
                num_indices: 1
            })
        ),
        "Expected InvalidProjWrongArgCount {{ got: 1, expected: 2, num_params: 1, num_indices: 1 }}, got {:?}",
        result
    );
}

/// Test that projection rejects over-applied types (too many type arguments)
/// Per Lean 4 (type_checker.cpp:237-238), args.size() must equal nparams + nindices exactly
#[test]
fn test_proj_type_inference_over_applied() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    // Create Pair : Type → Type → Type with num_params = 2, num_indices = 0
    let mut env = Environment::new();

    // Add Nat first
    let nat_name = Name::from_string("Nat");
    let nat_type = Expr::const_(nat_name.clone(), vec![]);
    let nat_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: nat_name.clone(),
            type_: Expr::type_(),
            constructors: vec![
                Constructor {
                    name: Name::from_string("Nat.zero"),
                    type_: nat_type.clone(),
                },
                Constructor {
                    name: Name::from_string("Nat.succ"),
                    type_: Expr::pi(BinderInfo::Default, nat_type.clone(), nat_type.clone()),
                },
            ],
        }],
    };
    env.add_inductive(nat_decl).unwrap();

    // Create Pair : Type → Type → Type
    let pair = Name::from_string("Pair");
    let pair_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(),
        Expr::pi(BinderInfo::Default, Expr::type_(), Expr::type_()),
    );
    // Pair.mk : (A : Type) → (B : Type) → A → B → Pair A B
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(), // A
        Expr::pi(
            BinderInfo::Default,
            Expr::type_(), // B
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(1), // a : A
                Expr::pi(
                    BinderInfo::Default,
                    Expr::bvar(1), // b : B
                    Expr::app(
                        Expr::app(Expr::const_(pair.clone(), vec![]), Expr::bvar(3)),
                        Expr::bvar(2),
                    ),
                ),
            ),
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 2, // A and B are parameters
        types: vec![InductiveType {
            name: pair.clone(),
            type_: pair_type,
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: mk_type,
            }],
        }],
    };
    env.add_inductive(decl).unwrap();

    let mut tc = TypeChecker::new(&env);

    // Create a malformed expression: pretend something has type `Pair Nat Nat Nat` (over-applied)
    // type_args.len() = 3, but expected = num_params + num_indices = 2 + 0 = 2
    let over_applied_type = Expr::app(
        Expr::app(
            Expr::app(Expr::const_(pair.clone(), vec![]), nat_type.clone()),
            nat_type.clone(),
        ),
        nat_type.clone(), // extra argument
    );
    let fvar_id = tc.local_context_mut().push(
        Name::from_string("x"),
        over_applied_type,
        BinderInfo::Default,
    );
    let fvar = Expr::fvar(fvar_id);

    // Try to project from the FVar with over-applied type
    let proj = Expr::proj(pair, 0, fvar);
    let result = tc.infer_type(&proj);

    // Since #2208 changed is_prop to return Result (propagating errors via ?),
    // the is_prop call in infer_proj_type_from_impl fires before the arg-count
    // validation. Pair : Type -> Type -> Type, so App(App(App(Pair, Nat), Nat), Nat)
    // tries to apply Nat to Type (= Sort 1), which is not a Pi -> NotAFunction.
    assert!(
        matches!(result, Err(TypeError::NotAFunction { .. })),
        "Expected NotAFunction (is_prop propagates before arg-count check), got {:?}",
        result
    );
}

/// Regression test for #2172: projection type inference must substitute universe level
/// parameters on the constructor type before extracting field types.
#[test]
fn test_proj_type_inference_universe_level_substitution() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();
    let u_name = Name::from_string("u");
    let sort_container = Name::from_string("SortContainer");

    // SortContainer.{u} : Type u, field type is Sort(Param("u"))
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::sort(Level::param(u_name.clone())),
        Expr::const_(sort_container.clone(), vec![Level::param(u_name.clone())]),
    );
    let decl = InductiveDecl {
        level_params: vec![u_name.clone()],
        num_params: 0,
        types: vec![InductiveType {
            name: sort_container.clone(),
            type_: Expr::sort(Level::succ(Level::param(u_name.clone()))),
            constructors: vec![Constructor {
                name: Name::from_string("SortContainer.mk"),
                type_: mk_type,
            }],
        }],
    };
    env.add_inductive(decl).unwrap();
    let mut tc = TypeChecker::new(&env);

    // Test at u=0: projection should yield Sort(0) = Prop, not Sort(Param("u"))
    let fvar_id = tc.local_context_mut().push(
        Name::from_string("x"),
        Expr::const_(sort_container.clone(), vec![Level::zero()]),
        BinderInfo::Default,
    );
    let proj = Expr::proj(sort_container.clone(), 0, Expr::fvar(fvar_id));
    let proj_type = tc.infer_type(&proj).unwrap();
    assert_eq!(
        proj_type,
        Expr::sort(Level::zero()),
        "Field type should be Sort(0) after level subst, got {:?}",
        proj_type
    );

    // Test at u=1: projection should yield Sort(1) = Type
    let fvar_id2 = tc.local_context_mut().push(
        Name::from_string("y"),
        Expr::const_(sort_container.clone(), vec![Level::succ(Level::zero())]),
        BinderInfo::Default,
    );
    let proj2 = Expr::proj(sort_container, 0, Expr::fvar(fvar_id2));
    let proj2_type = tc.infer_type(&proj2).unwrap();
    assert_eq!(
        proj2_type,
        Expr::sort(Level::succ(Level::zero())),
        "Field type should be Sort(1) after level subst, got {:?}",
        proj2_type
    );
}

/// Regression test for #2921: malformed projection targets must reject
/// structure level-count mismatches instead of silently truncating level
/// substitution in release builds.
#[test]
fn test_proj_type_inference_rejects_level_count_mismatch() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();
    let u_name = Name::from_string("u");
    let sort_container = Name::from_string("SortContainer");

    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::sort(Level::param(u_name.clone())),
        Expr::const_(sort_container.clone(), vec![Level::param(u_name.clone())]),
    );
    let decl = InductiveDecl {
        level_params: vec![u_name.clone()],
        num_params: 0,
        types: vec![InductiveType {
            name: sort_container.clone(),
            type_: Expr::sort(Level::succ(Level::param(u_name.clone()))),
            constructors: vec![Constructor {
                name: Name::from_string("SortContainer.mk"),
                type_: mk_type,
            }],
        }],
    };
    env.add_inductive(decl).unwrap();
    let mut tc = TypeChecker::new(&env);

    // Simulate a malformed trusted import: local context contains SortContainer
    // without the required universe level argument.
    let bad_fvar = tc.local_context_mut().push(
        Name::from_string("x"),
        Expr::const_(sort_container.clone(), vec![]),
        BinderInfo::Default,
    );
    let proj = Expr::proj(sort_container.clone(), 0, Expr::fvar(bad_fvar));
    let result = tc.infer_type(&proj);

    assert!(
        matches!(
            result,
            Err(TypeError::LevelCountMismatch {
                ref name,
                expected: 1,
                got: 0,
            }) if name == &sort_container
        ),
        "Expected LevelCountMismatch for malformed projection target, got {result:?}"
    );
}

// =========================================================================
// Certified Type Inference Tests
// =========================================================================

#[test]
fn test_reduce_proj_index_comparison() {
    // Kill mutant: reduce_proj < with <=
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();

    // Create a 3-field structure
    // Fields are Type (Sort(1)), so result must be Sort(2) = Type 1
    let triple = Name::from_string("Triple");
    let triple_type = Expr::sort(Level::succ(Level::succ(Level::zero())));

    // mk : Type → Type → Type → Triple
    let mk_type = Expr::pi(
        BinderInfo::Default,
        Expr::type_(),
        Expr::pi(
            BinderInfo::Default,
            Expr::type_(),
            Expr::pi(
                BinderInfo::Default,
                Expr::type_(),
                Expr::const_(triple.clone(), vec![]),
            ),
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: triple.clone(),
            type_: triple_type,
            constructors: vec![Constructor {
                name: Name::from_string("Triple.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();
    let tc = TypeChecker::new(&env);

    // Build Triple.mk val0 val1 val2
    let mk = Expr::const_(Name::from_string("Triple.mk"), vec![]);
    let val0 = Expr::prop();
    let val1 = Expr::type_();
    let val2 = Expr::from_kind(ExprKind::Sort(Level::succ(Level::succ(Level::zero()))));

    // Build with correct arity (3 fields)
    let triple_val = Expr::app(
        Expr::app(Expr::app(mk, val0.clone()), val1.clone()),
        val2.clone(),
    );

    // Test all three projections
    let proj0 = Expr::proj(triple.clone(), 0, triple_val.clone());
    let proj1 = Expr::proj(triple.clone(), 1, triple_val.clone());
    let proj2 = Expr::proj(triple.clone(), 2, triple_val);

    let result0 = tc.whnf(&proj0);
    let result1 = tc.whnf(&proj1);
    let result2 = tc.whnf(&proj2);

    // Each projection should return the correct field
    assert_eq!(result0, val0, "proj.0 should return first field");
    assert_eq!(result1, val1, "proj.1 should return second field");
    assert_eq!(result2, val2, "proj.2 should return third field");
}

#[test]
fn test_reduce_proj_index_boundary() {
    // Kill mutant: reduce_proj < with <= (line 808)
    // Tests that field_idx < args.len() (not <=)

    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Create a structure with 2 fields: Pair
    let pair = Name::from_string("Pair");
    let pair_ref = Expr::const_(pair.clone(), vec![]);
    let pair_mk_type = Expr::arrow(Expr::prop(), Expr::arrow(Expr::prop(), pair_ref.clone()));

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: pair.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: pair_mk_type,
            }],
        }],
    };
    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Create Pair.mk p1 p2
    let mk = Expr::const_(Name::from_string("Pair.mk"), vec![]);
    let p1 = Expr::prop();
    let p2 = Expr::type_();
    let pair_val = Expr::app(Expr::app(mk, p1.clone()), p2.clone());

    // Projection 0 should work (field_idx = 0, args.len() = 2, 0 < 2)
    let proj0 = Expr::proj(pair.clone(), 0, pair_val.clone());
    let result0 = tc.whnf(&proj0);
    assert_eq!(result0, p1);

    // Projection 1 should work (field_idx = 1, args.len() = 2, 1 < 2)
    let proj1 = Expr::proj(pair.clone(), 1, pair_val.clone());
    let result1 = tc.whnf(&proj1);
    assert_eq!(result1, p2);

    // Projection 2 should NOT reduce (field_idx = 2, args.len() = 2, 2 < 2 is FALSE)
    let proj2 = Expr::proj(pair.clone(), 2, pair_val.clone());
    let result2 = tc.whnf(&proj2);
    // Should not have reduced - still a projection
    assert!(matches!(&result2.kind, ExprKind::Proj(_, _, _)));
}

/// Test that projection from Prop type with Prop field succeeds (valid case).
///
/// This is the counterpart to test_error_invalid_proj_from_prop, showing that
/// Prop-to-Prop projections are allowed.
#[test]
fn test_valid_proj_prop_to_prop() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Create a simple Prop-typed structure with a Prop field.
    // This mimics the common pattern in Lean like And/Or/Exists.
    //
    // We need a Prop to project from. Use True : Prop as a placeholder.
    let true_name = Name::from_string("True");
    let true_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: true_name.clone(),
            type_: Expr::prop(),
            constructors: vec![Constructor {
                name: Name::from_string("True.intro"),
                type_: Expr::const_(true_name.clone(), vec![]),
            }],
        }],
    };
    env.add_inductive(true_decl).unwrap();

    // PropWrapper : Prop
    // PropWrapper.mk : True → PropWrapper
    //
    // The field has type True : Prop, which IS in Prop.
    let pw_name = Name::from_string("PropWrapper");
    let true_ty = Expr::const_(true_name.clone(), vec![]);

    let pw_mk_type = Expr::pi(
        BinderInfo::Default,
        true_ty.clone(), // proof : True (IS in Prop!)
        Expr::const_(pw_name.clone(), vec![]),
    );

    let pw_decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: pw_name.clone(),
            type_: Expr::prop(), // Type is Prop
            constructors: vec![Constructor {
                name: Name::from_string("PropWrapper.mk"),
                type_: pw_mk_type,
            }],
        }],
    };
    env.add_inductive(pw_decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Create a value: PropWrapper.mk True.intro
    let intro = Expr::const_(Name::from_string("True.intro"), vec![]);
    let mk = Expr::const_(Name::from_string("PropWrapper.mk"), vec![]);
    let pw_val = Expr::app(mk, intro);

    // Project field 0 (the True field from a Prop-typed structure)
    // This SHOULD succeed because both are Props.
    let proj = Expr::proj(pw_name.clone(), 0, pw_val);
    let result = tc.infer_type(&proj);

    assert!(
        result.is_ok(),
        "Prop-to-Prop projection should succeed, got {result:?}"
    );

    // Verify the projected type is True
    let projected_type = result.unwrap();
    assert_eq!(
        projected_type,
        Expr::const_(true_name, vec![]),
        "Projected type should be True"
    );
}

/// Build a minimal environment with String, List, Char, Nat for projection tests.
fn build_string_env() -> Environment {
    let mut env = Environment::new();
    env.init_string().unwrap();
    env
}

/// Regression test for #1409: projection reduction must lower string literals
/// to constructor form before field extraction.
///
/// Per Lean 4 type_checker.cpp:360-361, `reduce_proj_core` calls
/// `string_lit_to_constructor` when the expression is a string literal.
/// Without this lowering, `Proj(String, 0, Lit(String("hi")))` cannot reduce.
#[test]
fn test_proj_string_literal_lowering() {
    let env = build_string_env();
    let tc = TypeChecker::new(&env);

    let string_name = Name::from_string("String");

    // Proj(String, 0, "hi") should reduce to the List Char form of "hi"
    let proj = Expr::proj(string_name.clone(), 0, Expr::str_lit("hi"));
    let result = tc.whnf(&proj);

    // The result must NOT be a Proj expression — it must have reduced
    assert!(
        !matches!(&result.kind, ExprKind::Proj(..)),
        "Proj on string literal should reduce, but got unreduced Proj: {result:?}"
    );

    // The result should be a List.cons application (since "hi" has chars)
    // String.mk takes one arg (List Char), so field 0 is that list.
    // After lowering "hi", we get String.ofList (List.cons ...) which whnf reduces
    // to String.mk (List.cons ...), then projection extracts the list.
    let head = result.get_app_fn();
    assert!(
        matches!(&head.kind, ExprKind::Const(n, _) if n == &Name::from_string("List.cons")),
        "Projected field should be a List.cons application (character list), got head: {head:?}"
    );

    // Also test empty string: Proj(String, 0, "") should give List.nil
    let proj_empty = Expr::proj(string_name.clone(), 0, Expr::str_lit(""));
    let result_empty = tc.whnf(&proj_empty);

    assert!(
        !matches!(&result_empty.kind, ExprKind::Proj(..)),
        "Proj on empty string literal should reduce, but got unreduced Proj: {result_empty:?}"
    );

    let head_empty = result_empty.get_app_fn();
    assert!(
        matches!(&head_empty.kind, ExprKind::Const(n, _) if n == &Name::from_string("List.nil")),
        "Projected field of empty string should be List.nil, got head: {head_empty:?}"
    );
}

#[test]
fn test_proj_string_literal_lowering_with_transparency() {
    use crate::env::TransparencyMode;

    let env = build_string_env();
    let tc = TypeChecker::new(&env);
    let string_name = Name::from_string("String");

    for mode in [
        TransparencyMode::Reducible,
        TransparencyMode::Instances,
        TransparencyMode::Default,
        TransparencyMode::All,
    ] {
        let proj = Expr::proj(string_name.clone(), 0, Expr::str_lit("hi"));
        let result = tc.whnf_with_transparency(&proj, mode);

        assert!(
            !matches!(&result.kind, ExprKind::Proj(..)),
            "Proj on string literal should reduce in mode {mode:?}, got: {result:?}"
        );

        let head = result.get_app_fn();
        assert!(
            matches!(&head.kind, ExprKind::Const(n, _) if n == &Name::from_string("List.cons")),
            "Projected field should be List.cons in mode {mode:?}, got head: {head:?}"
        );
    }

    let proj_empty = Expr::proj(string_name, 0, Expr::str_lit(""));
    let result_empty = tc.whnf_with_transparency(&proj_empty, TransparencyMode::Default);
    assert!(
        !matches!(&result_empty.kind, ExprKind::Proj(..)),
        "Proj on empty string literal should reduce in transparency mode"
    );

    let head_empty = result_empty.get_app_fn();
    assert!(
        matches!(&head_empty.kind, ExprKind::Const(n, _) if n == &Name::from_string("List.nil")),
        "Projected field of empty string should be List.nil, got head: {head_empty:?}"
    );
}

/// Test that projection on constructor-form string (String.mk <list>) still works.
/// This verifies no regression from adding string literal lowering.
#[test]
fn test_proj_string_constructor_form() {
    let env = build_string_env();
    let tc = TypeChecker::new(&env);

    let string_name = Name::from_string("String");
    let char_const = Expr::const_(Name::from_string("Char"), vec![]);
    let list_nil = Expr::app(
        Expr::const_(Name::from_string("List.nil"), vec![Level::zero()]),
        char_const.clone(),
    );

    // Build String.mk (List.nil Char) — constructor form directly
    let string_mk = Expr::const_(Name::from_string("String.mk"), vec![]);
    let ctor_form = Expr::app(string_mk, list_nil.clone());

    // Proj(String, 0, String.mk (List.nil Char)) should give List.nil Char
    let proj = Expr::proj(string_name, 0, ctor_form);
    let result = tc.whnf(&proj);

    assert!(
        !matches!(&result.kind, ExprKind::Proj(..)),
        "Proj on String.mk constructor should reduce, got: {result:?}"
    );

    let head = result.get_app_fn();
    assert!(
        matches!(&head.kind, ExprKind::Const(n, _) if n == &Name::from_string("List.nil")),
        "Projected field should be List.nil, got head: {head:?}"
    );
}

/// Regression test for #1441: projection string literal lowering must use the
/// caller's transparency mode, not Default.
///
/// Before the fix, the projection reducer called `whnf_impl` (Default/Full
/// mode) to reduce string literals, ignoring the caller's
/// `TransparencyMode`. After the fix, it calls the transparency-aware WHNF
/// path with the caller's mode.
///
/// We verify this by checking that `whnf_impl` is NOT invoked when the entire
/// projection reduction goes through the `whnf_with_transparency` path.
#[test]
fn test_proj_string_literal_lowering_uses_caller_transparency_mode() {
    use crate::env::TransparencyMode;

    let env = build_string_env();
    let tc = TypeChecker::new(&env);
    let string_name = Name::from_string("String");

    // Reset the whnf_impl call counter.
    tc.reset_whnf_impl_call_count_for_tests();
    assert_eq!(tc.whnf_impl_call_count_for_tests(), 0);

    // Reduce a string-literal projection through whnf_with_transparency.
    // This exercises the shared projection reducer's string lowering path.
    let proj = Expr::proj(string_name, 0, Expr::str_lit("a"));
    let result = tc.whnf_with_transparency(&proj, TransparencyMode::Reducible);

    // The projection must have reduced (not stuck).
    assert!(
        !matches!(&result.kind, ExprKind::Proj(..)),
        "Proj on string literal should reduce via whnf_with_transparency, got: {result:?}"
    );

    // Key regression assertion (#1441): whnf_impl (Default path) must NOT have
    // been called. Before the fix, the projection reducer called whnf_impl for
    // string lowering, which would increment this counter. After the fix, it
    // calls whnf_with_transparency_impl instead, leaving the counter at 0.
    assert_eq!(
        tc.whnf_impl_call_count_for_tests(),
        0,
        "projection reduction should use whnf_with_transparency_impl (not whnf_impl) \
         for string literal lowering when called from the WithTransparency path"
    );
}

/// Regression test for #3209: projection reduction must NOT check that the
/// constructor's inductive name matches the Proj's struct_name.
///
/// In Lean 4, type aliases create situations where Proj("Alias", 0, e) has
/// e that WHNFs to a constructor for the underlying type, not the alias.
/// For example, `Substring` might be an alias for `Substring.Raw`, so
/// `Proj("Substring", 0, x)` where x reduces to `Substring.Raw.mk(...)`.
///
/// Lean 4 type_checker.cpp:358-373 (`reduce_proj_core`) does NOT check
/// the struct name — it only checks that the head is a constructor and
/// that the field index is in bounds.
///
/// Before this fix, clean had an extra `ctor_val.inductive_name == struct_name`
/// check that prevented these projections from reducing, causing TypeMismatch
/// errors on 5 Init module constants.
#[test]
fn test_proj_reduces_across_type_alias_boundary() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    // Define the "real" type: RealPair : Type
    // RealPair.mk : Prop → Prop → RealPair
    let real_pair = Name::from_string("RealPair");
    let real_pair_mk_type = Expr::arrow(
        Expr::prop(),
        Expr::arrow(Expr::prop(), Expr::const_(real_pair.clone(), vec![])),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: real_pair.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("RealPair.mk"),
                type_: real_pair_mk_type,
            }],
        }],
    };
    env.add_inductive(decl).unwrap();

    let tc = TypeChecker::new(&env);

    // Build RealPair.mk val0 val1
    let mk = Expr::const_(Name::from_string("RealPair.mk"), vec![]);
    let val0 = Expr::prop();
    let val1 = Expr::type_();
    let pair_val = Expr::app(Expr::app(mk, val0.clone()), val1.clone());

    // Key scenario: Proj uses an ALIAS name, not the real inductive name.
    // This simulates the type alias pattern where Proj("AliasPair", 0, ...)
    // has a constructor from "RealPair" as the head.
    let alias_name = Name::from_string("AliasPair");

    // Proj("AliasPair", 0, RealPair.mk val0 val1) should STILL reduce
    // because Lean 4 does NOT check struct_name == constructor's inductive.
    let proj0 = Expr::proj(alias_name.clone(), 0, pair_val.clone());
    let result0 = tc.whnf(&proj0);
    assert_eq!(
        result0, val0,
        "Proj with alias name should reduce to field 0 (Part of #3209)"
    );

    let proj1 = Expr::proj(alias_name, 1, pair_val);
    let result1 = tc.whnf(&proj1);
    assert_eq!(
        result1, val1,
        "Proj with alias name should reduce to field 1 (Part of #3209)"
    );
}
