// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (recursor).
//
// Generated by splitting tc/tests.rs into submodules for maintainability.

use super::*;

/// Test K-axiom/UIP reduction (#781)
///
/// For K-like types (like Eq), the kernel should reduce any term `h : Eq a a`
/// to the unique constructor `Eq.refl a` when the indices are definitionally equal.
///
/// This test verifies that Eq.rec has is_k = true.
#[test]
fn test_k_axiom_reduction() {
    let mut env = Environment::new();
    env.init_eq().unwrap();

    // Verify that Eq.rec has is_k = true
    let eq_rec = env
        .get_recursor(&Name::from_string("Eq.rec"))
        .expect("Eq.rec should exist");
    assert!(
        eq_rec.is_k,
        "Eq.rec should have is_k = true, but it's false"
    );

    // Also check casesOn and recOn
    let eq_cases_on = env
        .get_recursor(&Name::from_string("Eq.casesOn"))
        .expect("Eq.casesOn should exist");
    assert!(eq_cases_on.is_k, "Eq.casesOn should have is_k = true");

    let eq_rec_on = env
        .get_recursor(&Name::from_string("Eq.recOn"))
        .expect("Eq.recOn should exist");
    assert!(eq_rec_on.is_k, "Eq.recOn should have is_k = true");
}

/// Test Eq.rec iota reduction with Eq.refl
///
/// Eq.rec uses Lean 4-style ordering: params → motive → minors → indices → major.
#[test]
fn test_eq_rec_iota_reduction() {
    let mut env = Environment::new();
    env.init_eq().unwrap();
    env.init_true_false().unwrap();

    // Verify Eq.rec structure matches Lean 4 fixed-index pattern
    let eq_rec = env.get_recursor(&Name::from_string("Eq.rec")).unwrap();
    assert_eq!(
        eq_rec.num_params, 2,
        "Eq.rec num_params (α, a — a promoted from index)"
    );
    assert_eq!(
        eq_rec.num_indices, 1,
        "Eq.rec num_indices (b — only b remains)"
    );
    assert_eq!(eq_rec.num_motives, 1, "Eq.rec num_motives");
    assert_eq!(eq_rec.num_minors, 1, "Eq.rec num_minors");
    assert!(eq_rec.is_k, "Eq.rec is_k should be true");

    let tc = TypeChecker::new(&env);

    // Recursor ordering (MajorAfterMinors):
    // args_before_major = num_params + num_motives + num_minors + num_indices
    //                   = 2 + 1 + 1 + 1 = 5
    // args layout: [param(α), param(a), motive, minor, idx(b), major]

    let prop = Expr::prop();
    let true_const = Expr::const_(Name::from_string("True"), vec![]);

    // Motive: λ (b : α) (_ : Eq a b), True
    // With fixed-index, motive takes 1 index (b) + proof, not 2 indices
    let motive = Expr::lam(
        BinderInfo::Default,
        prop.clone(),
        Expr::lam(BinderInfo::Default, Expr::prop(), true_const.clone()),
    );

    // Minor premise: True.intro (no lambda — refl minor for K-like with fixed a)
    let minor = Expr::const_(Name::from_string("True.intro"), vec![]);

    // Major premise: Eq.refl Prop True (a proof of Eq Prop True True)
    let eq_refl = Expr::const_(
        Name::from_string("Eq.refl"),
        vec![Level::succ(Level::zero())],
    );
    let h = Expr::app(Expr::app(eq_refl, prop.clone()), true_const.clone());

    // Build: Eq.rec α a motive minor b major
    // args = [param(α), param(a), motive, minor, index(b), major(h)]
    let eq_rec_const = Expr::const_(
        Name::from_string("Eq.rec"),
        vec![Level::zero(), Level::succ(Level::zero())],
    );

    let app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(
                        Expr::app(eq_rec_const, prop.clone()), // α = Prop (param 0)
                        true_const.clone(),                    // a = True (param 1, promoted)
                    ),
                    motive.clone(), // motive
                ),
                minor.clone(), // minor
            ),
            true_const.clone(), // index (b = True)
        ),
        h, // major (Eq.refl Prop True)
    );

    // WHNF should reduce this to True.intro
    let result = tc.whnf(&app);

    // The result should be True.intro
    assert_eq!(
        result,
        Expr::const_(Name::from_string("True.intro"), vec![]),
        "Eq.rec with Eq.refl should reduce to the base case. Got: {result:?}"
    );
}

/// Regression test: Eq.rec should reduce even when the major proof term is opaque.
///
/// This exercises K-conversion on a non-constructor major premise
/// (`Eq.testOpaqueProof : Eq Nat 0 0`), matching Lean 4's behavior.
#[test]
fn test_eq_rec_iota_reduction_with_opaque_major_proof() {
    use crate::env::Declaration;

    let mut env = Environment::new();
    env.init_nat().unwrap();
    env.init_eq().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);

    // Add an opaque proof constant: Eq.testOpaqueProof : Eq Nat 0 0.
    let eq_const = Expr::const_(Name::from_string("Eq"), vec![Level::succ(Level::zero())]);
    let eq_nat_zero_zero = Expr::app(
        Expr::app(Expr::app(eq_const.clone(), nat.clone()), zero.clone()),
        zero.clone(),
    );
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("Eq.testOpaqueProof"),
        level_params: vec![],
        type_: eq_nat_zero_zero,
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    // motive: λ (x : Nat) (h : Eq Nat 0 x) => Nat
    let motive = Expr::lam(
        BinderInfo::Default,
        nat.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::app(
                Expr::app(Expr::app(eq_const, nat.clone()), zero.clone()),
                Expr::bvar(0),
            ),
            nat.clone(),
        ),
    );
    let minor = zero.clone();
    let opaque_major = Expr::const_(Name::from_string("Eq.testOpaqueProof"), vec![]);

    // Eq.rec.{1,1} {Nat} {0} motive minor {0} opaque_major
    let eq_rec = Expr::const_(
        Name::from_string("Eq.rec"),
        vec![Level::succ(Level::zero()), Level::succ(Level::zero())],
    );
    let app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_rec, nat.clone()), zero.clone()),
                    motive,
                ),
                minor.clone(),
            ),
            zero,
        ),
        opaque_major,
    );

    assert_eq!(
        tc.whnf(&app),
        minor,
        "Eq.rec should reduce via K-conversion when major proof is opaque"
    );
}

/// ADVERSARIAL (WS7 soundness): K-reduction must NOT fire when the major
/// premise's indices are not definitionally equal.
///
/// `Eq.rec C m b (h : Eq Nat a b)` may only K-reduce to `m` when `a ≡ b`
/// (the unique constructor `Eq.refl` proves `Eq Nat a a`). Here the opaque
/// proof has type `Eq Nat 0 1` — `0` and `1` are distinct constructors and
/// never definitionally equal — so `to_cnstr_when_K` must reject the
/// conversion (its `is_def_eq(e_type, ctor_type)` gate fails) and `whnf` must
/// leave the `Eq.rec` application STUCK rather than collapse it to `m`.
///
/// This is the completeness-vs-soundness boundary for the WS7 `RecursorVal.k`
/// fix: enabling K for `Eq.rec`/`HEq.rec` must never let an ill-formed
/// elimination pass.
#[test]
fn test_eq_rec_k_reduction_rejects_unequal_indices() {
    use crate::env::Declaration;

    let mut env = Environment::new();
    env.init_nat().unwrap();
    env.init_eq().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let one = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        zero.clone(),
    );

    // Opaque proof `Eq.bogus : Eq Nat 0 1` (indices NOT definitionally equal).
    let eq_const = Expr::const_(Name::from_string("Eq"), vec![Level::succ(Level::zero())]);
    let eq_nat_zero_one = Expr::app(
        Expr::app(Expr::app(eq_const.clone(), nat.clone()), zero.clone()),
        one.clone(),
    );
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("Eq.bogus"),
        level_params: vec![],
        type_: eq_nat_zero_one,
    })
    .unwrap();

    let tc = TypeChecker::new(&env);

    // motive: λ (x : Nat) (h : Eq Nat 0 x) => Nat
    let motive = Expr::lam(
        BinderInfo::Default,
        nat.clone(),
        Expr::lam(
            BinderInfo::Default,
            Expr::app(
                Expr::app(Expr::app(eq_const, nat.clone()), zero.clone()),
                Expr::bvar(0),
            ),
            nat.clone(),
        ),
    );
    let minor = zero.clone();
    let bogus_major = Expr::const_(Name::from_string("Eq.bogus"), vec![]);

    // Eq.rec.{1,1} {Nat} {0} motive minor {1} bogus_major
    let eq_rec = Expr::const_(
        Name::from_string("Eq.rec"),
        vec![Level::succ(Level::zero()), Level::succ(Level::zero())],
    );
    let app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::app(Expr::app(eq_rec, nat.clone()), zero.clone()),
                    motive,
                ),
                minor.clone(),
            ),
            one,
        ),
        bogus_major,
    );

    let reduced = tc.whnf(&app);
    assert_ne!(
        reduced, minor,
        "K-reduction must NOT collapse Eq.rec to the minor premise when the \
         major premise's indices (0 vs 1) are not definitionally equal"
    );
}

/// Test that non-K types (like Nat) have is_k = false
#[test]
fn test_non_k_types() {
    let mut env = Environment::new();
    env.init_nat().unwrap();

    // Nat has two constructors (zero, succ), so is_k should be false
    let nat_rec = env
        .get_recursor(&Name::from_string("Nat.rec"))
        .expect("Nat.rec should exist");
    assert!(
        !nat_rec.is_k,
        "Nat.rec should have is_k = false (has multiple constructors)"
    );
}

/// Test that structures are not K-like (they have fields)
#[test]
fn test_structure_not_k_like() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();
    env.init_nat().unwrap();

    // Define a simple Pair structure
    let pair_name = Name::from_string("Pair");
    let pair_ref = Expr::const_(pair_name.clone(), vec![]);

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);

    // Pair.mk : Nat → Nat → Pair
    let mk_type = Expr::pi(
        BinderInfo::Default,
        nat.clone(),
        Expr::pi(BinderInfo::Default, nat.clone(), pair_ref.clone()),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: pair_name.clone(),
            type_: Expr::type_(),
            constructors: vec![Constructor {
                name: Name::from_string("Pair.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    // Pair has one constructor, but it has fields (not nullary after params)
    // So is_k should be false
    let pair_rec = env
        .get_recursor(&Name::from_string("Pair.rec"))
        .expect("Pair.rec should exist");
    assert!(
        !pair_rec.is_k,
        "Pair.rec should have is_k = false (constructor has fields)"
    );
}

/// Test that phantom-argument inductives are NOT K-like (#1396).
///
/// `Bad4.mk : (phantom : Nat) → Bad4 0` has a constructor arg that does NOT
/// appear in the return type's indices (the index is the literal 0, not BVar
/// referencing phantom). Lean 4's `init_K_target` would reject this because
/// after fixedIndicesToParams, `phantom` is a real field. Previously clean
/// used a weaker `num_ctor_args <= num_indices` check that would incorrectly
/// classify this as K-like — enabling unsound K-reduction.
#[test]
fn test_phantom_arg_not_k_like() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();
    env.init_nat().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let bad_name = Name::from_string("Bad4");
    let bad_const = Expr::const_(bad_name.clone(), vec![]);

    // Bad4 : Nat → Prop
    let bad_type = Expr::pi(
        BinderInfo::Default,
        nat.clone(),
        Expr::from_kind(ExprKind::Sort(Level::zero())),
    );

    // Bad4.mk : (phantom : Nat) → Bad4 0
    // Under 1 binder: phantom = BVar(0)
    // Return type: Bad4 (Nat.zero) — index is Nat.zero, NOT BVar(0)
    let nat_zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    let mk_type = Expr::pi(
        BinderInfo::Default,
        nat.clone(),
        Expr::app(bad_const.clone(), nat_zero),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: bad_name.clone(),
            type_: bad_type,
            constructors: vec![Constructor {
                name: Name::from_string("Bad4.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    let bad_rec = env
        .get_recursor(&Name::from_string("Bad4.rec"))
        .expect("Bad4.rec should exist");
    assert!(
        !bad_rec.is_k,
        "Bad4.rec should have is_k = false (phantom arg doesn't fill index)"
    );
}

/// Test that a Prop inductive whose constructor arg fills the index IS K-like.
///
/// `Good.mk : (x : Nat) → Good x` — the constructor arg `x` appears directly
/// as the index in the return type. This matches the fixed-index-to-params
/// promotion pattern (like Eq.refl's `a` argument).
#[test]
fn test_fixed_index_arg_is_k_like() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();
    env.init_nat().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let good_name = Name::from_string("Good");
    let good_const = Expr::const_(good_name.clone(), vec![]);

    // Good : Nat → Prop
    let good_type = Expr::pi(
        BinderInfo::Default,
        nat.clone(),
        Expr::from_kind(ExprKind::Sort(Level::zero())),
    );

    // Good.mk : (x : Nat) → Good x
    // Under 1 binder: x = BVar(0)
    // Return type: Good BVar(0) — index IS BVar(0) ✓
    let mk_type = Expr::pi(
        BinderInfo::Default,
        nat.clone(),
        Expr::app(good_const.clone(), Expr::bvar(0)),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: good_name.clone(),
            type_: good_type,
            constructors: vec![Constructor {
                name: Name::from_string("Good.mk"),
                type_: mk_type,
            }],
        }],
    };

    env.add_inductive(decl).unwrap();

    let good_rec = env
        .get_recursor(&Name::from_string("Good.rec"))
        .expect("Good.rec should exist");
    assert!(
        good_rec.is_k,
        "Good.rec should have is_k = true (ctor arg fills index)"
    );
}

// ============================================================================
// Property-based tests for iota reduction (#1027)
// ============================================================================

use proptest::prelude::*;

/// Build a Nat.rec application with proper typing for property testing.
///
/// Returns (app, env) where app is the Nat.rec application.
fn build_typed_nat_rec(n: usize) -> (Expr, Environment) {
    let mut env = Environment::new();
    env.init_nat().unwrap();

    let nat = Expr::const_(Name::from_string("Nat"), vec![]);

    // Build Nat value: succ^n(zero)
    let mut nat_val = Expr::const_(Name::from_string("Nat.zero"), vec![]);
    for _ in 0..n {
        nat_val = Expr::app(Expr::const_(Name::from_string("Nat.succ"), vec![]), nat_val);
    }

    // Motive: λ (n : Nat). Nat (maps Nat to Nat)
    let motive = Expr::lam(BinderInfo::Default, nat.clone(), nat.clone());

    // Zero case: Nat.zero (value when n = 0)
    let zero_case = Expr::const_(Name::from_string("Nat.zero"), vec![]);

    // Succ case: λ (n : Nat) (ih : Nat). succ ih
    // When we have succ(k), apply succ to the recursive result
    let succ_case = Expr::lam(
        BinderInfo::Default,
        nat.clone(), // n : Nat
        Expr::lam(
            BinderInfo::Default,
            nat.clone(), // ih : Nat (motive n)
            Expr::app(
                Expr::const_(Name::from_string("Nat.succ"), vec![]),
                Expr::bvar(0), // succ ih
            ),
        ),
    );

    // Nat.rec : {motive : Nat → Sort u} → motive zero → ((n : Nat) → motive n → motive (succ n)) → (t : Nat) → motive t
    let nat_rec = Expr::const_(
        Name::from_string("Nat.rec"),
        vec![Level::succ(Level::zero())],
    );

    // Apply: Nat.rec motive zero_case succ_case nat_val
    let app = Expr::app(
        Expr::app(Expr::app(Expr::app(nat_rec, motive), zero_case), succ_case),
        nat_val,
    );

    (app, env)
}

proptest! {
    #![proptest_config(proptest::test_runner::Config::with_cases(32))]

    /// Property: Iota reduction preserves type (#1027)
    ///
    /// ENSURES: If e : T and try_iota_reduction(e) = Some(r), then r : T.
    ///
    /// This tests the type preservation contract documented in tc/mod.rs.
    #[test]
    fn prop_iota_preserves_type(n in 0usize..8) {
        let (app, env) = build_typed_nat_rec(n);
        let tc = TypeChecker::new(&env);

        // Type the original expression
        let original_type = tc.infer_type(&app)
            .expect("Original rec application should be well-typed");

        // Reduce to WHNF (which applies iota reduction)
        let reduced = tc.whnf(&app);

        // Type the reduced expression
        let reduced_type = tc.infer_type(&reduced)
            .expect("Reduced expression should be well-typed");

        // Types must be definitionally equal
        prop_assert!(
            tc.is_def_eq(&original_type, &reduced_type),
            "Type preservation violated: \
             original type {:?} != reduced type {:?} for n={}",
            original_type, reduced_type, n
        );
    }

    /// Property: Iota reduction produces definitionally equal result (#1027)
    ///
    /// ENSURES: If try_iota_reduction(e) = Some(r), then e ≡ r.
    ///
    /// This is semantic preservation: the recursor application and its
    /// reduced form are definitionally equal.
    #[test]
    fn prop_iota_semantic_preservation(n in 0usize..8) {
        let (app, env) = build_typed_nat_rec(n);
        let tc = TypeChecker::new(&env);

        // Get WHNF (applies iota reduction internally)
        let reduced = tc.whnf(&app);

        // The original and reduced should be definitionally equal
        prop_assert!(
            tc.is_def_eq(&app, &reduced),
            "Semantic preservation violated: rec app not def_eq to reduced form for n={}",
            n
        );
    }

    /// Property: Nat.rec computes correct value (specification test)
    ///
    /// For our identity-like recursor (rec n = n), verify the computed
    /// value equals the input. This tests the actual computation, not just
    /// type preservation.
    #[test]
    fn prop_nat_rec_computes_identity(n in 0usize..8) {
        let (app, env) = build_typed_nat_rec(n);
        let tc = TypeChecker::new(&env);

        // Reduce to WHNF
        let reduced = tc.whnf(&app);

        // Build expected result: succ^n(zero) (same as input since our rec computes identity)
        let mut expected = Expr::const_(Name::from_string("Nat.zero"), vec![]);
        for _ in 0..n {
            expected = Expr::app(
                Expr::const_(Name::from_string("Nat.succ"), vec![]),
                expected,
            );
        }

        // Result should be definitionally equal to expected
        prop_assert!(
            tc.is_def_eq(&reduced, &expected),
            "Nat.rec {} did not reduce to expected succ^{}(zero). Got: {:?}",
            n, n, reduced
        );
    }
}

/// Test iota reduction with both argument order modes (#1027)
///
/// Verifies that both `MajorAfterMinors` (standard Nat.rec) and
/// `MajorAfterMotive` (recOn style) produce correct results.
#[test]
fn test_iota_both_arg_orders() {
    let mut env = Environment::new();
    env.init_nat().unwrap();

    let tc = TypeChecker::new(&env);

    // Test MajorAfterMinors (Nat.rec)
    let nat_rec = env
        .get_recursor(&Name::from_string("Nat.rec"))
        .expect("Nat.rec should exist");
    assert_eq!(
        nat_rec.arg_order,
        crate::inductive::RecursorArgOrder::MajorAfterMinors,
        "Nat.rec should use MajorAfterMinors"
    );

    // Test MajorAfterMotive (Nat.recOn)
    let nat_rec_on = env
        .get_recursor(&Name::from_string("Nat.recOn"))
        .expect("Nat.recOn should exist");
    assert_eq!(
        nat_rec_on.arg_order,
        crate::inductive::RecursorArgOrder::MajorAfterMotive,
        "Nat.recOn should use MajorAfterMotive"
    );

    // Build test: both should reduce succ(zero) correctly
    let nat = Expr::const_(Name::from_string("Nat"), vec![]);
    let nat_val = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        Expr::const_(Name::from_string("Nat.zero"), vec![]),
    ); // succ(zero) = 1

    // Motive: λ (n : Nat). Nat
    let motive = Expr::lam(BinderInfo::Default, nat.clone(), nat.clone());

    // Zero case: zero
    let zero_case = Expr::const_(Name::from_string("Nat.zero"), vec![]);

    // Succ case: λ n ih. succ ih
    let succ_case = Expr::lam(
        BinderInfo::Default,
        nat.clone(),
        Expr::lam(
            BinderInfo::Default,
            nat.clone(),
            Expr::app(
                Expr::const_(Name::from_string("Nat.succ"), vec![]),
                Expr::bvar(0),
            ),
        ),
    );

    // Nat.rec motive zero_case succ_case nat_val (MajorAfterMinors)
    let rec_app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::const_(
                        Name::from_string("Nat.rec"),
                        vec![Level::succ(Level::zero())],
                    ),
                    motive.clone(),
                ),
                zero_case.clone(),
            ),
            succ_case.clone(),
        ),
        nat_val.clone(),
    );

    // Nat.recOn motive nat_val zero_case succ_case (MajorAfterMotive)
    let rec_on_app = Expr::app(
        Expr::app(
            Expr::app(
                Expr::app(
                    Expr::const_(
                        Name::from_string("Nat.recOn"),
                        vec![Level::succ(Level::zero())],
                    ),
                    motive.clone(),
                ),
                nat_val.clone(),
            ),
            zero_case,
        ),
        succ_case,
    );

    // Both should reduce to succ(zero)
    let expected = Expr::app(
        Expr::const_(Name::from_string("Nat.succ"), vec![]),
        Expr::const_(Name::from_string("Nat.zero"), vec![]),
    );

    let rec_result = tc.whnf(&rec_app);
    let rec_on_result = tc.whnf(&rec_on_app);

    assert!(
        tc.is_def_eq(&rec_result, &expected),
        "Nat.rec with MajorAfterMinors failed: {:?}",
        rec_result
    );
    assert!(
        tc.is_def_eq(&rec_on_result, &expected),
        "Nat.recOn with MajorAfterMotive failed: {:?}",
        rec_on_result
    );
}

// ============================================================================
// K-axiom edge case tests (#1357)
// ============================================================================

/// And : Prop → Prop → Prop with 1 constructor but 2 fields and 0 indices.
/// K requires indices > 0, so And should NOT be K-like.
#[test]
fn test_and_not_k_like() {
    let mut env = Environment::new();
    env.init_and().unwrap();

    let and_rec = env
        .get_recursor(&Name::from_string("And.rec"))
        .expect("And.rec should exist");
    assert!(
        !and_rec.is_k,
        "And.rec should have is_k = false (no indices)"
    );

    let and_cases = env
        .get_recursor(&Name::from_string("And.casesOn"))
        .expect("And.casesOn should exist");
    assert!(
        !and_cases.is_k,
        "And.casesOn should have is_k = false (no indices)"
    );
}

/// Unit : Type with 1 constructor, 0 fields, but NOT in Prop.
/// K requires the type to be in Prop, so Unit should NOT be K-like.
/// Unit is now a reducible definition for PUnit.{1} (#3418), so there is no
/// Unit.rec. Instead we test that PUnit.rec (which Unit delegates to) is not
/// K-like. PUnit.{u} : Sort u lives outside Prop for u >= 1.
#[test]
fn test_punit_not_k_like() {
    let mut env = Environment::new();
    env.init_unit().unwrap(); // also initializes PUnit

    let punit_rec = env
        .get_recursor(&Name::from_string("PUnit.rec"))
        .expect("PUnit.rec should exist");
    assert!(
        !punit_rec.is_k,
        "PUnit.rec should have is_k = false (PUnit lives in Sort u, not Prop)"
    );
}

/// True : Prop with 1 constructor (True.intro), 0 fields, and 0 indices.
/// Lean 4's init_K_target accepts this: in Prop, 1 ctor, 0 fields beyond params.
/// K-reduction for True is equivalent to standard iota, but Lean 4 marks it K.
#[test]
fn test_true_is_k_like() {
    let mut env = Environment::new();
    env.init_eq().unwrap(); // Ne (defined in init_true_false) depends on Eq
    env.init_true_false().unwrap();

    let true_rec = env
        .get_recursor(&Name::from_string("True.rec"))
        .expect("True.rec should exist");
    assert!(
        true_rec.is_k,
        "True.rec should have is_k = true (Prop, 1 ctor, 0 fields — matches Lean 4)"
    );
}

/// Or : Prop → Prop → Prop with 2 constructors (inl, inr).
/// K requires exactly 1 constructor, so Or should NOT be K-like.
#[test]
fn test_or_not_k_like() {
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};

    let mut env = Environment::new();

    let or_name = Name::from_string("Or");

    // Or : Prop → Prop → Prop
    let or_type = Expr::pi(
        BinderInfo::Default,
        Expr::prop(),
        Expr::pi(BinderInfo::Default, Expr::prop(), Expr::prop()),
    );

    // Or.inl : (P Q : Prop) → P → Or P Q
    let inl_type = Expr::pi(
        BinderInfo::Default,
        Expr::prop(),
        Expr::pi(
            BinderInfo::Default,
            Expr::prop(),
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(1), // proof of P
                Expr::app(
                    Expr::app(Expr::const_(or_name.clone(), vec![]), Expr::bvar(2)),
                    Expr::bvar(1),
                ),
            ),
        ),
    );

    // Or.inr : (P Q : Prop) → Q → Or P Q
    let inr_type = Expr::pi(
        BinderInfo::Default,
        Expr::prop(),
        Expr::pi(
            BinderInfo::Default,
            Expr::prop(),
            Expr::pi(
                BinderInfo::Default,
                Expr::bvar(0), // proof of Q
                Expr::app(
                    Expr::app(Expr::const_(or_name.clone(), vec![]), Expr::bvar(2)),
                    Expr::bvar(1),
                ),
            ),
        ),
    );

    let decl = InductiveDecl {
        level_params: vec![],
        num_params: 2,
        types: vec![InductiveType {
            name: or_name,
            type_: or_type,
            constructors: vec![
                Constructor {
                    name: Name::from_string("Or.inl"),
                    type_: inl_type,
                },
                Constructor {
                    name: Name::from_string("Or.inr"),
                    type_: inr_type,
                },
            ],
        }],
    };

    env.add_inductive(decl).unwrap();

    let or_rec = env
        .get_recursor(&Name::from_string("Or.rec"))
        .expect("Or.rec should exist");
    assert!(
        !or_rec.is_k,
        "Or.rec should have is_k = false (2 constructors)"
    );
}

/// HEq is K-like: Prop-sorted, 1 constructor, has indices.
/// HEq : {α : Sort u} → α → {β : Sort u} → β → Prop
/// HEq.refl : {α : Sort u} → (a : α) → HEq a a
#[test]
fn test_heq_is_k_like() {
    let mut env = Environment::new();
    env.init_heq().unwrap();

    let heq_rec = env
        .get_recursor(&Name::from_string("HEq.rec"))
        .expect("HEq.rec should exist");
    assert!(
        heq_rec.is_k,
        "HEq.rec should have is_k = true (Prop, 1 ctor, has indices)"
    );
}

/// False : Prop with 0 constructors.
/// K requires exactly 1 constructor, so False should NOT be K-like.
#[test]
fn test_false_not_k_like() {
    let mut env = Environment::new();
    env.init_eq().unwrap(); // Ne (defined in init_true_false) depends on Eq
    env.init_true_false().unwrap();

    let false_rec = env
        .get_recursor(&Name::from_string("False.rec"))
        .expect("False.rec should exist");
    assert!(
        !false_rec.is_k,
        "False.rec should have is_k = false (0 constructors)"
    );
}
