// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Tests for type checker (whnf).
//
// Generated by splitting tc/tests.rs into submodules for maintainability.

use super::*;

#[test]
fn test_whnf_cache_cleared_on_local_context_mut() {
    // Tests that calling local_context_mut() clears the WHNF cache.
    // This is critical for correctness: WHNF results may depend on free
    // variables that change meaning when the local context is modified.
    let env = Environment::new();
    let mut tc = TypeChecker::new(&env);

    // Perform a WHNF reduction to populate the cache
    // (λ x : Prop. x) Prop -> Prop (beta reduces to Prop)
    let lam = Expr::lam(BinderInfo::Default, Expr::prop(), Expr::bvar(0));
    let app = Expr::app(lam.clone(), Expr::prop());
    let whnf_result = tc.whnf(&app);
    assert_eq!(
        whnf_result,
        Expr::prop(),
        "whnf of (λ x : Prop. x) Prop should be Prop"
    );

    // Verify cache has an entry
    assert!(
        !tc.whnf_cache.borrow().is_empty(),
        "Cache should have entry after WHNF"
    );

    // Call local_context_mut() which should clear the cache
    let ctx_mut = tc.local_context_mut();
    let _id = ctx_mut.push(Name::anon(), Expr::prop(), BinderInfo::Default);

    // Verify cache was actually cleared
    assert!(
        tc.whnf_cache.borrow().is_empty(),
        "Cache should be empty after local_context_mut()"
    );

    // The WHNF should still produce the same result (correctness check).
    let result = tc.whnf(&app);
    assert_eq!(result, Expr::prop());
}

// D4 transparency tests are in env/tests.rs (needs private field access)

/// Helper: build a simple let expression for idempotence tests.
fn test_let(ty: Expr, val: Expr, body: Expr) -> Expr {
    Expr::let_named(Name::anon(), ty, val, body, false)
}

/// Test WHNF idempotence property explicitly (not just debug assertion).
///
/// Contract: `whnf(whnf(e)) == whnf(e)` for all expressions.
/// This test verifies the idempotence claim in mod.rs:1762, 1767.
/// The debug assertion (line 1784-1790) only runs in debug builds.
#[test]
fn test_whnf_idempotent() {
    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    let test_cases: Vec<Expr> = vec![
        Expr::prop(),
        Expr::type_(),
        Expr::bvar(0),
        test_let(Expr::type_(), Expr::prop(), Expr::bvar(0)),
        test_let(
            Expr::type_(),
            test_let(Expr::type_(), Expr::prop(), Expr::bvar(0)),
            Expr::bvar(0),
        ),
        Expr::app(
            Expr::lam(BinderInfo::Default, Expr::type_(), Expr::bvar(0)),
            Expr::prop(),
        ),
        Expr::app(
            Expr::lam(BinderInfo::Default, Expr::type_(), Expr::bvar(0)),
            Expr::app(
                Expr::lam(BinderInfo::Default, Expr::type_(), Expr::bvar(0)),
                Expr::type_(),
            ),
        ),
        Expr::from_kind(ExprKind::Sort(Level::succ(Level::succ(Level::zero())))),
        Expr::pi(
            BinderInfo::Default,
            Expr::prop(),
            test_let(Expr::type_(), Expr::type_(), Expr::bvar(0)),
        ),
        Expr::lam(
            BinderInfo::Default,
            Expr::prop(),
            test_let(Expr::type_(), Expr::type_(), Expr::bvar(0)),
        ),
    ];

    for e in test_cases {
        let whnf1 = tc.whnf(&e);
        let whnf2 = tc.whnf(&whnf1);
        assert_eq!(
            whnf1, whnf2,
            "WHNF not idempotent for {e:?}\nFirst WHNF: {whnf1:?}\nSecond WHNF: {whnf2:?}"
        );
    }
}

// ============================================================================
// whnf_with_transparency tests
// ============================================================================

/// Test whnf_with_transparency respects TransparencyMode for delta reduction.
///
/// Sets up constants with different reducibility levels and verifies
/// that each TransparencyMode only unfolds what it should.
#[test]
fn test_whnf_with_transparency_reducible_mode() {
    use crate::env::{Reducibility, TransparencyMode};

    let mut env = Environment::new();

    // Add a reducible definition: `myTrue := Prop`
    let mut info_reducible = crate::env::ConstantInfo::new(
        Name::from_string("myReducible"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    info_reducible.reducibility = Reducibility::Reducible;
    env.extend_constants_unchecked(std::iter::once(info_reducible));

    // Add a semireducible definition: `mySemi := Prop`
    let mut info_semi = crate::env::ConstantInfo::new(
        Name::from_string("mySemi"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    info_semi.reducibility = Reducibility::Regular(0);
    env.extend_constants_unchecked(std::iter::once(info_semi));

    // Add an irreducible definition: `myIrred := Prop`
    let mut info_irred = crate::env::ConstantInfo::new(
        Name::from_string("myIrred"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    info_irred.reducibility = Reducibility::Irreducible;
    env.extend_constants_unchecked(std::iter::once(info_irred));

    let tc = TypeChecker::new(&env);

    let reducible_expr = Expr::const_(Name::from_string("myReducible"), vec![]);
    let semi_expr = Expr::const_(Name::from_string("mySemi"), vec![]);
    let irred_expr = Expr::const_(Name::from_string("myIrred"), vec![]);

    // Reducible mode: only unfolds @[reducible]
    let r = tc.whnf_with_transparency(&reducible_expr, TransparencyMode::Reducible);
    assert_eq!(
        r,
        Expr::prop(),
        "Reducible const should unfold in Reducible mode"
    );

    let r = tc.whnf_with_transparency(&semi_expr, TransparencyMode::Reducible);
    assert_eq!(
        r, semi_expr,
        "Semireducible const should NOT unfold in Reducible mode"
    );

    let r = tc.whnf_with_transparency(&irred_expr, TransparencyMode::Reducible);
    assert_eq!(
        r, irred_expr,
        "Irreducible const should NOT unfold in Reducible mode"
    );
}

#[test]
fn test_whnf_with_transparency_default_mode() {
    use crate::env::{Reducibility, TransparencyMode};

    let mut env = Environment::new();

    let mut info = crate::env::ConstantInfo::new(
        Name::from_string("defSemi"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    info.reducibility = Reducibility::Regular(0);
    env.extend_constants_unchecked(std::iter::once(info));

    let mut info_irred = crate::env::ConstantInfo::new(
        Name::from_string("defIrred"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    info_irred.reducibility = Reducibility::Irreducible;
    env.extend_constants_unchecked(std::iter::once(info_irred));

    let tc = TypeChecker::new(&env);

    // Default mode: unfolds semireducible but not irreducible
    let semi_expr = Expr::const_(Name::from_string("defSemi"), vec![]);
    let r = tc.whnf_with_transparency(&semi_expr, TransparencyMode::Default);
    assert_eq!(
        r,
        Expr::prop(),
        "Semireducible should unfold in Default mode"
    );

    let irred_expr = Expr::const_(Name::from_string("defIrred"), vec![]);
    let r = tc.whnf_with_transparency(&irred_expr, TransparencyMode::Default);
    assert_eq!(
        r, irred_expr,
        "Irreducible should NOT unfold in Default mode"
    );
}

#[test]
fn test_whnf_with_transparency_all_mode() {
    use crate::env::{Reducibility, TransparencyMode};

    let mut env = Environment::new();

    let mut info = crate::env::ConstantInfo::new(
        Name::from_string("allIrred"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    info.reducibility = Reducibility::Irreducible;
    env.extend_constants_unchecked(std::iter::once(info));

    let tc = TypeChecker::new(&env);

    // All mode: unfolds everything including irreducible
    let irred_expr = Expr::const_(Name::from_string("allIrred"), vec![]);
    let r = tc.whnf_with_transparency(&irred_expr, TransparencyMode::All);
    assert_eq!(r, Expr::prop(), "Irreducible should unfold in All mode");
}

#[test]
fn test_whnf_with_transparency_beta_reduction() {
    use crate::env::TransparencyMode;

    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Beta reduction should work regardless of transparency mode
    // (λ x : Prop. x) Prop → Prop
    let lam = Expr::lam(BinderInfo::Default, Expr::prop(), Expr::bvar(0));
    let app = Expr::app(lam, Expr::prop());

    for mode in [
        TransparencyMode::Reducible,
        TransparencyMode::Default,
        TransparencyMode::All,
    ] {
        let r = tc.whnf_with_transparency(&app, mode);
        assert_eq!(
            r,
            Expr::prop(),
            "Beta reduction should work in {mode:?} mode"
        );
    }
}

#[test]
fn test_whnf_with_transparency_let_reduction() {
    use crate::env::TransparencyMode;

    let env = Environment::new();
    let tc = TypeChecker::new(&env);

    // Zeta reduction (let) should work regardless of transparency
    // let x : Type := Prop in x → Prop
    let let_expr = Expr::let_named(
        Name::anon(),
        Expr::type_(),
        Expr::prop(),
        Expr::bvar(0),
        false,
    );

    for mode in [
        TransparencyMode::Reducible,
        TransparencyMode::Default,
        TransparencyMode::All,
    ] {
        let r = tc.whnf_with_transparency(&let_expr, mode);
        assert_eq!(
            r,
            Expr::prop(),
            "Zeta reduction should work in {mode:?} mode"
        );
    }
}

fn build_single_projection_transparency_env() -> (Environment, Name, Name) {
    use crate::env::{Declaration, Reducibility};
    use crate::inductive::{Constructor, InductiveDecl, InductiveType};
    use crate::level::Level;

    let mut env = Environment::new();

    let semi_name = Name::from_string("semiProp");
    env.add_decl(Declaration::Definition {
        name: semi_name.clone(),
        level_params: vec![],
        type_: Expr::type_(),
        value: Expr::prop(),
        is_reducible: true,
    })
    .expect("semiProp declaration should be valid");
    assert!(
        env.set_reducibility(&semi_name, Reducibility::Regular(0)),
        "set_reducibility should succeed for semiProp"
    );

    // inductive Single : Type 1 where | mk : Type -> Single
    let single_name = Name::from_string("Single");
    let single_ref = Expr::const_(single_name.clone(), vec![]);
    env.add_inductive(InductiveDecl {
        level_params: vec![],
        num_params: 0,
        types: vec![InductiveType {
            name: single_name.clone(),
            type_: Expr::sort(Level::succ(Level::succ(Level::zero()))),
            constructors: vec![Constructor {
                name: Name::from_string("Single.mk"),
                type_: Expr::pi(BinderInfo::Default, Expr::type_(), single_ref.clone()),
            }],
        }],
    })
    .expect("Single inductive declaration should be valid");

    (env, single_name, semi_name)
}

fn single_mk_expr(value: Expr) -> Expr {
    Expr::app(Expr::const_(Name::from_string("Single.mk"), vec![]), value)
}

/// Regression test for WHNF core unification:
/// projection reduction under `whnf_with_transparency` must re-enter WHNF with
/// the same transparency mode when the projection succeeds.
#[test]
fn test_whnf_with_transparency_proj_result_respects_mode() {
    use crate::env::TransparencyMode;

    let (env, single_name, semi_name) = build_single_projection_transparency_env();

    let tc = TypeChecker::new(&env);

    let semi_const = Expr::const_(semi_name, vec![]);
    let single_val = single_mk_expr(semi_const.clone());
    let proj = Expr::proj(single_name, 0, single_val);

    let reducible = tc.whnf_with_transparency(&proj, TransparencyMode::Reducible);
    assert_eq!(
        reducible, semi_const,
        "Reducible mode should not unfold semireducible projection result"
    );

    let default = tc.whnf_with_transparency(&proj, TransparencyMode::Default);
    assert_eq!(
        default,
        Expr::prop(),
        "Default mode should unfold semireducible projection result"
    );
}

/// Regression test for WHNF core unification:
/// projection reduction must recurse when the extracted field is itself a
/// projection expression.
///
/// Lean 4's `whnfCore` calls `go e` after successful projection extraction,
/// even when `e` is another `.proj`. The shared reducer must preserve that
/// behavior under the caller's transparency mode.
#[test]
fn test_whnf_with_transparency_proj_result_recurses_when_field_is_proj() {
    use crate::env::TransparencyMode;

    let (env, single_name, semi_name) = build_single_projection_transparency_env();

    let tc = TypeChecker::new(&env);

    let semi_const = Expr::const_(semi_name, vec![]);
    let inner_proj = Expr::proj(single_name.clone(), 0, single_mk_expr(semi_const.clone()));
    let outer_proj = Expr::proj(single_name, 0, single_mk_expr(inner_proj));

    let reducible = tc.whnf_with_transparency(&outer_proj, TransparencyMode::Reducible);
    assert_eq!(
        reducible, semi_const,
        "Reducible mode should recurse through nested projection results without unfolding semireducible defs"
    );

    let default = tc.whnf_with_transparency(&outer_proj, TransparencyMode::Default);
    assert_eq!(
        default,
        Expr::prop(),
        "Default mode should recurse through nested projection results and unfold semireducible defs"
    );
}

// ============================================================================
// Transparency-aware reduction vs. kernel completeness (#3208 follow-up)
//
// These tests pin the contract that `whnf_with_transparency` honors the Lean 4
// `@[irreducible]`/`@[reducible]` hints bridged from `.olean` (an elaboration-
// time transparency concern), while the kernel type-checker's `whnf`/`is_def_eq`
// stays COMPLETE by unfolding everything except `Opaque`. Skipping irreducible
// unfolding in the kernel path would incompletely reject valid def-eq; these
// tests guard against that regression.
// ============================================================================

/// Build an environment with one `@[irreducible]` def and one `@[reducible]`
/// def, both whose value is `Prop`. Returns the env plus the const exprs.
fn build_irreducible_reducible_env() -> (Environment, Expr, Expr) {
    use crate::env::Reducibility;

    let mut env = Environment::new();

    let mut irred = crate::env::ConstantInfo::new(
        Name::from_string("transpIrred"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    irred.reducibility = Reducibility::Irreducible;
    env.extend_constants_unchecked(std::iter::once(irred));

    let mut red = crate::env::ConstantInfo::new(
        Name::from_string("transpRed"),
        vec![],
        Expr::type_(),
        Some(Expr::prop()),
        false,
    );
    red.reducibility = Reducibility::Reducible;
    env.extend_constants_unchecked(std::iter::once(red));

    let irred_expr = Expr::const_(Name::from_string("transpIrred"), vec![]);
    let red_expr = Expr::const_(Name::from_string("transpRed"), vec![]);
    (env, irred_expr, red_expr)
}

/// A `Default`-transparency WHNF must NOT unfold an `@[irreducible]` def — the
/// constant stays in head position (matches the elaborator's def-eq behavior).
#[test]
fn test_whnf_default_transparency_skips_irreducible() {
    let (env, irred_expr, _red_expr) = build_irreducible_reducible_env();
    let tc = TypeChecker::new(&env);

    let r = tc.whnf_with_transparency(&irred_expr, TransparencyMode::Default);
    assert_eq!(
        r, irred_expr,
        "Default transparency must leave @[irreducible] def folded (no delta unfold)"
    );
}

/// A `Default`-transparency WHNF DOES eagerly unfold an `@[reducible]` def.
#[test]
fn test_whnf_default_transparency_unfolds_reducible() {
    let (env, _irred_expr, red_expr) = build_irreducible_reducible_env();
    let tc = TypeChecker::new(&env);

    let r = tc.whnf_with_transparency(&red_expr, TransparencyMode::Default);
    assert_eq!(
        r,
        Expr::prop(),
        "Default transparency must eagerly unfold @[reducible] def to its value"
    );
}

/// An `All`-transparency WHNF unfolds even `@[irreducible]` defs, AND the kernel
/// type-checker (`whnf` / `is_def_eq`) still unfolds the same irreducible def —
/// confirming kernel completeness is preserved (the kernel has no transparency).
#[test]
fn test_whnf_all_transparency_unfolds_irreducible() {
    let (env, irred_expr, _red_expr) = build_irreducible_reducible_env();
    let tc = TypeChecker::new(&env);

    // All-mode transparency: unfolds irreducible.
    let r_all = tc.whnf_with_transparency(&irred_expr, TransparencyMode::All);
    assert_eq!(
        r_all,
        Expr::prop(),
        "All transparency must unfold @[irreducible] def to its value"
    );

    // Kernel type-checker path: `whnf` (full delta, no transparency) must ALSO
    // unfold the irreducible def — otherwise the kernel would be INCOMPLETE.
    let r_kernel = tc.whnf(&irred_expr);
    assert_eq!(
        r_kernel,
        Expr::prop(),
        "Kernel whnf must unfold @[irreducible] def (completeness preserved)"
    );

    // And kernel def-eq must therefore see the irreducible const as def-eq to
    // its unfolded value — the property a transparency-skipping kernel would break.
    let tc2 = TypeChecker::new(&env);
    assert!(
        tc2.is_def_eq(&irred_expr, &Expr::prop()),
        "Kernel is_def_eq must equate @[irreducible] def with its value (completeness)"
    );
}

// ============================================================================
// TypeError error path tests (#416)
// These tests verify that the type checker correctly rejects ill-typed
// expressions with the appropriate error type.
// ============================================================================
