// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Certificate export for pseudo-Boolean proofs.
//!
//! Generates verifiable certificates from VeriPB proofs, including:
//! - Formula fingerprinting via blake3 hashing
//! - Proof step statistics by rule type
//! - Proof size ratio (certificate bytes / formula bytes)
//!
//! Certificates provide a trust anchor: given the formula hash and the proof
//! text, any VeriPB-compatible checker can independently verify the result.

use std::collections::HashMap;

use super::rules::PbRule;
use super::types::PbFormula;
use super::veripb::{VeriPbProof, VeriPbStep};

/// A certificate attesting to a verified PB proof.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PbCertificate {
    /// Blake3 hash of the formula in canonical OPB representation.
    pub formula_hash: String,
    /// Number of proof steps.
    pub num_steps: usize,
    /// Whether the proof was verified successfully.
    pub verified: bool,
    /// Statistics about the proof.
    pub stats: CertificateStats,
    /// The VeriPB format proof text.
    pub proof_text: String,
}

/// Statistics about a PB proof certificate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CertificateStats {
    /// Count of each rule type used in the proof.
    pub rule_counts: HashMap<String, usize>,
    /// Number of input constraints in the formula.
    pub formula_size: usize,
    /// Size of the VeriPB proof text in bytes.
    pub proof_size_bytes: usize,
    /// Number of delete operations in the proof.
    pub delete_count: usize,
    /// Number of undo operations in the proof.
    pub undo_count: usize,
}

/// Export a VeriPB proof as a certificate with formula hashing.
///
/// The certificate includes:
/// 1. Blake3 hash of the formula in canonical OPB format
/// 2. The VeriPB proof text
/// 3. Verification result
/// 4. Proof statistics
pub(crate) fn export_certificate(proof: &VeriPbProof) -> PbCertificate {
    let proof_text = export_veripb(proof);
    let formula_hash = hash_formula(&proof.formula);
    let verified = proof.verify().is_ok();
    let stats = compute_stats(proof);

    PbCertificate {
        formula_hash,
        num_steps: proof.steps.len(),
        verified,
        stats,
        proof_text,
    }
}

/// Export the VeriPB proof text with a blake3 hash header.
///
/// Wraps `VeriPbProof::to_veripb_format()` with a formula fingerprint
/// comment line for integrity verification.
#[must_use]
pub(crate) fn export_veripb(proof: &VeriPbProof) -> String {
    let hash = hash_formula(&proof.formula);
    let veripb_text = proof.to_veripb_format();

    format!("* formula-hash: blake3:{hash}\n{veripb_text}")
}

/// Compute the blake3 hash of a PB formula in canonical OPB representation.
///
/// The canonical form is generated by `write_opb`, which produces a
/// deterministic string for any given formula. This ensures that
/// structurally identical formulas always produce the same hash.
#[must_use]
pub(crate) fn hash_formula(formula: &PbFormula) -> String {
    let canonical = super::opb_format::write_opb(formula);
    let hash = blake3::hash(canonical.as_bytes());
    hash.to_hex().to_string()
}

/// Compute statistics for a VeriPB proof.
fn compute_stats(proof: &VeriPbProof) -> CertificateStats {
    let mut rule_counts: HashMap<String, usize> = HashMap::new();
    let mut delete_count = 0usize;
    let mut undo_count = 0usize;

    for step in &proof.steps {
        match step {
            VeriPbStep::PolynomialAddition { rule, .. } => {
                let name = rule_name(rule);
                *rule_counts.entry(name).or_insert(0) += 1;
            }
            VeriPbStep::ReverseUnitPropagation { .. } => {
                *rule_counts.entry("rup".to_string()).or_insert(0) += 1;
            }
            VeriPbStep::RedundantAddition { .. } => {
                *rule_counts.entry("red".to_string()).or_insert(0) += 1;
            }
            VeriPbStep::Delete { .. } => {
                delete_count += 1;
            }
            VeriPbStep::Undo { .. } => {
                undo_count += 1;
            }
            VeriPbStep::Conclude => {
                *rule_counts.entry("conclude".to_string()).or_insert(0) += 1;
            }
        }
    }

    let proof_text = proof.to_veripb_format();

    CertificateStats {
        rule_counts,
        formula_size: proof.formula.constraints.len(),
        proof_size_bytes: proof_text.len(),
        delete_count,
        undo_count,
    }
}

/// Human-readable name for a PB proof rule.
fn rule_name(rule: &PbRule) -> String {
    match rule {
        PbRule::Input(_) => "input".to_string(),
        PbRule::Addition { .. } => "addition".to_string(),
        PbRule::Multiplication { .. } => "multiplication".to_string(),
        PbRule::Division { .. } => "division".to_string(),
        PbRule::Saturation(_) => "saturation".to_string(),
        PbRule::Rounding(_) => "rounding".to_string(),
        PbRule::GeneralizedResolution { .. } => "generalized_resolution".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::super::types::PbConstraint;
    use super::*;

    fn make_simple_proof() -> VeriPbProof {
        let mut formula = PbFormula::new(1);
        formula.add_constraint(PbConstraint::new(vec![(1, 1)], 1));
        formula.add_constraint(PbConstraint::new(vec![(1, -1)], 1));

        let mut proof = VeriPbProof::new(formula);
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![(1, 1)], 1),
            rule: PbRule::Input(0),
        });
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![(1, -1)], 1),
            rule: PbRule::Input(1),
        });
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![], 1),
            rule: PbRule::GeneralizedResolution {
                left: 0,
                right: 1,
                var: 1,
            },
        });
        proof.add_step(VeriPbStep::Conclude);
        proof
    }

    #[test]
    fn test_export_certificate_verified() {
        let proof = make_simple_proof();
        let cert = export_certificate(&proof);

        assert!(cert.verified);
        assert!(!cert.formula_hash.is_empty());
        assert_eq!(cert.num_steps, 4);
    }

    #[test]
    fn test_export_certificate_stats() {
        let proof = make_simple_proof();
        let cert = export_certificate(&proof);

        assert_eq!(cert.stats.formula_size, 2);
        assert_eq!(cert.stats.rule_counts.get("input"), Some(&2));
        assert_eq!(
            cert.stats.rule_counts.get("generalized_resolution"),
            Some(&1)
        );
        assert_eq!(cert.stats.rule_counts.get("conclude"), Some(&1));
        assert!(cert.stats.proof_size_bytes > 0);
    }

    #[test]
    fn test_export_veripb_includes_hash() {
        let proof = make_simple_proof();
        let text = export_veripb(&proof);

        assert!(text.starts_with("* formula-hash: blake3:"));
        assert!(text.contains("pseudo-Boolean proof version 2.0"));
    }

    #[test]
    fn test_hash_formula_deterministic() {
        let mut formula = PbFormula::new(2);
        formula.add_constraint(PbConstraint::new(vec![(1, 1), (2, 2)], 3));

        let hash1 = hash_formula(&formula);
        let hash2 = hash_formula(&formula);
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_hash_formula_different_formulas_different_hashes() {
        let mut f1 = PbFormula::new(2);
        f1.add_constraint(PbConstraint::new(vec![(1, 1), (2, 2)], 3));

        let mut f2 = PbFormula::new(2);
        f2.add_constraint(PbConstraint::new(vec![(1, 1), (2, 2)], 4)); // different degree

        assert_ne!(hash_formula(&f1), hash_formula(&f2));
    }

    #[test]
    fn test_certificate_unverified_proof() {
        let mut formula = PbFormula::new(1);
        formula.add_constraint(PbConstraint::new(vec![(1, 1)], 1));

        let mut proof = VeriPbProof::new(formula);
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![(1, 1)], 1),
            rule: PbRule::Input(0),
        });
        // No conclude step — proof is incomplete.

        let cert = export_certificate(&proof);
        assert!(!cert.verified);
    }

    #[test]
    fn test_certificate_stats_with_delete() {
        let mut formula = PbFormula::new(1);
        formula.add_constraint(PbConstraint::new(vec![(1, 1)], 1));
        formula.add_constraint(PbConstraint::new(vec![(1, -1)], 1));

        let mut proof = VeriPbProof::new(formula);
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![(1, 1)], 1),
            rule: PbRule::Input(0),
        });
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![(1, -1)], 1),
            rule: PbRule::Input(1),
        });
        proof.add_step(VeriPbStep::PolynomialAddition {
            result: PbConstraint::new(vec![], 1),
            rule: PbRule::GeneralizedResolution {
                left: 0,
                right: 1,
                var: 1,
            },
        });
        proof.add_step(VeriPbStep::Delete { id: 0 });
        proof.add_step(VeriPbStep::Conclude);

        let cert = export_certificate(&proof);
        assert!(cert.verified);
        assert_eq!(cert.stats.delete_count, 1);
    }
}
