// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Polynomial Calculus over GF(2) -- S44: `pc_soundness_gf2`
//!
//! Encodes propositional satisfiability as polynomial algebra over the
//! two-element Galois field GF(2) = ({0,1}, XOR, AND).
//!
//! ## Encoding
//!
//! A clause (x1 v x2 v ... v xk) is unsatisfied exactly when all
//! literals are false. For positive literal xi, "false" means xi=0;
//! for negative literal !xi, "false" means xi=1. The clause is
//! encoded as the polynomial:
//!
//!   prod(1 - xi) for positive literals, prod(xi) for negative literals = 0
//!
//! More precisely: for literal li, let fi = (1-xi) if li=xi, or fi=xi
//! if li=!xi. Then the clause polynomial is prod fi = 0.
//!
//! ## GF(2) Arithmetic
//!
//! - Addition is XOR: 0+0=0, 0+1=1, 1+0=1, 1+1=0.
//! - Multiplication is AND: only 1*1=1.
//! - The field equation x^2 = x holds for all elements (idempotency).
//!
//! ## Proof System (PC/GF(2))
//!
//! A Polynomial Calculus proof derives the constant polynomial 1
//! (contradiction in GF(2), since 1=0 is false) from axiom polynomials
//! using these rules:
//!
//! - **Axiom**: introduce a clause polynomial.
//! - **Addition**: p + q (XOR of two derived polynomials).
//! - **Multiplication**: p * xi (multiply by a single variable).
//! - **Weakening**: add an arbitrary monomial (sound over GF(2) since
//!   we work modulo the ideal generated by {xi^2 - xi}).
//!
//! ## References
//!
//! - Clegg, Edmonds, Impagliazzo (1996). Using the Groebner basis
//!   algorithm to find proofs of unsatisfiability. STOC'96.
//! - Razborov (1998). Lower bounds for the polynomial calculus.
//!   Computational Complexity 7(4), pp. 291-324.

use std::collections::BTreeSet;
use std::collections::HashMap;

/// A multilinear polynomial over GF(2).
///
/// Represented as a map from monomials (sets of variable indices) to
/// coefficients in {0, 1}. Only monomials with coefficient 1 are stored;
/// absent monomials have coefficient 0.
///
/// The constant monomial is represented by the empty set.
///
/// Invariant: after every operation, `reduce()` ensures x^2 = x
/// (multilinearity), and zero-coefficient monomials are removed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GF2Polynomial {
    /// Monomials with coefficient 1. Key = sorted set of variable indices.
    terms: HashMap<BTreeSet<usize>, bool>,
}

impl GF2Polynomial {
    /// Create the zero polynomial.
    #[must_use]
    pub fn zero() -> Self {
        Self {
            terms: HashMap::new(),
        }
    }

    /// Create the constant polynomial 1.
    #[must_use]
    pub fn one() -> Self {
        let mut terms = HashMap::new();
        terms.insert(BTreeSet::new(), true);
        Self { terms }
    }

    /// Create a single-variable polynomial xi.
    #[must_use]
    pub fn var(i: usize) -> Self {
        let mut terms = HashMap::new();
        let mut mono = BTreeSet::new();
        mono.insert(i);
        terms.insert(mono, true);
        Self { terms }
    }

    /// Create a polynomial from a single monomial (product of variables).
    #[must_use]
    pub fn monomial(vars: &[usize]) -> Self {
        let mut terms = HashMap::new();
        let mono: BTreeSet<usize> = vars.iter().copied().collect();
        terms.insert(mono, true);
        Self { terms }
    }

    /// Check if this is the zero polynomial.
    #[must_use]
    pub fn is_zero(&self) -> bool {
        self.terms.is_empty()
    }

    /// Check if this equals the constant polynomial 1.
    #[must_use]
    pub fn is_one(&self) -> bool {
        self.terms.len() == 1 && self.terms.contains_key(&BTreeSet::new())
    }

    /// Add two polynomials over GF(2) (XOR of coefficients).
    #[must_use]
    pub fn add(&self, other: &Self) -> Self {
        let mut result = self.terms.clone();
        for mono in other.terms.keys() {
            if result.contains_key(mono) {
                // 1 + 1 = 0 in GF(2): remove the monomial.
                result.remove(mono);
            } else {
                result.insert(mono.clone(), true);
            }
        }
        Self { terms: result }
    }

    /// Multiply two polynomials over GF(2), then reduce (x^2 = x).
    #[must_use]
    pub fn mul(&self, other: &Self) -> Self {
        let mut result_terms: HashMap<BTreeSet<usize>, bool> = HashMap::new();

        for m1 in self.terms.keys() {
            for m2 in other.terms.keys() {
                // Multiply monomials: union of variable sets (multilinear).
                let product: BTreeSet<usize> = m1.union(m2).copied().collect();
                // XOR the coefficient.
                if let std::collections::hash_map::Entry::Vacant(e) =
                    result_terms.entry(product.clone())
                {
                    e.insert(true);
                } else {
                    result_terms.remove(&product);
                }
            }
        }

        let mut poly = Self {
            terms: result_terms,
        };
        poly.reduce();
        poly
    }

    /// Multiply by a single variable.
    #[must_use]
    pub fn mul_var(&self, var: usize) -> Self {
        self.mul(&Self::var(var))
    }

    /// Reduce modulo the field equations x^2 = x for all variables.
    ///
    /// Since we represent monomials as sets (no repeated variables),
    /// multilinearity is already enforced by construction. This method
    /// cleans up any zero-coefficient terms.
    pub fn reduce(&mut self) {
        self.terms.retain(|_, coeff| *coeff);
    }

    /// Maximum degree (size of largest monomial).
    #[must_use]
    pub fn degree(&self) -> usize {
        self.terms.keys().map(BTreeSet::len).max().unwrap_or(0)
    }

    /// Number of nonzero terms.
    #[must_use]
    pub fn num_terms(&self) -> usize {
        self.terms.len()
    }

    /// Evaluate the polynomial at a given point (variable -> bool assignment).
    ///
    /// Variables not in the assignment are treated as 0.
    #[must_use]
    pub fn evaluate(&self, assignment: &HashMap<usize, bool>) -> bool {
        let mut result = false;
        for mono in self.terms.keys() {
            // A monomial evaluates to 1 iff all its variables are 1.
            let mono_val = mono
                .iter()
                .all(|v| assignment.get(v).copied().unwrap_or(false));
            // XOR into result.
            result ^= mono_val;
        }
        result
    }
}

/// Encode a CNF clause as a GF(2) polynomial.
///
/// Clause (l1 v l2 v ... v lk) is unsatisfied when all literals are false.
/// For positive literal xi (represented as positive i32), "false" means xi=0,
/// so the factor is (1 - xi). For negative literal !xi (represented as
/// negative i32), "false" means xi=1, so the factor is xi.
///
/// The clause polynomial is the product of these factors, and the clause
/// is encoded as: polynomial = 0.
///
/// DIMACS convention: variable indices are 1-based positive integers.
/// We map DIMACS variable |lit| to polynomial variable (|lit| - 1).
#[must_use]
pub fn clause_to_polynomial(clause: &[i32]) -> GF2Polynomial {
    let mut result = GF2Polynomial::one();
    for &lit in clause {
        let var_idx = (lit.abs() - 1) as usize;
        let factor = if lit > 0 {
            // Positive literal: factor is (1 - x) = 1 + x in GF(2).
            GF2Polynomial::one().add(&GF2Polynomial::var(var_idx))
        } else {
            // Negative literal: factor is x.
            GF2Polynomial::var(var_idx)
        };
        result = result.mul(&factor);
    }
    result
}

/// A step in a Polynomial Calculus proof over GF(2).
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum PCStep {
    /// Introduce an axiom polynomial (index into the axiom list).
    Axiom(usize),
    /// Add two previously derived polynomials (by proof-line index).
    Add(usize, usize),
    /// Multiply a previously derived polynomial by a variable.
    Multiply(usize, usize),
    /// Weaken: add a monomial to a previously derived polynomial.
    /// The monomial is specified as a set of variable indices.
    Weaken(usize, Vec<usize>),
}

/// S44: Verify a Polynomial Calculus proof over GF(2).
///
/// Axioms are the clause polynomials. Each proof step derives a new
/// polynomial. The proof is valid if:
///   1. Each step correctly applies its rule.
///   2. The final derived polynomial is the constant 1 (contradiction).
///
/// Returns `true` if the proof is a valid refutation.
#[must_use]
pub fn verify_pc_proof(axioms: &[GF2Polynomial], steps: &[PCStep]) -> bool {
    let mut derived: Vec<GF2Polynomial> = Vec::new();

    for step in steps {
        let poly = match step {
            PCStep::Axiom(idx) => {
                if *idx >= axioms.len() {
                    return false;
                }
                axioms[*idx].clone()
            }
            PCStep::Add(idx1, idx2) => {
                if *idx1 >= derived.len() || *idx2 >= derived.len() {
                    return false;
                }
                derived[*idx1].add(&derived[*idx2])
            }
            PCStep::Multiply(idx, var) => {
                if *idx >= derived.len() {
                    return false;
                }
                derived[*idx].mul_var(*var)
            }
            PCStep::Weaken(idx, mono_vars) => {
                if *idx >= derived.len() {
                    return false;
                }
                let mono = GF2Polynomial::monomial(mono_vars);
                derived[*idx].add(&mono)
            }
        };
        derived.push(poly);
    }

    // Proof succeeds if the final derived polynomial is the constant 1.
    derived.last().is_some_and(GF2Polynomial::is_one)
}

/// Compute the maximum degree across all polynomials in a proof trace.
#[must_use]
pub fn proof_degree(axioms: &[GF2Polynomial], steps: &[PCStep]) -> usize {
    let mut derived: Vec<GF2Polynomial> = Vec::new();
    let mut max_deg = axioms.iter().map(GF2Polynomial::degree).max().unwrap_or(0);

    for step in steps {
        let poly = match step {
            PCStep::Axiom(idx) => {
                if *idx >= axioms.len() {
                    return max_deg;
                }
                axioms[*idx].clone()
            }
            PCStep::Add(idx1, idx2) => {
                if *idx1 >= derived.len() || *idx2 >= derived.len() {
                    return max_deg;
                }
                derived[*idx1].add(&derived[*idx2])
            }
            PCStep::Multiply(idx, var) => {
                if *idx >= derived.len() {
                    return max_deg;
                }
                derived[*idx].mul_var(*var)
            }
            PCStep::Weaken(idx, mono_vars) => {
                if *idx >= derived.len() {
                    return max_deg;
                }
                let mono = GF2Polynomial::monomial(mono_vars);
                derived[*idx].add(&mono)
            }
        };
        let d = poly.degree();
        if d > max_deg {
            max_deg = d;
        }
        derived.push(poly);
    }

    max_deg
}

/// Maximum monomial degree of a polynomial (number of variables in
/// the largest term). Free-function wrapper around [`GF2Polynomial::degree`].
#[must_use]
pub fn polynomial_degree(poly: &GF2Polynomial) -> usize {
    poly.degree()
}

/// Evaluate a polynomial at a given 0/1 assignment provided as a slice.
///
/// `assignment[i]` gives the Boolean value for polynomial variable `i`.
/// Variables with indices beyond the slice length are treated as `false`.
#[must_use]
pub fn evaluate_polynomial(poly: &GF2Polynomial, assignment: &[bool]) -> bool {
    let mut result = false;
    for mono in poly.terms.keys() {
        let mono_val = mono
            .iter()
            .all(|&v| assignment.get(v).copied().unwrap_or(false));
        result ^= mono_val;
    }
    result
}

/// Attempt to convert a GF(2) polynomial back to a DIMACS clause.
///
/// A polynomial represents a clause iff it is a product of linear
/// factors of the form `(1 - xi)` (positive literal) or `xi` (negative
/// literal). Not all polynomials have this shape; this function returns
/// `None` for polynomials that do not correspond to any single clause.
///
/// The conversion works by checking if the polynomial can be expressed
/// as a product of single-variable linear factors. For each variable
/// `i` appearing in the polynomial, we determine its polarity and
/// verify the product matches.
#[must_use]
pub fn polynomial_to_clause(poly: &GF2Polynomial) -> Option<Vec<i32>> {
    if poly.is_zero() {
        return Some(vec![]);
    }

    // Collect all variables appearing in any monomial.
    let mut all_vars: BTreeSet<usize> = BTreeSet::new();
    for mono in poly.terms.keys() {
        for &v in mono {
            all_vars.insert(v);
        }
    }

    if all_vars.is_empty() {
        // Constant polynomial 1 -- not a clause (empty clause would be 0).
        return None;
    }

    // Try all 2^k polarity assignments for k variables (k is small for
    // clauses). For each variable, polarity is either positive (factor
    // = 1+x, literal = +var) or negative (factor = x, literal = -var).
    let vars: Vec<usize> = all_vars.iter().copied().collect();
    let k = vars.len();

    // For clauses with many variables this is exponential, but clauses
    // in practice are small. Cap at 20 variables to avoid blowup.
    if k > 20 {
        return None;
    }

    for mask in 0u32..(1u32 << k) {
        let mut candidate_clause: Vec<i32> = Vec::with_capacity(k);
        for (bit_pos, &var_idx) in vars.iter().enumerate() {
            let dimacs_var = (var_idx + 1) as i32;
            if mask & (1 << bit_pos) != 0 {
                // Positive literal: factor = (1 - x) = (1 + x) in GF(2).
                candidate_clause.push(dimacs_var);
            } else {
                // Negative literal: factor = x.
                candidate_clause.push(-dimacs_var);
            }
        }
        let candidate_poly = clause_to_polynomial(&candidate_clause);
        if candidate_poly == *poly {
            // Sort by absolute value for canonical form.
            candidate_clause.sort_by_key(|lit| lit.abs());
            return Some(candidate_clause);
        }
    }

    None
}
