// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

use super::*;
use crate::test_utils::{build_spec_with_stack, run_with_stack};
use clean_kernel::{Environment, Expr, Level, Name, Reducibility};
use std::collections::{HashMap, HashSet};

#[test]
fn test_specification_creation() {
    let spec = build_spec_with_stack();
    assert!(spec.definitions().contains_key("Eq"));
    assert!(spec.definitions().contains_key("has_type"));
    assert!(spec.definitions().contains_key("TypePreservation"));
    assert!(spec.definitions().contains_key("tc_check_type_rule"));
    assert!(spec.definitions().contains_key("tc_infer_type_rule"));
    assert!(spec.definitions().contains_key("tc_is_def_eq_rule"));
    assert!(spec.definitions().contains_key("tc_infer_soundness"));
    assert!(spec.definitions().contains_key("tc_check_completeness"));
    assert!(spec.definitions().contains_key("tc_def_eq_transitivity"));
    assert!(spec.definitions().contains_key("tc_subject_reduction"));
}

#[test]
fn test_spec_expr_elaborate() {
    let env = Environment::new();
    let mut expr = SpecExpr::new("Type -> Type");
    expr.elaborate(&env)
        .expect("elaborating 'Type -> Type' should succeed");
}

#[test]
fn test_spec_level_parse() {
    let mut level = SpecLevel::new("0");
    level.parse().expect("parsing level '0' should succeed");
    assert_eq!(*level.parse().unwrap(), Level::Zero);
}

#[test]
fn test_core_definitions_exist() {
    let spec = build_spec_with_stack();

    // Core equality (inductive generates Eq.rec eliminator).
    assert!(spec.definitions().contains_key("Eq"));
    assert!(spec.definitions().contains_key("Eq.refl"));
    assert!(
        spec.definitions().contains_key("Eq.rec"),
        "Eq.rec should be auto-generated by add_inductive"
    );
    assert!(spec.definitions().contains_key("Eq.symm"));
    assert!(spec.definitions().contains_key("Eq.trans"));
    assert!(spec.definitions().contains_key("Eq.cong"));
    assert!(spec.definitions().contains_key("Eq.subst"));
    assert!(spec.definitions().contains_key("def_eq_eq_left"));
    assert!(spec.definitions().contains_key("def_eq_eq_right"));
}

#[test]
fn checked_eq_cong_keeps_domain_and_codomain_universes_distinct() {
    run_with_stack(|| {
        let mut spec = Specification {
            env: Environment::new(),
            definitions: HashMap::new(),
        };
        spec.add_inductive(
            r"inductive Eq (α : Sort u) : α → α → Prop
| refl : forall (a : α), Eq α a a",
            "Parameterized equality",
        )
        .expect("Eq should register");

        let type_src = "forall (α : Sort u) (β : Sort v) (f : α -> β) (a : α) (b : α), Eq α a b -> Eq β (f a) (f b)";
        let value_src =
            "fun (α : Sort u) (β : Sort v) (f : α -> β) (a : α) (b : α) (h : Eq α a b) => \
             Eq.rec α a (fun (x : α) (_h : Eq α a x) => Eq β (f a) (f x)) \
             (Eq.refl β (f a)) b h";
        spec.add_definition_checked(SpecDefinition {
            name: "Eq.cong".to_string(),
            type_src: type_src.to_string(),
            value_src: Some(value_src.to_string()),
            is_axiom: false,
            description: "Mixed-universe congruence regression".to_string(),
            category: AxiomCategory::DerivedLemma,
            proof_status: ProofStatus::DerivedProved,
            elaborated_type: None,
            elaborated_value: None,
            dependencies: Some(HashSet::from([
                "Eq".to_string(),
                "Eq.rec".to_string(),
                "Eq.refl".to_string(),
            ])),
            axiom_deps: HashSet::new(),
        })
        .expect("checked Eq.cong must preserve independent u/v universes");

        let info = spec
            .env()
            .get_const(&Name::from_string("Eq.cong"))
            .expect("Eq.cong should be registered");
        assert_eq!(
            info.level_params.len(),
            2,
            "Eq.cong must retain independent domain/codomain universes"
        );
        assert_ne!(info.level_params[0], info.level_params[1]);
    });
}

#[test]
fn test_type_preservation_definitions_exist() {
    let spec = build_spec_with_stack();

    // Typing definitions.
    assert!(spec.definitions().contains_key("Typing"));
    assert!(spec.definitions().contains_key("Typing.sort"));
    assert!(spec.definitions().contains_key("Typing.pi"));
    assert!(spec.definitions().contains_key("Typing.lam"));
    assert!(spec.definitions().contains_key("Typing.app"));
    assert!(spec.definitions().contains_key("Typing.conv"));
    assert!(spec.definitions().contains_key("Typing.rec"));

    // DefEq definitions.
    assert!(spec.definitions().contains_key("DefEq"));
    assert!(spec.definitions().contains_key("DefEq.refl"));
    assert!(spec.definitions().contains_key("DefEq.symm"));
    assert!(spec.definitions().contains_key("DefEq.trans"));
    assert!(spec.definitions().contains_key("DefEq.beta"));
    assert!(spec.definitions().contains_key("DefEq.rec"));

    // Type preservation.
    assert!(spec.definitions().contains_key("TypePreservation"));
}

#[test]
fn test_type_aliases_register_as_semireducible_definitions() {
    let spec = build_spec_with_stack();

    for name in ["is_def_eq", "has_type"] {
        let info = spec
            .env()
            .get_const(&Name::from_string(name))
            .unwrap_or_else(|| panic!("{name} should be registered in the environment"));

        assert!(
            matches!(info.reducibility, Reducibility::Regular(_)),
            "{name} should be semireducible/Regular, got {:?}",
            info.reducibility
        );
        assert!(
            !info.is_reducible,
            "{name} should not be marked fully reducible"
        );
    }
}

#[test]
fn test_axiom_category_stats() {
    let spec = build_spec_with_stack();
    let (foundational, derived, helper) = spec.axiom_category_stats();
    assert!(foundational > 0, "Expected some foundational rules");
    assert!(derived > 0, "Expected some derived lemmas");
    // Census-11 drain (Stage 2B-iii): tc_infer_soundness — the LAST
    // HelperAxiom — is now a DerivedProved DerivedLemma, so the HelperAxiom
    // category is EMPTY and must stay empty (a new HelperAxiom would be a
    // silent trust regression past the 3-axiom finish line).
    assert_eq!(
        helper, 0,
        "Expected ZERO helper axioms after the census-11 drain (tc_infer_soundness \
         was the last); a new HelperAxiom is a trust regression"
    );
}

/// Regression test for #821: Eq inductive registration causes NotAFunction errors.
///
/// Part of #821: This is an **isolation test** to diagnose whether the bug is
/// in `env.add_inductive` registration vs spec definition sequencing.
///
/// Test procedure:
/// 1. Builds a fresh Specification (without core_spec)
/// 2. Adds Nat and Nat.zero first (prerequisites)
/// 3. Adds Eq as a parameterized inductive
/// 4. Attempts to elaborate `Eq Nat Nat.zero Nat.zero`
///
/// **Diagnostic interpretation:**
/// - If FAILS with NotAFunction: issue is in add_inductive registration
/// - If PASSES (current): issue is in definition ordering/sequencing in core_spec
///
/// This test PASSES, confirming the #821 bug is NOT in add_inductive itself
/// but rather in how core_spec sequences its ~160 definitions.
#[test]
fn test_eq_inductive_registration_821() {
    run_with_stack(|| {
        // Create empty spec without core_spec (to isolate Eq registration).
        let mut spec = Specification {
            env: Environment::new(),
            definitions: HashMap::new(),
        };

        // Add Nat first (prerequisite for Eq test expression).
        spec.add_inductive(
            r"inductive Nat : Type
| zero : Nat
| succ (n : Nat) : Nat",
            "Natural numbers",
        )
        .expect("Nat inductive should succeed");

        // Verify Nat and Nat.zero are in the environment.
        assert!(
            spec.definitions().contains_key("Nat"),
            "Nat should be registered"
        );
        assert!(
            spec.definitions().contains_key("Nat.zero"),
            "Nat.zero should be registered"
        );

        // Add Eq as parameterized inductive (the actual test).
        // Constructor type must use forall syntax (parser doesn't handle binders before :).
        let eq_result = spec.add_inductive(
            r"inductive Eq (A : Type) : A → A → Type
| refl : forall (a : A), Eq A a a",
            "Parameterized equality type for #821 regression",
        );

        // First check: does add_inductive succeed?
        assert!(
            eq_result.is_ok(),
            "Eq parameterized inductive should register: {:?}",
            eq_result.err()
        );

        // Verify Eq is registered.
        assert!(
            spec.definitions().contains_key("Eq"),
            "Eq should be registered after add_inductive"
        );
        assert!(
            spec.definitions().contains_key("Eq.refl"),
            "Eq.refl constructor should be registered"
        );

        // Second check: can we elaborate an expression using Eq?
        // This is where #821 fails with NotAFunction(Const(Eq, [])).
        let mut test_expr = SpecExpr::new("Eq Nat Nat.zero Nat.zero");
        let elab_result = test_expr.elaborate(spec.env());

        // This assertion documents the expected behavior.
        // If this fails with NotAFunction, that's the #821 bug.
        assert!(
            elab_result.is_ok(),
            "Eq Nat Nat.zero Nat.zero should elaborate without NotAFunction: {:?}",
            elab_result.err()
        );
    });
}

/// Extended regression test for #821: Eq inductive with Nat.add context.
///
/// Part of #821: This **isolation test** mirrors the `nat_add_zero` definition
/// context from core_spec to check if the issue is specific to that expression pattern.
///
/// This test PASSES, further confirming the #821 bug is environment-state-dependent
/// rather than being in the Nat.add + Eq combination itself.
#[test]
fn test_eq_inductive_with_nat_add_context_821() {
    run_with_stack(|| {
        let mut spec = Specification {
            env: Environment::new(),
            definitions: HashMap::new(),
        };

        // Add Nat inductive (arrow syntax; parser doesn't handle binder form).
        spec.add_inductive(
            r"inductive Nat : Type
| zero : Nat
| succ : Nat → Nat",
            "Natural numbers",
        )
        .expect("Nat inductive should succeed");

        // Add Nat.add recursive definition.
        spec.add_recursive_def(
            r"def Nat.add (m n : Nat) : Nat := match m with
| Nat.zero => n
| Nat.succ m' => Nat.succ (Nat.add m' n)",
            "Natural number addition",
        )
        .expect("Nat.add should succeed");

        // Add Eq as parameterized inductive.
        // Constructor type must use forall syntax (parser doesn't handle binders before :).
        spec.add_inductive(
            r"inductive Eq (A : Type) : A → A → Type
| refl : forall (a : A), Eq A a a",
            "Parameterized equality type",
        )
        .expect("Eq parameterized inductive should succeed");

        // Verify Eq.refl has correct type in environment.
        let eq_refl_name = Name::from_string("Eq.refl");
        if let Some(ctor) = spec.env().get_constructor(&eq_refl_name) {
            // Eq.refl should have type: (A : Type) → (a : A) → Eq A a a.
            let ty_str = format!("{:?}", ctor.type_);
            assert!(
                ty_str.contains("Pi"),
                "Eq.refl should be a Pi type, got: {}",
                ty_str
            );
        }

        // Test the nat_add_zero type expression.
        // This is where #821 originally failed.
        let mut test_expr = SpecExpr::new("forall (n : Nat), Eq Nat (Nat.add n Nat.zero) n");
        let elab_result = test_expr.elaborate(spec.env());

        assert!(
            elab_result.is_ok(),
            "nat_add_zero type should elaborate: {:?}",
            elab_result.err()
        );
    });
}

/// Test that shows the #821 issue is isolated: building spec context matters.
///
/// This test documents the finding: Eq inductive works in isolation (tests above pass),
/// but fails when added to an existing spec that has axiom Eq definitions.
/// The fix path is to convert Eq from axiom to inductive at the START of core_spec,
/// before any other definitions reference it.
///
/// Part of #821 investigation; documents isolation behavior for future fix attempts.
#[test]
fn test_eq_inductive_isolation_findings_821() {
    run_with_stack(|| {
        // Test 1: Fresh spec with Eq inductive FIRST; should work.
        {
            let mut spec = Specification {
                env: Environment::new(),
                definitions: HashMap::new(),
            };

            // Add Eq inductive FIRST (before Nat or anything else).
            // Constructor type must use forall syntax (parser doesn't handle binders before :).
            spec.add_inductive(
                r"inductive Eq (A : Type) : A → A → Type
| refl : forall (a : A), Eq A a a",
                "Eq inductive first",
            )
            .expect("Eq inductive first should work");

            // Then add Nat.
            spec.add_inductive(
                r"inductive Nat : Type
| zero : Nat
| succ : forall (n : Nat), Nat",
                "Nat after Eq",
            )
            .expect("Nat after Eq should work");

            // Elaborating Eq expression should work.
            let mut test_expr = SpecExpr::new("Eq Nat Nat.zero Nat.zero");
            assert!(
                test_expr.elaborate(spec.env()).is_ok(),
                "Eq expression should work when Eq is added first"
            );
        }

        // Test 2: Adding to existing spec with Eq; documents the conflict.
        // This shows that the issue might be about duplicate registration.
        {
            let spec = build_spec_with_stack();

            // The existing spec already has Eq as an axiom.
            // Trying to add another Eq inductive would conflict.
            // This is documented behavior, not a test failure.
            assert!(
                spec.definitions().contains_key("Eq"),
                "Existing spec should have Eq axiom"
            );

            // The fix for #821 is to change core_spec to use add_inductive
            // for Eq instead of add_definition with is_axiom: true.
        }
    });
}

/// Test for #821 fix: Full nat_add_zero value elaboration with Eq inductive.
#[test]
fn test_eq_inductive_nat_add_zero_value_821() {
    run_with_stack(|| {
        let mut spec = Specification {
            env: Environment::new(),
            definitions: HashMap::new(),
        };

        // Using "Type u" triggers auto-binding of universe param u.
        // Constructor type must use forall syntax, not binder syntax:
        // | refl : forall (a : A), Eq A a a  (CORRECT)
        // | refl (a : A) : Eq A a a          (parser doesn't handle binders before :)
        spec.add_inductive(
            r"inductive Eq (A : Type u) : A → A → Type
| refl : forall (a : A), Eq A a a",
            "Parameterized equality",
        )
        .expect("Eq inductive should succeed");

        spec.add_inductive(
            r"inductive Nat : Type
| zero : Nat
| succ : forall (n : Nat), Nat",
            "Natural numbers",
        )
        .expect("Nat inductive should succeed");

        spec.add_recursive_def(
            r"def Nat.add (m n : Nat) : Nat := match m with
| Nat.zero => n
| Nat.succ m' => Nat.succ (Nat.add m' n)",
            "Addition",
        )
        .expect("Nat.add should succeed");

        spec.add_definition(SpecDefinition {
            name: "Eq.cong".to_string(),
            type_src: "forall (A : Type) (B : Type) (f : A -> B) (x : A) (y : A), Eq A x y -> Eq B (f x) (f y)".to_string(),
            value_src: None,
            is_axiom: true,
            description: "Congruence".to_string(),
            category: AxiomCategory::HelperAxiom,
            proof_status: ProofStatus::default(),
            elaborated_type: None,
            elaborated_value: None,
            dependencies: None,
            axiom_deps: HashSet::new(),
        })
        .expect("Eq.cong axiom should succeed");

        // Verify universe params are now set (fix for #821).
        let eq_name = Name::from_string("Eq");
        let eq_info = spec.env().get_const(&eq_name).expect("Eq should exist");
        assert!(
            !eq_info.level_params.is_empty(),
            "Eq should have universe params (fix for #821): got {:?}",
            eq_info.level_params
        );

        // Also check Eq.refl has correct Pi structure.
        let eq_refl_name = Name::from_string("Eq.refl");
        let eq_refl_info = spec
            .env()
            .get_const(&eq_refl_name)
            .expect("Eq.refl should exist");

        fn count_pis(e: &Expr) -> usize {
            match e.kind() {
                clean_kernel::ExprKind::Pi(_, _, body) => 1 + count_pis(body),
                _ => 0,
            }
        }

        let pi_depth = count_pis(&eq_refl_info.type_);
        // Eq.refl : {A : Type u} -> (a : A) -> Eq A a a.
        assert!(
            pi_depth >= 2,
            "Eq.refl should have at least 2 Pi binders (got {})",
            pi_depth
        );

        // Type elaboration.
        let mut type_expr = SpecExpr::new("forall (n : Nat), Eq Nat (Nat.add n Nat.zero) n");
        assert!(
            type_expr.elaborate(spec.env()).is_ok(),
            "nat_add_zero type should elaborate"
        );

        // Value elaboration (THIS WAS FAILING with NotAFunction before fix).
        let nat_add_zero_value = concat!(
            "fun (n : Nat) => Nat.rec ",
            "(fun (k : Nat) => Eq Nat (Nat.add k Nat.zero) k) ",
            "(Eq.refl Nat Nat.zero) ",
            "(fun (p : Nat) (ih : Eq Nat (Nat.add p Nat.zero) p) => ",
            "Eq.cong Nat Nat Nat.succ (Nat.add p Nat.zero) p ih) ",
            "n"
        );
        let mut value_expr = SpecExpr::new(nat_add_zero_value);
        let value_result = value_expr.elaborate(spec.env());
        assert!(
            value_result.is_ok(),
            "nat_add_zero value should elaborate (fix for #821): {:?}",
            value_result.err()
        );
    });
}
