// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Differential testing baseline infrastructure.
//!
//! This module provides infrastructure for differential testing of clean's type
//! checker against Lean4's reference implementation. The baseline system:
//!
//! - Captures Lean4 type inference results for a set of test expressions
//! - Normalizes type strings for comparison (handling forall/arrow equivalence, whitespace)
//! - Caches results to JSON to allow testing without Lean4 installed
//!
//! # Usage
//!
//! Regenerate baseline: `REGEN_BASELINE=1 cargo test --test lean4_parity -- lean4_parity_check`
//!
//! Test expressions: `tests/differential/expressions.txt`
//! Integration test: `tests/lean4_parity.rs` (renamed from `differential.rs`)

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::NamedTempFile;

/// Relative path to the test expressions file from the crate manifest directory.
pub const EXPRESSIONS_PATH: &str = "../../tests/differential/expressions.txt";
/// Relative path to the cached Lean4 baseline JSON file.
pub const BASELINE_PATH: &str = "../../tests/differential/lean4_baseline.json";
/// Current schema version for baseline JSON files (for forward compatibility).
pub const BASELINE_SCHEMA_VERSION: u32 = 1;
/// Version of the type string normalization algorithm. Bump when `normalize_type_str` changes.
pub const NORMALIZATION_VERSION: u32 = 2;

/// Cached Lean4 baseline for differential testing.
/// Generated by running Lean4 once, then used for deterministic tests without Lean4.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lean4Baseline {
    /// Schema version for forward compatibility
    pub schema_version: u32,
    /// Unix timestamp when baseline was generated (format: `unix:SECONDS`)
    pub generated_at: String,
    /// Lean4 version string (from `lean --version`)
    pub lean4_version: String,
    /// SHA256 of expressions.txt for validation
    pub expressions_sha256: String,
    /// Normalization version - bump when normalize_type_str changes
    pub normalization_version: u32,
    /// Baseline cases: one per expression line
    pub cases: Vec<BaselineCase>,
}

/// A single test case in the differential baseline.
///
/// Each case stores an expression and its normalized type as inferred by Lean4.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaselineCase {
    /// Original expression from expressions.txt
    pub expr: String,
    /// Normalized type string from Lean4
    pub type_norm: String,
}

impl Lean4Baseline {
    /// Generate a new baseline by running Lean4 on all expressions.
    /// Requires Lean4 binary to be available.
    ///
    /// # Contract
    ///
    /// ENSURES: Ok(result) where result.cases.len() == expressions.len()
    /// ENSURES: Ok(result) where result.schema_version == BASELINE_SCHEMA_VERSION
    /// ENSURES: Ok(result) where result.normalization_version == NORMALIZATION_VERSION
    /// ENSURES: Err(_) if Lean4 binary not available in PATH or ~/.elan/bin
    pub fn generate(expressions: &[String]) -> Result<Self> {
        let lean4_version = get_lean4_version()?;
        let lean4_types = run_lean4(expressions)?;

        if lean4_types.len() != expressions.len() {
            return Err(anyhow!(
                "Lean4 produced {} results for {} expressions",
                lean4_types.len(),
                expressions.len()
            ));
        }

        let cases: Vec<BaselineCase> = expressions
            .iter()
            .zip(lean4_types.iter())
            .map(|(expr, ty)| BaselineCase {
                expr: expr.clone(),
                type_norm: ty.clone(),
            })
            .collect();

        let expressions_sha256 = compute_expressions_sha256(expressions);

        // Use std::time for timestamp to avoid adding chrono dependency
        let generated_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| format!("unix:{}", d.as_secs()))
            .unwrap_or_else(|_| "unknown".to_string());

        Ok(Self {
            schema_version: BASELINE_SCHEMA_VERSION,
            generated_at,
            lean4_version,
            expressions_sha256,
            normalization_version: NORMALIZATION_VERSION,
            cases,
        })
    }

    /// Load baseline from JSON file
    ///
    /// # Contract
    ///
    /// ENSURES: Ok(result) where result is deserialized Lean4Baseline on success
    /// ENSURES: Err(_) if file doesn't exist or isn't valid JSON
    pub fn load(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let baseline: Self =
            serde_json::from_str(&content).with_context(|| "failed to parse baseline JSON")?;
        Ok(baseline)
    }

    /// Save baseline to JSON file
    ///
    /// # Contract
    ///
    /// ENSURES: file at path contains pretty-printed JSON of self
    pub fn save(&self, path: &Path) -> Result<()> {
        let content = serde_json::to_string_pretty(self)?;
        fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))?;
        Ok(())
    }

    /// Validate that this baseline matches the current expressions file
    ///
    /// # Contract
    ///
    /// ENSURES: Ok(()) iff self.schema_version == BASELINE_SCHEMA_VERSION
    /// ENSURES: Ok(()) iff self.normalization_version == NORMALIZATION_VERSION
    /// ENSURES: Ok(()) iff self.expressions_sha256 == sha256(expressions)
    /// ENSURES: Ok(()) iff self.cases.len() == expressions.len()
    /// ENSURES: Err(_) with descriptive message if any check fails
    pub fn validate(&self, expressions: &[String]) -> Result<()> {
        if self.schema_version != BASELINE_SCHEMA_VERSION {
            return Err(anyhow!(
                "baseline schema version mismatch: {} != {} (expected). Regenerate with REGEN_BASELINE=1",
                self.schema_version,
                BASELINE_SCHEMA_VERSION
            ));
        }
        if self.normalization_version != NORMALIZATION_VERSION {
            return Err(anyhow!(
                "baseline normalization version mismatch: {} != {} (expected). Regenerate with REGEN_BASELINE=1",
                self.normalization_version,
                NORMALIZATION_VERSION
            ));
        }

        let current_sha = compute_expressions_sha256(expressions);
        if self.expressions_sha256 != current_sha {
            return Err(anyhow!(
                "expressions.txt has changed since baseline was generated.\n\
                 Baseline SHA: {}\n\
                 Current SHA:  {}\n\
                 Regenerate with REGEN_BASELINE=1",
                self.expressions_sha256,
                current_sha
            ));
        }

        if self.cases.len() != expressions.len() {
            return Err(anyhow!(
                "baseline has {} cases but expressions.txt has {} entries",
                self.cases.len(),
                expressions.len()
            ));
        }

        Ok(())
    }

    /// Get types as vector (same format as run_lean4 output)
    ///
    /// # Contract
    ///
    /// ENSURES: result.len() == self.cases.len()
    /// ENSURES: result\[i\] == self.cases\[i\].type_norm for all i
    pub fn get_types(&self) -> Vec<String> {
        self.cases.iter().map(|c| c.type_norm.clone()).collect()
    }
}

fn compute_expressions_sha256(expressions: &[String]) -> String {
    let mut hasher = Sha256::new();
    for expr in expressions {
        hasher.update(expr.as_bytes());
        hasher.update(b"\n");
    }
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn get_lean4_version() -> Result<String> {
    let lean = find_lean_binary().ok_or_else(|| {
        anyhow!("Lean4 binary not found in PATH or ~/.elan/bin. Install Lean4 to regenerate.")
    })?;
    let output = Command::new(lean)
        .arg("--version")
        .output()
        .context("failed to run `lean --version`")?;
    if !output.status.success() {
        return Err(anyhow!("lean --version failed"));
    }
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

/// Check if the lean (Lean 4) binary is available in PATH
fn lean_binary_available() -> bool {
    let Some(lean) = find_lean_binary() else {
        return false;
    };
    Command::new(lean)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn find_lean_binary() -> Option<PathBuf> {
    if let Some(path) = find_in_path("lean") {
        return Some(path);
    }
    let home = std::env::var_os("HOME")?;
    let fallback = PathBuf::from(home).join(".elan").join("bin").join("lean");
    if fallback.is_file() {
        return Some(fallback);
    }
    None
}

fn find_in_path(cmd: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join(cmd);
        if candidate.is_file() {
            return Some(candidate);
        }
        #[cfg(windows)]
        {
            let candidate = dir.join(format!("{cmd}.exe"));
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

/// Load Lean4 types either from cached baseline or by running Lean4.
///
/// Priority:
/// 1. If REGEN_BASELINE=1, regenerate baseline (requires Lean4)
/// 2. If baseline file exists and is valid, use it (no Lean4 needed)
/// 3. If Lean4 is available, generate baseline and run live
/// 4. Error if neither baseline nor Lean4 available (no silent skips per #438)
///
/// # Contract
///
/// REQUIRES: expressions.len() > 0 (undefined behavior if empty)
/// ENSURES: Ok(result) where result.len() == expressions.len()
/// ENSURES: Ok(result) where all types are normalized via normalize_type_str
/// ENSURES: Err(_) if neither baseline nor Lean4 available
pub fn load_lean4_types(expressions: &[String]) -> Result<Vec<String>> {
    let baseline_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(BASELINE_PATH);

    // Check if regeneration is requested
    if std::env::var("REGEN_BASELINE").is_ok() {
        if !lean_binary_available() {
            return Err(anyhow!(
                "REGEN_BASELINE=1 but Lean4 binary not found. Install Lean4 to regenerate."
            ));
        }
        eprintln!("Regenerating Lean4 baseline...");
        let baseline = Lean4Baseline::generate(expressions)?;
        baseline.save(&baseline_path)?;
        eprintln!(
            "Baseline saved to {} with {} cases",
            baseline_path.display(),
            baseline.cases.len()
        );
        return Ok(baseline.get_types());
    }

    // Try to load cached baseline
    if baseline_path.exists() {
        match Lean4Baseline::load(&baseline_path) {
            Ok(baseline) => {
                if let Err(e) = baseline.validate(expressions) {
                    eprintln!("Baseline validation failed: {e}");
                    // Fall through to try running Lean4
                } else {
                    eprintln!(
                        "Using cached baseline (generated: {}, lean4: {})",
                        baseline.generated_at, baseline.lean4_version
                    );
                    return Ok(baseline.get_types());
                }
            }
            Err(e) => {
                eprintln!("Failed to load baseline: {e}");
                // Fall through to try running Lean4
            }
        }
    }

    // Baseline not available or invalid - try running Lean4 live
    if lean_binary_available() {
        eprintln!("No valid baseline found. Running Lean4 live...");
        let baseline = Lean4Baseline::generate(expressions)?;
        // Save it for future runs
        if let Err(e) = baseline.save(&baseline_path) {
            eprintln!("Warning: could not save baseline: {e}");
        } else {
            eprintln!("Baseline saved for future runs.");
        }
        return Ok(baseline.get_types());
    }

    // No baseline and no Lean4 - fail the test (per #438: no silent skips)
    Err(anyhow!(
        "Differential test cannot run: no baseline at {} and Lean4 binary not in PATH.\n\
         \n\
         To fix, either:\n\
         1. Generate baseline: REGEN_BASELINE=1 cargo test differential_against_lean4\n\
         2. Install Lean4 and ensure `lean` is in PATH or ~/.elan/bin\n\
         3. Check in a baseline file to tests/differential/lean4_baseline.json",
        baseline_path.display()
    ))
}

/// Load test expressions from the expressions file.
///
/// Reads `expressions.txt` and returns all non-empty, non-comment lines.
/// Comments are lines starting with `#`.
///
/// # Contract
///
/// ENSURES: Ok(result) where result contains no empty strings
/// ENSURES: Ok(result) where result contains no comment lines (starting with '#')
/// ENSURES: Ok(result) where result.len() > 0
/// ENSURES: Err(_) if file doesn't exist or contains no valid expressions
pub fn load_expressions() -> Result<Vec<String>> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(EXPRESSIONS_PATH);
    let content = fs::read_to_string(&path)
        .with_context(|| format!("failed to read expressions file at {}", path.display()))?;
    let mut expressions = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        expressions.push(trimmed.to_string());
    }
    if expressions.is_empty() {
        return Err(anyhow!("no expressions loaded from {}", path.display()));
    }
    Ok(expressions)
}

fn run_lean4(expressions: &[String]) -> Result<Vec<String>> {
    let mut file = NamedTempFile::new().context("failed to create temp lean file")?;
    writeln!(file, "set_option linter.unusedVariables false")?;
    writeln!(file, "set_option pp.universes true")?;
    for expr in expressions {
        writeln!(file, "#check {expr}")?;
    }

    let lean = find_lean_binary().ok_or_else(|| {
        anyhow!("Lean4 binary not found in PATH or ~/.elan/bin. Install Lean4 to regenerate.")
    })?;
    let output = Command::new(lean)
        .arg(file.path())
        .output()
        .context("failed to spawn lean (Lean 4)")?;
    if !output.status.success() {
        return Err(anyhow!(
            "lean exited with {}: {}\nstdout:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
            String::from_utf8_lossy(&output.stdout)
        ));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut results = Vec::new();
    for line in stdout.lines() {
        // Find the separator " : " where preceding parens are balanced
        // This handles `(A : Type) → A : Type 1` correctly
        let type_part = extract_type_from_check_output(line);
        let normalized = normalize_type_str(type_part.trim());
        if !normalized.is_empty() {
            results.push(normalized);
        }
    }
    Ok(results)
}

/// Extract the type part from Lean's `#check` output.
/// Output format: `expr : type`, but expr can contain ` : ` in binder annotations.
/// We find ` : ` where the preceding text has balanced parentheses.
fn extract_type_from_check_output(line: &str) -> &str {
    let bytes = line.as_bytes();
    let separator = b" : ";
    let mut paren_depth: i32 = 0;
    let mut i = 0;

    while i + 3 <= bytes.len() {
        match bytes[i] {
            b'(' => paren_depth += 1,
            b')' => paren_depth = paren_depth.saturating_sub(1),
            b' ' if paren_depth == 0 && &bytes[i..i + 3] == separator => {
                return &line[i + 3..];
            }
            _ => {}
        }
        i += 1;
    }

    // Fallback: return entire line
    line
}

/// Normalize a type string for comparison between Lean4 and clean.
///
/// This handles:
/// - Unicode replacement (`→` to `->`, `∀` to `forall`)
/// - Whitespace normalization
/// - Forall/arrow equivalence (`forall (x : T),` to `(x : T) ->`)
/// - Combined binder expansion (`forall (a b : T),` to separate binders)
///
/// # Contract
///
/// ENSURES: result contains no '→' or '∀' unicode characters
/// ENSURES: result is lowercase
/// ENSURES: result has normalized whitespace (single spaces)
/// ENSURES: binder names are canonicalized to v0, v1, v2, ...
pub fn normalize_type_str(s: &str) -> String {
    // Replace unicode symbols but PRESERVE CASE for now (needed for correct canonicalization)
    let mut result = s.replace('→', "->").replace('∀', "forall");

    // Ensure arrows are tokenized with surrounding whitespace.
    result = result.replace("->", " -> ");

    // Collapse whitespace first
    result = result.split_whitespace().collect::<Vec<_>>().join(" ");

    // First: expand combined forall binders "forall (a b : T)," -> "forall (a : T), forall (b : T),"
    result = expand_forall_combined_binders(&result);

    // Handle sequences of forall binders: "forall (a : T) (b : U)," -> "forall (a : T), forall (b : U),"
    result = expand_forall_binder_sequences(&result);

    // Then: normalize "forall (x : T)," to "(x : T) ->" for consistent format
    // Limit iterations to prevent infinite loop on malformed input (defensive)
    const MAX_FORALL_ITERATIONS: usize = 1000;
    for _ in 0..MAX_FORALL_ITERATIONS {
        if let Some(start) = result.find("forall (") {
            let after_forall = &result[start + 8..]; // skip "forall ("
            if let Some(end) = find_balanced_paren_comma_inner(after_forall) {
                let binder_content = &after_forall[..end];
                let rest = after_forall[end + 2..].trim_start();
                let replacement = format!("({binder_content}) -> {rest}");
                result = format!("{}{}", &result[..start], replacement);
                continue;
            }
        }
        break;
    }

    // Then: expand remaining combined binders outside forall context
    result = expand_combined_binders(&result);

    // Final whitespace normalization
    result = result.split_whitespace().collect::<Vec<_>>().join(" ");

    // Strip unused binder names: "(v0 : T) -> body" becomes "T -> body" if v0 isn't used
    result = strip_unused_binders(&result);

    // Canonicalize variable names to make comparison order-independent
    // This MUST happen before lowercasing to avoid collisions like A/a -> same name
    result = canonicalize_binder_names(&result);

    // Finally lowercase everything for case-insensitive comparison
    result.to_lowercase()
}

/// Strip binder names when the bound variable is unused in the body.
/// Transforms "(x : T) -> body" to "T -> body" when x doesn't appear in body.
fn strip_unused_binders(s: &str) -> String {
    let mut result = s.to_string();

    // Iterate until no more changes (handles nested binders)
    // Limit iterations to prevent infinite loop on malformed input (defensive)
    const MAX_STRIP_ITERATIONS: usize = 1000;
    for _ in 0..MAX_STRIP_ITERATIONS {
        if let Some(new_result) = strip_one_unused_binder(&result) {
            result = new_result;
        } else {
            break;
        }
    }
    result
}

/// Try to strip one unused binder. Returns Some(new_string) if successful.
fn strip_one_unused_binder(s: &str) -> Option<String> {
    // Find pattern "(name : type) -> body"
    let chars: Vec<char> = s.chars().collect();
    let mut i = 0;

    while i < chars.len() {
        if chars[i] == '(' {
            // Try to parse a binder "(name : type)"
            let start = i;
            i += 1;

            // Skip whitespace
            while i < chars.len() && chars[i].is_whitespace() {
                i += 1;
            }

            // Collect name
            let name_start = i;
            while i < chars.len()
                && (chars[i].is_alphanumeric() || chars[i] == '_')
                && chars[i] != ' '
            {
                i += 1;
            }
            let name: String = chars[name_start..i].iter().collect();

            // Skip whitespace
            while i < chars.len() && chars[i].is_whitespace() {
                i += 1;
            }

            // Check for ":"
            if i >= chars.len() || chars[i] != ':' {
                continue;
            }
            i += 1;

            // Skip whitespace after colon
            while i < chars.len() && chars[i].is_whitespace() {
                i += 1;
            }

            // Collect type (balanced parens until ")")
            let type_start = i;
            let mut depth = 1;
            while i < chars.len() && depth > 0 {
                if chars[i] == '(' {
                    depth += 1;
                } else if chars[i] == ')' {
                    depth -= 1;
                }
                if depth > 0 {
                    i += 1;
                }
            }
            if depth != 0 {
                continue;
            }
            let type_str: String = chars[type_start..i].iter().collect();
            let type_str = type_str.trim();

            // Skip the closing ")"
            i += 1;

            // Skip whitespace
            while i < chars.len() && chars[i].is_whitespace() {
                i += 1;
            }

            // Check for "->" with optional surrounding whitespace
            if i + 2 > chars.len() || chars[i] != '-' || chars[i + 1] != '>' {
                continue;
            }
            let mut arrow_end = i + 2;
            while arrow_end < chars.len() && chars[arrow_end].is_whitespace() {
                arrow_end += 1;
            }

            // Get the body after the arrow
            let body: String = chars[arrow_end..].iter().collect();

            // Check if name appears in body as a word boundary
            if name.is_empty() || name == "_" {
                // Anonymous binder, always strip
            } else if body_uses_variable(&body, &name) {
                // Variable is used, don't strip
                continue;
            }

            // Strip: replace "(name : type) -> body" with "type -> body"
            let before: String = chars[..start].iter().collect();
            return Some(format!("{before}{type_str} -> {body}"));
        }
        i += 1;
    }

    None
}

/// Check if a variable name appears in the body as a word (not part of another word).
fn body_uses_variable(body: &str, var_name: &str) -> bool {
    let chars: Vec<char> = body.chars().collect();
    let var_chars: Vec<char> = var_name.chars().collect();
    let var_len = var_chars.len();

    let mut i = 0;
    while i + var_len <= chars.len() {
        // Check if we're at the start of a word
        let at_word_start = i == 0 || !chars[i - 1].is_alphanumeric() && chars[i - 1] != '_';

        if at_word_start {
            // Check if the variable name matches
            let matches = (0..var_len).all(|j| chars[i + j] == var_chars[j]);

            if matches {
                // Check if we're at the end of a word
                let at_word_end = i + var_len >= chars.len()
                    || (!chars[i + var_len].is_alphanumeric() && chars[i + var_len] != '_');

                if at_word_end {
                    return true;
                }
            }
        }
        i += 1;
    }
    false
}

/// Expand "forall (a : T) (b : U)," -> "forall (a : T), forall (b : U),"
fn expand_forall_binder_sequences(s: &str) -> String {
    let mut result = s.to_string();

    loop {
        // Find "forall (binder1) (binder2)" pattern
        if let Some(start) = result.find("forall (") {
            let after_forall = &result[start + 7..];
            // Collect all consecutive (binder) groups until we hit ","
            let mut binders = Vec::new();
            let mut pos = 0;
            let bytes = after_forall.as_bytes();

            while pos < bytes.len() {
                // Skip whitespace
                while pos < bytes.len() && bytes[pos].is_ascii_whitespace() {
                    pos += 1;
                }

                if pos >= bytes.len() {
                    break;
                }

                if bytes[pos] == b'(' {
                    // Find matching close paren
                    let binder_start = pos;
                    let mut depth = 0;
                    while pos < bytes.len() {
                        if bytes[pos] == b'(' {
                            depth += 1;
                        } else if bytes[pos] == b')' {
                            depth -= 1;
                            if depth == 0 {
                                pos += 1;
                                break;
                            }
                        }
                        pos += 1;
                    }
                    let binder = &after_forall[binder_start..pos];
                    binders.push(binder.to_string());
                } else if bytes[pos] == b',' {
                    // End of binder sequence
                    pos += 1;
                    break;
                } else {
                    // Something else (like body starting), stop
                    break;
                }
            }

            // If we found multiple binders, expand them
            if binders.len() > 1 {
                let expanded: Vec<String> =
                    binders.iter().map(|b| format!("forall {b},")).collect();
                let replacement = expanded.join(" ");
                let rest = &after_forall[pos..].trim_start();
                result = format!("{}{} {}", &result[..start], replacement, rest);
                continue;
            }
        }
        break;
    }

    result
}

/// Expand "forall (a b c : T)," to "forall (a : T), forall (b : T), forall (c : T),"
fn expand_forall_combined_binders(s: &str) -> String {
    let mut result = s.to_string();

    loop {
        if let Some(start) = result.find("forall (") {
            let after_forall = &result[start + 8..]; // skip "forall ("
            if let Some(close) = after_forall.find("),") {
                let content = &after_forall[..close];
                // Check if it has " : " and multiple words before colon
                if let Some(colon_pos) = content.find(" : ") {
                    let before_colon = &content[..colon_pos];
                    let after_colon = &content[colon_pos + 3..];
                    let names: Vec<&str> = before_colon.split_whitespace().collect();
                    if names.len() > 1 {
                        // Expand "forall (a b : T)," -> "forall (a : T), forall (b : T),"
                        let expanded: Vec<String> = names
                            .iter()
                            .map(|n| format!("forall ({n} : {after_colon}),"))
                            .collect();
                        let replacement = expanded.join(" ");
                        let rest = &after_forall[close + 2..];
                        result = format!("{}{} {}", &result[..start], replacement, rest);
                        continue;
                    }
                }
            }
        }
        break;
    }

    result
}

/// Canonicalize binder names to v0, v1, v2, ... for consistent comparison
fn canonicalize_binder_names(s: &str) -> String {
    use std::collections::HashMap;

    let mut result = String::new();
    let mut name_map: HashMap<String, String> = HashMap::new();
    let mut counter = 0;

    // Reserved keywords that shouldn't be renamed
    let reserved: std::collections::HashSet<&str> = ["type", "prop", "sort", "forall", "fun"]
        .iter()
        .copied()
        .collect();

    let chars: Vec<char> = s.chars().collect();
    let mut i = 0;

    while i < chars.len() {
        // Check for binder pattern "(<name> :"
        if chars[i] == '(' {
            result.push('(');
            i += 1;

            // Skip whitespace
            while i < chars.len() && chars[i].is_whitespace() {
                result.push(chars[i]);
                i += 1;
            }

            // If next char is '(', this is nested parens - don't try to parse as binder
            if i < chars.len() && chars[i] == '(' {
                // Don't consume the '(' - let the main loop handle it
                continue;
            }

            // Collect the potential binder name (until ' ' or ':' or '-' or ')' or '(')
            let name_start = i;
            while i < chars.len()
                && chars[i] != ' '
                && chars[i] != ':'
                && chars[i] != '-'
                && chars[i] != ')'
                && chars[i] != '('
            {
                i += 1;
            }
            let name: String = chars[name_start..i].iter().collect();

            // Check if this is a binder (followed by " :")
            let rest: String = chars[i..].iter().collect();
            if rest.starts_with(" :") && !name.is_empty() && !reserved.contains(name.as_str()) {
                // This is a binder - ALWAYS give it a fresh canonical name
                // (even if a variable with the same name was seen before, because this shadows it)
                let canonical = format!("v{counter}");
                counter += 1;
                name_map.insert(name.clone(), canonical.clone());
                result.push_str(&canonical);
            } else if !name.is_empty() && !reserved.contains(name.as_str()) {
                // This might be a variable reference inside parens (like in "(b -> c)")
                if let Some(canonical) = name_map.get(&name) {
                    result.push_str(canonical);
                } else {
                    result.push_str(&name);
                }
            } else {
                // Reserved word or empty, output as-is
                result.push_str(&name);
            }
            continue;
        }

        // Check for variable reference (a word not in a binder position)
        if chars[i].is_alphabetic() || chars[i] == '_' {
            let name_start = i;
            while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let name: String = chars[name_start..i].iter().collect();

            // If this name was bound, replace it with canonical name (unless reserved)
            if reserved.contains(name.as_str()) {
                result.push_str(&name);
            } else if let Some(canonical) = name_map.get(&name) {
                result.push_str(canonical);
            } else {
                result.push_str(&name);
            }
            continue;
        }

        result.push(chars[i]);
        i += 1;
    }

    result
}

/// Expand combined binders "(a b c : T)" to "(a : T) -> (b : T) -> (c : T)"
fn expand_combined_binders(s: &str) -> String {
    let mut result = s.to_string();
    let mut search_from = 0;

    loop {
        // Find "(names : Type)" pattern where names contains spaces (multiple binders)
        let search_slice = &result[search_from..];
        if let Some(rel_start) = search_slice.find('(') {
            let start = search_from + rel_start;
            let rest = &result[start + 1..];
            if let Some(close) = rest.find(')') {
                let content = &rest[..close];
                // Check if it has " : " and multiple words before colon
                if let Some(colon_pos) = content.find(" : ") {
                    let before_colon = &content[..colon_pos];
                    let after_colon = &content[colon_pos + 3..];
                    let names: Vec<&str> = before_colon.split_whitespace().collect();
                    if names.len() > 1 {
                        // Expand "(a b : T)" -> "(a : T) -> (b : T)"
                        let expanded: Vec<String> = names
                            .iter()
                            .map(|n| format!("({n} : {after_colon})"))
                            .collect();
                        let replacement = expanded.join(" -> ");
                        let new_result = format!(
                            "{}{}{}",
                            &result[..start],
                            replacement,
                            &result[start + 1 + close + 1..]
                        );
                        // Continue searching from after the replacement
                        search_from = start + replacement.len();
                        result = new_result;
                        continue;
                    }
                }
                // No expansion needed, move past this paren
                search_from = start + 1;
                continue;
            }
        }
        break;
    }

    result
}

/// Find the position of ")," after we're already inside the opening paren
/// Called when starting AFTER "forall ("
fn find_balanced_paren_comma_inner(s: &str) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut depth = 1; // We're already inside one paren
    for (i, &b) in bytes.iter().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    // Check if followed by ","
                    if bytes.get(i + 1) == Some(&b',') {
                        return Some(i);
                    }
                    return None;
                }
            }
            _ => {}
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // normalize_type_str tests (#1357)
    // ========================================================================

    #[test]
    fn test_normalize_identity() {
        // Simple types should round-trip cleanly
        assert_eq!(normalize_type_str("Nat"), "nat");
        assert_eq!(normalize_type_str("Prop"), "prop");
    }

    #[test]
    fn test_normalize_unicode_arrow() {
        // Unicode → should become ->
        let result = normalize_type_str("Nat → Bool");
        assert!(result.contains("->"), "Should convert → to ->: {result}");
    }

    #[test]
    fn test_normalize_unicode_forall() {
        // ∀ should become forall and then be expanded
        let result = normalize_type_str("∀ (x : Nat), Bool");
        // After normalization: (x : nat) -> bool, then strip unused binder: nat -> bool
        assert!(result.contains("->"), "Should contain arrow: {result}");
    }

    #[test]
    fn test_normalize_whitespace_collapse() {
        // Multiple spaces should collapse to single space
        let result = normalize_type_str("Nat   ->   Bool");
        assert_eq!(result, normalize_type_str("Nat -> Bool"));
    }

    #[test]
    fn test_normalize_forall_to_arrow() {
        // "forall (x : T)," should become "(x : T) ->"
        let result = normalize_type_str("forall (x : Nat), Bool");
        assert!(
            !result.contains("forall"),
            "forall should be eliminated: {result}"
        );
        assert!(result.contains("->"), "Should contain arrow: {result}");
    }

    #[test]
    fn test_normalize_case_insensitive() {
        // Output should be lowercase
        let result = normalize_type_str("Nat -> Bool");
        assert_eq!(result, result.to_lowercase());
    }

    #[test]
    fn test_normalize_empty_string() {
        assert_eq!(normalize_type_str(""), "");
    }

    #[test]
    fn test_normalize_combined_binders() {
        // "forall (a b : T)," should expand to individual binders
        let result = normalize_type_str("forall (a b : Nat), Bool");
        // Both a and b should appear as binders
        assert!(result.contains("->"), "Should contain arrows: {result}");
    }

    // ========================================================================
    // Lean4Baseline validation tests (#1357)
    // ========================================================================

    #[test]
    fn test_baseline_validate_schema_mismatch() {
        let baseline = Lean4Baseline {
            schema_version: 999, // Wrong version
            generated_at: "unix:0".to_string(),
            lean4_version: "test".to_string(),
            expressions_sha256: "abc".to_string(),
            normalization_version: NORMALIZATION_VERSION,
            cases: vec![],
        };
        let err = baseline.validate(&[]).unwrap_err();
        assert!(
            format!("{err:?}").contains("schema"),
            "Should mention schema: {err:?}"
        );
    }

    #[test]
    fn test_baseline_validate_normalization_mismatch() {
        let baseline = Lean4Baseline {
            schema_version: BASELINE_SCHEMA_VERSION,
            generated_at: "unix:0".to_string(),
            lean4_version: "test".to_string(),
            expressions_sha256: "abc".to_string(),
            normalization_version: 999, // Wrong version
            cases: vec![],
        };
        let err = baseline.validate(&[]).unwrap_err();
        assert!(
            format!("{err:?}").contains("normalization"),
            "Should mention normalization: {err:?}"
        );
    }

    #[test]
    fn test_baseline_validate_count_mismatch() {
        let expressions = vec!["expr1".to_string()];
        let sha = compute_expressions_sha256(&expressions);
        let baseline = Lean4Baseline {
            schema_version: BASELINE_SCHEMA_VERSION,
            generated_at: "unix:0".to_string(),
            lean4_version: "test".to_string(),
            expressions_sha256: sha,
            normalization_version: NORMALIZATION_VERSION,
            cases: vec![], // 0 cases but 1 expression
        };
        let err = baseline.validate(&expressions).unwrap_err();
        let msg = format!("{err:?}");
        assert!(
            msg.contains("0") && msg.contains("1"),
            "Should mention count mismatch: {msg}"
        );
    }

    #[test]
    fn test_baseline_get_types_empty() {
        let baseline = Lean4Baseline {
            schema_version: BASELINE_SCHEMA_VERSION,
            generated_at: "unix:0".to_string(),
            lean4_version: "test".to_string(),
            expressions_sha256: "abc".to_string(),
            normalization_version: NORMALIZATION_VERSION,
            cases: vec![],
        };
        assert!(baseline.get_types().is_empty());
    }

    #[test]
    fn test_baseline_get_types_with_cases() {
        let baseline = Lean4Baseline {
            schema_version: BASELINE_SCHEMA_VERSION,
            generated_at: "unix:0".to_string(),
            lean4_version: "test".to_string(),
            expressions_sha256: "abc".to_string(),
            normalization_version: NORMALIZATION_VERSION,
            cases: vec![
                BaselineCase {
                    expr: "e1".to_string(),
                    type_norm: "nat".to_string(),
                },
                BaselineCase {
                    expr: "e2".to_string(),
                    type_norm: "bool -> nat".to_string(),
                },
            ],
        };
        let types = baseline.get_types();
        assert_eq!(types.len(), 2);
        assert_eq!(types[0], "nat");
        assert_eq!(types[1], "bool -> nat");
    }

    // ========================================================================
    // find_balanced_paren_comma_inner tests (#1357)
    // ========================================================================

    #[test]
    fn test_find_balanced_simple() {
        // "x : T)," — depth starts at 1, ')' is at index 5
        assert_eq!(find_balanced_paren_comma_inner("x : T),"), Some(5));
    }

    #[test]
    fn test_find_balanced_nested() {
        // "(a -> b) : T)," — nested parens
        assert_eq!(find_balanced_paren_comma_inner("(a -> b) : T),"), Some(12));
    }

    #[test]
    fn test_find_balanced_no_comma() {
        // "x : T)" — closing paren without comma
        assert_eq!(find_balanced_paren_comma_inner("x : T)"), None);
    }

    #[test]
    fn test_find_balanced_no_close() {
        // "x : T" — no closing paren
        assert_eq!(find_balanced_paren_comma_inner("x : T"), None);
    }
}
