// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Checkpointed Isabelle session-ROOT generator for the AFP capture waves —
//! the typed Rust port of the retired `scripts/isabelle/afp_session_gen.py`
//! (CLI: `clean mathverse isabelle-sessions`).
//!
//! The corpus v4 (AFP) lane chains AFP entries on a captured post-Library heap
//! (ZP-Lib3e; ZP-Lib2 as the interim probe parent). Each AFP entry is
//! re-elaborated on the parent heap under `record_proofs=4` with the baked
//! zproof capture hook, so its zproof terms are captured as
//! `<Entry>.<Thy>.jsonl` (the hook keys files by `Context.theory_long_name`).
//!
//! THE LIB3 LESSON (`docs/analysis/zproof-v3-backfill.md` §7.1): cumulative
//! `record_proofs=4` transient RSS across theories in ONE Poly/ML process is
//! the binding constraint. Isabelle runs each *session* in its own process,
//! so: one session per entry (per-entry RSS reset), and an entry with more
//! than `cap` theories is split into chained sub-sessions with heap saves at
//! each checkpoint.
//!
//! Three modes, exactly as the Python had them:
//! - [`afp::plan_afp_wave`] — per-entry fragments (Wave A / Wave C bodies);
//! - [`spine::plan_spine`] — the six HOL-* Wave-B spine capture heaps;
//! - [`wavec::plan_wavec`] — the AFP-on-AFP topological DAG build order.
//!
//! **Byte parity contract:** every emitted file is byte-for-byte reproducible
//! and locked by the golden fixtures under `tests/fixtures/isabelle_sessions/`.
//! The port matches the Python generator's output except for one deliberate
//! change: the fragment headers now credit the Rust generator
//! (`auto-generated by clean mathverse isabelle-sessions`) rather than the
//! retired `afp_session_gen.py`; the goldens were regenerated to match (see the
//! parity test's documented `REGEN_ISABELLE_SESSIONS_GOLDEN=1` path). A quirk
//! kept for compatibility: empty list files are written as a single `"\n"`
//! (Python's `"\n".join([]) + "\n"`). Other cleanups must come behind the
//! parity tests.
//!
//! One intentional dead-code drop: the Python `parse_root` also collected
//! each session's umbrella `theories` list, but no mode ever consumed it
//! (chunking uses the on-disk `.thy` topo closure instead). The port keeps
//! only the session-header scan that gates the "no session parsed" skip.

pub mod afp;
pub mod error;
pub(crate) mod root_parse;
pub mod spine;
pub mod wavec;

use std::fs;
use std::path::{Path, PathBuf};

pub use error::IsabelleSessionsError;

/// One generated `ROOT.<session>` fragment.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionFragment {
    /// Session name (the fragment is written as `ROOT.<session>`).
    pub session: String,
    /// Exact file contents (header + session stanza).
    pub contents: String,
}

/// One `manifest.tsv` row: `session \t source \t parent \t n_theories \t
/// capture_prefix` (`source` is the AFP entry in afp mode, the spine session
/// in spine mode).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestRow {
    /// Emitted (sub-)session name, e.g. `ZP-AFP-Graph_Theory-2`.
    pub session: String,
    /// AFP entry (afp mode) or HOL-* spine session (spine mode).
    pub source: String,
    /// Parent heap this (sub-)session chains on.
    pub parent: String,
    /// Number of theories in this checkpoint chunk.
    pub n_theories: usize,
    /// Capture-file prefix for the collect glob (`<source>.`).
    pub capture_prefix: String,
}

/// Read a wave entries file: one entry per line, `#` starts a comment
/// (inline `# CODEGEN` / `# BIG` tags are stripped), blank lines skipped.
pub fn read_entries_file(path: &Path) -> Result<Vec<String>, IsabelleSessionsError> {
    let text = read_text_py(path)?;
    Ok(text
        .lines()
        .filter_map(|line| {
            let name = line.split('#').next().unwrap_or(line).trim();
            (!name.is_empty()).then(|| name.to_string())
        })
        .collect())
}

/// Expand a leading `~`/`~/` to `$HOME`, mirroring Python's
/// `os.path.expanduser` for the forms the wave tooling uses (`~user` is not
/// supported and is returned unchanged).
#[must_use]
pub fn expand_tilde(path: &Path) -> PathBuf {
    let Some(s) = path.to_str() else {
        return path.to_path_buf();
    };
    let home = std::env::var_os("HOME");
    match (s, home) {
        ("~", Some(home)) => PathBuf::from(home),
        (s, Some(home)) if s.starts_with("~/") => PathBuf::from(home).join(&s[2..]),
        _ => path.to_path_buf(),
    }
}

/// Read a text file the way Python's `open(path, errors="ignore")` does:
/// invalid UTF-8 sequences are dropped (not replaced) and newlines are
/// universal-translated (`\r\n` / `\r` → `\n`).
pub(crate) fn read_text_py(path: &Path) -> Result<String, IsabelleSessionsError> {
    let bytes = fs::read(path).map_err(|source| IsabelleSessionsError::Read {
        path: path.to_path_buf(),
        source,
    })?;
    let decoded = decode_utf8_ignore(bytes);
    Ok(normalize_newlines(&decoded))
}

/// Decode UTF-8, silently dropping invalid sequences (Python `errors="ignore"`).
fn decode_utf8_ignore(bytes: Vec<u8>) -> String {
    match String::from_utf8(bytes) {
        Ok(s) => s,
        Err(err) => {
            let bytes = err.into_bytes();
            let mut out = String::with_capacity(bytes.len());
            let mut rest = bytes.as_slice();
            while !rest.is_empty() {
                match std::str::from_utf8(rest) {
                    Ok(tail) => {
                        out.push_str(tail);
                        break;
                    }
                    Err(e) => {
                        let valid = e.valid_up_to();
                        if let Ok(prefix) = std::str::from_utf8(&rest[..valid]) {
                            out.push_str(prefix);
                        }
                        let invalid = e.error_len().unwrap_or(rest.len() - valid).max(1);
                        rest = &rest[(valid + invalid).min(rest.len())..];
                    }
                }
            }
            out
        }
    }
}

/// Universal-newline translation (Python text-mode `open` default).
fn normalize_newlines(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\r', "\n")
}

/// Python `repr()` of a string, for the `{...!r}` header interpolations.
/// Covers the forms session/entry names can take; control characters beyond
/// `\n`/`\r`/`\t` do not occur in those names.
pub(crate) fn py_repr(s: &str) -> String {
    let quote = if s.contains('\'') && !s.contains('"') {
        '"'
    } else {
        '\''
    };
    let mut out = String::with_capacity(s.len() + 2);
    out.push(quote);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c == quote => {
                out.push('\\');
                out.push(c);
            }
            c => out.push(c),
        }
    }
    out.push(quote);
    out
}

/// `"\n".join(lines) + "\n"` — including the Python quirk that an empty list
/// still writes a single newline.
pub(crate) fn join_lines(lines: &[String]) -> String {
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// Write one output file, mapping IO failures to a typed error.
pub(crate) fn write_file(path: &Path, contents: &str) -> Result<(), IsabelleSessionsError> {
    fs::write(path, contents).map_err(|source| IsabelleSessionsError::Write {
        path: path.to_path_buf(),
        source,
    })
}

/// `os.makedirs(outdir, exist_ok=True)`.
pub(crate) fn ensure_outdir(outdir: &Path) -> Result<(), IsabelleSessionsError> {
    fs::create_dir_all(outdir).map_err(|source| IsabelleSessionsError::CreateDir {
        path: outdir.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_py_repr_plain_name_single_quoted() {
        assert_eq!(py_repr("ZP-Lib3e"), "'ZP-Lib3e'");
        assert_eq!(py_repr("Group-Ring-Module"), "'Group-Ring-Module'");
    }

    #[test]
    fn test_py_repr_embedded_single_quote_switches_to_double() {
        assert_eq!(py_repr("it's"), "\"it's\"");
        assert_eq!(py_repr("both'\""), "'both\\'\"'");
    }

    #[test]
    fn test_join_lines_empty_list_is_single_newline() {
        assert_eq!(join_lines(&[]), "\n");
        assert_eq!(join_lines(&["a".into(), "b".into()]), "a\nb\n");
    }

    #[test]
    fn test_decode_utf8_ignore_drops_invalid_bytes() {
        let bytes = vec![b'a', 0xFF, b'b', 0xC3, 0xA9, 0xC3];
        assert_eq!(decode_utf8_ignore(bytes), "ab\u{e9}");
    }

    #[test]
    fn test_normalize_newlines_universal() {
        assert_eq!(normalize_newlines("a\r\nb\rc\n"), "a\nb\nc\n");
    }
}
