// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Internal state for the specialization pass.
//!
//! Contains the ground-value tracking context (`SpecContext`), mutable pass
//! state (`SpecState`), and the cache key types used for deduplication.

use crate::lcnf::{Arg, FunDecl, LetDecl, LetValue};
use clean_kernel::{FVarId, Name};
use std::collections::{HashMap, HashSet};

/// Context for specialization pass.
#[derive(Debug, Clone)]
pub(crate) struct SpecContext {
    /// Set of FVarIds in scope.
    pub(crate) scope: HashSet<FVarId>,
    /// Set of let-declarations that are "ground" (don't depend on runtime params).
    pub(crate) ground: HashSet<FVarId>,
    /// Name of the declaration being processed.
    pub(crate) decl_name: Name,
    /// Map from FVarId to its LetValue for ground value extraction.
    pub(crate) bindings: HashMap<FVarId, LetValue>,
    /// Local function definitions tracked for specialization.
    pub(crate) local_funs: HashMap<FVarId, FunDecl>,
}

impl SpecContext {
    pub(crate) fn new(decl_name: Name) -> Self {
        Self {
            scope: HashSet::new(),
            ground: HashSet::new(),
            decl_name,
            bindings: HashMap::new(),
            local_funs: HashMap::new(),
        }
    }

    /// Add a let-declaration to scope, tracking if it's ground.
    pub(crate) fn with_let_decl(&mut self, decl: &LetDecl) {
        let is_ground = self.is_value_ground(&decl.value);
        let fvar_id = decl.fvar_id;
        self.scope.insert(fvar_id);
        // Store binding for ground value extraction
        self.bindings.insert(fvar_id, decl.value.clone());
        if is_ground {
            self.ground.insert(fvar_id);
        }
    }

    /// Check if a let-value is ground (doesn't depend on non-ground FVars).
    pub(crate) fn is_value_ground(&self, value: &LetValue) -> bool {
        match value {
            LetValue::Lit(_) | LetValue::Erased => true,
            LetValue::Const { args, .. } | LetValue::Ctor { args, .. } => {
                args.iter().all(|arg| self.is_arg_ground(arg))
            }
            LetValue::FVar { fvar, args } => {
                self.is_fvar_ground(*fvar) && args.iter().all(|arg| self.is_arg_ground(arg))
            }
            LetValue::Proj { structure, .. } => self.is_fvar_ground(*structure),
            LetValue::Reuse { slot, args, .. } => {
                self.is_fvar_ground(*slot) && args.iter().all(|arg| self.is_arg_ground(arg))
            }
        }
    }

    /// Check if an argument is ground.
    pub(crate) fn is_arg_ground(&self, arg: &Arg) -> bool {
        match arg {
            Arg::FVar(fvar) => self.is_fvar_ground(*fvar),
            Arg::Type(_) | Arg::Erased | Arg::Index(_) => true,
        }
    }

    /// Check if an FVar is ground (either not in scope or marked ground).
    pub(crate) fn is_fvar_ground(&self, fvar: FVarId) -> bool {
        !self.scope.contains(&fvar) || self.ground.contains(&fvar)
    }
}

/// Key for caching specialization.
///
/// Identifies a unique specialization based on the original function
/// and the ground arguments being specialized on.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SpecCacheKey {
    /// Original function being specialized.
    pub original: Name,
    /// Ground argument values that form the specialization key.
    pub ground_args: Vec<SpecKey>,
}

/// Key component for caching specialization.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SpecKey {
    /// Ground argument (constant value).
    Ground(GroundValue),
    /// Non-ground argument (erased in key).
    Erased,
}

/// Representation of a ground value for caching.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum GroundValue {
    /// Literal value.
    Lit(u64),
    /// Constant reference.
    Const(Name),
    /// Constructor application.
    Ctor(Name, Vec<GroundValue>),
}

/// Key for caching local function specializations.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(crate) struct LocalSpecKey {
    /// Original local function FVarId.
    pub(crate) original_fvar: FVarId,
    /// Ground argument values forming the specialization key.
    pub(crate) ground_args: Vec<SpecKey>,
}

/// Base offset for FVarIds generated by the specialization pass.
/// High enough to avoid collisions with existing FVarIds.
pub(crate) const SPEC_FVAR_BASE: u64 = 10_000_000;

/// State for specialization pass.
#[derive(Debug)]
pub(crate) struct SpecState {
    /// Generated specialized declarations.
    pub(crate) generated_decls: Vec<crate::lcnf::Decl>,
    /// Cache mapping (original_name, ground_args) -> specialized_name.
    pub(crate) spec_cache: HashMap<SpecCacheKey, Name>,
    /// Counter for generating unique names.
    counter: u32,
    /// Pending specialized local functions to emit at the next Code::Let.
    pub(crate) pending_local_specs: Vec<FunDecl>,
    /// Cache for local function specializations: (fvar, ground_args) -> specialized fvar.
    pub(crate) local_spec_cache: HashMap<LocalSpecKey, FVarId>,
}

impl SpecState {
    pub(crate) fn new() -> Self {
        Self {
            generated_decls: Vec::new(),
            spec_cache: HashMap::new(),
            counter: 0,
            pending_local_specs: Vec::new(),
            local_spec_cache: HashMap::new(),
        }
    }

    /// Generate a unique name for a specialized declaration.
    pub(crate) fn gen_spec_name(&mut self, original: &Name, context: &Name) -> Name {
        let suffix = format!("_spec_{}", self.counter);
        self.counter += 1;
        // Pattern: original._at_.context.spec.N
        // e.g., List.map._at_.main.spec.0
        Name::from_string(&format!("{}._at_.{}.spec{}", original, context, suffix))
    }

    /// Generate a unique FVarId for a specialized local function.
    pub(crate) fn gen_spec_fvar(&mut self) -> FVarId {
        let id = SPEC_FVAR_BASE + self.counter as u64;
        self.counter += 1;
        FVarId::new(id)
    }

    /// Look up or insert a cache entry, returning the specialized name if cached.
    pub(crate) fn lookup_cache(&self, key: &SpecCacheKey) -> Option<&Name> {
        self.spec_cache.get(key)
    }

    /// Insert a new specialization into the cache.
    pub(crate) fn cache_spec(&mut self, key: SpecCacheKey, name: Name) {
        self.spec_cache.insert(key, name);
    }
}
