// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Runtime interpreter for MData-tagged isDefEq expressions.

use super::MetaCtx;
use crate::stack_safe;
use crate::unify::MetaState;
use clean_kernel::{Environment, Expr, ExprFolder, ExprKind, Name};
use std::sync::Arc;

/// Result of a runtime q-pattern match attempt
#[derive(Debug, Clone)]
pub struct RuntimeMatchResult {
    /// Whether the pattern matched
    pub matched: bool,
    /// Bindings from pattern variables to their matched values
    /// Only valid if `matched` is true
    pub bindings: Vec<(String, Expr)>,
}

impl RuntimeMatchResult {
    /// Create a successful match result with bindings
    pub fn success(bindings: Vec<(String, Expr)>) -> Self {
        Self {
            matched: true,
            bindings,
        }
    }

    /// Create a failed match result
    pub fn failure() -> Self {
        Self {
            matched: false,
            bindings: Vec::new(),
        }
    }
}

/// Try to match a scrutinee against a pattern at runtime
///
/// This is the main entry point for runtime q-pattern matching.
/// It handles:
/// 1. Creating fresh metavariables for pattern variables
/// 2. Attempting unification
/// 3. Extracting bindings on success
///
/// # Arguments
/// * `meta_ctx` - The MetaM context
/// * `scrutinee` - The expression being matched
/// * `pattern` - The pattern expression (with metavariables for pattern vars)
/// * `pattern_var_metas` - Map from pattern variable names to their metavariable FVarIds
///
/// # Returns
/// A `RuntimeMatchResult` indicating success/failure and bindings
pub fn try_runtime_match(
    meta_ctx: &mut MetaCtx<'_>,
    scrutinee: &Expr,
    pattern: &Expr,
    pattern_var_metas: &[(String, clean_kernel::FVarId)],
) -> RuntimeMatchResult {
    // Use reducible transparency for pattern matching
    let matched = meta_ctx.with_reducible(|ctx| ctx.is_def_eq(scrutinee, pattern));

    if !matched {
        return RuntimeMatchResult::failure();
    }

    // Extract bindings from metavariable assignments
    let mut bindings = Vec::new();
    for (name, fvar_id) in pattern_var_metas {
        if let Some(meta_id) = MetaState::from_fvar(*fvar_id) {
            if let Some(val) = meta_ctx.metas().get_assignment(meta_id) {
                bindings.push((name.clone(), meta_ctx.instantiate_mvars(val)));
            } else {
                // Metavariable not assigned - pattern variable is unconstrained
                // This is valid in some cases (e.g., wildcard-like patterns)
                // For now, return the metavariable itself
                bindings.push((name.clone(), Expr::fvar(*fvar_id)));
            }
        }
    }

    RuntimeMatchResult::success(bindings)
}

/// Result of interpreting a runtime expression
#[derive(Debug, Clone)]
pub enum RuntimeInterpretResult {
    /// Expression evaluated to a concrete value
    Value(Expr),
    /// Expression could not be interpreted (needs further evaluation)
    NotInterpreted(Expr),
    /// Runtime pattern match failed
    MatchFailure,
}

/// Runtime interpreter context for evaluating MData-tagged expressions
///
/// This interprets the expressions generated by `elaborate_runtime_q_match`:
/// - `qq_runtime_check` tags: Execute isDefEq checks
/// - `qq_runtime_binding` tags: Extract pattern variable values
/// - `qq_match_failure` tags: Signal match failures
/// - `ite` applications: Conditional branching based on check results
pub struct RuntimeInterpreter<'a> {
    /// MetaM context for isDefEq checks
    meta_ctx: MetaCtx<'a>,
    /// Current pattern variable bindings (populated during matching)
    bindings: std::collections::HashMap<String, Expr>,
}

// Staged Lean4-parity scaffold with no caller yet (tests included): kept per the
// keep-and-annotate doctrine — see docs/AUDIT_LEAN4_REPLACEMENT_2026-07-22.md (dated 2026-07-30).
#[allow(dead_code)]
impl<'a> RuntimeInterpreter<'a> {
    /// Create a new runtime interpreter
    pub fn new(env: &'a Environment) -> Self {
        Self {
            meta_ctx: MetaCtx::new(env),
            bindings: std::collections::HashMap::new(),
        }
    }

    /// Create interpreter with existing MetaM context
    pub fn with_meta_ctx(meta_ctx: MetaCtx<'a>) -> Self {
        Self {
            meta_ctx,
            bindings: std::collections::HashMap::new(),
        }
    }

    /// Get the MetaM context
    pub fn meta_ctx(&self) -> &MetaCtx<'a> {
        &self.meta_ctx
    }

    /// Get mutable MetaM context
    pub fn meta_ctx_mut(&mut self) -> &mut MetaCtx<'a> {
        &mut self.meta_ctx
    }

    /// Get current bindings
    pub fn bindings(&self) -> &std::collections::HashMap<String, Expr> {
        &self.bindings
    }

    /// Interpret an expression, evaluating MData-tagged runtime constructs
    ///
    /// This is the main entry point for runtime q-pattern matching evaluation.
    pub fn interpret(&mut self, expr: &Expr) -> RuntimeInterpretResult {
        stack_safe(|| match expr.kind() {
            // Handle MData-tagged expressions
            ExprKind::MData(metadata, inner) => self.interpret_mdata(metadata, inner),

            // Handle ite (if-then-else) for runtime conditionals
            ExprKind::App(func, arg) => {
                if let Some(result) = self.try_interpret_ite(expr) {
                    return result;
                }
                // Not an ite, try to interpret sub-expressions
                self.interpret_app(func, arg)
            }

            // Handle let bindings (may contain runtime binding placeholders)
            ExprKind::Let(name, ty, val, body, non_dep) => {
                self.interpret_let(name, ty, val, body, *non_dep)
            }

            // Constants are values (including Bool.true, Bool.false)
            ExprKind::Const(_, _) => RuntimeInterpretResult::Value(expr.clone()),

            // Sorts, literals, and other atomic values
            ExprKind::Sort(_) | ExprKind::Lit(_) => RuntimeInterpretResult::Value(expr.clone()),

            // Other expressions pass through
            _ => RuntimeInterpretResult::NotInterpreted(expr.clone()),
        })
    }

    /// Interpret MData-tagged expression
    fn interpret_mdata(
        &mut self,
        metadata: &clean_kernel::MDataMap,
        inner: &Expr,
    ) -> RuntimeInterpretResult {
        stack_safe(|| {
            use clean_kernel::{MDataValue, Name};

            // Check for qq_runtime_check tag
            if let Some((_, MDataValue::Bool(true))) = metadata
                .iter()
                .find(|(k, _)| *k == Name::from_string("qq_runtime_check"))
            {
                return self.eval_is_def_eq_check(metadata, inner);
            }

            // Check for qq_runtime_binding tag
            if let Some((_, MDataValue::String(var_name))) = metadata
                .iter()
                .find(|(k, _)| *k == Name::from_string("qq_runtime_binding"))
            {
                return self.eval_runtime_binding(var_name);
            }

            // Check for qq_match_failure tag
            if let Some((_, MDataValue::Bool(true))) = metadata
                .iter()
                .find(|(k, _)| *k == Name::from_string("qq_match_failure"))
            {
                return RuntimeInterpretResult::MatchFailure;
            }

            // Unknown MData - interpret the inner expression
            match self.interpret(inner) {
                RuntimeInterpretResult::Value(v) => RuntimeInterpretResult::Value(v),
                RuntimeInterpretResult::NotInterpreted(e) => {
                    RuntimeInterpretResult::NotInterpreted(Expr::mdata(metadata.clone(), e))
                }
                RuntimeInterpretResult::MatchFailure => RuntimeInterpretResult::MatchFailure,
            }
        })
    }

    /// Evaluate a qq_runtime_check tagged expression
    ///
    /// The inner expression should be: App(App(Prod.mk, scrutinee), pattern)
    /// The metadata contains binding entries: `qq_binding_<varname>` = FVarId (as Nat)
    fn eval_is_def_eq_check(
        &mut self,
        metadata: &clean_kernel::MDataMap,
        inner: &Expr,
    ) -> RuntimeInterpretResult {
        use clean_kernel::Name;

        // Extract scrutinee and pattern from Prod.mk application
        if let ExprKind::App(func_app, pattern) = inner.kind() {
            if let ExprKind::App(prod_mk, scrutinee) = func_app.kind() {
                // Verify it's Prod.mk
                if let ExprKind::Const(name, _) = prod_mk.kind() {
                    if *name == Name::from_string("Prod.mk") {
                        // Perform isDefEq check
                        let matched = self
                            .meta_ctx
                            .with_reducible(|ctx| ctx.is_def_eq(scrutinee, pattern));

                        // Extract bindings if matched, using the binding metadata
                        if matched {
                            self.extract_bindings_from_metadata(metadata);
                        }

                        // Return Bool result
                        let result = if matched {
                            Expr::const_(Name::from_string("Bool.true"), vec![])
                        } else {
                            Expr::const_(Name::from_string("Bool.false"), vec![])
                        };

                        return RuntimeInterpretResult::Value(result);
                    }
                }
            }
        }

        // Couldn't parse the check expression
        RuntimeInterpretResult::NotInterpreted(inner.clone())
    }

    /// Extract bindings using the metadata mapping from variable names to FVarIds
    ///
    /// The metadata contains entries like `qq_binding_x = 42` where 42 is the FVarId
    /// of the metavariable that holds the bound value for pattern variable `x`.
    fn extract_bindings_from_metadata(&mut self, metadata: &clean_kernel::MDataMap) {
        use clean_kernel::{FVarId, MDataValue};

        const QQ_BINDING_PREFIX: &str = "qq_binding_";

        for (key, value) in metadata {
            let key_str = key.to_string();
            if let Some(var_name) = key_str.strip_prefix(QQ_BINDING_PREFIX) {
                if let MDataValue::Nat(fvar_id_val) = value {
                    let fvar_id = FVarId::new(*fvar_id_val);
                    // Look up the metavariable assignment by FVarId
                    if let Some(meta_id) = MetaState::from_fvar(fvar_id) {
                        if let Some(val) = self.meta_ctx.metas().get_assignment(meta_id) {
                            // Store binding with the actual variable name
                            let instantiated = self.meta_ctx.instantiate_mvars(val);
                            self.bindings.insert(var_name.to_string(), instantiated);
                        }
                    }
                }
            }
        }
    }

    /// Evaluate a qq_runtime_binding placeholder
    fn eval_runtime_binding(&self, var_name: &str) -> RuntimeInterpretResult {
        if let Some(val) = self.bindings.get(var_name) {
            RuntimeInterpretResult::Value(val.clone())
        } else {
            // Binding not found - this shouldn't happen if pattern matched
            RuntimeInterpretResult::NotInterpreted(Expr::const_(
                Name::from_string("Lean.Expr.hole"),
                vec![],
            ))
        }
    }

    /// Try to interpret an expression as ite (if-then-else)
    fn try_interpret_ite(&mut self, expr: &Expr) -> Option<RuntimeInterpretResult> {
        stack_safe(|| {
            use clean_kernel::Name;

            // ite is: App(App(App(ite, cond), then), else)
            if let ExprKind::App(outer, else_branch) = expr.kind() {
                if let ExprKind::App(middle, then_branch) = outer.kind() {
                    if let ExprKind::App(ite_cond, cond) = middle.kind() {
                        if let ExprKind::Const(name, _) = ite_cond.kind() {
                            if *name == Name::from_string("ite") {
                                // Evaluate the condition
                                match self.interpret(cond) {
                                    RuntimeInterpretResult::Value(v) => {
                                        // Check if condition is Bool.true or Bool.false
                                        if let ExprKind::Const(bool_name, _) = v.kind() {
                                            if *bool_name == Name::from_string("Bool.true") {
                                                return Some(self.interpret(then_branch));
                                            } else if *bool_name == Name::from_string("Bool.false")
                                            {
                                                return Some(self.interpret(else_branch));
                                            }
                                        }
                                        // Condition evaluated but not to a boolean - can't reduce
                                        return Some(RuntimeInterpretResult::NotInterpreted(
                                            expr.clone(),
                                        ));
                                    }
                                    RuntimeInterpretResult::NotInterpreted(_) => {
                                        // Condition couldn't be evaluated
                                        return Some(RuntimeInterpretResult::NotInterpreted(
                                            expr.clone(),
                                        ));
                                    }
                                    RuntimeInterpretResult::MatchFailure => {
                                        return Some(RuntimeInterpretResult::MatchFailure);
                                    }
                                }
                            }
                        }
                    }
                }
            }

            None
        })
    }

    /// Interpret application expression
    fn interpret_app(&mut self, func: &Arc<Expr>, arg: &Arc<Expr>) -> RuntimeInterpretResult {
        stack_safe(|| {
            let func_result = self.interpret(func);
            let arg_result = self.interpret(arg);

            match (func_result, arg_result) {
                (RuntimeInterpretResult::Value(f), RuntimeInterpretResult::Value(a)) => {
                    // Both reduced - reconstruct application
                    RuntimeInterpretResult::Value(Expr::app(f, a))
                }
                (RuntimeInterpretResult::MatchFailure, _)
                | (_, RuntimeInterpretResult::MatchFailure) => RuntimeInterpretResult::MatchFailure,
                _ => RuntimeInterpretResult::NotInterpreted(Expr::app(
                    func.as_ref().clone(),
                    arg.as_ref().clone(),
                )),
            }
        })
    }

    /// Interpret let binding
    fn interpret_let(
        &mut self,
        name: &Name,
        ty: &Arc<Expr>,
        val: &Arc<Expr>,
        body: &Arc<Expr>,
        non_dep: bool,
    ) -> RuntimeInterpretResult {
        stack_safe(|| {
            // First interpret the value
            match self.interpret(val) {
                RuntimeInterpretResult::Value(v) => {
                    // Value evaluated - substitute into body
                    let substituted = self.substitute_bvar0(body, &v);
                    self.interpret(&substituted)
                }
                RuntimeInterpretResult::NotInterpreted(v) => {
                    // Try to interpret the body
                    match self.interpret(body) {
                        RuntimeInterpretResult::Value(b) => RuntimeInterpretResult::Value(
                            Expr::let_named(name.clone(), ty.as_ref().clone(), v, b, non_dep),
                        ),
                        RuntimeInterpretResult::NotInterpreted(b) => {
                            RuntimeInterpretResult::NotInterpreted(Expr::let_named(
                                name.clone(),
                                ty.as_ref().clone(),
                                v,
                                b,
                                non_dep,
                            ))
                        }
                        RuntimeInterpretResult::MatchFailure => {
                            RuntimeInterpretResult::MatchFailure
                        }
                    }
                }
                RuntimeInterpretResult::MatchFailure => RuntimeInterpretResult::MatchFailure,
            }
        })
    }

    /// Substitute an expression for BVar(0) in a body
    fn substitute_bvar0(&self, body: &Expr, replacement: &Expr) -> Expr {
        self.substitute_bvar(body, 0, replacement)
    }

    pub(crate) fn substitute_bvar(&self, expr: &Expr, depth: u32, replacement: &Expr) -> Expr {
        struct SubstituteBvarFolder<'a> {
            depth: u32,
            replacement: &'a Expr,
        }
        impl ExprFolder for SubstituteBvarFolder<'_> {
            fn fold_binder_body(&mut self, expr: &Expr) -> Expr {
                self.depth += 1;
                let result = self.fold_expr(expr);
                self.depth -= 1;
                result
            }
            fn fold_bvar(&mut self, idx: u32) -> Expr {
                if idx == self.depth {
                    self.replacement.clone()
                } else {
                    Expr::bvar(idx)
                }
            }
        }
        let mut folder = SubstituteBvarFolder { depth, replacement };
        folder.fold_expr(expr)
    }
}

/// Convenience function to interpret a runtime q-match expression
///
/// This is the primary entry point for external callers.
pub fn interpret_runtime_match(env: &Environment, expr: &Expr) -> RuntimeInterpretResult {
    let mut interpreter = RuntimeInterpreter::new(env);
    interpreter.interpret(expr)
}
