// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Statement formalization pipeline: converts extracted LaTeX statements into
//! clean type expressions with definition-first ordering, concept linking,
//! semantic validation, and quarantine staging.
//!
//! Architecture (addresses AI Model/AI Model review findings):
//!   1. Definition-First Pipeline: formalize definitions before theorems
//!   2. Concept Linking: match NL concepts to Mathlib/Mathverse Library names
//!   3. LLM Formalization: generate candidate clean type expressions
//!   4. Type Check: verify with clean kernel
//!   5. Semantic Validation: roundtrip check, counter-example search
//!   6. Quarantine: staged admission (candidate → audited → verified)

use serde::{Deserialize, Serialize};

use super::formalize_prompt::{
    ANTI_HALLUCINATION_PROMPT, FAILURE_PATTERNS_PROMPT, KNOWN_TYPES_PROMPT,
    LEAN4_INIT_TYPES_PROMPT, RULES_PROMPT,
};

// ════════════════════════════════════════════════════════════════════════════
// Admission Tiers (quarantine staging)
// ════════════════════════════════════════════════════════════════════════════

/// Admission tier for formalized statements. Formalizations progress through
/// these tiers as they pass additional validation gates.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AdmissionTier {
    /// Just generated by LLM. May or may not type-check.
    Candidate,
    /// Type-checks in clean kernel.
    TypeChecked,
    /// Passed semantic alignment validation (roundtrip + counter-example).
    AuditedAlignment,
    /// Fully kernel-proved (proof term verified, not just type signature).
    KernelProved,
}

// ════════════════════════════════════════════════════════════════════════════
// Concept Linking
// ════════════════════════════════════════════════════════════════════════════

/// A mapping from a natural language concept to its Lean 4 / Mathlib name.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ConceptLink {
    /// Natural language term (e.g., "abelian group").
    pub nl_term: String,
    /// Lean 4 / Mathlib name (e.g., "CommGroup").
    pub lean_name: String,
    /// Confidence score (1.0 = exact match from seed dictionary).
    pub confidence: f64,
}

/// Find Mathlib concepts referenced in a LaTeX statement using the seed dictionary.
/// In production, this would also use the Mathverse Library's 5 search modes.
#[must_use]
pub(crate) fn find_concepts(latex: &str) -> Vec<ConceptLink> {
    let lower = latex.to_lowercase();
    let mut found = Vec::new();

    // Sort by length descending so longer matches take priority
    let mut entries: Vec<_> = CONCEPT_MAP.iter().collect();
    entries.sort_by_key(|(k, _)| std::cmp::Reverse(k.len()));

    for (nl_term, lean_name) in entries {
        if lower.contains(nl_term) {
            found.push(ConceptLink {
                nl_term: nl_term.to_string(),
                lean_name: lean_name.to_string(),
                confidence: 1.0,
            });
        }
    }
    found
}

/// Seed mapping of common math concepts to Mathlib names.
const CONCEPT_MAP: &[(&str, &str)] = &[
    // Number systems
    ("natural number", "Nat"),
    ("integer", "Int"),
    ("rational", "Rat"),
    ("real number", "Real"),
    ("complex number", "Complex"),
    ("prime", "Nat.Prime"),
    ("finite", "Fintype"),
    ("infinite", "Infinite"),
    // Algebra
    ("abelian group", "CommGroup"),
    ("group", "Group"),
    ("commutative ring", "CommRing"),
    ("ring", "Ring"),
    ("field", "Field"),
    ("ideal", "Ideal"),
    ("subgroup", "Subgroup"),
    ("homomorphism", "MonoidHom"),
    ("isomorphism", "MulEquiv"),
    ("module", "Module"),
    ("vector space", "Module"),
    // Analysis
    ("continuous", "Continuous"),
    ("differentiable", "Differentiable"),
    ("integrable", "MeasureTheory.Integrable"),
    ("bounded", "Bornology.IsBounded"),
    ("convergent", "Filter.Tendsto"),
    ("limit", "Filter.Tendsto"),
    // Topology
    ("topological space", "TopologicalSpace"),
    ("metric space", "MetricSpace"),
    ("open set", "IsOpen"),
    ("closed set", "IsClosed"),
    ("compact", "IsCompact"),
    ("connected", "IsConnected"),
    ("hausdorff", "T2Space"),
    // Combinatorics
    ("graph", "SimpleGraph"),
    ("bipartite", "SimpleGraph.IsBipartite"),
    ("finite set", "Finset"),
    ("set", "Set"),
    ("cardinality", "Set.ncard"),
];

// ════════════════════════════════════════════════════════════════════════════
// Formalization Attempt
// ════════════════════════════════════════════════════════════════════════════

/// A single attempt to formalize a statement.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FormalizationAttempt {
    /// Generated Lean 4 code.
    pub lean_code: String,
    /// Whether it type-checks in the clean kernel.
    pub type_checks: bool,
    /// Error message if type-check failed.
    pub error_message: String,
    /// Back-translated natural language (for semantic alignment check).
    pub roundtrip_nl: String,
    /// Semantic similarity score between original and roundtrip (0.0–1.0).
    pub roundtrip_score: f64,
    /// Current admission tier.
    pub tier: AdmissionTier,
}

/// Result of formalizing one extracted statement.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FormalizationResult {
    /// Source paper ID.
    pub paper_id: String,
    /// Statement label (e.g., "Theorem 1").
    pub label: String,
    /// Whether this is a theorem or definition.
    pub kind: String,
    /// Original LaTeX statement.
    pub original_latex: String,
    /// Proof LaTeX (if available).
    pub proof_latex: String,
    /// Labels this statement depends on.
    pub depends_on: Vec<String>,
    /// All formalization attempts, best first.
    pub attempts: Vec<FormalizationAttempt>,
    /// Best successful formalization (empty if none succeeded).
    pub best_lean: String,
    /// Whether any attempt succeeded.
    pub success: bool,
    /// Highest admission tier reached.
    pub tier: AdmissionTier,
}

/// Aggregate formalization result for one paper.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PaperFormalization {
    pub paper_id: String,
    pub title: String,
    pub definitions: Vec<FormalizationResult>,
    pub theorems: Vec<FormalizationResult>,
    pub def_formalized: usize,
    pub def_total: usize,
    pub thm_formalized: usize,
    pub thm_total: usize,
}

// ════════════════════════════════════════════════════════════════════════════
// Dependency Ordering
// ════════════════════════════════════════════════════════════════════════════

/// An item to formalize, with metadata for dependency ordering.
#[derive(Clone, Debug)]
pub(crate) struct OrderableItem {
    pub kind: String,
    pub label: String,
    pub ref_label: String,
    pub latex: String,
    pub proof_latex: String,
    pub dependencies: Vec<String>,
}

/// Order items by dependencies: definitions first (in dependency order), then theorems.
#[must_use]
pub(crate) fn order_by_dependencies(items: &[OrderableItem]) -> Vec<usize> {
    use std::collections::{HashMap, HashSet};

    let by_label: HashMap<&str, usize> = items
        .iter()
        .enumerate()
        .filter(|(_, item)| !item.ref_label.is_empty())
        .map(|(i, item)| (item.ref_label.as_str(), i))
        .collect();

    let definitions: Vec<usize> = items
        .iter()
        .enumerate()
        .filter(|(_, item)| item.kind == "definition")
        .map(|(i, _)| i)
        .collect();

    let theorems: Vec<usize> = items
        .iter()
        .enumerate()
        .filter(|(_, item)| item.kind != "definition")
        .map(|(i, _)| i)
        .collect();

    // Topological sort for definitions
    let mut ordered_defs = Vec::new();
    let mut visited = HashSet::new();

    fn visit(
        idx: usize,
        items: &[OrderableItem],
        by_label: &HashMap<&str, usize>,
        visited: &mut HashSet<usize>,
        ordered: &mut Vec<usize>,
    ) {
        if visited.contains(&idx) {
            return;
        }
        visited.insert(idx);
        for dep in &items[idx].dependencies {
            if let Some(&dep_idx) = by_label.get(dep.as_str()) {
                visit(dep_idx, items, by_label, visited, ordered);
            }
        }
        ordered.push(idx);
    }

    for &def_idx in &definitions {
        visit(def_idx, items, &by_label, &mut visited, &mut ordered_defs);
    }

    ordered_defs.extend(theorems);
    ordered_defs
}

// ════════════════════════════════════════════════════════════════════════════
// Prompt Builder
// ════════════════════════════════════════════════════════════════════════════

/// Build an LLM prompt for formalizing a LaTeX statement.
#[must_use]
pub(crate) fn build_formalization_prompt(
    statement_latex: &str,
    kind: &str,
    concepts: &[ConceptLink],
    macros: &[(String, String)],
    prior_definitions: &[String],
) -> String {
    let mut prompt = String::with_capacity(2048);

    let kind_word = if kind == "definition" {
        "definition"
    } else {
        "theorem statement"
    };

    prompt.push_str(&format!(
        "You are a mathematical formalization expert. Convert the following \
         LaTeX {kind_word} into a Lean 4 type declaration.\n\n\
         ## LaTeX {kind_word}\n```latex\n{statement_latex}\n```\n"
    ));

    if !concepts.is_empty() {
        prompt.push_str("\n## Relevant Mathlib types\n");
        for c in concepts.iter().take(10) {
            prompt.push_str(&format!("- \"{}\" → `{}`\n", c.nl_term, c.lean_name));
        }
    }

    if !macros.is_empty() {
        prompt.push_str("\n## Paper-specific notation\n");
        for (name, body) in macros.iter().take(15) {
            prompt.push_str(&format!("- `\\{name}` = `{body}`\n"));
        }
    }

    if !prior_definitions.is_empty() {
        prompt.push_str("\n## Already formalized from this paper\n```lean\n");
        for d in prior_definitions.iter().rev().take(10).rev() {
            prompt.push_str(d);
            prompt.push('\n');
        }
        prompt.push_str("```\n");
    }

    prompt.push_str(LEAN4_INIT_TYPES_PROMPT);
    prompt.push_str(ANTI_HALLUCINATION_PROMPT);
    prompt.push_str(KNOWN_TYPES_PROMPT);
    prompt.push_str(FAILURE_PATTERNS_PROMPT);
    prompt.push_str(RULES_PROMPT);

    prompt
}

// ════════════════════════════════════════════════════════════════════════════
// Lean Code Extraction
// ════════════════════════════════════════════════════════════════════════════

/// Extract Lean 4 code from an LLM response that may contain markdown fencing
/// and explanatory text.
#[must_use]
pub(crate) fn extract_lean_code(response: &str) -> String {
    // Look for ```lean ... ``` blocks
    if let Some(start) = response.find("```lean\n") {
        let code_start = start + 8;
        if let Some(end) = response[code_start..].find("```") {
            return response[code_start..code_start + end].trim().to_string();
        }
    }

    // Look for lines starting with common Lean keywords
    let lean_keywords = [
        "theorem",
        "def",
        "lemma",
        "structure",
        "class",
        "instance",
        "import",
        "open",
        "variable",
        "namespace",
        "section",
        "noncomputable",
        "private",
        "protected",
        "@",
    ];

    let mut in_code = false;
    let mut lean_lines = Vec::new();
    for line in response.lines() {
        let trimmed = line.trim();
        if lean_keywords.iter().any(|k| trimmed.starts_with(k)) {
            in_code = true;
        }
        if in_code {
            lean_lines.push(line);
        }
    }

    if !lean_lines.is_empty() {
        return lean_lines.join("\n").trim().to_string();
    }

    response.trim().to_string()
}

// ════════════════════════════════════════════════════════════════════════════
// Tests
// ════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_find_concepts_algebra() {
        let latex = "Let $G$ be a finite abelian group and $R$ a commutative ring.";
        let concepts = find_concepts(latex);
        let names: Vec<&str> = concepts.iter().map(|c| c.lean_name.as_str()).collect();
        assert!(
            names.contains(&"CommGroup"),
            "should find abelian group → CommGroup"
        );
        assert!(
            names.contains(&"CommRing"),
            "should find commutative ring → CommRing"
        );
        assert!(names.contains(&"Fintype"), "should find finite → Fintype");
    }

    #[test]
    fn test_find_concepts_topology() {
        let latex = "Let $X$ be a compact hausdorff topological space.";
        let concepts = find_concepts(latex);
        let names: Vec<&str> = concepts.iter().map(|c| c.lean_name.as_str()).collect();
        assert!(names.contains(&"IsCompact"));
        assert!(names.contains(&"T2Space"));
        assert!(names.contains(&"TopologicalSpace"));
    }

    #[test]
    fn test_extract_lean_code_fenced() {
        let response =
            "Here is the formalization:\n```lean\ntheorem foo : True := trivial\n```\nDone.";
        assert_eq!(extract_lean_code(response), "theorem foo : True := trivial");
    }

    #[test]
    fn test_extract_lean_code_unfenced() {
        let response = "I think the formalization is:\ntheorem bar : 1 + 1 = 2 := by norm_num\n";
        assert_eq!(
            extract_lean_code(response),
            "theorem bar : 1 + 1 = 2 := by norm_num"
        );
    }

    #[test]
    fn test_build_prompt_includes_concepts() {
        let concepts = vec![ConceptLink {
            nl_term: "prime".to_string(),
            lean_name: "Nat.Prime".to_string(),
            confidence: 1.0,
        }];
        let prompt = build_formalization_prompt(
            "There are infinitely many primes.",
            "theorem",
            &concepts,
            &[],
            &[],
        );
        assert!(prompt.contains("Nat.Prime"));
        assert!(prompt.contains("theorem statement"));
    }

    #[test]
    fn test_improved_prompt_no_mathlib_types() {
        let prompt = build_formalization_prompt("Let $X$ be a set.", "definition", &[], &[], &[]);
        // Anti-hallucination (existing)
        assert!(prompt.contains("CarrierGraph"), "warn against CarrierGraph");
        assert!(prompt.contains("Do NOT invent fictional Mathlib types"));
        assert!(prompt.contains("sorry"), "suggest sorry-based local defs");
        assert!(
            prompt.contains("TopologicalSpace"),
            "list known-valid types"
        );
        assert!(prompt.contains("import Mathlib.Data.Nat.Basic"));
        // Init types section (new)
        assert!(
            prompt.contains("Lean 4 Init types"),
            "should list Init types"
        );
        assert!(prompt.contains("Prop"), "should list Prop");
        // Tactics (new)
        assert!(prompt.contains("rfl"), "should list rfl tactic");
        assert!(prompt.contains("simp"), "should list simp tactic");
        // Failure patterns guidance (new)
        assert!(
            prompt.contains("Incomplete let bindings"),
            "warn about incomplete let"
        );
        assert!(
            prompt.contains("Missing binders"),
            "warn about missing binders"
        );
        assert!(prompt.contains("Dot notation"), "warn about dot notation");
        // Explicit bind rule (new)
        assert!(prompt.contains("ALWAYS bind free variables explicitly"));
    }

    #[test]
    fn test_dependency_ordering() {
        let items = vec![
            OrderableItem {
                kind: "theorem".to_string(),
                label: "Theorem 1".to_string(),
                ref_label: "thm:1".to_string(),
                latex: "...".to_string(),
                proof_latex: String::new(),
                dependencies: vec!["def:A".to_string()],
            },
            OrderableItem {
                kind: "definition".to_string(),
                label: "Definition B".to_string(),
                ref_label: "def:B".to_string(),
                latex: "...".to_string(),
                proof_latex: String::new(),
                dependencies: vec!["def:A".to_string()],
            },
            OrderableItem {
                kind: "definition".to_string(),
                label: "Definition A".to_string(),
                ref_label: "def:A".to_string(),
                latex: "...".to_string(),
                proof_latex: String::new(),
                dependencies: vec![],
            },
        ];

        let order = order_by_dependencies(&items);
        // Definition A should come before Definition B (dependency order)
        let a_pos = order.iter().position(|&i| i == 2).unwrap();
        let b_pos = order.iter().position(|&i| i == 1).unwrap();
        let thm_pos = order.iter().position(|&i| i == 0).unwrap();
        assert!(a_pos < b_pos, "Definition A before Definition B");
        assert!(b_pos < thm_pos, "Definitions before theorems");
    }
}
