// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Safe-lazy Rust emission from ExtractionIR (rank 7, brick B5).
//!
//! The fourth stage of the rank-7 pipeline: an [`super::Corec`] becomes a
//! self-contained Rust program that computes the same stream, lazily.
//!
//! # `#![forbid(unsafe_code)]` is the claim
//!
//! The ladder asks for "safe lazy Rust". That phrase is a description until
//! something checks it, so the emitted program carries
//! `#![forbid(unsafe_code)]` and is compiled by a real `rustc`. The attribute
//! is what makes the claim mechanical: if any emitted construct ever needed
//! `unsafe`, the emitted crate stops compiling rather than quietly becoming
//! unsafe-but-working.
//!
//! This is deliberately NOT an extension of the existing `emit_rust` backend,
//! which traffics in raw `*mut CleanObj` and `pub unsafe fn`, and does not
//! route through the C runtime. Reusing either would forfeit the property this
//! brick exists to establish.
//!
//! # The laziness has to be real
//!
//! A `for` loop that folds the step function `k` times would produce the right
//! numbers and would not be a lazy lowering at all. The emitted program
//! therefore builds genuine memoized suspensions: each layer holds its state
//! and an initially-empty tail cell, and forcing a tail computes the next layer
//! exactly once and caches it. That is call-by-need, in safe Rust, with `Rc`
//! and `RefCell` — the design's "start with `Rc` and a deterministic
//! single-threaded runtime".
//!
//! # What this does NOT establish
//!
//! That the emitted program agrees with the source is checked by RUNNING it and
//! comparing against values the kernel proved, at the depths run. It is a
//! differential, not a proof. The proof — that source and target are related by
//! the descriptor's indexed bisimulation at every finite depth — is B7, and it
//! does not exist.

use super::{Corec, Op};

/// Render an [`Op`] as a Rust expression over `s` (state) and `p` (params).
fn op_to_rust(op: &Op) -> String {
    match op {
        Op::Lit(n) => format!("Some({n}u64)"),
        // `.get(..).unwrap_or(0)` rather than `s[i]`, to match the reference
        // interpreter's TOTALITY exactly. The interpreter reads an out-of-range
        // slot as 0; direct indexing would panic. That difference would be a
        // divergence between the two implementations the differential exists to
        // compare -- on a malformed IR the interpreter would report a value and
        // the binary would abort, and the harness would be comparing a number
        // against a crash instead of against an answer.
        Op::State(i) => format!("Some(s.get({i}).copied().unwrap_or(0))"),
        Op::Param(i) => format!("Some(p.get({i}).copied().unwrap_or(0))"),
        // CHECKED, mirroring the reference semantics exactly. The source's
        // `Nat` is unbounded and the target's word is not, so past 2^64 there is
        // no target value representing the source's. Wrapping here would make
        // the binary and the interpreter agree on the same WRONG number, which
        // turns a real source/target divergence into evidence of correctness.
        Op::Add(a, b) => format!(
            "({}).and_then(|x| ({}).and_then(|y| x.checked_add(y)))",
            op_to_rust(a),
            op_to_rust(b)
        ),
        Op::Succ(a) => format!("({}).and_then(|x| x.checked_add(1))", op_to_rust(a)),
    }
}

/// Emit a self-contained, safe, lazy Rust program for `c`.
///
/// The program reads `params` from its compiled-in constant and prints
/// `nth(0)..nth(depth-1)`, one value per line — a shape the differential
/// harness can compare line-by-line against the reference interpreter.
#[must_use]
pub fn emit_program(c: &Corec, params: &[u64], depth: u64) -> String {
    let init: Vec<String> = c.init.iter().map(op_to_rust).collect();
    let step: Vec<String> = c.step.iter().map(op_to_rust).collect();
    let observe = op_to_rust(&c.observe);
    let params_lit: Vec<String> = params.iter().map(|v| format!("{v}u64")).collect();

    format!(
        r#"// GENERATED by clean-compiler extraction_ir::emit_rust (rank 7, B5).
// Safe lazy lowering of a codata corecursor. Do not edit.
#![forbid(unsafe_code)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{{AtomicU64, Ordering}};

/// How many tails were actually COMPUTED (cache misses).
///
/// Reported on stderr so the differential harness can check that call-by-need
/// is doing something: walking a shared stream to depth N must compute N tails,
/// not N^2/2. Without sharing and memoization this counter grows quadratically,
/// which is how a "lazy" lowering that memoizes nothing gets caught.
static STEPS: AtomicU64 = AtomicU64::new(0);

/// One observed layer of the stream, with a memoized suspended tail.
struct Layer {{
    head: Option<u64>,
    state: Vec<u64>,
    params: Vec<u64>,
    /// The rest of the stream. `None` until forced -- this cell IS the
    /// suspension, and filling it exactly once IS the memoization.
    tail: RefCell<Option<Rc<Layer>>>,
}}

fn observe(s: &[u64], p: &[u64]) -> Option<u64> {{
    let _ = (s, p);
    {observe}
}}

/// `None` if any slot's arithmetic overflowed: the stream has no faithful
/// continuation from a wrapped value.
fn step(s: &[u64], p: &[u64]) -> Option<Vec<u64>> {{
    let _ = (s, p);
    vec![{step}].into_iter().collect()
}}

fn layer(state: Vec<u64>, params: Vec<u64>) -> Rc<Layer> {{
    let head = observe(&state, &params);
    Rc::new(Layer {{ head, state, params, tail: RefCell::new(None) }})
}}

fn overflow_layer(params: Vec<u64>) -> Rc<Layer> {{
    Rc::new(Layer {{ head: None, state: Vec::new(), params, tail: RefCell::new(None) }})
}}

fn force_tail(l: &Rc<Layer>) -> Rc<Layer> {{
    if let Some(t) = l.tail.borrow().as_ref() {{
        return Rc::clone(t);
    }}
    // Overflow is absorbing: once a step has no faithful next state, every
    // later depth is unrepresentable too. Without this an overflow layer's
    // empty state would read as zeros and the stream would silently RESUME
    // from a value the source never had.
    if l.head.is_none() {{
        let t = overflow_layer(l.params.clone());
        *l.tail.borrow_mut() = Some(Rc::clone(&t));
        return t;
    }}
    STEPS.fetch_add(1, Ordering::Relaxed);
    let t = match step(&l.state, &l.params) {{
        Some(next) => layer(next, l.params.clone()),
        None => overflow_layer(l.params.clone()),
    }};
    *l.tail.borrow_mut() = Some(Rc::clone(&t));
    t
}}

fn nth(k: u64, params: &[u64]) -> Option<u64> {{
    let init: Vec<u64> = {{
        // `init` is written in the definition's parameter scope, with no state
        // in scope yet.
        let s: &[u64] = &[];
        let p: &[u64] = params;
        let _ = (s, p);
        let slots: Option<Vec<u64>> = vec![{init}].into_iter().collect();
        slots?
    }};
    let mut cur = layer(init, params.to_vec());
    for _ in 0..k {{
        cur = force_tail(&cur);
    }}
    cur.head
}}

fn main() {{
    let params: Vec<u64> = vec![{params}];

    // ONE shared stream, walked once. Calling `nth(k)` per k would rebuild from
    // the initial state every time -- correct, quadratic, and it would never
    // re-force a tail, leaving the memoization below dead at runtime. Sharing
    // the root is what makes call-by-need do any work.
    let init: Option<Vec<u64>> = {{
        let s: &[u64] = &[];
        let p: &[u64] = &params;
        let _ = (s, p);
        vec![{init}].into_iter().collect()
    }};
    match init {{
        None => {{
            for _ in 0..{depth}u64 {{
                println!("OVERFLOW");
            }}
        }}
        Some(init) => {{
            let root = layer(init, params.clone());
            // TWO passes over the same shared root. The first computes each
            // tail; the second must find every one of them already cached. A
            // single pass would force each tail exactly once whether or not
            // forcing memoizes, so it could not tell the two apart -- the
            // second pass is what makes the cache observable.
            let mut cur = Rc::clone(&root);
            for k in 0..{depth}u64 {{
                // `OVERFLOW` rather than a wrapped number: the reference
                // interpreter reports ForceError::Overflow at exactly these
                // depths, and the two sides must agree about REFUSING, not
                // merely about answers.
                match cur.head {{
                    Some(v) => println!("{{v}}"),
                    None => println!("OVERFLOW"),
                }}
                if k + 1 < {depth}u64 {{
                    cur = force_tail(&cur);
                }}
            }}
            let mut again = root;
            for k in 0..{depth}u64 {{
                if k + 1 < {depth}u64 {{
                    again = force_tail(&again);
                }}
            }}
        }}
    }}
    eprintln!("STEPS={{}}", STEPS.load(Ordering::Relaxed));
}}
"#,
        observe = observe,
        step = step.join(", "),
        init = init.join(", "),
        params = params_lit.join(", "),
        depth = depth,
    )
}

#[cfg(test)]
#[path = "emit_rust_tests.rs"]
mod tests;
