// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Control flow monad transformers for do-notation (#1818 Phase 4A).
//!
//! Kernel axioms required by the ControlStack:
//! - `Except` type: `Except.ok`, `Except.error`
//! - `ExceptT` transformer: `ExceptT`, `ExceptT.mk`, `ExceptT.run`
//! - `OptionT` transformer: `OptionT`, `OptionT.mk`, `OptionT.run`, `OptionT.fail`
//! - `MonadExcept`: `throw`, `tryCatch`, `tryCatchThe`, `tryFinally`
//!
//! Reference: ~/lean4-ref/src/Init/Control/Except.lean
//! Reference: ~/lean4-ref/src/Init/Control/Option.lean

use super::decl_builder::EnvDeclBuilder;
use crate::env::{Constructor, Declaration, EnvError, Environment, InductiveDecl, InductiveType};
use crate::expr::{BinderInfo, Expr, ExprKind};
use crate::level::Level;
use crate::name::Name;

impl Environment {
    /// Initialize Except type, ExceptT, OptionT, and MonadExcept.
    pub fn init_except_t(&mut self) -> Result<(), EnvError> {
        if self.except_t_init {
            return Ok(());
        }
        self.init_except_type()?;
        self.init_except_bind()?;
        self.init_except_t_transformer()?;
        self.init_monad_except_decls()?;
        self.except_t_init = true;
        Ok(())
    }

    pub(crate) fn has_except_t(&self) -> bool {
        self.except_t_init
    }

    /// Initialize OptionT transformer (used by BreakT/ContinueT).
    pub fn init_option_t(&mut self) -> Result<(), EnvError> {
        if self.option_t_init {
            return Ok(());
        }
        self.init_option_t_type()?;
        self.init_option_t_ops()?;
        self.option_t_init = true;
        Ok(())
    }

    pub(crate) fn has_option_t(&self) -> bool {
        self.option_t_init
    }

    /// Except : Type u → Type u → Type u, as a genuine 2-constructor inductive
    /// (Except.error / Except.ok) with a real `Except.rec`/`Except.casesOn`
    /// recursor generated by `add_inductive`. Mirrors the `init_sum` template
    /// but keeps the single-universe signature (`Type u → Type u → Type u`)
    /// that every existing dependent — `ExceptT`, `MonadExcept`, and the
    /// `monad_reduce` native reducers — was written against, so those
    /// `Except`/`Except.ok`/`Except.error` references resolve unchanged.
    ///
    /// Constructor order is Lean 4's canonical `error`, then `ok`, so the
    /// generated `Except.casesOn` takes the error handler as its first minor
    /// premise and the ok handler as its second — matching the
    /// `Except.casesOn scrut err_handler ok_handler` shape that the
    /// monad-presentation tactic (`monad_pres.rs`) expects.
    ///
    /// Registering `Except` as a real inductive (rather than three opaque
    /// `Axiom`s) lets `match e with | .ok x => … | .error y => …` bind the
    /// constructor payloads at the right types and lets monad-law / runsAgree
    /// proofs reduce through the recursor. Axiom-free: `add_inductive` builds
    /// the recursor from the kernel's recursor generator, no axioms emitted.
    fn init_except_type(&mut self) -> Result<(), EnvError> {
        let u_name = Name::from_string("u");
        let u_level = Level::param(u_name.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let except_const = Expr::const_(Name::from_string("Except"), vec![u_level]);

        // Except : Type u → Type u → Type u
        let except_type = Expr::pi(
            BinderInfo::Default,
            type_u.clone(),
            Expr::pi(BinderInfo::Default, type_u.clone(), type_u.clone()),
        );

        // Except.error : {ε α : Type u} → ε → Except ε α
        let error_type = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (err_id, _) = b.fresh_local(eps.clone());
            let r = Expr::app(Expr::app(except_const.clone(), eps.clone()), alpha);
            let r = b.mk_pi(err_id, BinderInfo::Default, eps, r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };

        // Except.ok : {ε α : Type u} → α → Except ε α
        let ok_type = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (val_id, _) = b.fresh_local(alpha.clone());
            let r = Expr::app(Expr::app(except_const.clone(), eps), alpha.clone());
            let r = b.mk_pi(val_id, BinderInfo::Default, alpha.clone(), r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };

        let except_decl = InductiveDecl {
            level_params: vec![u_name],
            num_params: 2,
            types: vec![InductiveType {
                name: Name::from_string("Except"),
                type_: except_type,
                constructors: vec![
                    Constructor {
                        name: Name::from_string("Except.error"),
                        type_: error_type,
                    },
                    Constructor {
                        name: Name::from_string("Except.ok"),
                        type_: ok_type,
                    },
                ],
            }],
        };

        self.add_inductive(except_decl)
    }

    /// `Except.bind : {ε α β : Type u} → Except ε α → (α → Except ε β) → Except ε β`
    /// as a genuine, axiom-free `Definition` whose body is the canonical
    /// `Except.casesOn` split (matching Lean 4 core's `Except.bind`).
    ///
    /// Our `Except` is single-universe (`Type u → Type u → Type u`), so the
    /// definition is monomorphic in one universe `u` covering `ε`, `α`, `β`.
    /// Every in-scope use (`(Sem.run m s).bind …`, where everything lives in
    /// `Type 0`) instantiates `u := 0`.
    ///
    /// The body
    ///   `fun ε α β e f =>
    ///      Except.casesOn.{u+1, u} ε α (fun _ => Except ε β) e
    ///        (fun err => Except.error ε β err) (fun a => f a)`
    /// reduces definitionally: `Except.bind (.ok a) f ⟶ f a` and
    /// `Except.bind (.error e) f ⟶ .error e`. That is exactly what
    /// `Sem.run_bind := rfl` (`(Sem.run m s).bind …`) needs to close, and it
    /// is what `Bind.bind` on the `Except` monad unfolds to, so registering it
    /// keeps the dot-notation `e.bind f` sound. `add_decl` kernel-checks the
    /// definition; no axioms are emitted.
    fn init_except_bind(&mut self) -> Result<(), EnvError> {
        let u_name = Name::from_string("u");
        let u_level = Level::param(u_name.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let except_const = Expr::const_(Name::from_string("Except"), vec![u_level.clone()]);
        let except_of = |eps: &Expr, a: &Expr| {
            Expr::app(Expr::app(except_const.clone(), eps.clone()), a.clone())
        };
        let error_const = Expr::const_(Name::from_string("Except.error"), vec![u_level.clone()]);
        // Except.casesOn.{w, u}: motive universe w := u+1 (motive returns
        // `Except ε β : Type u = Sort (u+1)`), then the inductive's own `u`.
        let cases_const = Expr::const_(
            Name::from_string("Except.casesOn"),
            vec![Level::succ(u_level.clone()), u_level.clone()],
        );

        // Type: {ε α β : Type u} → Except ε α → (α → Except ε β) → Except ε β
        let bind_type = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (beta_id, beta) = b.fresh_local(type_u.clone());
            let e_ty = except_of(&eps, &alpha);
            let res_ty = except_of(&eps, &beta);
            let (e_id, _) = b.fresh_local(e_ty.clone());
            let f_ty = {
                let mut c = EnvDeclBuilder::child_of(&b);
                let (a_id, _) = c.fresh_local(alpha.clone());
                let r = c.mk_pi(a_id, BinderInfo::Default, alpha.clone(), res_ty.clone());
                c.finish_child(r)
            };
            let (f_id, _) = b.fresh_local(f_ty.clone());
            let r = res_ty.clone();
            let r = b.mk_pi(f_id, BinderInfo::Default, f_ty, r);
            let r = b.mk_pi(e_id, BinderInfo::Default, e_ty, r);
            let r = b.mk_pi(beta_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };

        // Value: fun {ε α β} e f =>
        //   Except.casesOn ε α (fun _ => Except ε β) e
        //     (fun err => Except.error ε β err) (fun a => f a)
        let bind_value = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (beta_id, beta) = b.fresh_local(type_u.clone());
            let e_ty = except_of(&eps, &alpha);
            let res_ty = except_of(&eps, &beta);
            let (e_id, e) = b.fresh_local(e_ty.clone());
            let f_ty = {
                let mut c = EnvDeclBuilder::child_of(&b);
                let (a_id, _) = c.fresh_local(alpha.clone());
                let r = c.mk_pi(a_id, BinderInfo::Default, alpha.clone(), res_ty.clone());
                c.finish_child(r)
            };
            let (f_id, f) = b.fresh_local(f_ty.clone());

            // motive : Except ε α → Type u := fun _ => Except ε β
            let motive = {
                let (z_id, _) = b.fresh_local(e_ty.clone());
                b.mk_lam(z_id, BinderInfo::Default, e_ty.clone(), res_ty.clone())
            };
            // error minor : ε → Except ε β := fun err => Except.error ε β err
            let error_minor = {
                let (err_id, err) = b.fresh_local(eps.clone());
                let body = Expr::apps(error_const.clone(), [eps.clone(), beta.clone(), err]);
                b.mk_lam(err_id, BinderInfo::Default, eps.clone(), body)
            };
            // ok minor : α → Except ε β := fun a => f a
            let ok_minor = {
                let (a_id, a) = b.fresh_local(alpha.clone());
                let body = Expr::app(f.clone(), a);
                b.mk_lam(a_id, BinderInfo::Default, alpha.clone(), body)
            };
            // This kernel's `add_inductive`-generated `casesOn` follows the
            // Lean-faithful recOn telescope (`build_rec_on_type`):
            //   params → motive → indices → major → minors
            // so the scrutinee (`e`, the major premise) comes between the
            // motive and the minors, exactly as in Lean 4 core.
            let cases = Expr::apps(
                cases_const.clone(),
                [
                    eps.clone(),
                    alpha.clone(),
                    motive,
                    e.clone(),
                    error_minor,
                    ok_minor,
                ],
            );
            let r = cases;
            let r = b.mk_lam(f_id, BinderInfo::Default, f_ty, r);
            let r = b.mk_lam(e_id, BinderInfo::Default, e_ty, r);
            let r = b.mk_lam(beta_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_lam(eps_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };

        self.add_decl(Declaration::Definition {
            name: Name::from_string("Except.bind"),
            level_params: vec![u_name],
            type_: bind_type,
            value: bind_value,
            is_reducible: false,
        })
    }

    /// ExceptT : Type u → (Type u → Type v) → Type u → Type v, with mk/run
    fn init_except_t_transformer(&mut self) -> Result<(), EnvError> {
        let u_name = Name::from_string("u");
        let v_name = Name::from_string("v");
        let u_level = Level::param(u_name.clone());
        let v_level = Level::param(v_name.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let type_v = Expr::from_kind(ExprKind::Sort(Level::succ(v_level.clone())));
        let m_ty = Expr::pi(BinderInfo::Default, type_u.clone(), type_v.clone());
        let except_const = Expr::const_(Name::from_string("Except"), vec![u_level.clone()]);
        let lvs = vec![u_level.clone(), v_level];

        // ExceptT : Type u → (Type u → Type v) → Type u → Type v
        let t = Expr::pi(
            BinderInfo::Default,
            type_u.clone(),
            Expr::pi(
                BinderInfo::Default,
                m_ty.clone(),
                Expr::pi(BinderInfo::Default, type_u.clone(), type_v.clone()),
            ),
        );
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("ExceptT"),
            level_params: vec![u_name.clone(), v_name.clone()],
            type_: t,
        })?;

        let et = Expr::const_(Name::from_string("ExceptT"), lvs.clone());

        // ExceptT.mk : {ε : Type u} → {m} → {α : Type u} → m (Except ε α) → ExceptT ε m α
        let mk_type = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (m_id, m) = b.fresh_local(m_ty.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let except_ea = Expr::app(Expr::app(except_const.clone(), eps.clone()), alpha.clone());
            let m_except = Expr::app(m.clone(), except_ea);
            let (val_id, _) = b.fresh_local(m_except.clone());
            let r = Expr::app(Expr::app(Expr::app(et.clone(), eps), m), alpha);
            let r = b.mk_pi(val_id, BinderInfo::Default, m_except, r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(m_id, BinderInfo::Implicit, m_ty.clone(), r);
            let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("ExceptT.mk"),
            level_params: vec![u_name.clone(), v_name.clone()],
            type_: mk_type,
        })?;

        // ExceptT.run : {ε : Type u} → {m} → {α : Type u} → ExceptT ε m α → m (Except ε α)
        let run_type = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (m_id, m) = b.fresh_local(m_ty.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let et_ema = Expr::app(
                Expr::app(Expr::app(et, eps.clone()), m.clone()),
                alpha.clone(),
            );
            let except_ea = Expr::app(Expr::app(except_const, eps), alpha);
            let m_except = Expr::app(m, except_ea);
            let (val_id, _) = b.fresh_local(et_ema.clone());
            let r = m_except;
            let r = b.mk_pi(val_id, BinderInfo::Default, et_ema, r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(m_id, BinderInfo::Implicit, m_ty, r);
            let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u, r);
            b.finish(r)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("ExceptT.run"),
            level_params: vec![u_name, v_name],
            type_: run_type,
        })
    }

    /// MonadExcept.throw, MonadExcept.tryCatch, tryCatchThe, tryFinally
    fn init_monad_except_decls(&mut self) -> Result<(), EnvError> {
        let u = Name::from_string("u");
        let v = Name::from_string("v");
        let w = Name::from_string("w");
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(u.clone()))));
        let type_v = Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(v.clone()))));
        let type_w = Expr::from_kind(ExprKind::Sort(Level::succ(Level::param(w.clone()))));
        let m_vw = Expr::pi(BinderInfo::Default, type_v.clone(), type_w.clone());

        // MonadExcept.throw : {ε : Type u} → {m : Type v → Type w} → {α} → ε → m α
        let throw_type = {
            let mut b = EnvDeclBuilder::new();
            let (eps_id, eps) = b.fresh_local(type_u.clone());
            let (m_id, m) = b.fresh_local(m_vw.clone());
            let (alpha_id, alpha) = b.fresh_local(type_v.clone());
            let (err_id, _) = b.fresh_local(eps.clone());
            let r = Expr::app(m, alpha);
            let r = b.mk_pi(err_id, BinderInfo::Default, eps, r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_v.clone(), r);
            let r = b.mk_pi(m_id, BinderInfo::Implicit, m_vw.clone(), r);
            let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("MonadExcept.throw"),
            level_params: vec![u.clone(), v.clone(), w.clone()],
            type_: throw_type,
        })?;

        // MonadExcept.tryCatch : {ε} → {m} → {α} → m α → (ε → m α) → m α
        let tc_type = self.build_try_catch_type(&type_u, &type_v, &type_w, &m_vw)?;
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("MonadExcept.tryCatch"),
            level_params: vec![u.clone(), v.clone(), w],
            type_: tc_type,
        })?;

        // tryCatchThe : same signature (typed catch, instance implicit)
        let m_vv = Expr::pi(BinderInfo::Default, type_v.clone(), type_v.clone());
        let tct_type = self.build_try_catch_type(&type_u, &type_v, &type_v, &m_vv)?;
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("tryCatchThe"),
            level_params: vec![u.clone(), v.clone()],
            type_: tct_type,
        })?;

        // tryFinally : {m} → {α β} → m α → m β → m α
        let m_uv = Expr::pi(BinderInfo::Default, type_u.clone(), type_v.clone());
        let tf_type = {
            let mut b = EnvDeclBuilder::new();
            let (m_id, m) = b.fresh_local(m_uv.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (beta_id, beta) = b.fresh_local(type_u.clone());
            let m_a = Expr::app(m.clone(), alpha.clone());
            let m_b = Expr::app(m, beta);
            let (body_id, _) = b.fresh_local(m_a.clone());
            let (fin_id, _) = b.fresh_local(m_b.clone());
            let r = m_a.clone();
            let r = b.mk_pi(fin_id, BinderInfo::Default, m_b, r);
            let r = b.mk_pi(body_id, BinderInfo::Default, m_a, r);
            let r = b.mk_pi(beta_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u, r);
            let r = b.mk_pi(m_id, BinderInfo::Implicit, m_uv, r);
            b.finish(r)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("tryFinally"),
            level_params: vec![u, v],
            type_: tf_type,
        })
    }

    /// Build the shared tryCatch type: {ε} → {m} → {α} → m α → (ε → m α) → m α
    fn build_try_catch_type(
        &self,
        type_u: &Expr,
        type_v: &Expr,
        type_w: &Expr,
        m_ty: &Expr,
    ) -> Result<Expr, EnvError> {
        let mut b = EnvDeclBuilder::new();
        let (eps_id, eps) = b.fresh_local(type_u.clone());
        let (m_id, m) = b.fresh_local(m_ty.clone());
        let (alpha_id, alpha) = b.fresh_local(type_v.clone());
        let m_alpha = Expr::app(m, alpha);
        let (body_id, _) = b.fresh_local(m_alpha.clone());
        let handler_ty = {
            let mut c = EnvDeclBuilder::child_of(&b);
            let (e_id, _) = c.fresh_local(eps.clone());
            let r = m_alpha.clone();
            let r = c.mk_pi(e_id, BinderInfo::Default, eps.clone(), r);
            c.finish_child(r)
        };
        let (h_id, _) = b.fresh_local(handler_ty.clone());
        let r = m_alpha.clone();
        let r = b.mk_pi(h_id, BinderInfo::Default, handler_ty, r);
        let r = b.mk_pi(body_id, BinderInfo::Default, m_alpha, r);
        let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_v.clone(), r);
        let r = b.mk_pi(m_id, BinderInfo::Implicit, m_ty.clone(), r);
        let r = b.mk_pi(eps_id, BinderInfo::Implicit, type_u.clone(), r);
        let _ = type_w; // Used implicitly via m_ty's range
        Ok(b.finish(r))
    }

    /// OptionT type + mk constructor
    fn init_option_t_type(&mut self) -> Result<(), EnvError> {
        let u = Name::from_string("u");
        let v = Name::from_string("v");
        let u_level = Level::param(u.clone());
        let v_level = Level::param(v.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let type_v = Expr::from_kind(ExprKind::Sort(Level::succ(v_level.clone())));
        let m_ty = Expr::pi(BinderInfo::Default, type_u.clone(), type_v.clone());
        let option_c = Expr::const_(Name::from_string("Option"), vec![u_level.clone()]);
        let lvs = vec![u_level, v_level];

        // OptionT : (Type u → Type v) → Type u → Type v
        let t = Expr::pi(
            BinderInfo::Default,
            m_ty.clone(),
            Expr::pi(BinderInfo::Default, type_u.clone(), type_v.clone()),
        );
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("OptionT"),
            level_params: vec![u.clone(), v.clone()],
            type_: t,
        })?;

        let ot = Expr::const_(Name::from_string("OptionT"), lvs);

        // OptionT.mk : {m} → {α} → m (Option α) → OptionT m α
        let mk_type = {
            let mut b = EnvDeclBuilder::new();
            let (m_id, m) = b.fresh_local(m_ty.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let opt_a = Expr::app(option_c, alpha.clone());
            let m_opt = Expr::app(m.clone(), opt_a);
            let (val_id, _) = b.fresh_local(m_opt.clone());
            let r = Expr::app(Expr::app(ot, m), alpha);
            let r = b.mk_pi(val_id, BinderInfo::Default, m_opt, r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(m_id, BinderInfo::Implicit, m_ty, r);
            b.finish(r)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("OptionT.mk"),
            level_params: vec![u, v],
            type_: mk_type,
        })
    }

    /// OptionT.run and OptionT.fail
    fn init_option_t_ops(&mut self) -> Result<(), EnvError> {
        let u = Name::from_string("u");
        let v = Name::from_string("v");
        let u_level = Level::param(u.clone());
        let v_level = Level::param(v.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let type_v = Expr::from_kind(ExprKind::Sort(Level::succ(v_level.clone())));
        let m_ty = Expr::pi(BinderInfo::Default, type_u.clone(), type_v.clone());
        let option_c = Expr::const_(Name::from_string("Option"), vec![u_level.clone()]);
        let ot = Expr::const_(Name::from_string("OptionT"), vec![u_level, v_level]);

        // OptionT.run : {m} → {α} → OptionT m α → m (Option α)
        let run_type = {
            let mut b = EnvDeclBuilder::new();
            let (m_id, m) = b.fresh_local(m_ty.clone());
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let ot_ma = Expr::app(Expr::app(ot.clone(), m.clone()), alpha.clone());
            let opt_a = Expr::app(option_c, alpha);
            let m_opt = Expr::app(m, opt_a);
            let (val_id, _) = b.fresh_local(ot_ma.clone());
            let r = m_opt;
            let r = b.mk_pi(val_id, BinderInfo::Default, ot_ma, r);
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            let r = b.mk_pi(m_id, BinderInfo::Implicit, m_ty.clone(), r);
            b.finish(r)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("OptionT.run"),
            level_params: vec![u.clone(), v.clone()],
            type_: run_type,
        })?;

        // OptionT.fail : {m} → {α} → OptionT m α
        //
        // IMPORT MODE (`suppress_lossy_structure_stubs`): this is a
        // REDUCED-ARITY stub — Lean v4.30's genuine signature is
        // `{m : Type u → Type v} → [inst : Monad m] → {α : Type u} →
        // OptionT m α` (the `variable [Monad m]` binder is used by the body
        // `OptionT.mk (pure none)`). With the 2-binder stub seeded first, the
        // olean twin fails the type-defeq dedup AND the checked axiom-upgrade,
        // so the stub stays authoritative and every olean value applying
        // `@OptionT.fail m inst α` (OptionT.instAlternative,
        // OptionT.instMonadExceptOfPUnit) typechecks `inst : Monad m` against
        // the `{α : Type u}` slot and masks out (census roots:
        // Init.Control.Option). Suppressing the stub in import mode lets the
        // genuine olean definition (with its value) flow through the normal
        // CHECKED `add_decl` import path. SOUNDNESS-NEUTRAL: only WITHHOLDS a
        // Clean-native stub in the import-only prelude; the imported constant
        // is the genuine olean value, re-checked by the unmodified kernel.
        // The do-notation elaboration lane (`Environment::new()`,
        // `mk_option_t_fail` in clean-elab building `@OptionT.fail m α`)
        // keeps the 2-binder stub — it cannot supply a Monad instance today
        // (`DoMonadInfo.m` is a metavariable and `OptionT.instMonad` is not
        // seeded), matching the reduced-arity `MonadExcept.throw` convention
        // used by the same lowering.
        if !self.suppress_lossy_structure_stubs {
            let fail_type = {
                let mut b = EnvDeclBuilder::new();
                let (m_id, m) = b.fresh_local(m_ty.clone());
                let (alpha_id, alpha) = b.fresh_local(type_u.clone());
                let r = Expr::app(Expr::app(ot, m), alpha);
                let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u, r);
                let r = b.mk_pi(m_id, BinderInfo::Implicit, m_ty, r);
                b.finish(r)
            };
            self.add_decl(Declaration::Axiom {
                name: Name::from_string("OptionT.fail"),
                level_params: vec![u, v],
                type_: fail_type,
            })?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::env::Environment;
    use crate::expr::Expr;
    use crate::name::Name;

    #[test]
    fn test_init_except_t() {
        let mut env = Environment::new();
        env.init_except_t().expect("init_except_t");
        assert!(env.has_except_t());

        for name_str in [
            "Except",
            "Except.ok",
            "Except.error",
            "Except.bind",
            "ExceptT",
            "ExceptT.mk",
            "ExceptT.run",
            "MonadExcept.throw",
            "MonadExcept.tryCatch",
            "tryCatchThe",
            "tryFinally",
        ] {
            let name = Name::from_string(name_str);
            let ci = env
                .get_const(&name)
                .unwrap_or_else(|| panic!("{name_str} not registered after init_except_t"));
            assert_eq!(ci.name, name, "{name_str}: name mismatch");
        }
    }

    #[test]
    fn test_init_except_t_idempotent() {
        let mut env = Environment::new();
        env.init_except_t().expect("first");
        env.init_except_t().expect("idempotent");
    }

    #[test]
    fn test_init_option_t() {
        let mut env = Environment::new();
        // OptionT.mk references Option, which must be initialized first
        env.init_option().expect("init_option");
        env.init_option_t().expect("init_option_t");
        assert!(env.has_option_t());

        for name_str in ["OptionT", "OptionT.mk", "OptionT.run", "OptionT.fail"] {
            let name = Name::from_string(name_str);
            let ci = env
                .get_const(&name)
                .unwrap_or_else(|| panic!("{name_str} not registered after init_option_t"));
            assert_eq!(ci.name, name, "{name_str}: name mismatch");
        }
    }

    #[test]
    fn test_init_option_t_idempotent() {
        let mut env = Environment::new();
        env.init_option().expect("init_option");
        env.init_option_t().expect("first");
        env.init_option_t().expect("idempotent");
    }

    #[test]
    fn test_except_t_key_types_well_formed() {
        use crate::expr::ExprKind;
        use crate::level::Level;
        use crate::tc::TypeChecker;

        let mut env = Environment::new();
        env.init_except_t().expect("init_except_t");
        let tc = TypeChecker::new(&env);

        // Except : Type u → Type u → Type u  (1 level param)
        for name in &["Except", "ExceptT", "MonadExcept.throw"] {
            let n = Name::from_string(name);
            let ci = env.get_const(&n).expect(name);
            let levels: Vec<Level> = ci.level_params.iter().map(|_| Level::zero()).collect();
            let expr = Expr::const_(n, levels);
            let ty = tc
                .infer_type(&expr)
                .unwrap_or_else(|e| panic!("{name}: tc.infer_type failed: {e}"));
            // All are Pi types (they take type arguments)
            assert!(
                matches!(&ty.kind, ExprKind::Pi(..)),
                "{name}: expected Pi type, got {ty:?}"
            );
        }
    }

    #[test]
    fn test_option_t_key_types_well_formed() {
        use crate::expr::ExprKind;
        use crate::level::Level;
        use crate::tc::TypeChecker;

        let mut env = Environment::new();
        env.init_option().expect("init_option");
        env.init_option_t().expect("init_option_t");
        let tc = TypeChecker::new(&env);

        for name in &["OptionT", "OptionT.mk", "OptionT.run", "OptionT.fail"] {
            let n = Name::from_string(name);
            let ci = env.get_const(&n).expect(name);
            let levels: Vec<Level> = ci.level_params.iter().map(|_| Level::zero()).collect();
            let expr = Expr::const_(n, levels);
            let ty = tc
                .infer_type(&expr)
                .unwrap_or_else(|e| panic!("{name}: tc.infer_type failed: {e}"));
            assert!(
                matches!(&ty.kind, ExprKind::Pi(..)),
                "{name}: expected Pi type, got {ty:?}"
            );
        }
    }
}
