// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! `Multiset` — the faithful quotient of `List` by permutation.
//!
//! This module builds the substrate toward a real `Finset`/`Fintype`:
//!
//! - `List.Nodup : List α → Prop` — a direct inductive witnessing that a list
//!   has no duplicate elements (a `Finset` prerequisite).
//! - `Multiset α := Quot (@List.Perm α)` — the quotient of `List α` by the
//!   permutation relation. Because the quotient is taken modulo `List.Perm`,
//!   `[1, 2]` and `[2, 1]` are **equal** as multisets (witnessed by
//!   `Quot.sound` applied to a `List.Perm.swap` derivation); the type is
//!   genuinely order-insensitive, never a thinly-wrapped order-sensitive list.
//! - `Multiset.nil`, `Multiset.cons`, `Multiset.Mem`, and the `Membership`
//!   instance, all defined by lifting the corresponding `List` operations
//!   through the quotient (`Quot.mk` / `Quot.lift`), discharging the
//!   "respects-`Perm`" obligations with `Quot.sound` and `List.Perm.cons`
//!   (for `cons`) and the `List.Perm.mem_iff` congruence + `propext` (for
//!   `Mem`).
//!
//! Every declaration here is constructive and its transitive axiom closure is
//! `⊆ {Quot.sound, propext}` — both FOUNDATIONAL. No domain-specific axiom,
//! `sorry`, or unchecked declaration is introduced.
//!
//! Universe handling: `List.{u} : Type u → Type u`, so `List α : Type u =
//! Sort (u+1)`. The quotient is therefore taken at level `u+1`: `Multiset α =
//! @Quot.{u+1} (List α) (@List.Perm α)`.

use crate::env::decl_builder::EnvDeclBuilder;
use crate::env::{Constructor, Declaration, EnvError, Environment, InductiveDecl, InductiveType};
use crate::expr::{BinderInfo, Expr, ExprKind};
use crate::level::Level;
use crate::name::Name;

impl Environment {
    /// Initialize `List.Nodup`, the `Multiset` quotient, and its core
    /// operations (`nil`, `cons`, `Mem`) plus membership lemmas.
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: On success, `self.multiset_init == true`
    /// ENSURES: On success, `List.Nodup` (+ ctors + rec), `Multiset`,
    ///          `Multiset.nil`, `Multiset.cons`, `Multiset.Mem`,
    ///          `Multiset.instMembership`, `List.Perm.mem_iff`, and
    ///          `Multiset.mem_cons_self` are registered.
    /// ENSURES: Idempotent - calling multiple times returns `Ok(())` without
    ///          duplication.
    pub fn init_multiset(&mut self) -> Result<(), EnvError> {
        if self.multiset_init {
            return Ok(());
        }

        // Dependencies: List (+ nil/cons/rec), List.Mem (+ Membership), and
        // List.Perm (+ rec/cons). Quot.* and propext are needed for the
        // quotient construction; Or/Eq for the membership characterization.
        self.init_list_mem()?;
        self.init_list_perm()?;
        self.init_true_false()?; // provides `Not` (used by List.Nodup.cons)
        self.init_or()?; // provides `Or` (used by List.mem_cons_iff)
        self.init_quot();
        self.init_quot_sound()?;
        self.init_propext()?;
        self.init_iff()?;

        self.init_list_nodup()?;
        self.init_multiset_core()?;
        self.init_multiset_mem()?;

        self.multiset_init = true;
        Ok(())
    }

    /// Register `List.Nodup` — the faithful "no duplicates" inductive.
    ///
    /// ```text
    /// inductive List.Nodup : List α → Prop
    ///   | nil  : Nodup []
    ///   | cons {a : α} {l : List α} : ¬ List.Mem a l → Nodup l → Nodup (a :: l)
    /// ```
    ///
    /// `α` is the sole parameter; the `List α` argument is the single index.
    /// `List.Nodup.rec` is generated by `add_inductive`.
    fn init_list_nodup(&mut self) -> Result<(), EnvError> {
        let u = Name::from_string("u");
        let u_level = Level::param(u.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let prop = Expr::from_kind(ExprKind::Sort(Level::zero()));

        let list_const = Expr::const_(Name::from_string("List"), vec![u_level.clone()]);
        let list_nil = Expr::const_(Name::from_string("List.nil"), vec![u_level.clone()]);
        let list_cons = Expr::const_(Name::from_string("List.cons"), vec![u_level.clone()]);
        let mem_const = Expr::const_(Name::from_string("List.Mem"), vec![u_level.clone()]);
        let not_const = Expr::const_(Name::from_string("Not"), vec![]);
        let nodup_const = Expr::const_(Name::from_string("List.Nodup"), vec![u_level.clone()]);

        let list_of = |a: &Expr| Expr::app(list_const.clone(), a.clone());
        let nil_of = |a: &Expr| Expr::app(list_nil.clone(), a.clone());
        let cons_of = |a: &Expr, x: Expr, l: Expr| Expr::apps(list_cons.clone(), [a.clone(), x, l]);
        let mem = |a: &Expr, x: Expr, l: Expr| Expr::apps(mem_const.clone(), [a.clone(), x, l]);
        let nodup = |a: &Expr, l: Expr| Expr::apps(nodup_const.clone(), [a.clone(), l]);
        let not = |p: Expr| Expr::app(not_const.clone(), p);

        // ── List.Nodup : {α : Type u} → List α → Prop ───────────────────────
        let nodup_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (l_id, _l) = b.fresh_local(list_of(&alpha));
            let e = prop.clone();
            let e = b.mk_pi(l_id, BinderInfo::Default, list_of(&alpha), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };

        // ── List.Nodup.nil : {α} → Nodup [] ─────────────────────────────────
        let nodup_nil_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let concl = nodup(&alpha, nil_of(&alpha));
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), concl);
            b.finish(e)
        };

        // ── List.Nodup.cons :
        //      {α} → {a : α} → {l : List α} → ¬ List.Mem a l → Nodup l
        //          → Nodup (a :: l) ─────────────────────────────────────────
        let nodup_cons_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (l_id, l) = b.fresh_local(list_of(&alpha));
            let not_mem = not(mem(&alpha, a.clone(), l.clone()));
            let (hm_id, _hm) = b.fresh_local(not_mem.clone());
            let nodup_l = nodup(&alpha, l.clone());
            let (hn_id, _hn) = b.fresh_local(nodup_l.clone());
            let concl = nodup(&alpha, cons_of(&alpha, a.clone(), l.clone()));
            let e = b.mk_pi(hn_id, BinderInfo::Default, nodup_l, concl);
            let e = b.mk_pi(hm_id, BinderInfo::Default, not_mem, e);
            let e = b.mk_pi(l_id, BinderInfo::Implicit, list_of(&alpha), e);
            let e = b.mk_pi(a_id, BinderInfo::Implicit, alpha.clone(), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };

        let nodup_decl = InductiveDecl {
            level_params: vec![u.clone()],
            num_params: 1, // α is the sole parameter; `List α` is the index
            types: vec![InductiveType {
                name: Name::from_string("List.Nodup"),
                type_: nodup_type,
                constructors: vec![
                    Constructor {
                        name: Name::from_string("List.Nodup.nil"),
                        type_: nodup_nil_type,
                    },
                    Constructor {
                        name: Name::from_string("List.Nodup.cons"),
                        type_: nodup_cons_type,
                    },
                ],
            }],
        };

        self.add_inductive(nodup_decl)?;
        Ok(())
    }

    /// Register the `Multiset` quotient type and its core operations.
    fn init_multiset_core(&mut self) -> Result<(), EnvError> {
        let u = Name::from_string("u");
        let u_level = Level::param(u.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        // `List α : Type u = Sort (u+1)`, so the quotient lives at `u+1`.
        let lvl_su = Level::succ(u_level.clone());

        let list_const = Expr::const_(Name::from_string("List"), vec![u_level.clone()]);
        let list_cons = Expr::const_(Name::from_string("List.cons"), vec![u_level.clone()]);
        let list_nil = Expr::const_(Name::from_string("List.nil"), vec![u_level.clone()]);
        let perm_const = Expr::const_(Name::from_string("List.Perm"), vec![u_level.clone()]);
        let perm_cons = Expr::const_(Name::from_string("List.Perm.cons"), vec![u_level.clone()]);
        let multiset_const = Expr::const_(Name::from_string("Multiset"), vec![u_level.clone()]);

        // Quot.* constants. Note: in `Quot.mk` the relation `r` is EXPLICIT,
        // whereas in `Quot.lift`/`Quot.sound` it is IMPLICIT.
        let quot = Expr::const_(Name::from_string("Quot"), vec![lvl_su.clone()]);
        let quot_mk = Expr::const_(Name::from_string("Quot.mk"), vec![lvl_su.clone()]);
        // Quot.lift.{u v}: here the domain is `List α : Sort (u+1)` and the
        // codomain `Multiset α : Sort (u+1)`, so both universes are `u+1`.
        let quot_lift = Expr::const_(
            Name::from_string("Quot.lift"),
            vec![lvl_su.clone(), lvl_su.clone()],
        );
        let quot_sound = Expr::const_(Name::from_string("Quot.sound"), vec![lvl_su.clone()]);

        let list_of = |a: &Expr| Expr::app(list_const.clone(), a.clone());
        let nil_of = |a: &Expr| Expr::app(list_nil.clone(), a.clone());
        let cons_of = |a: &Expr, x: Expr, l: Expr| Expr::apps(list_cons.clone(), [a.clone(), x, l]);
        // `@List.Perm α` (the relation, partially applied to α).
        let perm_rel = |a: &Expr| Expr::app(perm_const.clone(), a.clone());
        let perm =
            |a: &Expr, l1: Expr, l2: Expr| Expr::apps(perm_const.clone(), [a.clone(), l1, l2]);
        // `Multiset α`
        let mset_of = |a: &Expr| Expr::app(multiset_const.clone(), a.clone());
        // `@Quot.{u+1} (List α) (@List.Perm α)` — the underlying quotient type.
        let quot_of = |a: &Expr| Expr::apps(quot.clone(), [list_of(a), perm_rel(a)]);
        // `@Quot.mk (List α) (@List.Perm α) l`
        let mk_of = |a: &Expr, l: Expr| Expr::apps(quot_mk.clone(), [list_of(a), perm_rel(a), l]);

        // ── Multiset : Type u → Type u := fun α => @Quot.{u+1} (List α) (Perm α)
        let multiset_type = Expr::pi(BinderInfo::Default, type_u.clone(), type_u.clone());
        let multiset_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let body = quot_of(&alpha);
            let e = b.mk_lam(alpha_id, BinderInfo::Default, type_u.clone(), body);
            b.finish(e)
        };
        self.add_decl(Declaration::Definition {
            name: Name::from_string("Multiset"),
            level_params: vec![u.clone()],
            type_: multiset_type,
            value: multiset_value,
            is_reducible: true,
        })?;

        // ── Multiset.nil : {α} → Multiset α := @Quot.mk _ (Perm α) (nil α) ──
        let multiset_nil_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let e = b.mk_pi(
                alpha_id,
                BinderInfo::Implicit,
                type_u.clone(),
                mset_of(&alpha),
            );
            b.finish(e)
        };
        let multiset_nil_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let body = mk_of(&alpha, nil_of(&alpha));
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), body);
            b.finish(e)
        };
        self.add_decl(Declaration::Definition {
            name: Name::from_string("Multiset.nil"),
            level_params: vec![u.clone()],
            type_: multiset_nil_type,
            value: multiset_nil_value,
            is_reducible: true,
        })?;

        // ── Multiset.cons : {α} → α → Multiset α → Multiset α ───────────────
        // = fun α a s => @Quot.lift (List α) (Perm α) (Multiset α)
        //     (fun l => @Quot.mk _ (Perm α) (a :: l))
        //     (fun l1 l2 h => @Quot.sound _ (Perm α) (a::l1) (a::l2)
        //                       (@List.Perm.cons α a l1 l2 h))
        //     s
        let multiset_cons_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, _a) = b.fresh_local(alpha.clone());
            let (s_id, _s) = b.fresh_local(mset_of(&alpha));
            let e = mset_of(&alpha);
            let e = b.mk_pi(s_id, BinderInfo::Default, mset_of(&alpha), e);
            let e = b.mk_pi(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        let multiset_cons_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (s_id, s) = b.fresh_local(mset_of(&alpha));

            // f := fun (l : List α) => @Quot.mk _ (Perm α) (a :: l)
            let f = {
                let (l_id, l) = b.fresh_local(list_of(&alpha));
                let body = mk_of(&alpha, cons_of(&alpha, a.clone(), l.clone()));
                b.mk_lam(l_id, BinderInfo::Default, list_of(&alpha), body)
            };

            // h := fun (l1 l2 : List α) (hp : Perm α l1 l2) =>
            //        @Quot.sound (List α) (Perm α) (a::l1) (a::l2)
            //          (@List.Perm.cons α a l1 l2 hp)
            let h = {
                let (l1_id, l1) = b.fresh_local(list_of(&alpha));
                let (l2_id, l2) = b.fresh_local(list_of(&alpha));
                let (hp_id, hp) = b.fresh_local(perm(&alpha, l1.clone(), l2.clone()));
                // @List.Perm.cons α a l1 l2 hp : Perm (a::l1) (a::l2)
                let perm_cons_app = Expr::apps(
                    perm_cons.clone(),
                    [alpha.clone(), a.clone(), l1.clone(), l2.clone(), hp.clone()],
                );
                // @Quot.sound (List α) (Perm α) (a::l1) (a::l2) perm_cons_app
                let body = Expr::apps(
                    quot_sound.clone(),
                    [
                        list_of(&alpha),
                        perm_rel(&alpha),
                        cons_of(&alpha, a.clone(), l1.clone()),
                        cons_of(&alpha, a.clone(), l2.clone()),
                        perm_cons_app,
                    ],
                );
                let e = b.mk_lam(
                    hp_id,
                    BinderInfo::Default,
                    perm(&alpha, l1.clone(), l2.clone()),
                    body,
                );
                let e = b.mk_lam(l2_id, BinderInfo::Default, list_of(&alpha), e);
                b.mk_lam(l1_id, BinderInfo::Default, list_of(&alpha), e)
            };

            // @Quot.lift (List α) (Perm α) (Multiset α) f h s
            let body = Expr::apps(
                quot_lift.clone(),
                [
                    list_of(&alpha),
                    perm_rel(&alpha),
                    mset_of(&alpha),
                    f,
                    h,
                    s.clone(),
                ],
            );
            let e = b.mk_lam(s_id, BinderInfo::Default, mset_of(&alpha), body);
            let e = b.mk_lam(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Definition {
            name: Name::from_string("Multiset.cons"),
            level_params: vec![u.clone()],
            type_: multiset_cons_type,
            value: multiset_cons_value,
            is_reducible: true,
        })?;

        Ok(())
    }

    /// Register `List.mem_cons_iff`, `List.Perm.mem_iff`, `Multiset.Mem`, the
    /// `Membership` instance, and `Multiset.mem_cons_self`.
    fn init_multiset_mem(&mut self) -> Result<(), EnvError> {
        let u = Name::from_string("u");
        let u_level = Level::param(u.clone());
        let type_u = Expr::from_kind(ExprKind::Sort(Level::succ(u_level.clone())));
        let prop = Expr::from_kind(ExprKind::Sort(Level::zero()));
        let lvl_su = Level::succ(u_level.clone());

        let list_const = Expr::const_(Name::from_string("List"), vec![u_level.clone()]);
        let list_cons = Expr::const_(Name::from_string("List.cons"), vec![u_level.clone()]);
        let mem_const = Expr::const_(Name::from_string("List.Mem"), vec![u_level.clone()]);
        let mem_head = Expr::const_(Name::from_string("List.Mem.head"), vec![u_level.clone()]);
        let mem_tail = Expr::const_(Name::from_string("List.Mem.tail"), vec![u_level.clone()]);
        // `List.Mem.casesOn.{u}` — `List.Mem` is a `Prop`, so its `casesOn`
        // only eliminates into `Prop` (small elimination) and carries the
        // single inductive level `u` (no separate motive universe).
        let mem_cases = Expr::const_(Name::from_string("List.Mem.casesOn"), vec![u_level.clone()]);
        // `List.casesOn.{1,u}` — computing a `Prop` (Sort 0 ⇒ motive type
        // `List α → Sort 1`, w = 1).
        let list_cases = Expr::const_(
            Name::from_string("List.casesOn"),
            vec![Level::succ(Level::zero()), u_level.clone()],
        );
        let perm_const = Expr::const_(Name::from_string("List.Perm"), vec![u_level.clone()]);
        let perm_rec = Expr::const_(Name::from_string("List.Perm.rec"), vec![u_level.clone()]);
        let multiset_const = Expr::const_(Name::from_string("Multiset"), vec![u_level.clone()]);

        let or_const = Expr::const_(Name::from_string("Or"), vec![]);
        let or_inl = Expr::const_(Name::from_string("Or.inl"), vec![]);
        let or_inr = Expr::const_(Name::from_string("Or.inr"), vec![]);
        // `Or` is a `Prop` with no level params; its small-elimination
        // `Or.casesOn` into `Prop` carries no level arguments.
        let or_cases = Expr::const_(Name::from_string("Or.casesOn"), vec![]);
        // `Eq` over `α`-values: `α : Type u = Sort (u+1)`, so the equality lives
        // at level `u+1` (`Eq.{u+1} {β : Sort (u+1)} ...` with `β := α`).
        let eq_const = Expr::const_(Name::from_string("Eq"), vec![lvl_su.clone()]);
        let eq_refl = Expr::const_(Name::from_string("Eq.refl"), vec![lvl_su.clone()]);
        // `Eq.rec.{0,u+1}` — eliminating an `Eq` of `α`-values into a `Prop`.
        let eq_rec = Expr::const_(
            Name::from_string("Eq.rec"),
            vec![Level::zero(), lvl_su.clone()],
        );

        let iff_const = Expr::const_(Name::from_string("Iff"), vec![]);
        let iff_intro = Expr::const_(Name::from_string("Iff.intro"), vec![]);
        let iff_mp = Expr::const_(Name::from_string("Iff.mp"), vec![]);
        let iff_mpr = Expr::const_(Name::from_string("Iff.mpr"), vec![]);
        let propext = Expr::const_(Name::from_string("propext"), vec![]);

        let quot_lift = Expr::const_(
            Name::from_string("Quot.lift"),
            vec![lvl_su.clone(), Level::succ(Level::zero())],
        );

        let list_of = |a: &Expr| Expr::app(list_const.clone(), a.clone());
        let cons_of = |a: &Expr, x: Expr, l: Expr| Expr::apps(list_cons.clone(), [a.clone(), x, l]);
        let mem = |a: &Expr, x: Expr, l: Expr| Expr::apps(mem_const.clone(), [a.clone(), x, l]);
        let perm_rel = |a: &Expr| Expr::app(perm_const.clone(), a.clone());
        let perm =
            |a: &Expr, l1: Expr, l2: Expr| Expr::apps(perm_const.clone(), [a.clone(), l1, l2]);
        let mset_of = |a: &Expr| Expr::app(multiset_const.clone(), a.clone());
        let or_ = |p: Expr, q: Expr| Expr::apps(or_const.clone(), [p, q]);
        let eq_ = |a: &Expr, x: Expr, y: Expr| Expr::apps(eq_const.clone(), [a.clone(), x, y]);
        let iff = |p: Expr, q: Expr| Expr::apps(iff_const.clone(), [p, q]);

        // ════════════════════════════════════════════════════════════════
        // List.mem_cons_iff {α} (a x : α) (l : List α) :
        //     Iff (Mem a (x :: l)) (Or (Eq a x) (Mem a l))
        // ════════════════════════════════════════════════════════════════
        let mem_cons_iff_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (x_id, x) = b.fresh_local(alpha.clone());
            let (l_id, l) = b.fresh_local(list_of(&alpha));
            let lhs = mem(&alpha, a.clone(), cons_of(&alpha, x.clone(), l.clone()));
            let rhs = or_(
                eq_(&alpha, a.clone(), x.clone()),
                mem(&alpha, a.clone(), l.clone()),
            );
            let concl = iff(lhs, rhs);
            let e = b.mk_pi(l_id, BinderInfo::Default, list_of(&alpha), concl);
            let e = b.mk_pi(x_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_pi(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        let mem_cons_iff_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (x_id, x) = b.fresh_local(alpha.clone());
            let (l_id, l) = b.fresh_local(list_of(&alpha));

            let lhs = mem(&alpha, a.clone(), cons_of(&alpha, x.clone(), l.clone()));
            let rhs = or_(
                eq_(&alpha, a.clone(), x.clone()),
                mem(&alpha, a.clone(), l.clone()),
            );

            // P : List α → Prop :=
            //   fun lst => List.casesOn.{1,u} α (fun _ => Prop) (Mem a l)
            //                (fun hd tl => Or (Eq a hd) (Mem a tl)) lst
            // (the nil branch is unreachable for a `Mem`, any Prop works.)
            let p_fun = {
                let (lst_id, lst) = b.fresh_local(list_of(&alpha));
                // motive for List.casesOn: fun (_ : List α) => Prop
                let cm = {
                    let (z_id, _z) = b.fresh_local(list_of(&alpha));
                    b.mk_lam(z_id, BinderInfo::Default, list_of(&alpha), prop.clone())
                };
                // cons branch: fun (hd : α) (tl : List α) => Or (Eq a hd) (Mem a tl)
                let cons_branch = {
                    let (hd_id, hd) = b.fresh_local(alpha.clone());
                    let (tl_id, tl) = b.fresh_local(list_of(&alpha));
                    let body = or_(
                        eq_(&alpha, a.clone(), hd.clone()),
                        mem(&alpha, a.clone(), tl.clone()),
                    );
                    let e = b.mk_lam(tl_id, BinderInfo::Default, list_of(&alpha), body);
                    b.mk_lam(hd_id, BinderInfo::Default, alpha.clone(), e)
                };
                // Lean-faithful casesOn order: motive, major, then minors.
                let body = Expr::apps(
                    list_cases.clone(),
                    [
                        alpha.clone(),
                        cm,
                        lst.clone(),
                        mem(&alpha, a.clone(), l.clone()), // nil branch (unreachable)
                        cons_branch,
                    ],
                );
                b.mk_lam(lst_id, BinderInfo::Default, list_of(&alpha), body)
            };

            // forward : Mem a (x::l) → Or (Eq a x) (Mem a l)
            //   = fun hm => List.Mem.casesOn α a
            //         (motive := fun lst _ => P lst)
            //         (head := fun as => Or.inl (Eq a a) (Mem a as) (Eq.refl a))
            //         (tail := fun b' as h => Or.inr (Eq a b') (Mem a as) h)
            //         (x::l) hm
            let forward = {
                let (hm_id, hm) = b.fresh_local(lhs.clone());
                // motive: fun (lst : List α) (_ : Mem a lst) => P lst
                let motive = {
                    let (m_lst_id, m_lst) = b.fresh_local(list_of(&alpha));
                    let (m_h_id, _m_h) = b.fresh_local(mem(&alpha, a.clone(), m_lst.clone()));
                    let body = Expr::app(p_fun.clone(), m_lst.clone());
                    let e = b.mk_lam(
                        m_h_id,
                        BinderInfo::Default,
                        mem(&alpha, a.clone(), m_lst.clone()),
                        body,
                    );
                    b.mk_lam(m_lst_id, BinderInfo::Default, list_of(&alpha), e)
                };
                // head minor: fun (as : List α) => Or.inl (Eq a a) (Mem a as) (Eq.refl a)
                let head_minor = {
                    let (as_id, as_) = b.fresh_local(list_of(&alpha));
                    let refl = Expr::apps(eq_refl.clone(), [alpha.clone(), a.clone()]);
                    let body = Expr::apps(
                        or_inl.clone(),
                        [
                            eq_(&alpha, a.clone(), a.clone()),
                            mem(&alpha, a.clone(), as_.clone()),
                            refl,
                        ],
                    );
                    b.mk_lam(as_id, BinderInfo::Default, list_of(&alpha), body)
                };
                // tail minor: fun (b' : α) (as : List α) (h : Mem a as) =>
                //               Or.inr (Eq a b') (Mem a as) h
                let tail_minor = {
                    let (b2_id, b2) = b.fresh_local(alpha.clone());
                    let (as_id, as_) = b.fresh_local(list_of(&alpha));
                    let mem_a_as = mem(&alpha, a.clone(), as_.clone());
                    let (h_id, h) = b.fresh_local(mem_a_as.clone());
                    let body = Expr::apps(
                        or_inr.clone(),
                        [
                            eq_(&alpha, a.clone(), b2.clone()),
                            mem_a_as.clone(),
                            h.clone(),
                        ],
                    );
                    let e = b.mk_lam(h_id, BinderInfo::Default, mem_a_as, body);
                    let e = b.mk_lam(as_id, BinderInfo::Default, list_of(&alpha), e);
                    b.mk_lam(b2_id, BinderInfo::Default, alpha.clone(), e)
                };
                // Lean-faithful casesOn order: motive, indices, major, minors.
                let body = Expr::apps(
                    mem_cases.clone(),
                    [
                        alpha.clone(),
                        a.clone(),
                        motive,
                        cons_of(&alpha, x.clone(), l.clone()), // index l (implicit)
                        hm.clone(),
                        head_minor,
                        tail_minor,
                    ],
                );
                b.mk_lam(hm_id, BinderInfo::Default, lhs.clone(), body)
            };

            // backward : Or (Eq a x) (Mem a l) → Mem a (x::l)
            //   = fun ho => Or.casesOn (Eq a x) (Mem a l)
            //        (motive := fun _ => Mem a (x::l))
            //        (inl := fun he =>
            //            @Eq.rec α a (fun y _ => Mem a (y::l)) (Mem.head a l) x he)
            //        (inr := fun hm => Mem.tail a x l hm)
            //        ho
            let backward = {
                let (ho_id, ho) = b.fresh_local(rhs.clone());
                let goal = mem(&alpha, a.clone(), cons_of(&alpha, x.clone(), l.clone()));
                // Or.casesOn motive: fun (_ : Or (Eq a x) (Mem a l)) => Mem a (x::l)
                let or_motive = {
                    let (z_id, _z) = b.fresh_local(rhs.clone());
                    b.mk_lam(z_id, BinderInfo::Default, rhs.clone(), goal.clone())
                };
                // inl: fun (he : Eq a x) =>
                //        @Eq.rec α a (fun (y:α)(_:Eq a y) => Mem a (y::l))
                //          (@List.Mem.head α a l) x he
                let inl_minor = {
                    let (he_id, he) = b.fresh_local(eq_(&alpha, a.clone(), x.clone()));
                    // Eq.rec motive: fun (y : α) (_ : Eq a y) => Mem a (y::l)
                    let rec_motive = {
                        let (y_id, y) = b.fresh_local(alpha.clone());
                        let (eh_id, _eh) = b.fresh_local(eq_(&alpha, a.clone(), y.clone()));
                        let body = mem(&alpha, a.clone(), cons_of(&alpha, y.clone(), l.clone()));
                        let e = b.mk_lam(
                            eh_id,
                            BinderInfo::Default,
                            eq_(&alpha, a.clone(), y.clone()),
                            body,
                        );
                        b.mk_lam(y_id, BinderInfo::Default, alpha.clone(), e)
                    };
                    // refl_case : Mem a (a::l) = @List.Mem.head α a l
                    let refl_case =
                        Expr::apps(mem_head.clone(), [alpha.clone(), a.clone(), l.clone()]);
                    let body = Expr::apps(
                        eq_rec.clone(),
                        [
                            alpha.clone(),
                            a.clone(),
                            rec_motive,
                            refl_case,
                            x.clone(),
                            he.clone(),
                        ],
                    );
                    b.mk_lam(
                        he_id,
                        BinderInfo::Default,
                        eq_(&alpha, a.clone(), x.clone()),
                        body,
                    )
                };
                // inr: fun (hm : Mem a l) => @List.Mem.tail α a x l hm
                let inr_minor = {
                    let mem_a_l = mem(&alpha, a.clone(), l.clone());
                    let (hm2_id, hm2) = b.fresh_local(mem_a_l.clone());
                    let body = Expr::apps(
                        mem_tail.clone(),
                        [alpha.clone(), a.clone(), x.clone(), l.clone(), hm2.clone()],
                    );
                    b.mk_lam(hm2_id, BinderInfo::Default, mem_a_l, body)
                };
                // Lean-faithful casesOn order: motive, major, then minors.
                let body = Expr::apps(
                    or_cases.clone(),
                    [
                        eq_(&alpha, a.clone(), x.clone()),
                        mem(&alpha, a.clone(), l.clone()),
                        or_motive,
                        ho.clone(),
                        inl_minor,
                        inr_minor,
                    ],
                );
                b.mk_lam(ho_id, BinderInfo::Default, rhs.clone(), body)
            };

            // @Iff.intro (Mem a (x::l)) (Or (Eq a x) (Mem a l)) forward backward
            let body = Expr::apps(
                iff_intro.clone(),
                [lhs.clone(), rhs.clone(), forward, backward],
            );
            let e = b.mk_lam(l_id, BinderInfo::Default, list_of(&alpha), body);
            let e = b.mk_lam(x_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_lam(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Theorem {
            name: Name::from_string("List.mem_cons_iff"),
            level_params: vec![u.clone()],
            type_: mem_cons_iff_type,
            value: mem_cons_iff_value,
        })?;

        // ════════════════════════════════════════════════════════════════
        // List.mem_cons {α} {a b : α} {l : List α} :
        //     a ∈ b :: l ↔ a = b ∨ a ∈ l
        // ════════════════════════════════════════════════════════════════
        // Lean 4 v4.30.0-rc2 (`Init/Data/List/Basic.lean`) states `mem_cons`
        // through the `Membership` instance (`a ∈ …` desugars to
        // `Membership.mem … a`, collection-first since Lean v4.9) with a, b, l
        // ALL IMPLICIT — distinct from the hand-rolled `List.mem_cons_iff`
        // above, which is raw-`List.Mem` with EXPLICIT `(a x : α) (l)`. AY's
        // LRAT soundness proofs cite the genuine core `List.mem_cons`, so it
        // must carry Lean's exact statement form or a positional application
        // would bind the wrong arguments.
        //
        // The proof reuses `List.mem_cons_iff`: its inferred type is the raw
        // `List.Mem` iff, and the kernel converges it to the `Membership.mem`
        // statement above via the reducible `List.instMembership` (the identical
        // convergence that lets `List.mem_cons_self`/`mem_cons_of_mem` be stated
        // in `Membership.mem` form yet proved with raw `List.Mem` constructors).
        // Constructive — closure is `List.mem_cons_iff` + `List.instMembership`,
        // no domain axiom.
        {
            let inst_membership_const = Expr::const_(
                Name::from_string("List.instMembership"),
                vec![u_level.clone()],
            );
            let membership_mem_const = Expr::const_(
                Name::from_string("Membership.mem"),
                vec![u_level.clone(), u_level.clone()],
            );
            // `@Membership.mem α (List α) (@List.instMembership α) l a`
            let mem_via_inst = |alpha: &Expr, a: Expr, l: Expr| {
                Expr::apps(
                    membership_mem_const.clone(),
                    [
                        alpha.clone(),
                        Expr::app(list_const.clone(), alpha.clone()),
                        Expr::app(inst_membership_const.clone(), alpha.clone()),
                        l,
                        a,
                    ],
                )
            };
            let mem_cons_iff_c = Expr::const_(
                Name::from_string("List.mem_cons_iff"),
                vec![u_level.clone()],
            );

            let mem_cons_type = {
                let mut b = EnvDeclBuilder::new();
                let (alpha_id, alpha) = b.fresh_local(type_u.clone());
                let (a_id, a) = b.fresh_local(alpha.clone());
                let (bb_id, bb) = b.fresh_local(alpha.clone());
                let (l_id, l) = b.fresh_local(list_of(&alpha));
                let lhs = mem_via_inst(&alpha, a.clone(), cons_of(&alpha, bb.clone(), l.clone()));
                let rhs = or_(
                    eq_(&alpha, a.clone(), bb.clone()),
                    mem_via_inst(&alpha, a.clone(), l.clone()),
                );
                let concl = iff(lhs, rhs);
                let e = b.mk_pi(l_id, BinderInfo::Implicit, list_of(&alpha), concl);
                let e = b.mk_pi(bb_id, BinderInfo::Implicit, alpha.clone(), e);
                let e = b.mk_pi(a_id, BinderInfo::Implicit, alpha.clone(), e);
                let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
                b.finish(e)
            };
            let mem_cons_value = {
                let mut b = EnvDeclBuilder::new();
                let (alpha_id, alpha) = b.fresh_local(type_u.clone());
                let (a_id, a) = b.fresh_local(alpha.clone());
                let (bb_id, bb) = b.fresh_local(alpha.clone());
                let (l_id, l) = b.fresh_local(list_of(&alpha));
                // @List.mem_cons_iff α a b l  (explicit `(a x l)` ← `a b l`)
                let body = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), bb.clone(), l.clone()],
                );
                let e = b.mk_lam(l_id, BinderInfo::Implicit, list_of(&alpha), body);
                let e = b.mk_lam(bb_id, BinderInfo::Implicit, alpha.clone(), e);
                let e = b.mk_lam(a_id, BinderInfo::Implicit, alpha.clone(), e);
                let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
                b.finish(e)
            };
            self.add_decl(Declaration::Theorem {
                name: Name::from_string("List.mem_cons"),
                level_params: vec![u.clone()],
                type_: mem_cons_type,
                value: mem_cons_value,
            })?;
        }

        // ════════════════════════════════════════════════════════════════
        // Small reusable Or-congruence helpers (registered as theorems so the
        // Perm recursion below stays compact). Both are constructive.
        // ════════════════════════════════════════════════════════════════
        //
        // Or.iff_congr_right' {p q r : Prop} : Iff q r → Iff (Or p q) (Or p r)
        let or_iff_right = Name::from_string("Or.iff_congr_right'");
        {
            let or_iff_right_type = {
                let mut b = EnvDeclBuilder::new();
                let (p_id, p) = b.fresh_local(prop.clone());
                let (q_id, q) = b.fresh_local(prop.clone());
                let (r_id, r) = b.fresh_local(prop.clone());
                let (h_id, _h) = b.fresh_local(iff(q.clone(), r.clone()));
                let concl = iff(or_(p.clone(), q.clone()), or_(p.clone(), r.clone()));
                let e = b.mk_pi(h_id, BinderInfo::Default, iff(q.clone(), r.clone()), concl);
                let e = b.mk_pi(r_id, BinderInfo::Implicit, prop.clone(), e);
                let e = b.mk_pi(q_id, BinderInfo::Implicit, prop.clone(), e);
                let e = b.mk_pi(p_id, BinderInfo::Implicit, prop.clone(), e);
                b.finish(e)
            };
            let or_iff_right_value = {
                let mut b = EnvDeclBuilder::new();
                let (p_id, p) = b.fresh_local(prop.clone());
                let (q_id, q) = b.fresh_local(prop.clone());
                let (r_id, r) = b.fresh_local(prop.clone());
                let (h_id, h) = b.fresh_local(iff(q.clone(), r.clone()));
                let opq = or_(p.clone(), q.clone());
                let opr = or_(p.clone(), r.clone());
                // map : (P → Q) form built from Or.casesOn
                // fwd : Or p q → Or p r
                let fwd = Self::build_or_map_right(
                    &mut b,
                    &p,
                    &q,
                    &r,
                    &opr,
                    Expr::apps(iff_mp.clone(), [q.clone(), r.clone(), h.clone()]),
                    &or_inl,
                    &or_inr,
                    &or_cases,
                );
                // bwd : Or p r → Or p q
                let bwd = Self::build_or_map_right(
                    &mut b,
                    &p,
                    &r,
                    &q,
                    &opq,
                    Expr::apps(iff_mpr.clone(), [q.clone(), r.clone(), h.clone()]),
                    &or_inl,
                    &or_inr,
                    &or_cases,
                );
                let body = Expr::apps(iff_intro.clone(), [opq.clone(), opr.clone(), fwd, bwd]);
                let e = b.mk_lam(h_id, BinderInfo::Default, iff(q.clone(), r.clone()), body);
                let e = b.mk_lam(r_id, BinderInfo::Implicit, prop.clone(), e);
                let e = b.mk_lam(q_id, BinderInfo::Implicit, prop.clone(), e);
                let e = b.mk_lam(p_id, BinderInfo::Implicit, prop.clone(), e);
                b.finish(e)
            };
            self.add_decl(Declaration::Theorem {
                name: or_iff_right.clone(),
                level_params: vec![],
                type_: or_iff_right_type,
                value: or_iff_right_value,
            })?;
        }

        // Or.left_comm' {p q r : Prop} : Iff (Or p (Or q r)) (Or q (Or p r))
        let or_left_comm = Name::from_string("Or.left_comm'");
        {
            let lhs_of = |p: &Expr, q: &Expr, r: &Expr| or_(p.clone(), or_(q.clone(), r.clone()));
            let rhs_of = |p: &Expr, q: &Expr, r: &Expr| or_(q.clone(), or_(p.clone(), r.clone()));
            let olc_type = {
                let mut b = EnvDeclBuilder::new();
                let (p_id, p) = b.fresh_local(prop.clone());
                let (q_id, q) = b.fresh_local(prop.clone());
                let (r_id, r) = b.fresh_local(prop.clone());
                let concl = iff(lhs_of(&p, &q, &r), rhs_of(&p, &q, &r));
                let e = b.mk_pi(r_id, BinderInfo::Implicit, prop.clone(), concl);
                let e = b.mk_pi(q_id, BinderInfo::Implicit, prop.clone(), e);
                let e = b.mk_pi(p_id, BinderInfo::Implicit, prop.clone(), e);
                b.finish(e)
            };
            let olc_value = {
                let mut b = EnvDeclBuilder::new();
                let (p_id, p) = b.fresh_local(prop.clone());
                let (q_id, q) = b.fresh_local(prop.clone());
                let (r_id, r) = b.fresh_local(prop.clone());
                let lhs = lhs_of(&p, &q, &r);
                let rhs = rhs_of(&p, &q, &r);
                // both directions are the same shape with p,q swapped.
                let fwd = Self::build_or_left_comm_map(
                    &mut b, &p, &q, &r, &rhs, &or_inl, &or_inr, &or_cases,
                );
                let bwd = Self::build_or_left_comm_map(
                    &mut b, &q, &p, &r, &lhs, &or_inl, &or_inr, &or_cases,
                );
                let body = Expr::apps(iff_intro.clone(), [lhs.clone(), rhs.clone(), fwd, bwd]);
                let e = b.mk_lam(r_id, BinderInfo::Implicit, prop.clone(), body);
                let e = b.mk_lam(q_id, BinderInfo::Implicit, prop.clone(), e);
                let e = b.mk_lam(p_id, BinderInfo::Implicit, prop.clone(), e);
                b.finish(e)
            };
            self.add_decl(Declaration::Theorem {
                name: or_left_comm.clone(),
                level_params: vec![],
                type_: olc_type,
                value: olc_value,
            })?;
        }

        // ════════════════════════════════════════════════════════════════
        // List.Perm.mem_iff {α} (a : α) {l1 l2 : List α} :
        //     Perm l1 l2 → Iff (Mem a l1) (Mem a l2)
        // by List.Perm.rec with motive λ l1 l2 _ => Iff (Mem a l1) (Mem a l2).
        // ════════════════════════════════════════════════════════════════
        let iff_rfl = Expr::const_(Name::from_string("Iff.rfl"), vec![]);
        let iff_symm = Expr::const_(Name::from_string("Iff.symm"), vec![]);
        let iff_trans = Expr::const_(Name::from_string("Iff.trans"), vec![]);
        let mem_cons_iff_c = Expr::const_(
            Name::from_string("List.mem_cons_iff"),
            vec![u_level.clone()],
        );
        let or_iff_right_c = Expr::const_(or_iff_right.clone(), vec![]);
        let or_left_comm_c = Expr::const_(or_left_comm.clone(), vec![]);
        let list_nil = Expr::const_(Name::from_string("List.nil"), vec![u_level.clone()]);
        let nil_of = |a: &Expr| Expr::app(list_nil.clone(), a.clone());

        let perm_mem_iff_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (l1_id, l1) = b.fresh_local(list_of(&alpha));
            let (l2_id, l2) = b.fresh_local(list_of(&alpha));
            let (hp_id, _hp) = b.fresh_local(perm(&alpha, l1.clone(), l2.clone()));
            let concl = iff(
                mem(&alpha, a.clone(), l1.clone()),
                mem(&alpha, a.clone(), l2.clone()),
            );
            let e = b.mk_pi(
                hp_id,
                BinderInfo::Default,
                perm(&alpha, l1.clone(), l2.clone()),
                concl,
            );
            let e = b.mk_pi(l2_id, BinderInfo::Implicit, list_of(&alpha), e);
            let e = b.mk_pi(l1_id, BinderInfo::Implicit, list_of(&alpha), e);
            let e = b.mk_pi(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        let perm_mem_iff_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());

            // motive : λ (m1 m2 : List α) (_ : Perm m1 m2) => Iff (Mem a m1) (Mem a m2)
            let motive = {
                let (m1_id, m1) = b.fresh_local(list_of(&alpha));
                let (m2_id, m2) = b.fresh_local(list_of(&alpha));
                let (mp_id, _mp) = b.fresh_local(perm(&alpha, m1.clone(), m2.clone()));
                let body = iff(
                    mem(&alpha, a.clone(), m1.clone()),
                    mem(&alpha, a.clone(), m2.clone()),
                );
                let e = b.mk_lam(
                    mp_id,
                    BinderInfo::Default,
                    perm(&alpha, m1.clone(), m2.clone()),
                    body,
                );
                let e = b.mk_lam(m2_id, BinderInfo::Default, list_of(&alpha), e);
                b.mk_lam(m1_id, BinderInfo::Default, list_of(&alpha), e)
            };

            // nil minor : Iff (Mem a []) (Mem a [])  =  @Iff.rfl (Mem a [])
            let m_nil = Expr::app(iff_rfl.clone(), mem(&alpha, a.clone(), nil_of(&alpha)));

            // cons minor : λ (x : α) (l1 l2 : List α) (hp : Perm l1 l2)
            //   (ih : Iff (Mem a l1) (Mem a l2)) =>
            //     Iff.trans (mem_cons_iff a x l1)
            //       (Iff.trans (Or.iff_congr_right' ih) (Iff.symm (mem_cons_iff a x l2)))
            // (binder order follows the Lean-faithful ctor: element first)
            let m_cons = {
                let (cx_id, cx) = b.fresh_local(alpha.clone());
                let (cl1_id, cl1) = b.fresh_local(list_of(&alpha));
                let (cl2_id, cl2) = b.fresh_local(list_of(&alpha));
                let (chp_id, _chp) = b.fresh_local(perm(&alpha, cl1.clone(), cl2.clone()));
                let ih_ty = iff(
                    mem(&alpha, a.clone(), cl1.clone()),
                    mem(&alpha, a.clone(), cl2.clone()),
                );
                let (ih_id, ih) = b.fresh_local(ih_ty.clone());

                let mem_xc1 = mem(&alpha, a.clone(), cons_of(&alpha, cx.clone(), cl1.clone()));
                let mem_xc2 = mem(&alpha, a.clone(), cons_of(&alpha, cx.clone(), cl2.clone()));
                let eqax = eq_(&alpha, a.clone(), cx.clone());
                let or1 = or_(eqax.clone(), mem(&alpha, a.clone(), cl1.clone()));
                let or2 = or_(eqax.clone(), mem(&alpha, a.clone(), cl2.clone()));

                // mci1 : Iff (Mem a (x::l1)) (Or (Eq a x) (Mem a l1))
                let mci1 = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), cx.clone(), cl1.clone()],
                );
                // mci2 : Iff (Mem a (x::l2)) (Or (Eq a x) (Mem a l2))
                let mci2 = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), cx.clone(), cl2.clone()],
                );
                // mci2_symm : Iff (Or (Eq a x) (Mem a l2)) (Mem a (x::l2))
                let mci2_symm = Expr::apps(iff_symm.clone(), [mem_xc2.clone(), or2.clone(), mci2]);
                // or_cong : Iff (Or (Eq a x)(Mem a l1)) (Or (Eq a x)(Mem a l2))
                //   = @Or.iff_congr_right' (Eq a x) (Mem a l1) (Mem a l2) ih
                let or_cong = Expr::apps(
                    or_iff_right_c.clone(),
                    [
                        eqax.clone(),
                        mem(&alpha, a.clone(), cl1.clone()),
                        mem(&alpha, a.clone(), cl2.clone()),
                        ih.clone(),
                    ],
                );
                // inner = Iff.trans or_cong mci2_symm : Iff or1 (Mem a (x::l2))
                let inner = Expr::apps(
                    iff_trans.clone(),
                    [
                        or1.clone(),
                        or2.clone(),
                        mem_xc2.clone(),
                        or_cong,
                        mci2_symm,
                    ],
                );
                // body = Iff.trans mci1 inner : Iff (Mem a (x::l1)) (Mem a (x::l2))
                let body = Expr::apps(
                    iff_trans.clone(),
                    [mem_xc1.clone(), or1.clone(), mem_xc2.clone(), mci1, inner],
                );
                let e = b.mk_lam(ih_id, BinderInfo::Default, ih_ty, body);
                let e = b.mk_lam(
                    chp_id,
                    BinderInfo::Default,
                    perm(&alpha, cl1.clone(), cl2.clone()),
                    e,
                );
                let e = b.mk_lam(cl2_id, BinderInfo::Default, list_of(&alpha), e);
                let e = b.mk_lam(cl1_id, BinderInfo::Default, list_of(&alpha), e);
                b.mk_lam(cx_id, BinderInfo::Default, alpha.clone(), e)
            };

            // swap minor : λ (x y : α) (l : List α) =>
            //   Iff (Mem a (y::x::l)) (Mem a (x::y::l))
            // Unfold both sides via mem_cons_iff (twice) and rotate the first
            // two disjuncts with Or.left_comm'.
            let m_swap = {
                let (sx_id, sx) = b.fresh_local(alpha.clone());
                let (sy_id, sy) = b.fresh_local(alpha.clone());
                let (sl_id, sl) = b.fresh_local(list_of(&alpha));
                let mem_a_l = mem(&alpha, a.clone(), sl.clone());
                let eqay = eq_(&alpha, a.clone(), sy.clone());
                let eqax = eq_(&alpha, a.clone(), sx.clone());

                let yxl = cons_of(&alpha, sy.clone(), cons_of(&alpha, sx.clone(), sl.clone()));
                let xyl = cons_of(&alpha, sx.clone(), cons_of(&alpha, sy.clone(), sl.clone()));
                let xl = cons_of(&alpha, sx.clone(), sl.clone());
                let yl = cons_of(&alpha, sy.clone(), sl.clone());

                let mem_yxl = mem(&alpha, a.clone(), yxl.clone());
                let mem_xyl = mem(&alpha, a.clone(), xyl.clone());
                let mem_xl = mem(&alpha, a.clone(), xl.clone());
                let mem_yl = mem(&alpha, a.clone(), yl.clone());

                // Layer-1 iffs:
                // A: Mem (y::x::l) ↔ Or (Eq a y) (Mem (x::l))
                let mci_y = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), sy.clone(), xl.clone()],
                );
                let or_y_xl = or_(eqay.clone(), mem_xl.clone());
                // inner-right congruence: Mem (x::l) ↔ Or (Eq a x)(Mem l) via mci_x
                let mci_x = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), sx.clone(), sl.clone()],
                );
                let or_x_l = or_(eqax.clone(), mem_a_l.clone());
                // cong_y : Or (Eq a y)(Mem (x::l)) ↔ Or (Eq a y)(Or (Eq a x)(Mem l))
                let cong_y = Expr::apps(
                    or_iff_right_c.clone(),
                    [eqay.clone(), mem_xl.clone(), or_x_l.clone(), mci_x.clone()],
                );
                let or_y_xl2 = or_(eqay.clone(), or_x_l.clone());
                // stepA = trans mci_y cong_y : Mem (y::x::l) ↔ Or(Eq a y)(Or(Eq a x)(Mem l))
                let step_a = Expr::apps(
                    iff_trans.clone(),
                    [
                        mem_yxl.clone(),
                        or_y_xl.clone(),
                        or_y_xl2.clone(),
                        mci_y,
                        cong_y,
                    ],
                );

                // rotate : Or(Eq a y)(Or(Eq a x)(Mem l)) ↔ Or(Eq a x)(Or(Eq a y)(Mem l))
                let or_x_yl2 = or_(eqax.clone(), or_(eqay.clone(), mem_a_l.clone()));
                let rotate = Expr::apps(
                    or_left_comm_c.clone(),
                    [eqay.clone(), eqax.clone(), mem_a_l.clone()],
                );
                // stepB = trans step_a rotate
                let step_b = Expr::apps(
                    iff_trans.clone(),
                    [
                        mem_yxl.clone(),
                        or_y_xl2.clone(),
                        or_x_yl2.clone(),
                        step_a,
                        rotate,
                    ],
                );

                // Now fold the RHS: Or(Eq a x)(Or(Eq a y)(Mem l)) ↔ Mem (x::y::l)
                // mci_y2 : Mem (y::l) ↔ Or (Eq a y)(Mem l)
                let mci_y2 = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), sy.clone(), sl.clone()],
                );
                let or_y_l = or_(eqay.clone(), mem_a_l.clone());
                // cong_x_sym : Or(Eq a x)(Or(Eq a y)(Mem l)) ↔ Or(Eq a x)(Mem (y::l))
                let cong_x = Expr::apps(
                    or_iff_right_c.clone(),
                    [
                        eqax.clone(),
                        or_y_l.clone(),
                        mem_yl.clone(),
                        Expr::apps(iff_symm.clone(), [mem_yl.clone(), or_y_l.clone(), mci_y2]),
                    ],
                );
                let or_x_yl = or_(eqax.clone(), mem_yl.clone());
                // stepC = trans step_b cong_x : Mem(y::x::l) ↔ Or(Eq a x)(Mem (y::l))
                let step_c = Expr::apps(
                    iff_trans.clone(),
                    [
                        mem_yxl.clone(),
                        or_x_yl2.clone(),
                        or_x_yl.clone(),
                        step_b,
                        cong_x,
                    ],
                );
                // mci_xy_sym : Or(Eq a x)(Mem (y::l)) ↔ Mem (x::y::l)
                let mci_xy = Expr::apps(
                    mem_cons_iff_c.clone(),
                    [alpha.clone(), a.clone(), sx.clone(), yl.clone()],
                );
                let mci_xy_sym =
                    Expr::apps(iff_symm.clone(), [mem_xyl.clone(), or_x_yl.clone(), mci_xy]);
                // body = trans step_c mci_xy_sym : Mem(y::x::l) ↔ Mem(x::y::l)
                let body = Expr::apps(
                    iff_trans.clone(),
                    [
                        mem_yxl.clone(),
                        or_x_yl.clone(),
                        mem_xyl.clone(),
                        step_c,
                        mci_xy_sym,
                    ],
                );
                let e = b.mk_lam(sl_id, BinderInfo::Default, list_of(&alpha), body);
                let e = b.mk_lam(sy_id, BinderInfo::Default, alpha.clone(), e);
                b.mk_lam(sx_id, BinderInfo::Default, alpha.clone(), e)
            };

            // trans minor : λ (l1 l2 l3 : List α) (h1 : Perm l1 l2) (h2 : Perm l2 l3)
            //   (ih1 : Iff (Mem a l1)(Mem a l2)) (ih2 : Iff (Mem a l2)(Mem a l3)) =>
            //     Iff.trans ih1 ih2
            let m_trans = {
                let (t1_id, t1) = b.fresh_local(list_of(&alpha));
                let (t2_id, t2) = b.fresh_local(list_of(&alpha));
                let (t3_id, t3) = b.fresh_local(list_of(&alpha));
                let (th1_id, _th1) = b.fresh_local(perm(&alpha, t1.clone(), t2.clone()));
                let (th2_id, _th2) = b.fresh_local(perm(&alpha, t2.clone(), t3.clone()));
                let ih1_ty = iff(
                    mem(&alpha, a.clone(), t1.clone()),
                    mem(&alpha, a.clone(), t2.clone()),
                );
                let ih2_ty = iff(
                    mem(&alpha, a.clone(), t2.clone()),
                    mem(&alpha, a.clone(), t3.clone()),
                );
                let (ih1_id, ih1) = b.fresh_local(ih1_ty.clone());
                let (ih2_id, ih2) = b.fresh_local(ih2_ty.clone());
                let body = Expr::apps(
                    iff_trans.clone(),
                    [
                        mem(&alpha, a.clone(), t1.clone()),
                        mem(&alpha, a.clone(), t2.clone()),
                        mem(&alpha, a.clone(), t3.clone()),
                        ih1.clone(),
                        ih2.clone(),
                    ],
                );
                let e = b.mk_lam(ih2_id, BinderInfo::Default, ih2_ty, body);
                let e = b.mk_lam(ih1_id, BinderInfo::Default, ih1_ty, e);
                let e = b.mk_lam(
                    th2_id,
                    BinderInfo::Default,
                    perm(&alpha, t2.clone(), t3.clone()),
                    e,
                );
                let e = b.mk_lam(
                    th1_id,
                    BinderInfo::Default,
                    perm(&alpha, t1.clone(), t2.clone()),
                    e,
                );
                let e = b.mk_lam(t3_id, BinderInfo::Default, list_of(&alpha), e);
                let e = b.mk_lam(t2_id, BinderInfo::Default, list_of(&alpha), e);
                b.mk_lam(t1_id, BinderInfo::Default, list_of(&alpha), e)
            };

            // @List.Perm.rec α motive m_nil m_cons m_swap m_trans l1 l2 hp
            let (l1_id, l1) = b.fresh_local(list_of(&alpha));
            let (l2_id, l2) = b.fresh_local(list_of(&alpha));
            let (hp_id, hp) = b.fresh_local(perm(&alpha, l1.clone(), l2.clone()));
            let body = Expr::apps(
                perm_rec.clone(),
                [
                    alpha.clone(),
                    motive,
                    m_nil,
                    m_cons,
                    m_swap,
                    m_trans,
                    l1.clone(),
                    l2.clone(),
                    hp.clone(),
                ],
            );
            let e = b.mk_lam(
                hp_id,
                BinderInfo::Default,
                perm(&alpha, l1.clone(), l2.clone()),
                body,
            );
            let e = b.mk_lam(l2_id, BinderInfo::Implicit, list_of(&alpha), e);
            let e = b.mk_lam(l1_id, BinderInfo::Implicit, list_of(&alpha), e);
            let e = b.mk_lam(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Theorem {
            name: Name::from_string("List.Perm.mem_iff"),
            level_params: vec![u.clone()],
            type_: perm_mem_iff_type,
            value: perm_mem_iff_value,
        })?;

        // ════════════════════════════════════════════════════════════════
        // Multiset.Mem, Membership instance, Multiset.mem_cons_self
        // ════════════════════════════════════════════════════════════════
        let perm_mem_iff_c = Expr::const_(
            Name::from_string("List.Perm.mem_iff"),
            vec![u_level.clone()],
        );

        // Multiset.Mem : {α} → α → Multiset α → Prop
        //   = fun α a s => @Quot.lift (List α) (Perm α) Prop
        //       (fun l => Mem a l)
        //       (fun l1 l2 hp => @propext (Mem a l1) (Mem a l2)
        //           (@Iff.mp _ _ (mem_iff a l1 l2 hp))
        //           (@Iff.mpr _ _ (mem_iff a l1 l2 hp)))
        //       s
        let multiset_mem_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, _a) = b.fresh_local(alpha.clone());
            let (s_id, _s) = b.fresh_local(mset_of(&alpha));
            let e = prop.clone();
            let e = b.mk_pi(s_id, BinderInfo::Default, mset_of(&alpha), e);
            let e = b.mk_pi(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        let multiset_mem_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (s_id, s) = b.fresh_local(mset_of(&alpha));
            let f = {
                let (l_id, l) = b.fresh_local(list_of(&alpha));
                let body = mem(&alpha, a.clone(), l.clone());
                b.mk_lam(l_id, BinderInfo::Default, list_of(&alpha), body)
            };
            let h = {
                let (l1_id, l1) = b.fresh_local(list_of(&alpha));
                let (l2_id, l2) = b.fresh_local(list_of(&alpha));
                let (hp_id, hp) = b.fresh_local(perm(&alpha, l1.clone(), l2.clone()));
                let mem1 = mem(&alpha, a.clone(), l1.clone());
                let mem2 = mem(&alpha, a.clone(), l2.clone());
                let iff_term = Expr::apps(
                    perm_mem_iff_c.clone(),
                    [alpha.clone(), a.clone(), l1.clone(), l2.clone(), hp.clone()],
                );
                // Faithful `propext : {a b} → (a ↔ b) → a = b` takes the `Iff`
                // directly; `iff_term : Iff mem1 mem2` is already in hand.
                let body = Expr::apps(propext.clone(), [mem1, mem2, iff_term]);
                let e = b.mk_lam(
                    hp_id,
                    BinderInfo::Default,
                    perm(&alpha, l1.clone(), l2.clone()),
                    body,
                );
                let e = b.mk_lam(l2_id, BinderInfo::Default, list_of(&alpha), e);
                b.mk_lam(l1_id, BinderInfo::Default, list_of(&alpha), e)
            };
            let body = Expr::apps(
                quot_lift.clone(),
                [
                    list_of(&alpha),
                    perm_rel(&alpha),
                    prop.clone(),
                    f,
                    h,
                    s.clone(),
                ],
            );
            let e = b.mk_lam(s_id, BinderInfo::Default, mset_of(&alpha), body);
            let e = b.mk_lam(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Definition {
            name: Name::from_string("Multiset.Mem"),
            level_params: vec![u.clone()],
            type_: multiset_mem_type,
            value: multiset_mem_value,
            is_reducible: true,
        })?;

        // Multiset.instMembership : {α : Type u} → Membership α (Multiset α)
        //   := Membership.mk α (Multiset α)
        //        (fun (s : Multiset α) (a : α) => Multiset.Mem α a s)
        // Genuine `Membership.mk`-based definition (NOT an axiom) so
        // `Membership.mem α (Multiset α) inst s a` proj-reduces to
        // `Multiset.Mem a s` (which itself β/quot-reduces to `List.Mem`). The
        // `Membership` field is COLLECTION-first since Lean v4.9
        // (`mem : γ → α → Prop`, Init/Prelude.lean:1746), while Clean's
        // hand-rolled `Multiset.Mem` carrier stays element-first, so the
        // instance wraps it in the flip lambda — the same pattern Lean v4.30
        // itself uses for `List` (`instance : Membership α (List α) :=
        // ⟨fun l a => Mem a l⟩`). Shape correction to MATCH Lean; the kernel
        // re-checks the body.
        let inst_membership_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let membership_uu = Expr::const_(
                Name::from_string("Membership"),
                vec![u_level.clone(), u_level.clone()],
            );
            let e = Expr::apps(membership_uu, [alpha.clone(), mset_of(&alpha)]);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        let inst_membership_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let membership_mk = Expr::const_(
                Name::from_string("Membership.mk"),
                vec![u_level.clone(), u_level.clone()],
            );
            let mset_mem = Expr::const_(Name::from_string("Multiset.Mem"), vec![u_level.clone()]);
            // Collection-first flip lambda over the element-first carrier:
            //   fun (s : Multiset α) (a : α) => Multiset.Mem α a s
            let flip_mem = {
                let mut c = EnvDeclBuilder::child_of(&b);
                let (s_id, s) = c.fresh_local(mset_of(&alpha));
                let (a_id, a) = c.fresh_local(alpha.clone());
                let body = Expr::apps(mset_mem, [alpha.clone(), a.clone(), s.clone()]);
                let r = c.mk_lam(a_id, BinderInfo::Default, alpha.clone(), body);
                let r = c.mk_lam(s_id, BinderInfo::Default, mset_of(&alpha), r);
                c.finish_child(r)
            };
            let body = Expr::apps(membership_mk, [alpha.clone(), mset_of(&alpha), flip_mem]);
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), body);
            b.finish(e)
        };
        self.add_decl(Declaration::Definition {
            name: Name::from_string("Multiset.instMembership"),
            level_params: vec![u.clone()],
            type_: inst_membership_type,
            value: inst_membership_value,
            is_reducible: true,
        })?;
        // Register it as a `Membership` instance so `a ∈ s` (Multiset) resolves.
        self.register_instance(crate::env::KernelInstanceInfo {
            name: Name::from_string("Multiset.instMembership"),
            class_name: Name::from_string("Membership"),
            priority: crate::env::DEFAULT_INSTANCE_PRIORITY,
            type_: None,
            value: None,
        });

        // Multiset.mem_cons_self : {α} (a) (s) : Multiset.Mem a (Multiset.cons a s)
        // Proof by Quot.ind on s: on a representative `l`,
        //   Multiset.cons a (Quot.mk l) ≡ Quot.mk (a::l)   (β/quot-reduce)
        //   Multiset.Mem a (Quot.mk (a::l)) ≡ List.Mem a (a::l)
        // inhabited by @List.Mem.head α a l.
        self.register_multiset_mem_cons_self(&u, &u_level, &type_u)?;

        Ok(())
    }

    /// Build `fun (o : Or p q) => Or.casesOn o (fun hp => Or.inl p r (... )) ...`
    /// mapping the right disjunct of `Or p q` to `Or p r` using `qr : q → r`.
    /// Returns a term of type `Or p q → out` where `out = Or p r`.
    ///
    /// Allocates its binders from the caller's builder `b` (so fvar IDs stay
    /// globally unique) and returns an OPEN term that may still reference the
    /// caller's `p`/`q`/`r` fvars — the caller closes those with its own
    /// binders.
    #[allow(clippy::too_many_arguments)]
    fn build_or_map_right(
        b: &mut EnvDeclBuilder,
        p: &Expr,
        q: &Expr,
        r: &Expr,
        out: &Expr,
        qr: Expr,
        or_inl: &Expr,
        or_inr: &Expr,
        or_cases: &Expr,
    ) -> Expr {
        let or_pq = Expr::apps(
            Expr::const_(Name::from_string("Or"), vec![]),
            [p.clone(), q.clone()],
        );
        let (o_id, o) = b.fresh_local(or_pq.clone());
        // motive : fun (_ : Or p q) => Or p r
        let motive = {
            let (z_id, _z) = b.fresh_local(or_pq.clone());
            b.mk_lam(z_id, BinderInfo::Default, or_pq.clone(), out.clone())
        };
        // inl: fun (hp : p) => Or.inl p r hp
        let inl = {
            let (hp_id, hp) = b.fresh_local(p.clone());
            let body = Expr::apps(or_inl.clone(), [p.clone(), r.clone(), hp.clone()]);
            b.mk_lam(hp_id, BinderInfo::Default, p.clone(), body)
        };
        // inr: fun (hq : q) => Or.inr p r (qr hq)
        let inr = {
            let (hq_id, hq) = b.fresh_local(q.clone());
            let mapped = Expr::app(qr, hq.clone());
            let body = Expr::apps(or_inr.clone(), [p.clone(), r.clone(), mapped]);
            b.mk_lam(hq_id, BinderInfo::Default, q.clone(), body)
        };
        // Lean-faithful casesOn order: motive, major, then minors.
        let body = Expr::apps(
            or_cases.clone(),
            [p.clone(), q.clone(), motive, o.clone(), inl, inr],
        );
        b.mk_lam(o_id, BinderInfo::Default, or_pq, body)
    }

    /// Build `fun (o : Or p (Or q r)) => ... : out` where `out = Or q (Or p r)`,
    /// rotating the first two disjuncts. Uses nested `Or.casesOn`.
    ///
    /// Allocates binders from the caller's builder `b` and returns an open term
    /// (see [`Self::build_or_map_right`]).
    #[allow(clippy::too_many_arguments)]
    fn build_or_left_comm_map(
        b: &mut EnvDeclBuilder,
        p: &Expr,
        q: &Expr,
        r: &Expr,
        out: &Expr,
        or_inl: &Expr,
        or_inr: &Expr,
        or_cases: &Expr,
    ) -> Expr {
        let or_qr = Expr::apps(
            Expr::const_(Name::from_string("Or"), vec![]),
            [q.clone(), r.clone()],
        );
        let in_ty = Expr::apps(
            Expr::const_(Name::from_string("Or"), vec![]),
            [p.clone(), or_qr.clone()],
        );
        // out = Or q (Or p r)
        let or_pr = Expr::apps(
            Expr::const_(Name::from_string("Or"), vec![]),
            [p.clone(), r.clone()],
        );
        let (o_id, o) = b.fresh_local(in_ty.clone());
        // outer motive : fun (_ : Or p (Or q r)) => out
        let outer_motive = {
            let (z_id, _z) = b.fresh_local(in_ty.clone());
            b.mk_lam(z_id, BinderInfo::Default, in_ty.clone(), out.clone())
        };
        // inl: fun (hp : p) => Or.inr q (Or p r) (Or.inl p r hp)
        let inl = {
            let (hp_id, hp) = b.fresh_local(p.clone());
            let inner = Expr::apps(or_inl.clone(), [p.clone(), r.clone(), hp.clone()]);
            let body = Expr::apps(or_inr.clone(), [q.clone(), or_pr.clone(), inner]);
            b.mk_lam(hp_id, BinderInfo::Default, p.clone(), body)
        };
        // inr: fun (hqr : Or q r) => Or.casesOn hqr
        //        (motive := fun _ => out)
        //        (fun hq => Or.inl q (Or p r) hq)
        //        (fun hr => Or.inr q (Or p r) (Or.inr p r hr))
        let inr = {
            let (hqr_id, hqr) = b.fresh_local(or_qr.clone());
            let inner_motive = {
                let (z_id, _z) = b.fresh_local(or_qr.clone());
                b.mk_lam(z_id, BinderInfo::Default, or_qr.clone(), out.clone())
            };
            let i_inl = {
                let (hq_id, hq) = b.fresh_local(q.clone());
                let body = Expr::apps(or_inl.clone(), [q.clone(), or_pr.clone(), hq.clone()]);
                b.mk_lam(hq_id, BinderInfo::Default, q.clone(), body)
            };
            let i_inr = {
                let (hr_id, hr) = b.fresh_local(r.clone());
                let inner = Expr::apps(or_inr.clone(), [p.clone(), r.clone(), hr.clone()]);
                let body = Expr::apps(or_inr.clone(), [q.clone(), or_pr.clone(), inner]);
                b.mk_lam(hr_id, BinderInfo::Default, r.clone(), body)
            };
            // Lean-faithful casesOn order: motive, major, then minors.
            let body = Expr::apps(
                or_cases.clone(),
                [
                    q.clone(),
                    r.clone(),
                    inner_motive,
                    hqr.clone(),
                    i_inl,
                    i_inr,
                ],
            );
            b.mk_lam(hqr_id, BinderInfo::Default, or_qr.clone(), body)
        };
        let body = Expr::apps(
            or_cases.clone(),
            [p.clone(), or_qr.clone(), outer_motive, o.clone(), inl, inr],
        );
        // Open term referencing caller fvars (`p`/`q`/`r`); the caller closes
        // them. This builder's own fvars are all closed via `mk_lam`.
        b.mk_lam(o_id, BinderInfo::Default, in_ty, body)
    }

    /// Register `Multiset.mem_cons_self {α} (a) (s) :
    /// Multiset.Mem a (Multiset.cons a s)`.
    ///
    /// Proved by `Quot.ind` on `s`. On a `Quot.mk` representative `l` the
    /// reducible `Multiset.cons`/`Multiset.Mem` definitions quot-reduce so the
    /// goal becomes `List.Mem a (a :: l)`, inhabited by `@List.Mem.head α a l`.
    fn register_multiset_mem_cons_self(
        &mut self,
        u: &Name,
        u_level: &Level,
        type_u: &Expr,
    ) -> Result<(), EnvError> {
        let lvl_su = Level::succ(u_level.clone());

        let list_const = Expr::const_(Name::from_string("List"), vec![u_level.clone()]);
        let perm_const = Expr::const_(Name::from_string("List.Perm"), vec![u_level.clone()]);
        let multiset_const = Expr::const_(Name::from_string("Multiset"), vec![u_level.clone()]);
        let mset_cons = Expr::const_(Name::from_string("Multiset.cons"), vec![u_level.clone()]);
        let mset_mem = Expr::const_(Name::from_string("Multiset.Mem"), vec![u_level.clone()]);
        let mem_head = Expr::const_(Name::from_string("List.Mem.head"), vec![u_level.clone()]);
        // `Quot.ind.{u+1}` — carrier `List α : Sort (u+1)`.
        let quot_ind = Expr::const_(Name::from_string("Quot.ind"), vec![lvl_su.clone()]);

        let list_of = |a: &Expr| Expr::app(list_const.clone(), a.clone());
        let perm_rel = |a: &Expr| Expr::app(perm_const.clone(), a.clone());
        let mset_of = |a: &Expr| Expr::app(multiset_const.clone(), a.clone());
        let mcons = |a: &Expr, x: Expr, s: Expr| Expr::apps(mset_cons.clone(), [a.clone(), x, s]);
        let mmem = |a: &Expr, x: Expr, s: Expr| Expr::apps(mset_mem.clone(), [a.clone(), x, s]);

        let mem_cons_self_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (s_id, s) = b.fresh_local(mset_of(&alpha));
            let concl = mmem(&alpha, a.clone(), mcons(&alpha, a.clone(), s.clone()));
            let e = b.mk_pi(s_id, BinderInfo::Default, mset_of(&alpha), concl);
            let e = b.mk_pi(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        let mem_cons_self_value = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (a_id, a) = b.fresh_local(alpha.clone());
            let (s_id, s) = b.fresh_local(mset_of(&alpha));

            // motive β : fun (s : Multiset α) => Multiset.Mem a (Multiset.cons a s)
            let motive = {
                let (ms_id, ms) = b.fresh_local(mset_of(&alpha));
                let body = mmem(&alpha, a.clone(), mcons(&alpha, a.clone(), ms.clone()));
                b.mk_lam(ms_id, BinderInfo::Default, mset_of(&alpha), body)
            };

            // hyp : ∀ (l : List α), β (Quot.mk l)
            //     = fun (l : List α) => @List.Mem.head α a l
            // (its declared type, β (Quot.mk l), quot-reduces to List.Mem a (a::l)).
            let hyp = {
                let (l_id, l) = b.fresh_local(list_of(&alpha));
                let body = Expr::apps(mem_head.clone(), [alpha.clone(), a.clone(), l.clone()]);
                b.mk_lam(l_id, BinderInfo::Default, list_of(&alpha), body)
            };

            // @Quot.ind (List α) (Perm α) β hyp s
            let body = Expr::apps(
                quot_ind.clone(),
                [list_of(&alpha), perm_rel(&alpha), motive, hyp, s.clone()],
            );
            let e = b.mk_lam(s_id, BinderInfo::Default, mset_of(&alpha), body);
            let e = b.mk_lam(a_id, BinderInfo::Default, alpha.clone(), e);
            let e = b.mk_lam(alpha_id, BinderInfo::Implicit, type_u.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Theorem {
            name: Name::from_string("Multiset.mem_cons_self"),
            level_params: vec![u.clone()],
            type_: mem_cons_self_type,
            value: mem_cons_self_value,
        })?;

        Ok(())
    }
}

#[cfg(test)]
mod multiset_tests {
    use super::*;
    use crate::env::ConstantKind;
    use crate::tc::TypeChecker;

    fn env_with_multiset() -> Environment {
        let mut env = Environment::new();
        env.init_multiset().expect("Multiset should initialize");
        env
    }

    #[test]
    fn test_init_multiset_idempotent() {
        let mut env = env_with_multiset();
        env.init_multiset()
            .expect("idempotent re-initialization should succeed");
        assert!(env.multiset_init);
    }

    /// The full membership chain is registered and each lemma's transitive
    /// axiom closure is `⊆ {propext, Quot.sound}` (both FOUNDATIONAL): the
    /// Mem-respecting congruence is genuinely constructive, the quotient lift
    /// uses `propext` to turn the `Iff` into an `Eq`, and `mem_cons_self` rides
    /// `Quot.ind`. No domain axiom is introduced.
    #[test]
    fn test_multiset_mem_chain_registered_and_axiom_clean() {
        let env = env_with_multiset();
        let tc = TypeChecker::new(&env);
        for name in [
            "List.Perm.mem_iff",
            "Multiset.Mem",
            "Multiset.instMembership",
            "Multiset.mem_cons_self",
            "Or.iff_congr_right'",
            "Or.left_comm'",
        ] {
            assert!(
                env.get_const(&Name::from_string(name)).is_some(),
                "{name} should be registered"
            );
        }
        // Each proof/def whose value the kernel stores must type-check and have
        // an axiom closure within the foundational set (axiom_deps filters out
        // foundational axioms, so it should be empty for these).
        for name in [
            "List.Perm.mem_iff",
            "Multiset.mem_cons_self",
            "Or.iff_congr_right'",
            "Or.left_comm'",
            "Multiset.Mem",
        ] {
            let info = env
                .get_const(&Name::from_string(name))
                .unwrap_or_else(|| panic!("{name} registered"));
            if let Some(value) = info.value.clone() {
                let inferred = tc
                    .infer_type(&value)
                    .unwrap_or_else(|e| panic!("{name} value should type-check, got {e:?}"));
                assert!(
                    tc.is_def_eq(&inferred, &info.type_),
                    "{name}: inferred type must match declared type"
                );
            }
            let deps = env
                .axiom_deps(&Name::from_string(name))
                .unwrap_or_else(|| panic!("axiom_deps for {name}"));
            assert!(
                deps.is_empty(),
                "{name} must have an empty domain-axiom closure (⊆ FOUNDATIONAL), got {deps:?}"
            );
        }
    }

    /// `List.mem_cons` is the genuine core Lean-4 statement — `Membership.mem`
    /// form with a, b, l IMPLICIT (`a ∈ b :: l ↔ a = b ∨ a ∈ l`) — proved via
    /// the raw `List.mem_cons_iff`, with an empty domain-axiom closure. A
    /// concrete `Nat` instantiation type-checks to the `Membership.mem` iff,
    /// confirming the kernel converges the `Membership.mem` statement to the
    /// raw `List.Mem` proof through the reducible `List.instMembership`.
    #[test]
    fn test_list_mem_cons_genuine_membership_form() {
        let env = env_with_multiset();
        let tc = TypeChecker::new(&env);
        let info = env
            .get_const(&Name::from_string("List.mem_cons"))
            .expect("List.mem_cons should be registered");
        assert_eq!(info.kind, ConstantKind::Theorem);
        let value = info.value.clone().expect("theorem retains its value");
        let inferred = tc
            .infer_type(&value)
            .unwrap_or_else(|e| panic!("List.mem_cons value should type-check: {e:?}"));
        assert!(
            tc.is_def_eq(&inferred, &info.type_),
            "List.mem_cons inferred type must match its declared Membership.mem form"
        );
        let deps = env
            .axiom_deps(&Name::from_string("List.mem_cons"))
            .expect("axiom_deps for List.mem_cons");
        assert!(
            deps.is_empty(),
            "List.mem_cons must have an empty domain-axiom closure, got {deps:?}"
        );

        // Concrete instance: @List.mem_cons.{0} Nat (a:=0) (b:=0) (l:=[]) must
        // type-check to the `Membership.mem` iff `0 ∈ [0] ↔ 0 = 0 ∨ 0 ∈ []`.
        let lvl0 = Level::zero();
        let nat = Expr::const_(Name::from_string("Nat"), vec![]);
        let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
        let nil = Expr::app(
            Expr::const_(Name::from_string("List.nil"), vec![lvl0.clone()]),
            nat.clone(),
        );
        let inst = Expr::apps(
            Expr::const_(Name::from_string("List.mem_cons"), vec![lvl0.clone()]),
            [nat.clone(), zero.clone(), zero.clone(), nil.clone()],
        );
        let _ty = tc
            .infer_type(&inst)
            .expect("concrete List.mem_cons instance should type-check");
    }

    /// Faithfulness witness #2: `Multiset.mem_cons_self` gives a real proof of
    /// `Multiset.Mem 0 (Multiset.cons 0 Multiset.nil)` over `Multiset Nat`,
    /// where the membership is computed through the `Quot.lift`/`Quot.ind`
    /// reductions on the canonical representative.
    #[test]
    fn test_multiset_mem_cons_self_inhabits_concrete_goal() {
        let env = env_with_multiset();
        let tc = TypeChecker::new(&env);
        let lvl0 = Level::zero();
        let nat = Expr::const_(Name::from_string("Nat"), vec![]);
        let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
        let mnil = Expr::app(
            Expr::const_(Name::from_string("Multiset.nil"), vec![lvl0.clone()]),
            nat.clone(),
        );
        let mcons0 = Expr::apps(
            Expr::const_(Name::from_string("Multiset.cons"), vec![lvl0.clone()]),
            [nat.clone(), zero.clone(), mnil.clone()],
        );
        let goal = Expr::apps(
            Expr::const_(Name::from_string("Multiset.Mem"), vec![lvl0.clone()]),
            [nat.clone(), zero.clone(), mcons0.clone()],
        );
        let proof = Expr::apps(
            Expr::const_(
                Name::from_string("Multiset.mem_cons_self"),
                vec![lvl0.clone()],
            ),
            [nat.clone(), zero.clone(), mnil.clone()],
        );
        let inferred = tc
            .infer_type(&proof)
            .expect("Multiset.mem_cons_self application should type-check");
        assert!(
            tc.is_def_eq(&inferred, &goal),
            "mem_cons_self must prove `0 ∈ {{0}}` as a Multiset Nat"
        );
    }

    #[test]
    fn test_list_mem_cons_iff_is_constructive() {
        let env = env_with_multiset();
        let info = env
            .get_const(&Name::from_string("List.mem_cons_iff"))
            .expect("List.mem_cons_iff should be registered");
        let value = info
            .value
            .clone()
            .expect("List.mem_cons_iff must retain its proof value");
        let tc = TypeChecker::new(&env);
        let inferred = tc
            .infer_type(&value)
            .expect("List.mem_cons_iff proof term should type-check");
        assert!(
            tc.is_def_eq(&inferred, &info.type_),
            "List.mem_cons_iff inferred type must match declared type"
        );
        let deps = env
            .axiom_deps(&Name::from_string("List.mem_cons_iff"))
            .expect("axiom_deps should be reported");
        assert!(
            deps.is_empty(),
            "List.mem_cons_iff must have an empty domain-axiom closure, got {deps:?}"
        );
    }

    #[test]
    fn test_list_nodup_inductive_and_constructors_registered() {
        let env = env_with_multiset();
        for name in [
            "List.Nodup",
            "List.Nodup.nil",
            "List.Nodup.cons",
            "List.Nodup.rec",
        ] {
            assert!(
                env.get_const(&Name::from_string(name)).is_some(),
                "{name} should be registered"
            );
        }
        let ind = env
            .inductives
            .get(&Name::from_string("List.Nodup"))
            .expect("List.Nodup should be an inductive");
        assert_eq!(ind.num_params, 1, "α is the sole parameter");
        assert_eq!(ind.num_indices, 1, "`List α` is the single index");
    }

    #[test]
    fn test_list_nodup_rec_infers_a_sort() {
        let env = env_with_multiset();
        let rec = env
            .get_const(&Name::from_string("List.Nodup.rec"))
            .expect("List.Nodup.rec should be registered");
        let tc = TypeChecker::new(&env);
        let _sort = tc
            .infer_type(&rec.type_)
            .expect("List.Nodup.rec type should infer a sort");
    }

    #[test]
    fn test_multiset_type_and_ops_registered() {
        let env = env_with_multiset();
        for name in ["Multiset", "Multiset.nil", "Multiset.cons"] {
            assert!(
                env.get_const(&Name::from_string(name)).is_some(),
                "{name} should be registered"
            );
        }
    }

    /// `Multiset`, `Multiset.nil`, and `Multiset.cons` are genuine
    /// `Declaration::Definition`s whose stored value kernel-type-checks at the
    /// declared type, and whose transitive axiom closure is empty (they are
    /// built from `Quot.mk`/`Quot.lift`/`Quot.sound` + `List.Perm.cons`, with
    /// `Quot.*`/`Quot.sound` whitelisted as FOUNDATIONAL).
    #[test]
    fn test_multiset_defs_type_check() {
        let env = env_with_multiset();
        let tc = TypeChecker::new(&env);
        for name in ["Multiset", "Multiset.nil", "Multiset.cons"] {
            let info = env
                .get_const(&Name::from_string(name))
                .unwrap_or_else(|| panic!("{name} should be registered"));
            assert_eq!(info.kind, ConstantKind::Definition);
            let value = info
                .value
                .clone()
                .unwrap_or_else(|| panic!("{name} must retain its value"));
            let inferred = tc
                .infer_type(&value)
                .unwrap_or_else(|e| panic!("{name} value should type-check, got {e:?}"));
            assert!(
                tc.is_def_eq(&inferred, &info.type_),
                "{name}: inferred type must match declared type"
            );
        }
    }

    /// Faithfulness witness: `Multiset.cons` respects `List.Perm` through
    /// `Quot.sound`, so the order-insensitivity equation
    ///   `Multiset.cons a (Multiset.cons b nil) = Multiset.cons b (Multiset.cons a nil)`
    /// is provable. We build the proof term and confirm it kernel-checks at
    /// that `Eq` type over `Multiset Nat`.
    ///
    /// Proof: `Quot.sound` applied to `List.Perm.swap a b []`, after reducing
    /// `Multiset.cons` on the canonical `Quot.mk` representatives. Concretely
    /// both sides reduce to `Quot.mk` of `[a,b]` and `[b,a]`, and
    /// `List.Perm.swap` witnesses `[a,b] ~ [b,a]` (note `swap` produces
    /// `Perm (y::x::l) (x::y::l)`).
    #[test]
    fn test_multiset_cons_order_insensitive_via_quot_sound() {
        let env = env_with_multiset();
        let tc = TypeChecker::new(&env);

        let nat = Expr::const_(Name::from_string("Nat"), vec![]);
        let zero = Expr::const_(Name::from_string("Nat.zero"), vec![]);
        let one = Expr::app(
            Expr::const_(Name::from_string("Nat.succ"), vec![]),
            zero.clone(),
        );
        // Levels: Nat : Type 0, so List Nat : Type 0 = Sort 1, quotient at lvl 1.
        let lvl0 = Level::zero();
        let lvl1 = Level::succ(Level::zero());

        let list_nat = Expr::app(
            Expr::const_(Name::from_string("List"), vec![lvl0.clone()]),
            nat.clone(),
        );
        let nil_nat = Expr::app(
            Expr::const_(Name::from_string("List.nil"), vec![lvl0.clone()]),
            nat.clone(),
        );
        let cons_nat = |h: Expr, t: Expr| {
            Expr::apps(
                Expr::const_(Name::from_string("List.cons"), vec![lvl0.clone()]),
                [nat.clone(), h, t],
            )
        };
        let perm_rel_nat = Expr::app(
            Expr::const_(Name::from_string("List.Perm"), vec![lvl0.clone()]),
            nat.clone(),
        );
        let mset_nat = Expr::app(
            Expr::const_(Name::from_string("Multiset"), vec![lvl0.clone()]),
            nat.clone(),
        );
        let mcons = |h: Expr, s: Expr| {
            Expr::apps(
                Expr::const_(Name::from_string("Multiset.cons"), vec![lvl0.clone()]),
                [nat.clone(), h, s],
            )
        };
        let mnil = Expr::app(
            Expr::const_(Name::from_string("Multiset.nil"), vec![lvl0.clone()]),
            nat.clone(),
        );

        // LHS = cons 0 (cons 1 nil); RHS = cons 1 (cons 0 nil)
        let lhs = mcons(zero.clone(), mcons(one.clone(), mnil.clone()));
        let rhs = mcons(one.clone(), mcons(zero.clone(), mnil.clone()));

        // Goal: @Eq (Multiset Nat) lhs rhs
        let goal = Expr::apps(
            Expr::const_(Name::from_string("Eq"), vec![lvl1.clone()]),
            [mset_nat.clone(), lhs.clone(), rhs.clone()],
        );

        // Proof: @Quot.sound (List Nat) (Perm Nat) [0,1] [1,0]
        //          (@List.Perm.swap Nat 0 1 []) reduces under the right shape.
        // `List.Perm.swap x y l : Perm (y::x::l) (x::y::l)`. We want
        // [0,1] ~ [1,0]: pick x=1, y=0, l=[] so (0::1::[]) ~ (1::0::[]).
        let l01 = cons_nat(zero.clone(), cons_nat(one.clone(), nil_nat.clone()));
        let l10 = cons_nat(one.clone(), cons_nat(zero.clone(), nil_nat.clone()));
        let perm_swap = Expr::apps(
            Expr::const_(Name::from_string("List.Perm.swap"), vec![lvl0.clone()]),
            [nat.clone(), one.clone(), zero.clone(), nil_nat.clone()],
        );
        let proof = Expr::apps(
            Expr::const_(Name::from_string("Quot.sound"), vec![lvl1.clone()]),
            [list_nat.clone(), perm_rel_nat.clone(), l01, l10, perm_swap],
        );

        let inferred = tc
            .infer_type(&proof)
            .expect("order-insensitivity proof term should type-check");
        assert!(
            tc.is_def_eq(&inferred, &goal),
            "Quot.sound(swap) must prove cons-order-insensitivity over Multiset Nat;\n inferred = {inferred:?}"
        );
    }
}
