// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Kernel-level declarations for Polynomial Calculus soundness over GF(2).
//!
//! Formalizes the soundness of the Polynomial Calculus proof system over
//! the two-element Galois field GF(2) = ({0,1}, XOR, AND), certifying
//! that Groebner basis certificates are valid UNSAT proofs.
//!
//! ## Encoding
//!
//! A CNF clause C = (x_1 OR x_2 OR NOT x_3) becomes a polynomial
//! p_C = (1-x_1)(1-x_2)(x_3) = 0 over GF(2). The ideal
//! I = <p_{C_1}, ..., p_{C_m}, x_1^2 - x_1, ..., x_n^2 - x_n>
//! encodes the formula. If Buchberger's algorithm derives 1 from I,
//! the formula is UNSAT.
//!
//! ## Main Theorem (T5 PC Soundness)
//!
//! If 1 is in the ideal generated by clause polynomials and Boolean
//! axioms x_i^2 - x_i = 0 over GF(2), then the original CNF formula
//! is unsatisfiable.
//!
//! Type and operation definitions live here; theorem registrations are
//! in `gf2_polynomial_calculus_theorems.rs`.
//!
//! Reference: Clegg, Edmonds, Impagliazzo (1996), "Using the Groebner
//!            basis algorithm to find proofs of unsatisfiability", STOC'96.
//!            Razborov (1998), "Lower bounds for the polynomial calculus",
//!            Computational Complexity 7(4), pp. 291-324.
//!
//! Part of #3165.

#[cfg(test)]
use crate::env::decl_builder::EnvDeclBuilder;
#[cfg(test)]
use crate::env::{Declaration, EnvError, Environment};
#[cfg(test)]
use crate::expr::{BinderInfo, Expr, ExprKind};
#[cfg(test)]
use crate::level::Level;
#[cfg(test)]
use crate::name::Name;

/// Shared constants for GF(2) Polynomial Calculus formalization.
#[cfg(test)]
#[allow(dead_code)] // 2026-07-31: no caller in any build (lib or lib-test); kept, not deleted.
pub(super) struct GF2PCConsts {
    pub(super) nat: Expr,
    pub(super) prop: Expr,
    pub(super) type0: Expr,
    /// ProofTheory.GF2PolynomialCalculus.GF2Polynomial : Type
    pub(super) gf2_poly: Expr,
    /// ProofTheory.GF2PolynomialCalculus.CNFClause : Type
    pub(super) cnf_clause: Expr,
    /// ProofTheory.GF2PolynomialCalculus.CNFFormula : Type
    pub(super) cnf_formula: Expr,
    /// ProofTheory.GF2PolynomialCalculus.BooleanAssignment : Type
    pub(super) bool_assignment: Expr,
    /// ProofTheory.GF2PolynomialCalculus.clause_to_polynomial
    pub(super) clause_to_poly: Expr,
    /// ProofTheory.GF2PolynomialCalculus.polynomial_evaluates_zero
    pub(super) poly_eval_zero: Expr,
    /// ProofTheory.GF2PolynomialCalculus.ideal_membership
    pub(super) ideal_mem: Expr,
    /// ProofTheory.GF2PolynomialCalculus.assignment_satisfies_clause
    pub(super) sat_clause: Expr,
    /// ProofTheory.GF2PolynomialCalculus.assignment_satisfies_formula
    pub(super) sat_formula: Expr,
    /// ProofTheory.GF2PolynomialCalculus.spoly_reduce
    pub(super) spoly_reduce: Expr,
    /// ProofTheory.GF2PolynomialCalculus.gf2_one : GF2Polynomial
    pub(super) gf2_one: Expr,
    /// Not : Prop -> Prop
    pub(super) not_: Expr,
    /// Iff : Prop -> Prop -> Prop
    pub(super) iff: Expr,
}

#[cfg(test)]
const NS: &str = "ProofTheory.GF2PolynomialCalculus";

#[cfg(test)]
pub(super) fn ns(suffix: &str) -> String {
    format!("{NS}.{suffix}")
}

#[cfg(test)]
impl GF2PCConsts {
    #[cfg(test)]
    pub(super) fn new() -> Self {
        Self {
            nat: Expr::const_(Name::from_string("Nat"), vec![]),
            prop: Expr::from_kind(ExprKind::Sort(Level::zero())),
            type0: Expr::from_kind(ExprKind::Sort(Level::succ(Level::zero()))),
            gf2_poly: Expr::const_(Name::from_string(&ns("GF2Polynomial")), vec![]),
            cnf_clause: Expr::const_(Name::from_string(&ns("CNFClause")), vec![]),
            cnf_formula: Expr::const_(Name::from_string(&ns("CNFFormula")), vec![]),
            bool_assignment: Expr::const_(Name::from_string(&ns("BooleanAssignment")), vec![]),
            clause_to_poly: Expr::const_(Name::from_string(&ns("clause_to_polynomial")), vec![]),
            poly_eval_zero: Expr::const_(
                Name::from_string(&ns("polynomial_evaluates_zero")),
                vec![],
            ),
            ideal_mem: Expr::const_(Name::from_string(&ns("ideal_membership")), vec![]),
            sat_clause: Expr::const_(
                Name::from_string(&ns("assignment_satisfies_clause")),
                vec![],
            ),
            sat_formula: Expr::const_(
                Name::from_string(&ns("assignment_satisfies_formula")),
                vec![],
            ),
            spoly_reduce: Expr::const_(Name::from_string(&ns("spoly_reduce")), vec![]),
            gf2_one: Expr::const_(Name::from_string(&ns("gf2_one")), vec![]),
            not_: Expr::const_(Name::from_string("Not"), vec![]),
            iff: Expr::const_(Name::from_string("Iff"), vec![]),
        }
    }
}

#[cfg(test)]
impl Environment {
    /// Initialize GF(2) Polynomial Calculus soundness declarations.
    ///
    /// Depends on: `init_bool()`, `init_nat()`.
    #[cfg(test)]
    pub(crate) fn init_gf2_polynomial_calculus(&mut self) -> Result<(), EnvError> {
        if self.gf2_polynomial_calculus_init {
            return Ok(());
        }
        self.init_bool()?;
        self.init_nat()?;

        let c = GF2PCConsts::new();

        // Types
        self.register_gf2pc_gf2_polynomial(&c)?;
        self.register_gf2pc_cnf_clause(&c)?;
        self.register_gf2pc_cnf_formula(&c)?;
        self.register_gf2pc_boolean_assignment(&c)?;
        self.register_gf2pc_gf2_one(&c)?;

        // Operations
        self.register_gf2pc_clause_to_polynomial(&c)?;
        self.register_gf2pc_formula_ideal(&c)?;
        self.register_gf2pc_polynomial_evaluates_zero(&c)?;
        self.register_gf2pc_ideal_membership(&c)?;
        self.register_gf2pc_assignment_satisfies_clause(&c)?;
        self.register_gf2pc_assignment_satisfies_formula(&c)?;
        self.register_gf2pc_spoly_reduce(&c)?;

        // Theorems (in gf2_polynomial_calculus_theorems.rs)
        self.register_gf2pc_clause_encoding_soundness(&c)?;
        self.register_gf2pc_field_idempotent(&c)?;
        self.register_gf2pc_ideal_closed_addition(&c)?;
        self.register_gf2pc_ideal_closed_multiplication(&c)?;
        self.register_gf2pc_pc_soundness(&c)?;
        self.register_gf2pc_spoly_preserves_ideal(&c)?;

        self.gf2_polynomial_calculus_init = true;
        Ok(())
    }

    // ====================================================================
    // Type definitions
    // ====================================================================

    /// `GF2Polynomial : Type` -- multilinear polynomial over GF(2).
    #[cfg(test)]
    fn register_gf2pc_gf2_polynomial(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("GF2Polynomial");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: c.type0.clone(),
        })
    }

    /// `CNFClause : Type` -- a clause in a CNF formula.
    #[cfg(test)]
    fn register_gf2pc_cnf_clause(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("CNFClause");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: c.type0.clone(),
        })
    }

    /// `CNFFormula : Type` -- a formula in CNF (list of clauses).
    #[cfg(test)]
    fn register_gf2pc_cnf_formula(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("CNFFormula");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: c.type0.clone(),
        })
    }

    /// `BooleanAssignment : Type` -- assignment of {0,1} to variables.
    #[cfg(test)]
    fn register_gf2pc_boolean_assignment(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("BooleanAssignment");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: c.type0.clone(),
        })
    }

    /// `gf2_one : GF2Polynomial` -- the constant polynomial 1.
    #[cfg(test)]
    fn register_gf2pc_gf2_one(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("gf2_one");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: c.gf2_poly.clone(),
        })
    }

    // ====================================================================
    // Operations
    // ====================================================================

    /// `clause_to_polynomial : CNFClause -> GF2Polynomial`
    ///
    /// Encode a clause as a polynomial: (x1 OR x2 OR NOT x3) becomes
    /// (1-x1)(1-x2)(x3) over GF(2).
    #[cfg(test)]
    fn register_gf2pc_clause_to_polynomial(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("clause_to_polynomial");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = Expr::pi(
            BinderInfo::Default,
            c.cnf_clause.clone(),
            c.gf2_poly.clone(),
        );
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }

    /// `formula_ideal : CNFFormula -> Nat -> Type`
    ///
    /// The ideal I = <p_{C_1},...,p_{C_m}, x_1^2 - x_1,..., x_n^2 - x_n>
    /// generated by clause polynomials and Boolean axioms for n variables.
    #[cfg(test)]
    fn register_gf2pc_formula_ideal(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("formula_ideal");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = {
            let mut b = EnvDeclBuilder::new();
            let (f_id, _) = b.fresh_local(c.cnf_formula.clone());
            let (n_id, _) = b.fresh_local(c.nat.clone());
            let e = b.mk_pi(n_id, BinderInfo::Default, c.nat.clone(), c.type0.clone());
            let e = b.mk_pi(f_id, BinderInfo::Default, c.cnf_formula.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }

    /// `polynomial_evaluates_zero : GF2Polynomial -> BooleanAssignment -> Prop`
    #[cfg(test)]
    fn register_gf2pc_polynomial_evaluates_zero(
        &mut self,
        c: &GF2PCConsts,
    ) -> Result<(), EnvError> {
        let name = ns("polynomial_evaluates_zero");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = {
            let mut b = EnvDeclBuilder::new();
            let (p_id, _) = b.fresh_local(c.gf2_poly.clone());
            let (a_id, _) = b.fresh_local(c.bool_assignment.clone());
            let e = b.mk_pi(
                a_id,
                BinderInfo::Default,
                c.bool_assignment.clone(),
                c.prop.clone(),
            );
            let e = b.mk_pi(p_id, BinderInfo::Default, c.gf2_poly.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }

    /// `ideal_membership : GF2Polynomial -> CNFFormula -> Nat -> Prop`
    ///
    /// p is in the ideal generated by the clause polynomials of formula f
    /// with n variables (including Boolean axioms x_i^2 - x_i = 0).
    #[cfg(test)]
    fn register_gf2pc_ideal_membership(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("ideal_membership");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = {
            let mut b = EnvDeclBuilder::new();
            let (p_id, _) = b.fresh_local(c.gf2_poly.clone());
            let (f_id, _) = b.fresh_local(c.cnf_formula.clone());
            let (n_id, _) = b.fresh_local(c.nat.clone());
            let e = b.mk_pi(n_id, BinderInfo::Default, c.nat.clone(), c.prop.clone());
            let e = b.mk_pi(f_id, BinderInfo::Default, c.cnf_formula.clone(), e);
            let e = b.mk_pi(p_id, BinderInfo::Default, c.gf2_poly.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }

    /// `assignment_satisfies_clause : BooleanAssignment -> CNFClause -> Prop`
    #[cfg(test)]
    fn register_gf2pc_assignment_satisfies_clause(
        &mut self,
        c: &GF2PCConsts,
    ) -> Result<(), EnvError> {
        let name = ns("assignment_satisfies_clause");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = {
            let mut b = EnvDeclBuilder::new();
            let (a_id, _) = b.fresh_local(c.bool_assignment.clone());
            let (cl_id, _) = b.fresh_local(c.cnf_clause.clone());
            let e = b.mk_pi(
                cl_id,
                BinderInfo::Default,
                c.cnf_clause.clone(),
                c.prop.clone(),
            );
            let e = b.mk_pi(a_id, BinderInfo::Default, c.bool_assignment.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }

    /// `assignment_satisfies_formula : BooleanAssignment -> CNFFormula -> Prop`
    #[cfg(test)]
    fn register_gf2pc_assignment_satisfies_formula(
        &mut self,
        c: &GF2PCConsts,
    ) -> Result<(), EnvError> {
        let name = ns("assignment_satisfies_formula");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = {
            let mut b = EnvDeclBuilder::new();
            let (a_id, _) = b.fresh_local(c.bool_assignment.clone());
            let (f_id, _) = b.fresh_local(c.cnf_formula.clone());
            let e = b.mk_pi(
                f_id,
                BinderInfo::Default,
                c.cnf_formula.clone(),
                c.prop.clone(),
            );
            let e = b.mk_pi(a_id, BinderInfo::Default, c.bool_assignment.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }

    /// `spoly_reduce : GF2Polynomial -> GF2Polynomial -> GF2Polynomial`
    ///
    /// S-polynomial reduction step used in Buchberger's algorithm.
    #[cfg(test)]
    fn register_gf2pc_spoly_reduce(&mut self, c: &GF2PCConsts) -> Result<(), EnvError> {
        let name = ns("spoly_reduce");
        if self.get_const(&Name::from_string(&name)).is_some() {
            return Ok(());
        }
        let ty = {
            let mut b = EnvDeclBuilder::new();
            let (p_id, _) = b.fresh_local(c.gf2_poly.clone());
            let (q_id, _) = b.fresh_local(c.gf2_poly.clone());
            let e = b.mk_pi(
                q_id,
                BinderInfo::Default,
                c.gf2_poly.clone(),
                c.gf2_poly.clone(),
            );
            let e = b.mk_pi(p_id, BinderInfo::Default, c.gf2_poly.clone(), e);
            b.finish(e)
        };
        self.add_decl(Declaration::Axiom {
            name: Name::from_string(&name),
            level_params: vec![],
            type_: ty,
        })
    }
}
