// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! MASQUERADE-prevention proof-quality lint.
//!
//! Implements `Environment::assert_proof_nontrivial(name)` per design doc
//! `designs/2026-04-19-demasquerade-cxxx-pattern.md` Phase 4. Detects four
//! patterns: M1 alias-collapse, M2 argument-discarding carrier, M3 IH-ignoring
//! inductive step, M4 Eq.refl root. Enable with `CLEAN_STRICT_PROOF_QUALITY=1`
//! — default off pending Tier-C sweep.

use crate::expr::{Expr, ExprKind};
use crate::name::Name;

use super::types::{ConstantInfo, ConstantKind};
use super::Environment;

/// Environment variable that enables strict proof-quality checking on
/// `add_decl(Declaration::Theorem { … })`. Default off — flipped by the
/// Prover after the Tier-C demasquerade sweep is complete.
pub const STRICT_ENV_VAR: &str = "CLEAN_STRICT_PROOF_QUALITY";

/// Returns `true` iff `CLEAN_STRICT_PROOF_QUALITY=1` is set.
pub fn strict_mode_enabled() -> bool {
    strict_mode_enabled_for_value(std::env::var(STRICT_ENV_VAR).ok().as_deref())
}

/// Parse the strict-mode environment value without consulting process-global
/// state. Kept separate so tests never need to mutate the process environment
/// while other threads are registering declarations.
pub(crate) fn strict_mode_enabled_for_value(value: Option<&str>) -> bool {
    matches!(value, Some("1"))
}

/// Names considered α-equivalent to the canonical `Eq.refl` constructor when
/// detecting Rule M4. `rfl` is the notation alias generated by the elaborator
/// and also shows up as a stand-alone constant in some .olean shards.
const REFL_NAMES: &[&str] = &["Eq.refl", "rfl", "HEq.refl"];

/// Propositional combinators that M4 peels off before inspecting the root.
/// Order matters for debugging — leftmost entry is the common case.
const PROP_COMBINATORS: &[&str] = &[
    "Eq.symm", "Eq.trans", "Eq.subst", "Eq.mpr", "Eq.mp", "congrArg", "congrFun", "congr", "id",
];

/// Recursors whose minor premises *may* carry an induction hypothesis, paired
/// with the **argument index of the motive** in the fully-applied (`@`-form)
/// recursor application `@Rec a₀ a₁ …`. The motive is what lets M3 tell a
/// genuine IH binder (`ih : motive k`) apart from the ordinary hypotheses a
/// base/step minor binds from the motive's own telescope.
///
/// Index per Lean 4's recursor-generation convention (params, then motive,
/// then minors, then indices, then major):
/// - `Nat.rec`    `@Nat.rec motive z s t`          → motive at 0
/// - `Nat.le.rec` `@Nat.le.rec n motive r s m h`   → motive at 1 (after param n)
/// - `List.rec`   `@List.rec α motive nil cons t`  → motive at 1 (after param α)
/// - `Fin.rec`    `@Fin.rec n motive mk t`         → motive at 1 (after param n)
/// - `And.rec`    `@And.rec a b motive mk t`        → motive at 2 (after a, b)
/// - `Or.rec`     `@Or.rec a b motive inl inr t`    → motive at 2 (after a, b)
///
/// `Fin.rec`/`And.rec`/`Or.rec` are non-recursive, so their minors never bind a
/// motive-application binder and are therefore never flagged — they are listed
/// only so the scan is explicit about which recursors it considers.
///
/// Used only by the non-gating [`find_unused_ih`] structural diagnostic (M3 no
/// longer gates `check_proof_nontrivial` — see the SOUNDNESS note there).
#[allow(dead_code)]
const RECURSORS_WITH_IH: &[(&str, usize)] = &[
    ("Nat.rec", 0),
    ("Nat.le.rec", 1),
    ("List.rec", 1),
    ("Fin.rec", 1),
    ("And.rec", 2),
    ("Or.rec", 2),
];

/// A single MASQUERADE-pattern finding reported by the proof-quality lint.
///
/// Each variant carries enough evidence to reconstruct why the lint fired,
/// without requiring the caller to re-run the analysis.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum ProofQualityFinding {
    /// M4 — the proof term root, after peeling propositional combinators and
    /// outer lambdas, is `Eq.refl` (or an alias listed in [`REFL_NAMES`]) **and**
    /// the proved type (after peeling outer `Pi` binders) is an `Eq`/`HEq`
    /// application whose two value sides are *syntactically identical* — i.e. a
    /// vacuous `Eq a a`. A refl whose stated equality has DISTINCT sides
    /// (`Nat.sub a 0 = a`, defeq by computation) is a genuine proof and is NOT
    /// flagged. `depth` counts how many combinators were peeled.
    ReflProofTerm {
        /// Number of propositional combinators and lambdas peeled before
        /// reaching the refl root.
        depth: usize,
    },
    /// M2 — a reducible `Declaration::Definition` named in the theorem type
    /// has body `fun x₁ … xₙ => xᵢ` or `fun x₁ … xₙ => const_expr` with no
    /// `xᵢ` used. `carrier` is the Definition name; `shape` describes the
    /// offending body.
    ArgumentDiscardingCarrier {
        /// Name of the reducible Definition whose body is argument-discarding.
        carrier: Name,
        /// Human-readable description of the carrier shape.
        shape: String,
    },
    /// M3 — a recursor-minor-premise lambda binds a genuine induction
    /// hypothesis `ih : motive k` (a binder whose TYPE is an application of the
    /// recursor's motive), but the body never uses `ih`.
    ///
    /// NOT EMITTED by `check_proof_nontrivial`: unused-IH is a proof-STYLE
    /// observation, not a masquerade — on a kernel-checked corpus it has zero
    /// true positives (the sound "recursor used for case analysis" idiom). This
    /// variant is retained only for the non-gating [`find_unused_ih`] structural
    /// diagnostic. `recursor` is the recursor name.
    UnusedInductionHypothesis {
        /// Name of the recursor whose minor premise ignores its IH.
        recursor: Name,
    },
    /// M1 — both sides of an outer `Eq` contain a reducible `Definition`
    /// whose one-step unfolding leaves the two sides syntactically identical.
    /// `carrier` is the reducible Definition that witnesses the collapse.
    AliasCollapse {
        /// Name of the reducible Definition that aliases both sides.
        carrier: Name,
    },
}

/// Error returned by `Environment::assert_proof_nontrivial` when one or more
/// MASQUERADE patterns are detected.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
#[error("MASQUERADE proof for {name}: {} finding(s): {findings:?}", findings.len())]
pub struct ProofQualityError {
    /// Name of the theorem whose proof term failed the lint.
    pub name: Name,
    /// All findings observed; non-empty by construction.
    pub findings: Vec<ProofQualityFinding>,
}

impl Environment {
    /// Inspect a theorem's proof term for MASQUERADE patterns. Returns every
    /// finding observed (empty `Vec` = clean). `None` iff `name` is not a
    /// registered `Declaration::Theorem` with a concrete value.
    pub fn check_proof_nontrivial(&self, name: &Name) -> Option<Vec<ProofQualityFinding>> {
        let info = self.get_const(name)?;
        if info.kind != ConstantKind::Theorem {
            return None;
        }
        let value = info.value.as_ref()?;

        let mut findings = Vec::new();

        // M4 — refl root after peeling combinators and outer lambdas, but ONLY
        // when the proved equality is vacuous (syntactically identical sides). A
        // refl whose stated `Eq lhs rhs` has distinct sides is a genuine
        // definitional-equality proof (`Nat.add n 0 = n`) and is not a
        // masquerade.
        if let Some(depth) = refl_root_depth(value) {
            if equality_has_identical_sides(&info.type_) {
                findings.push(ProofQualityFinding::ReflProofTerm { depth });
            }
        }

        // M3 — DELIBERATELY NOT GATED. The "unused induction hypothesis in a
        // recursor minor premise" heuristic is a proof-STYLE observation, not a
        // soundness check, and on a kernel-checked corpus it has ZERO true
        // positives.
        //
        // SOUNDNESS: every theorem reaching `check_proof_nontrivial` has already
        // been type-checked by the kernel against its STATED type. If a step
        // minor `fun k (ih : motive k) => body` ignores `ih` and the whole
        // recursor application still type-checks, then `body` produces
        // `motive (succ k)` WITHOUT the hypothesis — i.e. the per-case goal was
        // provable directly. That is the ordinary, sound "recursor used for case
        // analysis" idiom (the double-`Nat.rec` min/max lemmas, the `Int`
        // arithmetic / `Nat.divmodAux` / `Nat.ulpRound` families, `Nat.pred_le`,
        // …): the kernel still verified the proof against the real, non-trivial
        // statement, so the goal is genuinely established. There is no way to
        // "fake" a theorem via an unused IH — the term either type-checks (and is
        // sound) or it is never registered. An exhaustive audit of every M3 flag
        // on the full corpus found 100% genuine, axiom-free, Constructive proofs.
        //
        // The ACTUAL masquerade patterns are caught elsewhere and remain gated:
        // M1 (alias-collapse — vacuously-true equation), M2 (argument-discarding
        // / hollow carrier), M4 (vacuous `Eq a a` refl, above), and the
        // gamma-crown `H -> H` hypothesis-projection gate. `find_unused_ih` is
        // retained below as a non-gating structural diagnostic (and is exercised
        // by the unit tests), but its result is intentionally NOT pushed here.

        // M2 — argument-discarding carrier named in the theorem type.
        for (carrier, shape) in argument_discarding_carriers(self, &info.type_) {
            findings.push(ProofQualityFinding::ArgumentDiscardingCarrier { carrier, shape });
        }

        // M1 — alias-collapse: both equation sides reduce to the same term
        // after one step of δ-reduction through a reducible Definition.
        if let Some(carrier) = alias_collapse_witness(self, &info.type_) {
            findings.push(ProofQualityFinding::AliasCollapse { carrier });
        }

        Some(findings)
    }

    /// Assert that a theorem's proof term passes the MASQUERADE lint.
    /// Returns `Ok(())` if the theorem is clean or not found; returns an
    /// error listing every finding if the lint fires.
    pub fn assert_proof_nontrivial(&self, name: &Name) -> Result<(), ProofQualityError> {
        match self.check_proof_nontrivial(name) {
            None => Ok(()),
            Some(v) if v.is_empty() => Ok(()),
            Some(findings) => Err(ProofQualityError {
                name: name.clone(),
                findings,
            }),
        }
    }
}

// ─── Detection helpers ──────────────────────────────────────────────────────

/// If `e` (or, recursively, its head) is `Expr::Const(name, _)`, returns the
/// constant name. Skips `MData` wrappers. Returns `None` for BVar/FVar/etc.
pub(super) fn head_const(e: &Expr) -> Option<&Name> {
    let mut cur = e;
    loop {
        match cur.kind() {
            ExprKind::App(f, _) => cur = f,
            ExprKind::MData(_, inner) => cur = inner,
            ExprKind::Const(n, _) => return Some(n),
            _ => return None,
        }
    }
}

/// Unwrap outer `Lam` binders. Returns the peeled body and the number of
/// binders peeled.
pub(super) fn peel_lambdas(e: &Expr) -> (&Expr, usize) {
    let mut depth = 0usize;
    let mut cur = e;
    loop {
        match cur.kind() {
            ExprKind::Lam(_, _, body) => {
                cur = body;
                depth += 1;
            }
            ExprKind::MData(_, inner) => cur = inner,
            _ => return (cur, depth),
        }
    }
}

/// Collect `App`-spine arguments: `f a b c` → `(&f, [&a, &b, &c])`.
fn collect_app_args(e: &Expr) -> (&Expr, Vec<&Expr>) {
    let mut args: Vec<&Expr> = Vec::new();
    let mut cur = e;
    loop {
        match cur.kind() {
            ExprKind::App(f, a) => {
                args.push(a);
                cur = f;
            }
            ExprKind::MData(_, inner) => cur = inner,
            _ => {
                args.reverse();
                return (cur, args);
            }
        }
    }
}

/// Peel propositional combinators from the head of an application chain.
/// `Eq.trans a b` → peel to `b`; `congrArg f a` → peel to `a`. Returns the
/// inner term and the peel depth.
fn peel_prop_combinators(e: &Expr) -> (&Expr, usize) {
    let mut cur = e;
    let mut depth = 0usize;
    loop {
        // Strip metadata / outer lambdas first.
        let (inner, lam_peel) = peel_lambdas(cur);
        depth += lam_peel;
        cur = inner;

        let (head, args) = collect_app_args(cur);
        let name = match head_const(head) {
            Some(n) => n,
            None => return (cur, depth),
        };
        let name_str = name.to_string();
        if !PROP_COMBINATORS.iter().any(|&c| name_str == c) {
            return (cur, depth);
        }
        if args.is_empty() {
            return (cur, depth);
        }
        // The "interesting" sub-proof is the last argument for the peelable
        // combinators: `Eq.trans hab hbc`, `Eq.symm h`, `congrArg f h`.
        cur = args[args.len() - 1];
        depth += 1;
    }
}

/// M4 detector: returns `Some(depth)` if the proof term, after peeling
/// outer lambdas and propositional combinators, is a `Const(Eq.refl, _)` or
/// an `App`-spine with head `Eq.refl`. Returns `None` otherwise.
pub(super) fn refl_root_depth(proof: &Expr) -> Option<usize> {
    let (root, depth) = peel_prop_combinators(proof);
    let (head, _args) = collect_app_args(root);
    let name = head_const(head)?;
    let name_str = name.to_string();
    if REFL_NAMES.iter().any(|&r| name_str == r) {
        Some(depth)
    } else {
        None
    }
}

/// Strip any `MData` wrappers from the head of `e`. (`MData` is transparent to
/// type checking.) Used by the non-gating [`find_unused_ih`] diagnostic.
#[allow(dead_code)]
fn strip_mdata(e: &Expr) -> &Expr {
    let mut cur = e;
    while let ExprKind::MData(_, inner) = cur.kind() {
        cur = inner;
    }
    cur
}

/// M4 vacuity test: returns `true` iff `type_`, after peeling outer `Pi`
/// binders (universal quantifiers and hypotheses) and metadata, is an
/// `Eq`/`HEq` application whose two **value sides are syntactically identical**
/// (`Expr`'s `PartialEq` is structural). Such a type is a vacuous `Eq a a` — the
/// only equality a `refl`-rooted proof can inhabit *without* doing definitional
/// work. If the sides differ, the refl is discharging a real computation
/// (`Nat.add n 0 = n`) and is genuine; if the head is not `Eq`/`HEq`, M4 does
/// not apply (a refl of some other reflexive relation is out of scope here).
pub(super) fn equality_has_identical_sides(type_: &Expr) -> bool {
    // Peel outer Pi binders and metadata to reach the equality body.
    let mut cur = type_;
    loop {
        match cur.kind() {
            ExprKind::Pi(_, _, body) => cur = body,
            ExprKind::MData(_, inner) => cur = inner,
            _ => break,
        }
    }
    let (head, args) = collect_app_args(cur);
    let name = match head_const(head) {
        Some(n) => n.to_string(),
        None => return false,
    };
    match name.as_str() {
        // `@Eq T lhs rhs` — the two value sides are the last two args.
        "Eq" => {
            let n = args.len();
            n >= 2 && args[n - 2] == args[n - 1]
        }
        // `@HEq A a B b` — the two value sides are `a` (args[n-3]) and `b`
        // (args[n-1]). We compare only the values; if the types differ the sides
        // are heterogeneous and not a vacuous identity.
        "HEq" => {
            let n = args.len();
            n >= 4 && args[n - 3] == args[n - 1]
        }
        _ => false,
    }
}

/// Return `true` iff `expr` uses `BVar(target)` anywhere in its tree.
/// Shifts the target index as it descends under new binders.
pub(super) fn expr_uses_bvar(expr: &Expr, target: u32) -> bool {
    let mut stack: Vec<(&Expr, u32)> = vec![(expr, target)];
    while let Some((e, t)) = stack.pop() {
        match e.kind() {
            ExprKind::BVar(idx) if *idx == t => {
                return true;
            }
            ExprKind::App(f, a) => {
                stack.push((f, t));
                stack.push((a, t));
            }
            ExprKind::Lam(_, ty, body) | ExprKind::Pi(_, ty, body) => {
                stack.push((ty, t));
                stack.push((body, t + 1));
            }
            ExprKind::Let(_, ty, val, body, _) => {
                stack.push((ty, t));
                stack.push((val, t));
                stack.push((body, t + 1));
            }
            ExprKind::Proj(_, _, inner) | ExprKind::MData(_, inner) => {
                stack.push((inner, t));
            }
            _ => {}
        }
    }
    false
}

/// M3 STRUCTURAL DIAGNOSTIC (non-gating): walk the proof term looking for
/// applications of a recursor in `RECURSORS_WITH_IH`. For each such application,
/// extract the motive (at the recorded argument index) and inspect each minor
/// premise that follows it. Reports the recursor name when a minor binds a
/// genuine induction hypothesis — a binder whose TYPE is an application of that
/// motive (`ih : motive k`) — that the body never uses. A BASE minor with no
/// motive-application binder is never reported, even if it ignores all of its
/// binders.
///
/// NOTE: this is a proof-STYLE observation, NOT a masquerade/soundness check —
/// `check_proof_nontrivial` deliberately does NOT push its result (see the
/// SOUNDNESS note there). It is retained, with full unit-test coverage of the
/// De Bruijn analysis, for diagnostic/tooling use only.
///
/// Returns the name of the first such recursor found, or `None`.
#[allow(dead_code)]
pub(super) fn find_unused_ih(proof: &Expr) -> Option<Name> {
    let mut stack: Vec<&Expr> = vec![proof];
    while let Some(e) = stack.pop() {
        let (head, args) = collect_app_args(e);
        if let Some(name) = head_const(head) {
            let name_str = name.to_string();
            if let Some(&(_, mot_idx)) = RECURSORS_WITH_IH.iter().find(|(r, _)| name_str == *r) {
                // Need the motive (and at least one following arg) to classify.
                if args.len() > mot_idx {
                    let motive = args[mot_idx];
                    for &arg in &args[mot_idx + 1..] {
                        if minor_premise_ignores_ih(arg, motive) {
                            return Some(name.clone());
                        }
                    }
                }
            }
        }
        // Recurse into sub-expressions.
        match e.kind() {
            ExprKind::App(f, a) => {
                stack.push(f);
                stack.push(a);
            }
            ExprKind::Lam(_, ty, body) | ExprKind::Pi(_, ty, body) => {
                stack.push(ty);
                stack.push(body);
            }
            ExprKind::Let(_, ty, val, body, _) => {
                stack.push(ty);
                stack.push(val);
                stack.push(body);
            }
            ExprKind::Proj(_, _, inner) | ExprKind::MData(_, inner) => stack.push(inner),
            _ => {}
        }
    }
    None
}

/// Inspect a single minor-premise candidate (`fun b₀ … b_{r-1} => body`)
/// against the recursor's `motive`. Returns `true` iff some binder is a genuine
/// induction hypothesis (its type is an application of `motive`) AND that binder
/// is unused in `body`. A minor with NO motive-application binder is a BASE case
/// and returns `false` — this is the over-fire fix: a base minor legitimately
/// binds the motive's own hypotheses and uses none, but it has no IH to ignore.
///
/// `minor` and `motive` are sibling arguments of the same recursor application,
/// so they live at the same context depth; [`binder_is_ih`] lifts the motive to
/// each binder's depth before matching.
#[allow(dead_code)]
fn minor_premise_ignores_ih(minor: &Expr, motive: &Expr) -> bool {
    // Collect the minor's binder types (skipping metadata) and the inner body.
    let mut binder_types: Vec<&Expr> = Vec::new();
    let mut cur = minor;
    loop {
        match cur.kind() {
            ExprKind::Lam(_, ty, body) => {
                binder_types.push(ty);
                cur = body;
            }
            ExprKind::MData(_, inner) => cur = inner,
            _ => break,
        }
    }
    let body = cur;
    let r = binder_types.len();
    if r == 0 {
        return false;
    }
    for (p, &ty) in binder_types.iter().enumerate() {
        if binder_is_ih(motive, ty, p) {
            // The binder at premise-position `p` (0 = outermost) is BVar(r-1-p)
            // as seen from the fully-peeled `body`.
            let bvar_idx = (r - 1 - p) as u32;
            if !expr_uses_bvar(body, bvar_idx) {
                return true;
            }
        }
    }
    false
}

/// Returns `true` iff `binder_ty` is an application of `motive` — i.e. the
/// binder it types is a genuine induction hypothesis `ih : motive k`. `p` is the
/// binder's premise-position, used to lift the motive (a sibling argument of the
/// recursor) to the binder's De Bruijn depth.
///
/// Two forms are accepted:
///   - **Form 1 (verbatim application):** `binder_ty` is `motive` applied to ≥1
///     argument — its app-spine head equals the (lifted) motive expression.
///     Covers non-lambda motives and not-yet-β-reduced lambda motives.
///   - **Form 2 (β-reduced lambda motive):** the motive is `fun p₁ … p_j => B`
///     and `binder_ty` is `B` with the parameters substituted away. We
///     structurally match the motive body `B` against `binder_ty` treating the
///     `j` motive parameters as wildcards (see [`template_match`]).
#[allow(dead_code)]
fn binder_is_ih(motive: &Expr, binder_ty: &Expr, p: usize) -> bool {
    let motive_p = motive.lift(p as u32);

    // Form 1: verbatim application of the motive.
    let (head, head_args) = collect_app_args(binder_ty);
    if !head_args.is_empty() && strip_mdata(head) == &motive_p {
        return true;
    }

    // Form 2: β-reduced lambda motive.
    let (motive_body, j) = peel_lambdas(&motive_p);
    let motive_body = strip_mdata(motive_body);
    if j == 0 {
        // Non-lambda motive: only the verbatim application form (above) applies.
        return false;
    }
    // Degenerate guard: if the motive body is a bare parameter variable the
    // template would be a pure wildcard matching every binder type. A
    // Sort-valued motive over a data type never has such a body, so refuse.
    if let ExprKind::BVar(idx) = motive_body.kind() {
        if (*idx as usize) < j {
            return false;
        }
    }
    template_match(motive_body, binder_ty, j, 0)
}

/// Structurally match a motive-body template `tmpl` against a candidate binder
/// type `targ`. `tmpl` is `motive.lift(p)` with its `j` outer lambdas peeled, so
/// its `j` innermost bound variables are the motive's parameters and act as
/// WILDCARDS (they were substituted away when the motive was applied). Every
/// other node must match structurally, with `tmpl`'s free variables (those that
/// outlive the motive's own `j` binders) shifted DOWN by `j` — the count of
/// lambdas that `targ` does not bind. `local` counts binders entered in lockstep
/// on both sides during the walk.
#[allow(dead_code)]
fn template_match(tmpl: &Expr, targ: &Expr, j: usize, local: usize) -> bool {
    let tmpl = strip_mdata(tmpl);
    let targ = strip_mdata(targ);
    match (tmpl.kind(), targ.kind()) {
        (ExprKind::BVar(ti), _) => {
            let ti = *ti as usize;
            if ti < local {
                // Bound by a binder entered inside the template body.
                matches!(targ.kind(), ExprKind::BVar(uj) if *uj as usize == ti)
            } else if ti - local < j {
                // Motive parameter → wildcard: matches any target subterm.
                true
            } else {
                // Free variable: present in `targ` shifted down by `j`.
                matches!(targ.kind(), ExprKind::BVar(uj) if *uj as usize == ti - j)
            }
        }
        (ExprKind::App(tf, ta), ExprKind::App(uf, ua)) => {
            template_match(tf, uf, j, local) && template_match(ta, ua, j, local)
        }
        (ExprKind::Lam(_, tt, tb), ExprKind::Lam(_, ut, ub))
        | (ExprKind::Pi(_, tt, tb), ExprKind::Pi(_, ut, ub)) => {
            template_match(tt, ut, j, local) && template_match(tb, ub, j, local + 1)
        }
        (ExprKind::Proj(tn, ti, te), ExprKind::Proj(un, ui, ue)) => {
            tn == un && ti == ui && template_match(te, ue, j, local)
        }
        (ExprKind::Let(_, tt, tv, tb, _), ExprKind::Let(_, ut, uv, ub, _)) => {
            template_match(tt, ut, j, local)
                && template_match(tv, uv, j, local)
                && template_match(tb, ub, j, local + 1)
        }
        // Leaves (Const/Sort/Lit/FVar/…) and kind mismatches: exact structural
        // equality is the correct conservative test — there are no wildcards or
        // free De Bruijn references to re-base inside these.
        _ => tmpl == targ,
    }
}

/// M2 detector: for each reducible Definition named in `type_`, inspect its
/// body. If the body has shape `fun x₁ … xₙ => xᵢ` (identity on one arg) or
/// `fun x₁ … xₙ => const_expr` (constant — no argument bound-var used),
/// report it.
fn argument_discarding_carriers(env: &Environment, type_: &Expr) -> Vec<(Name, String)> {
    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    let mut stack: Vec<&Expr> = vec![type_];
    while let Some(e) = stack.pop() {
        match e.kind() {
            ExprKind::Const(name, _) => {
                if !seen.insert(name.clone()) {
                    continue;
                }
                if let Some(info) = env.get_const(name) {
                    if info.kind == ConstantKind::Definition && info.is_reducible {
                        if let Some(body_shape) = classify_discarding_body(info) {
                            out.push((name.clone(), body_shape));
                        }
                    }
                }
            }
            ExprKind::App(f, a) => {
                stack.push(f);
                stack.push(a);
            }
            ExprKind::Lam(_, ty, body) | ExprKind::Pi(_, ty, body) => {
                stack.push(ty);
                stack.push(body);
            }
            ExprKind::Let(_, ty, val, body, _) => {
                stack.push(ty);
                stack.push(val);
                stack.push(body);
            }
            ExprKind::Proj(_, _, inner) | ExprKind::MData(_, inner) => stack.push(inner),
            _ => {}
        }
    }
    out
}

/// Returns a description of an offending body shape, or `None` if the
/// Definition is not argument-discarding. Shapes:
/// - `fun x₁ … xₙ => xᵢ` → "identity on arg i"
/// - `fun x₁ … xₙ => K` where K doesn't use any bound var → "constant"
///   Only fires for `n ≥ 1` (zero-arg Definitions can't discard arguments).
pub(super) fn classify_discarding_body(info: &ConstantInfo) -> Option<String> {
    let value = info.value.as_ref()?;
    let (body, n) = peel_lambdas(value);
    if n == 0 {
        return None;
    }
    // Identity on argument i: body is a bare BVar in [0, n).
    if let ExprKind::BVar(idx) = body.kind() {
        if (*idx as usize) < n {
            return Some(format!(
                "identity on arg {} (λ {} binders, body = BVar({}))",
                n - 1 - (*idx as usize),
                n,
                idx
            ));
        }
    }
    // Constant: no bound var in [0, n) is used in the body.
    let mut uses_any = false;
    for i in 0..n {
        if expr_uses_bvar(body, i as u32) {
            uses_any = true;
            break;
        }
    }
    if !uses_any {
        return Some(format!("constant body (λ {} binders, none referenced)", n));
    }
    None
}

/// M1 detector: extract the outermost `Eq`-like application from `type_`
/// (shape `Eq T lhs rhs` with any number of leading implicit type-class
/// args), then check whether both `lhs` and `rhs` are headed by the same
/// reducible `Definition` applied to arguments that make them syntactically
/// identical after a single δ-step. This is a **syntactic** approximation
/// of whnf-equality — sufficient for the canonical carriers seen in the
/// gamma-crown audit (`IB`, `Block.compose`, `LayerNorm.generators_after_ln`)
/// without invoking the full type-checker machinery.
fn alias_collapse_witness(env: &Environment, type_: &Expr) -> Option<Name> {
    // Strip leading Pi binders (`∀ n k …, Eq T lhs rhs`) to reach the Eq.
    let mut cur = type_;
    loop {
        match cur.kind() {
            ExprKind::Pi(_, _, body) => cur = body,
            ExprKind::MData(_, inner) => cur = inner,
            _ => break,
        }
    }
    let (head, args) = collect_app_args(cur);
    let head_name = head_const(head)?.to_string();
    if head_name != "Eq" && head_name != "HEq" {
        return None;
    }
    // Eq T lhs rhs — last two args are the sides.
    if args.len() < 2 {
        return None;
    }
    let lhs = args[args.len() - 2];
    let rhs = args[args.len() - 1];

    // Check whether both sides are headed by the same reducible Definition.
    let (lhs_head, lhs_args) = collect_app_args(lhs);
    let (rhs_head, rhs_args) = collect_app_args(rhs);
    let lhs_const = head_const(lhs_head)?;
    let rhs_const = head_const(rhs_head)?;
    if lhs_const != rhs_const {
        return None;
    }
    let info = env.get_const(lhs_const)?;
    if info.kind != ConstantKind::Definition || !info.is_reducible {
        return None;
    }
    // Require structural equality of arg lists (#3604): commutativity
    // and associativity share the head but differ in args, not aliases.
    if lhs_args.len() != rhs_args.len() || lhs_args.iter().zip(&rhs_args).any(|(la, ra)| la != ra) {
        return None;
    }
    Some(lhs_const.clone())
}

#[cfg(test)]
#[path = "tests_proof_quality.rs"]
mod tests;
