// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! FATE Mathlib stubs: generic Prime, IsPrincipalIdealRing, Polynomial.

use crate::env::decl_builder::EnvDeclBuilder;
use crate::env::{Declaration, EnvError, Environment};
use crate::expr::{BinderInfo, Expr, ExprKind};
use crate::level::Level;
use crate::name::Name;

impl Environment {
    // ==========================================================================
    // FATE Mathlib Stubs (#91)
    // These stubs enable FATE benchmark evaluation without full Mathlib support.
    // ==========================================================================

    /// Initialize generic Prime predicate
    ///
    /// Prime : {α : Type u} → [CommMonoidWithZero α] → α → Prop
    /// Prime p means: p is nonzero, not a unit, and if p ∣ ab then p ∣ a or p ∣ b
    ///
    /// This is a stub for FATE benchmark support - provides the typeclass signature
    /// without full Mathlib implementation.
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: On success, `self.prime_init == true`
    /// ENSURES: Idempotent - calling multiple times returns `Ok(())` without duplication
    pub fn init_prime(&mut self) -> Result<(), EnvError> {
        if self.prime_init {
            return Ok(());
        }

        // Dependencies
        self.init_eq()?;

        let u = Name::from_string("u");
        let u_level = Level::param(u.clone());
        let type_u = Expr::sort(Level::succ(u_level.clone())); // Type u = Sort (u+1) // Type u
        let prop = Expr::from_kind(ExprKind::Sort(Level::zero()));

        // Prime : {α : Type u} → α → Prop
        let prime_type = {
            let mut b = EnvDeclBuilder::new();
            let (alpha_id, alpha) = b.fresh_local(type_u.clone());
            let (p_id, _) = b.fresh_local(alpha.clone());
            let r = b.mk_pi(p_id, BinderInfo::Default, alpha, prop.clone());
            let r = b.mk_pi(alpha_id, BinderInfo::Implicit, type_u.clone(), r);
            b.finish(r)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Prime"),
            level_params: vec![u.clone()],
            type_: prime_type,
        })?;

        // Prime.ne_zero : ∀ {α} {p : α}, Prime p → p ≠ 0
        // (Stub - simplified without CommMonoidWithZero instance)

        // Prime.not_unit : ∀ {α} {p : α}, Prime p → ¬IsUnit p
        // (Stub - simplified)

        // Prime.dvd_or_dvd : ∀ {α} {p a b : α}, Prime p → p ∣ a * b → p ∣ a ∨ p ∣ b
        // (Stub - simplified)

        self.prime_init = true;
        Ok(())
    }

    /// Check if generic Prime has been initialized
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: Returns `true` iff `self.prime_init == true`
    pub fn has_prime(&self) -> bool {
        self.prime_init
    }

    /// Initialize IsPrincipalIdealRing typeclass
    ///
    /// IsPrincipalIdealRing : (R : Type u) → [Ring R] → Prop
    /// A principal ideal ring is a ring where every ideal is generated by a single element.
    ///
    /// This is a stub for FATE benchmark support.
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: On success, `self.is_principal_ideal_ring_init == true`
    /// ENSURES: Idempotent - calling multiple times returns `Ok(())` without duplication
    pub fn init_is_principal_ideal_ring(&mut self) -> Result<(), EnvError> {
        if self.is_principal_ideal_ring_init {
            return Ok(());
        }

        // Dependencies
        self.init_ring()?;

        let u = Name::from_string("u");
        let u_level = Level::param(u.clone());
        let type_u = Expr::sort(Level::succ(u_level.clone())); // Type u = Sort (u+1) // Type u
        let prop = Expr::from_kind(ExprKind::Sort(Level::zero()));

        // IsPrincipalIdealRing : (R : Type u) → [Ring R] → Prop
        // For stub purposes, we simplify to: IsPrincipalIdealRing : Type u → Prop
        let pir_type = Expr::pi(
            BinderInfo::Default,
            type_u.clone(), // (R : Type u)
            prop.clone(),   // → Prop
        );

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("IsPrincipalIdealRing"),
            level_params: vec![u.clone()],
            type_: pir_type,
        })?;

        // Key theorem for UFD problems:
        // IsPrincipalIdealRing.of_ufd : ∀ {R} [UFD R] [two_primes : has_only_two_primes R],
        //   IsPrincipalIdealRing R
        // This is the kind of thing FATE-X problems prove

        self.is_principal_ideal_ring_init = true;
        Ok(())
    }

    /// Check if IsPrincipalIdealRing has been initialized
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: Returns `true` iff `self.is_principal_ideal_ring_init == true`
    pub fn has_is_principal_ideal_ring(&self) -> bool {
        self.is_principal_ideal_ring_init
    }

    /// Initialize Polynomial type
    ///
    /// Polynomial : (R : Type u) → [Semiring R] → Type u
    /// The type of univariate polynomials over R.
    ///
    /// This is a stub for FATE benchmark support.
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: On success, `self.polynomial_init == true`
    /// ENSURES: Idempotent - calling multiple times returns `Ok(())` without duplication
    pub fn init_polynomial(&mut self) -> Result<(), EnvError> {
        if self.polynomial_init {
            return Ok(());
        }

        // Dependencies
        self.init_semiring()?;
        self.init_nat()?; // Polynomial.natDegree : Polynomial R → Nat
        self.init_prod()?; // Polynomial.divMod returns Prod (Polynomial R) (Polynomial R)

        let u = Name::from_string("u");
        let u_level = Level::param(u.clone());
        let type_u = Expr::sort(Level::succ(u_level.clone())); // Type u = Sort (u+1) // Type u

        // WithBot : Type u → Type u (needed for Polynomial.degree)
        // Declare inline if not already present, to avoid pulling in
        // init_fate_x_order_stubs which has its own unresolved dependencies.
        if self.get_const(&Name::from_string("WithBot")).is_none() {
            let with_bot_type = Expr::pi(BinderInfo::Default, type_u.clone(), type_u.clone());
            self.add_decl(Declaration::Axiom {
                name: Name::from_string("WithBot"),
                level_params: vec![u.clone()],
                type_: with_bot_type,
            })?;
        }

        // Polynomial : (R : Type u) → Type u
        // Simplified stub without Semiring instance
        let poly_type = Expr::pi(
            BinderInfo::Default,
            type_u.clone(), // (R : Type u)
            type_u.clone(), // → Type u
        );

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial"),
            level_params: vec![u.clone()],
            type_: poly_type,
        })?;

        // Helper: Polynomial R for a given R
        let mk_poly_r = |r: &Expr| -> Expr {
            Expr::app(
                Expr::const_(Name::from_string("Polynomial"), vec![u_level.clone()]),
                r.clone(),
            )
        };

        // Polynomial.X : ∀ {R}, Polynomial R
        let poly_x_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), mk_poly_r(&r));
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.X"),
            level_params: vec![u.clone()],
            type_: poly_x_type,
        })?;

        // Polynomial.C : ∀ {R}, R → Polynomial R
        let poly_c_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let (x_id, _) = b.fresh_local(r.clone());
            let result = b.mk_pi(x_id, BinderInfo::Default, r.clone(), mk_poly_r(&r));
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), result);
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.C"),
            level_params: vec![u.clone()],
            type_: poly_c_type,
        })?;

        // Polynomial.natDegree : ∀ {R}, Polynomial R → ℕ
        let nat = Expr::const_(Name::from_string("Nat"), vec![]);
        let poly_natdegree_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let (p_id, _) = b.fresh_local(mk_poly_r(&r));
            let result = b.mk_pi(p_id, BinderInfo::Default, mk_poly_r(&r), nat.clone());
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), result);
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.natDegree"),
            level_params: vec![u.clone()],
            type_: poly_natdegree_type,
        })?;

        // Polynomial.degree : ∀ {R}, Polynomial R → WithBot ℕ
        let withbot_nat = Expr::app(
            Expr::const_(Name::from_string("WithBot"), vec![Level::zero()]),
            nat.clone(),
        );
        let poly_degree_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let (p_id, _) = b.fresh_local(mk_poly_r(&r));
            let result = b.mk_pi(
                p_id,
                BinderInfo::Default,
                mk_poly_r(&r),
                withbot_nat.clone(),
            );
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), result);
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.degree"),
            level_params: vec![u.clone()],
            type_: poly_degree_type,
        })?;

        // Polynomial.leadingCoeff : ∀ {R}, Polynomial R → R
        let poly_leadingcoeff_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let (p_id, _) = b.fresh_local(mk_poly_r(&r));
            let result = b.mk_pi(p_id, BinderInfo::Default, mk_poly_r(&r), r.clone());
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), result);
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.leadingCoeff"),
            level_params: vec![u.clone()],
            type_: poly_leadingcoeff_type,
        })?;

        // Polynomial.div : ∀ {R}, Polynomial R → Polynomial R → Polynomial R
        let poly_div_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let poly_r_ty = mk_poly_r(&r);
            let (p_id, _) = b.fresh_local(poly_r_ty.clone());
            let (q_id, _) = b.fresh_local(poly_r_ty.clone());
            let result = b.mk_pi(
                q_id,
                BinderInfo::Default,
                poly_r_ty.clone(),
                poly_r_ty.clone(),
            );
            let result = b.mk_pi(p_id, BinderInfo::Default, poly_r_ty, result);
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), result);
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.div"),
            level_params: vec![u.clone()],
            type_: poly_div_type.clone(),
        })?;

        // Polynomial.mod : ∀ {R}, Polynomial R → Polynomial R → Polynomial R
        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.mod"),
            level_params: vec![u.clone()],
            type_: poly_div_type.clone(),
        })?;

        // Polynomial.divMod : ∀ {R}, Polynomial R → Polynomial R → Polynomial R × Polynomial R
        let poly_divmod_type = {
            let mut b = EnvDeclBuilder::new();
            let (r_id, r) = b.fresh_local(type_u.clone());
            let poly_r_ty = mk_poly_r(&r);
            let poly_prod = Expr::app(
                Expr::app(
                    Expr::const_(
                        Name::from_string("Prod"),
                        vec![u_level.clone(), u_level.clone()],
                    ),
                    poly_r_ty.clone(),
                ),
                poly_r_ty.clone(),
            );
            let (p_id, _) = b.fresh_local(poly_r_ty.clone());
            let (q_id, _) = b.fresh_local(poly_r_ty.clone());
            let result = b.mk_pi(q_id, BinderInfo::Default, poly_r_ty.clone(), poly_prod);
            let result = b.mk_pi(p_id, BinderInfo::Default, poly_r_ty, result);
            let result = b.mk_pi(r_id, BinderInfo::Implicit, type_u.clone(), result);
            b.finish(result)
        };

        self.add_decl(Declaration::Axiom {
            name: Name::from_string("Polynomial.divMod"),
            level_params: vec![u.clone()],
            type_: poly_divmod_type,
        })?;

        self.polynomial_init = true;
        Ok(())
    }

    /// Check if Polynomial has been initialized
    ///
    /// # Contract
    ///
    /// REQUIRES: `self` is a valid Environment instance
    /// ENSURES: Returns `true` iff `self.polynomial_init == true`
    pub fn has_polynomial(&self) -> bool {
        self.polynomial_init
    }
}
