// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! End-to-end tests for the omega Nat-**equality**-from-hypotheses path.
//!
//! Closes `hyp_eq_collection`: omega now proves a linear Nat equality goal
//! `glhs = grhs` when it FOLLOWS from hypothesis equalities `{hi : ai = bi}`, by
//! synthesizing a kernel-checked `congrArg` / `Eq.trans` / `Eq.symm` chain. The
//! decision gate reduces `glhs - grhs` against the integer lattice generated by
//! `{ai - bi}`; if it does not vanish the synthesizer returns `None` and omega
//! fails closed.
//!
//! Soundness teeth (every false / non-following goal MUST be rejected):
//! - PROVE: `(h : a = b) ⊢ a + 1 = b + 1`, `(h : a = b) ⊢ a + c = b + c`,
//!   `(h1 : a = b)(h2 : b = c) ⊢ a + 1 = c + 1`, `(h : a = b) ⊢ b = a`, and the
//!   goal-only `a + b = b + a` (no hyp) all close with ZERO trusted axioms.
//! - NEGATIVE: `(h : a = b) ⊢ a = c` (c free), `(h : a = b) ⊢ a + 1 = c + 1`
//!   (c unrelated), and the no-hyp `a + 1 = b + 1` (a ≠ b) ALL fail closed.
//! - KERNEL CHECK: the synthesized term for `(h : a = b) ⊢ a + 1 = b + 1`
//!   type-checks against the goal via a real `clean_kernel::TypeChecker` with a
//!   constant closure free of `trustedAy` / `trustedArith` / `sorry`.

use super::*;
use crate::tactic::arith_linarith_nat_eq::try_prove_nat_equality_from_hyps;
use clean_kernel::level::Level;
use clean_kernel::tc::TypeChecker;
use clean_kernel::Expr;
use serial_test::serial;
use std::collections::HashSet;

fn nat_type() -> Expr {
    Expr::const_(Name::from_string("Nat"), vec![])
}

fn nat_fvar(id: u64) -> Expr {
    Expr::fvar(FVarId::new(id))
}

fn nat_local(id: u64, name: &str) -> LocalDecl {
    LocalDecl {
        fvar: FVarId::new(id),
        name: name.to_string(),
        ty: nat_type(),
        value: None,
    }
}

fn nat_add(lhs: Expr, rhs: Expr) -> Expr {
    Expr::app(
        Expr::app(Expr::const_(Name::from_string("Nat.add"), vec![]), lhs),
        rhs,
    )
}

/// `@Eq Nat l r`.
fn nat_eq(l: Expr, r: Expr) -> Expr {
    Expr::apps(
        Expr::const_(Name::from_string("Eq"), vec![Level::succ(Level::zero())]),
        [nat_type(), l, r],
    )
}

fn eq_hyp(id: u64, name: &str, l: Expr, r: Expr) -> LocalDecl {
    LocalDecl {
        fvar: FVarId::new(id),
        name: name.to_string(),
        ty: nat_eq(l, r),
        value: None,
    }
}

fn collect_const_names(e: &Expr, out: &mut HashSet<String>) {
    use clean_kernel::expr::ExprKind;
    match e.kind() {
        ExprKind::Const(name, _) => {
            out.insert(name.to_string());
        }
        ExprKind::App(f, a) => {
            collect_const_names(f, out);
            collect_const_names(a, out);
        }
        ExprKind::Lam(_, ty, body) | ExprKind::Pi(_, ty, body) => {
            collect_const_names(ty, out);
            collect_const_names(body, out);
        }
        ExprKind::Let(_, ty, val, body, _) => {
            collect_const_names(ty, out);
            collect_const_names(val, out);
            collect_const_names(body, out);
        }
        _ => {}
    }
}

fn assert_omega_proves(mut state: ProofState, label: &str) -> ProofState {
    reset_all_counters();
    let axiom_before = axiom_snapshot();
    let result = omega(&mut state);
    assert!(
        result.is_ok(),
        "omega should prove `{label}`, got: {result:?}"
    );
    assert!(
        state.is_complete(),
        "goal `{label}` should be closed after omega succeeds"
    );
    assert_no_trusted_axiom_usage("omega", label, axiom_before);
    let ledger = state.trust_ledger();
    assert_eq!(
        ledger.trusted_arith_count, 0,
        "`{label}`: omega must not use trustedArith"
    );
    assert_eq!(
        ledger.trusted_ay_count, 0,
        "`{label}`: omega must not use trustedAy"
    );
    assert_eq!(
        ledger.sorry_count, 0,
        "`{label}`: omega must produce a real proof term (no sorry)"
    );
    state
}

fn assert_omega_rejects(mut state: ProofState, label: &str) {
    reset_all_counters();
    let result = omega(&mut state);
    assert!(
        result.is_err() && !state.is_complete(),
        "omega must REJECT the non-following goal `{label}`, but it closed: {result:?}"
    );
}

// ---------------------------------------------------------------------------
// PROVE: goals that genuinely follow from the hypothesis equalities.
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn test_omega_proves_a_eq_b_implies_a_plus_1_eq_b_plus_1() {
    // a b : Nat, h : a = b  ⊢  a + 1 = b + 1   (single-hyp congruence)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(
        nat_add(a.clone(), Expr::nat_lit(1)),
        nat_add(b.clone(), Expr::nat_lit(1)),
    );
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), nat_local(1, "b"), eq_hyp(2, "h", a, b)],
    );
    assert_omega_proves(state, "(h : a = b) ⊢ a + 1 = b + 1");
}

#[test]
#[serial]
fn test_omega_proves_a_eq_b_implies_a_plus_c_eq_b_plus_c() {
    // a b c : Nat, h : a = b  ⊢  a + c = b + c   (congrArg right-motive)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let c = nat_fvar(2);
    let goal = nat_eq(nat_add(a.clone(), c.clone()), nat_add(b.clone(), c));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            nat_local(2, "c"),
            eq_hyp(3, "h", a, b),
        ],
    );
    assert_omega_proves(state, "(h : a = b) ⊢ a + c = b + c");
}

#[test]
#[serial]
fn test_omega_proves_threaded_a_eq_b_b_eq_c_implies_a_plus_1_eq_c_plus_1() {
    // a b c : Nat, h1 : a = b, h2 : b = c  ⊢  a + 1 = c + 1  (trans + congr)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let c = nat_fvar(2);
    let goal = nat_eq(
        nat_add(a.clone(), Expr::nat_lit(1)),
        nat_add(c.clone(), Expr::nat_lit(1)),
    );
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            nat_local(2, "c"),
            eq_hyp(3, "h1", a, b.clone()),
            eq_hyp(4, "h2", b, c),
        ],
    );
    assert_omega_proves(state, "(h1 : a = b)(h2 : b = c) ⊢ a + 1 = c + 1");
}

#[test]
#[serial]
fn test_omega_proves_b_eq_a_from_a_eq_b() {
    // a b : Nat, h : a = b  ⊢  b = a   (Eq.symm)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(b.clone(), a.clone());
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), nat_local(1, "b"), eq_hyp(2, "h", a, b)],
    );
    assert_omega_proves(state, "(h : a = b) ⊢ b = a");
}

#[test]
#[serial]
fn test_omega_proves_goal_only_add_comm_still_works() {
    // a b : Nat  ⊢  a + b = b + a   (the d0255ecd goal-only case, no hyp)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(nat_add(a.clone(), b.clone()), nat_add(b, a));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), nat_local(1, "b")],
    );
    assert_omega_proves(state, "a + b = b + a");
}

// ---------------------------------------------------------------------------
// NEGATIVE TEETH: non-following / false goals must ALL fail closed.
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn test_omega_rejects_a_eq_c_from_a_eq_b() {
    // a b c : Nat, h : a = b  ⊢  a = c   (c free; D = a - c does not vanish)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let c = nat_fvar(2);
    let goal = nat_eq(a.clone(), c);
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            nat_local(2, "c"),
            eq_hyp(3, "h", a, b),
        ],
    );
    assert_omega_rejects(state, "(h : a = b) ⊢ a = c");
}

#[test]
#[serial]
fn test_omega_rejects_a_plus_1_eq_c_plus_1_from_a_eq_b() {
    // a b c : Nat, h : a = b  ⊢  a + 1 = c + 1   (c unrelated)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let c = nat_fvar(2);
    let goal = nat_eq(
        nat_add(a.clone(), Expr::nat_lit(1)),
        nat_add(c, Expr::nat_lit(1)),
    );
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            nat_local(2, "c"),
            eq_hyp(3, "h", a, b),
        ],
    );
    assert_omega_rejects(state, "(h : a = b) ⊢ a + 1 = c + 1");
}

#[test]
#[serial]
fn test_omega_rejects_no_hyp_a_plus_1_eq_b_plus_1() {
    // a b : Nat  ⊢  a + 1 = b + 1   (NO hyp; a ≠ b)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(
        nat_add(a.clone(), Expr::nat_lit(1)),
        nat_add(b.clone(), Expr::nat_lit(1)),
    );
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), nat_local(1, "b")],
    );
    assert_omega_rejects(state, "a + 1 = b + 1 (no hyp)");
}

// ---------------------------------------------------------------------------
// KERNEL TEETH: the synthesized term type-checks and is axiom-clean.
// ---------------------------------------------------------------------------

/// The synthesized term for `(h : a = b) ⊢ a + 1 = b + 1` type-checks against
/// the goal via a real kernel `TypeChecker`, with a constant closure free of any
/// trust axiom.
#[test]
#[serial]
fn test_omega_hyp_eq_term_kernel_checks_and_axiom_closure_clean() {
    // Build the goal/hyp over GLOBAL Nat constants so the bare-env kernel
    // TypeChecker (no local context) can check it; the prover matches on syntax.
    let mut env = Environment::with_prelude();
    for nm in ["a", "b"] {
        env.add_decl(Declaration::Axiom {
            name: Name::from_string(nm),
            level_params: vec![],
            type_: nat_type(),
        })
        .expect("Nat axiom should add");
    }
    let a = Expr::const_(Name::from_string("a"), vec![]);
    let b = Expr::const_(Name::from_string("b"), vec![]);
    // h : a = b  (a global proof axiom of the equality)
    env.add_decl(Declaration::Axiom {
        name: Name::from_string("h"),
        level_params: vec![],
        type_: nat_eq(a.clone(), b.clone()),
    })
    .expect("h : a = b axiom should add");
    let h = Expr::const_(Name::from_string("h"), vec![]);

    let goal = nat_eq(
        nat_add(a.clone(), Expr::nat_lit(1)),
        nat_add(b.clone(), Expr::nat_lit(1)),
    );

    let term = try_prove_nat_equality_from_hyps(&goal, &[(h, nat_eq(a, b))])
        .expect("prover should synthesize a term for `(h : a = b) ⊢ a + 1 = b + 1`");

    let tc = TypeChecker::with_mode(&env, env.mode());
    let inferred = tc
        .infer_type(&term)
        .expect("synthesized term must type-check in the kernel");
    tc.check_type(&term, &goal).unwrap_or_else(|err| {
        panic!(
            "synthesized term must check at the goal `a + 1 = b + 1`: {err:?}\n  inferred = {inferred:?}\n  goal     = {goal:?}"
        )
    });

    let mut consts = HashSet::new();
    collect_const_names(&term, &mut consts);
    for forbidden in ["trustedAy", "trustedArith", "sorry", "sorryAx"] {
        assert!(
            !consts.contains(forbidden),
            "synthesized term must not reference `{forbidden}`; closure = {consts:?}"
        );
    }
    assert!(
        consts.contains("congrArg"),
        "single-hyp congruence term should use congrArg; closure = {consts:?}"
    );
}

// ---------------------------------------------------------------------------
// UNIT TEETH on the synthesizer directly (no ProofState).
// ---------------------------------------------------------------------------

#[test]
fn test_synth_returns_none_for_non_following_goal() {
    // (h : a = b) ⊢ a = c  — must be None.
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let c = nat_fvar(2);
    let goal = nat_eq(a.clone(), c);
    assert!(
        try_prove_nat_equality_from_hyps(&goal, &[(nat_fvar(3), nat_eq(a, b))]).is_none(),
        "a = c does not follow from a = b; must be None"
    );
}

#[test]
fn test_synth_returns_some_for_following_goal() {
    // (h : a = b) ⊢ a + 1 = b + 1  — must be Some.
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(
        nat_add(a.clone(), Expr::nat_lit(1)),
        nat_add(b.clone(), Expr::nat_lit(1)),
    );
    assert!(
        try_prove_nat_equality_from_hyps(&goal, &[(nat_fvar(2), nat_eq(a, b))]).is_some(),
        "a + 1 = b + 1 follows from a = b; must be Some"
    );
}

// ---------------------------------------------------------------------------
// LITERAL-PINNING family (#omega-eq): equality hyps that PIN variables to
// ground values, driving equality / disequality / inequality / Nat.sub goals.
// Mirrors the reproduced gap: a goal beyond trivial direct/constant cases that
// must USE an equality hypothesis. Each PROVE asserts a closed, axiom-clean
// proof; each REJECT asserts fail-closed behaviour (soundness teeth).
// ---------------------------------------------------------------------------

/// `@GE.ge Nat instLENat a b` (`a ≥ b`).
fn nat_ge(a: Expr, b: Expr) -> Expr {
    Expr::apps(
        Expr::const_(Name::from_string("GE.ge"), vec![Level::zero()]),
        [
            nat_type(),
            Expr::const_(Name::from_string("instLENat"), vec![]),
            a,
            b,
        ],
    )
}

/// `@LE.le Nat instLENat a b` (`a ≤ b`).
fn nat_le(a: Expr, b: Expr) -> Expr {
    Expr::apps(
        Expr::const_(Name::from_string("LE.le"), vec![Level::zero()]),
        [
            nat_type(),
            Expr::const_(Name::from_string("instLENat"), vec![]),
            a,
            b,
        ],
    )
}

/// `@Ne Nat a b` (`a ≠ b`).
fn nat_ne(a: Expr, b: Expr) -> Expr {
    Expr::apps(
        Expr::const_(Name::from_string("Ne"), vec![Level::succ(Level::zero())]),
        [nat_type(), a, b],
    )
}

/// `Nat.sub a b` (`a - b`).
fn nat_sub(a: Expr, b: Expr) -> Expr {
    Expr::app(
        Expr::app(Expr::const_(Name::from_string("Nat.sub"), vec![]), a),
        b,
    )
}

fn ge_hyp(id: u64, name: &str, a: Expr, b: Expr) -> LocalDecl {
    LocalDecl {
        fvar: FVarId::new(id),
        name: name.to_string(),
        ty: nat_ge(a, b),
        value: None,
    }
}

#[test]
#[serial]
fn test_omega_proves_eq_hyp_drives_eq_goal_f1() {
    // a : Nat, h : a = 2  ⊢  a + 1 = 3
    let a = nat_fvar(0);
    let goal = nat_eq(nat_add(a.clone(), Expr::nat_lit(1)), Expr::nat_lit(3));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), eq_hyp(1, "h", a, Expr::nat_lit(2))],
    );
    assert_omega_proves(state, "(h : a = 2) ⊢ a + 1 = 3");
}

#[test]
#[serial]
fn test_omega_proves_two_eq_hyps_solve_for_b_f2() {
    // a b : Nat, h : a + b = 5, h2 : a = 2  ⊢  b = 3
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(b.clone(), Expr::nat_lit(3));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            eq_hyp(2, "h", nat_add(a.clone(), b), Expr::nat_lit(5)),
            eq_hyp(3, "h2", a, Expr::nat_lit(2)),
        ],
    );
    assert_omega_proves(state, "(h : a + b = 5)(h2 : a = 2) ⊢ b = 3");
}

#[test]
#[serial]
fn test_omega_proves_eq_hyps_drive_le_goal_f3() {
    // a b : Nat, h : a + b = 5, h2 : a = 2  ⊢  b ≤ 3
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_le(b.clone(), Expr::nat_lit(3));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            eq_hyp(2, "h", nat_add(a.clone(), b), Expr::nat_lit(5)),
            eq_hyp(3, "h2", a, Expr::nat_lit(2)),
        ],
    );
    assert_omega_proves(state, "(h : a + b = 5)(h2 : a = 2) ⊢ b ≤ 3");
}

#[test]
#[serial]
fn test_omega_proves_eq_hyp_drives_ne_goal_f4() {
    // a : Nat, h : a = 2  ⊢  a ≠ 3
    let a = nat_fvar(0);
    let goal = nat_ne(a.clone(), Expr::nat_lit(3));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), eq_hyp(1, "h", a, Expr::nat_lit(2))],
    );
    assert_omega_proves(state, "(h : a = 2) ⊢ a ≠ 3");
}

#[test]
#[serial]
fn test_omega_proves_ge_hyp_drives_sub_goal_f5() {
    // a : Nat, h : a ≥ 3  ⊢  a - 2 ≥ 1
    let a = nat_fvar(0);
    let goal = nat_ge(nat_sub(a.clone(), Expr::nat_lit(2)), Expr::nat_lit(1));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), ge_hyp(1, "h", a, Expr::nat_lit(3))],
    );
    assert_omega_proves(state, "(h : a ≥ 3) ⊢ a - 2 ≥ 1");
}

// SOUNDNESS TEETH: false goals over the same literal-pinning family MUST be
// rejected (no over-accept, no panic).

#[test]
#[serial]
fn test_omega_rejects_false_eq_hyp_eq_goal() {
    // a : Nat, h : a = 2  ⊢  a + 1 = 4   (FALSE: 2 + 1 = 3 ≠ 4)
    let a = nat_fvar(0);
    let goal = nat_eq(nat_add(a.clone(), Expr::nat_lit(1)), Expr::nat_lit(4));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), eq_hyp(1, "h", a, Expr::nat_lit(2))],
    );
    assert_omega_rejects(state, "(h : a = 2) ⊢ a + 1 = 4");
}

#[test]
#[serial]
fn test_omega_rejects_false_two_eq_hyps_solve_for_b() {
    // a b : Nat, h : a + b = 5, h2 : a = 2  ⊢  b = 4   (FALSE: b is 3)
    let a = nat_fvar(0);
    let b = nat_fvar(1);
    let goal = nat_eq(b.clone(), Expr::nat_lit(4));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![
            nat_local(0, "a"),
            nat_local(1, "b"),
            eq_hyp(2, "h", nat_add(a.clone(), b), Expr::nat_lit(5)),
            eq_hyp(3, "h2", a, Expr::nat_lit(2)),
        ],
    );
    assert_omega_rejects(state, "(h : a + b = 5)(h2 : a = 2) ⊢ b = 4");
}

#[test]
#[serial]
fn test_omega_rejects_false_ne_goal_a_eq_2_ne_2() {
    // a : Nat, h : a = 2  ⊢  a ≠ 2   (FALSE: a IS 2)
    let a = nat_fvar(0);
    let goal = nat_ne(a.clone(), Expr::nat_lit(2));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), eq_hyp(1, "h", a, Expr::nat_lit(2))],
    );
    assert_omega_rejects(state, "(h : a = 2) ⊢ a ≠ 2");
}

#[test]
#[serial]
fn test_omega_rejects_false_sub_goal() {
    // a : Nat, h : a ≥ 3  ⊢  a - 2 ≥ 2   (FALSE: a - 2 ≥ 1, not ≥ 2)
    let a = nat_fvar(0);
    let goal = nat_ge(nat_sub(a.clone(), Expr::nat_lit(2)), Expr::nat_lit(2));
    let state = ProofState::with_context(
        Environment::with_prelude(),
        goal,
        vec![nat_local(0, "a"), ge_hyp(1, "h", a, Expr::nat_lit(3))],
    );
    assert_omega_rejects(state, "(h : a ≥ 3) ⊢ a - 2 ≥ 2");
}
