// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! External certificate verification handlers.
//!
//! External certificates are proofs generated by external tools (e.g., SMT solvers)
//! that can be verified by the clean kernel. This module provides JSON-RPC handlers
//! for verifying Farkas certificates (proving linear constraint infeasibility) and
//! entailment certificates (proving bound derivability).

use super::state::ServerState;
use super::types::ns_from_us;
use crate::rpc::{RequestId, Response, RpcError};
use clean_elab::cert::external::{
    verify_alethe_certificate, verify_entailment_certificate, verify_farkas_certificate,
    ExternalCertError, ExternalCertificate,
};
use serde::{Deserialize, Serialize};
use std::time::{Duration, Instant};
use tracing::instrument;

// ============================================================================//
// Test-Only Delay Support
// ============================================================================//

#[cfg(test)]
use std::sync::atomic::{AtomicU64, Ordering};

/// Test-only delay in milliseconds to inject before verification.
/// Set to non-zero to trigger timeout tests deterministically.
///
/// Note: Tests using this should reset to 0 at both start and end to
/// minimize interference when tests run in parallel.
#[cfg(test)]
pub static TEST_DELAY_MS: AtomicU64 = AtomicU64::new(0);

/// Apply test-only delay if configured.
#[cfg(test)]
async fn apply_test_delay() {
    let delay_ms = TEST_DELAY_MS.load(Ordering::Relaxed);
    if delay_ms > 0 {
        tokio::time::sleep(Duration::from_millis(delay_ms)).await;
    }
}

/// No-op in production.
#[cfg(not(test))]
async fn apply_test_delay() {}

// ============================================================================//
// Request/Response Types
// ============================================================================//

/// Parameters for verifying a single external certificate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifyExternalCertParams {
    /// The external certificate to verify (Farkas or Entailment).
    pub certificate: ExternalCertificate,
    /// Optional timeout in milliseconds. Uses server default if not specified.
    pub timeout_ms: Option<u64>,
}

/// Result of verifying a Farkas certificate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifyFarkasCertResult {
    /// Whether the certificate is valid.
    pub valid: bool,
    /// The computed contradiction value (present when valid).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contradiction_value: Option<String>,
    /// Error code if verification failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Detailed error message if verification failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Verification time in microseconds.
    pub time_us: u64,
    /// Verification time in nanoseconds (normalized alias, Part of #2515).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_ns: Option<u64>,
}

/// Result of verifying an entailment certificate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifyEntailmentCertResult {
    /// Whether the certificate is valid.
    pub valid: bool,
    /// The derived bound from the certificate (present when valid).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub derived_bound: Option<String>,
    /// The claimed bound from the certificate (present when valid).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claimed_bound: Option<String>,
    /// Error code if verification failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Detailed error message if verification failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Verification time in microseconds.
    pub time_us: u64,
    /// Verification time in nanoseconds (normalized alias, Part of #2515).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_ns: Option<u64>,
}

/// Parameters for batch verification of external certificates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchVerifyExternalCertParams {
    /// List of certificates to verify in parallel.
    pub certificates: Vec<BatchExternalCertItem>,
    /// Number of threads for parallel verification (0 = rayon default pool).
    #[serde(default)]
    pub threads: usize,
    /// Optional timeout in milliseconds for the entire batch.
    pub timeout_ms: Option<u64>,
}

/// A single item in a batch certificate verification request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchExternalCertItem {
    /// Client-provided identifier for correlating results.
    pub id: String,
    /// The external certificate to verify.
    pub certificate: ExternalCertificate,
}

/// Result of batch certificate verification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchVerifyExternalCertResult {
    /// Per-item verification results.
    pub results: Vec<BatchExternalCertItemResult>,
    /// Aggregate statistics for the batch.
    pub stats: BatchExternalCertStats,
}

/// Result of verifying a single certificate in a batch.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchExternalCertItemResult {
    /// The client-provided identifier from the request.
    pub id: String,
    /// Whether the certificate is valid.
    pub valid: bool,
    /// Error code if verification failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Detailed error message if verification failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Verification time in microseconds.
    pub time_us: u64,
    /// Verification time in nanoseconds (normalized alias, Part of #2515).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_ns: Option<u64>,
}

/// Aggregate statistics for a batch verification operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchExternalCertStats {
    /// Total number of certificates processed.
    pub total: usize,
    /// Number of valid certificates.
    pub valid: usize,
    /// Number of invalid certificates.
    pub invalid: usize,
    /// Total wall-clock time in microseconds.
    pub total_time_us: u64,
    /// Total wall-clock time in nanoseconds (normalized alias, Part of #2515).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_time_ns: Option<u64>,
    /// Throughput in certificates per second.
    pub throughput_per_sec: f64,
}

// ============================================================================//
// Handlers
// ============================================================================//

/// Handle a request to verify a Farkas certificate.
///
/// Verifies that the provided Farkas coefficients yield a contradiction,
/// proving infeasibility of the linear constraint system.
#[instrument(skip(state))]
pub async fn handle_verify_farkas_certificate(
    state: &ServerState,
    id: RequestId,
    params: VerifyExternalCertParams,
) -> Response {
    let start = Instant::now();
    let timeout = Duration::from_millis(params.timeout_ms.unwrap_or(state.default_timeout_ms));

    let result = tokio::time::timeout(timeout, async {
        apply_test_delay().await;
        match params.certificate {
            ExternalCertificate::Farkas(cert) => verify_farkas_certificate(&cert),
            _ => Err(ExternalCertError::invalid_schema(
                "expected farkas_certificate".to_string(),
            )),
        }
    })
    .await;

    let elapsed_us = start.elapsed().as_micros() as u64;

    match result {
        Ok(Ok(value)) => {
            state
                .metrics
                .record_request("verify_farkas_certificate", true, elapsed_us);
            let out = VerifyFarkasCertResult {
                valid: true,
                contradiction_value: Some(value.to_compact_string()),
                error: None,
                detail: None,
                time_us: elapsed_us,
                time_ns: Some(ns_from_us(elapsed_us)),
            };
            Response::success_typed(id, &out).unwrap_or_else(|e| {
                Response::error(RequestId::Null, RpcError::internal_error(e.to_string()))
            })
        }
        Ok(Err(err)) => {
            state
                .metrics
                .record_request("verify_farkas_certificate", false, elapsed_us);
            let out = VerifyFarkasCertResult {
                valid: false,
                contradiction_value: None,
                error: Some(err.code.as_str().to_string()),
                detail: Some(err.detail),
                time_us: elapsed_us,
                time_ns: Some(ns_from_us(elapsed_us)),
            };
            Response::success_typed(id, &out).unwrap_or_else(|e| {
                Response::error(RequestId::Null, RpcError::internal_error(e.to_string()))
            })
        }
        Err(_) => {
            state
                .metrics
                .record_request("verify_farkas_certificate", false, elapsed_us);
            Response::error(id, RpcError::timeout(timeout.as_millis() as u64))
        }
    }
}

/// Handle a request to verify an entailment certificate.
///
/// Verifies that the provided coefficients prove the claimed bound
/// is derivable from the constraint system.
#[instrument(skip(state))]
pub async fn handle_verify_entailment_certificate(
    state: &ServerState,
    id: RequestId,
    params: VerifyExternalCertParams,
) -> Response {
    let start = Instant::now();
    let timeout = Duration::from_millis(params.timeout_ms.unwrap_or(state.default_timeout_ms));

    let result = tokio::time::timeout(timeout, async {
        apply_test_delay().await;
        match params.certificate {
            ExternalCertificate::Entailment(cert) => verify_entailment_certificate(&cert),
            _ => Err(ExternalCertError::invalid_schema(
                "expected entailment_certificate".to_string(),
            )),
        }
    })
    .await;

    let elapsed_us = start.elapsed().as_micros() as u64;

    match result {
        Ok(Ok((derived, claimed))) => {
            state
                .metrics
                .record_request("verify_entailment_certificate", true, elapsed_us);
            let out = VerifyEntailmentCertResult {
                valid: true,
                derived_bound: Some(derived.to_compact_string()),
                claimed_bound: Some(claimed.to_compact_string()),
                error: None,
                detail: None,
                time_us: elapsed_us,
                time_ns: Some(ns_from_us(elapsed_us)),
            };
            Response::success_typed(id, &out).unwrap_or_else(|e| {
                Response::error(RequestId::Null, RpcError::internal_error(e.to_string()))
            })
        }
        Ok(Err(err)) => {
            state
                .metrics
                .record_request("verify_entailment_certificate", false, elapsed_us);
            let out = VerifyEntailmentCertResult {
                valid: false,
                derived_bound: None,
                claimed_bound: None,
                error: Some(err.code.as_str().to_string()),
                detail: Some(err.detail),
                time_us: elapsed_us,
                time_ns: Some(ns_from_us(elapsed_us)),
            };
            Response::success_typed(id, &out).unwrap_or_else(|e| {
                Response::error(RequestId::Null, RpcError::internal_error(e.to_string()))
            })
        }
        Err(_) => {
            state
                .metrics
                .record_request("verify_entailment_certificate", false, elapsed_us);
            Response::error(id, RpcError::timeout(timeout.as_millis() as u64))
        }
    }
}

/// Handle a batch request to verify multiple external certificates.
///
/// Verifies certificates in parallel using Rayon, returning per-item
/// results and aggregate statistics.
#[instrument(skip(state))]
pub async fn handle_verify_certificates_batch(
    state: &ServerState,
    id: RequestId,
    params: BatchVerifyExternalCertParams,
) -> Response {
    let start = Instant::now();
    let timeout = Duration::from_millis(params.timeout_ms.unwrap_or(state.default_timeout_ms));

    let result = tokio::time::timeout(timeout, async {
        apply_test_delay().await;
        if params.certificates.is_empty() {
            return Ok::<_, ExternalCertError>(BatchVerifyExternalCertResult {
                results: Vec::new(),
                stats: BatchExternalCertStats {
                    total: 0,
                    valid: 0,
                    invalid: 0,
                    total_time_us: 0,
                    total_time_ns: None,
                    throughput_per_sec: 0.0,
                },
            });
        }

        let items = params.certificates;
        let threads = params.threads;
        let results = if threads > 0 {
            rayon::ThreadPoolBuilder::new()
                .num_threads(threads)
                .build()
                .map_err(|e| ExternalCertError::invalid_schema(e.to_string()))?
                .install(|| verify_external_items(items))
        } else {
            verify_external_items(items)
        };

        Ok::<_, ExternalCertError>(results)
    })
    .await;

    let elapsed_us = start.elapsed().as_micros() as u64;

    match result {
        Ok(Ok(out)) => {
            state
                .metrics
                .record_request("verify_certificates_batch", true, elapsed_us);
            Response::success_typed(id, &out).unwrap_or_else(|e| {
                Response::error(RequestId::Null, RpcError::internal_error(e.to_string()))
            })
        }
        Ok(Err(err)) => {
            state
                .metrics
                .record_request("verify_certificates_batch", false, elapsed_us);
            Response::error(id, RpcError::invalid_params(err.detail))
        }
        Err(_) => {
            state
                .metrics
                .record_request("verify_certificates_batch", false, elapsed_us);
            Response::error(id, RpcError::timeout(timeout.as_millis() as u64))
        }
    }
}

/// Verify a batch of external certificates in parallel using rayon.
///
/// Returns per-item results with timing and aggregate statistics.
fn verify_external_items(items: Vec<BatchExternalCertItem>) -> BatchVerifyExternalCertResult {
    use rayon::prelude::*;

    let start = Instant::now();
    let results: Vec<BatchExternalCertItemResult> = items
        .into_par_iter()
        .map(|item| {
            let item_start = Instant::now();
            let result = match item.certificate {
                ExternalCertificate::Farkas(cert) => verify_farkas_certificate(&cert).map(|_| ()),
                ExternalCertificate::Entailment(cert) => {
                    verify_entailment_certificate(&cert).map(|_| ())
                }
                ExternalCertificate::Alethe(cert) => {
                    verify_alethe_certificate(&cert).and_then(|valid| {
                        if valid {
                            Ok(())
                        } else {
                            Err(ExternalCertError::proof_verification_failed(
                                "proof was holey or not fully verified".to_string(),
                            ))
                        }
                    })
                }
            };
            let time_us = item_start.elapsed().as_micros() as u64;
            let time_ns = Some(ns_from_us(time_us));
            match result {
                Ok(()) => BatchExternalCertItemResult {
                    id: item.id,
                    valid: true,
                    error: None,
                    detail: None,
                    time_us,
                    time_ns,
                },
                Err(err) => BatchExternalCertItemResult {
                    id: item.id,
                    valid: false,
                    error: Some(err.code.as_str().to_string()),
                    detail: Some(err.detail),
                    time_us,
                    time_ns,
                },
            }
        })
        .collect();

    let total_time_us = start.elapsed().as_micros() as u64;
    let total = results.len();
    let valid = results.iter().filter(|r| r.valid).count();
    let invalid = total - valid;
    let throughput_per_sec = if total_time_us == 0 {
        0.0
    } else {
        (total as f64) * 1_000_000.0 / (total_time_us as f64)
    };

    BatchVerifyExternalCertResult {
        results,
        stats: BatchExternalCertStats {
            total,
            valid,
            invalid,
            total_time_us,
            total_time_ns: Some(ns_from_us(total_time_us)),
            throughput_per_sec,
        },
    }
}
