// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Dafny program verification importer (Boogie VCs → SMT cert replay).
//!
//! Dafny compiles programs to Boogie intermediate verification language, which
//! generates verification conditions (VCs) discharged by an SMT solver (Z3).
//! This module imports Boogie VCs and Dafny verification results into the
//! Mathverse trust framework.
//!
//! Trust model:
//! - Unverified VCs: `SMT_ORACLE` axiom profile, `TrustedOracle` trust level
//! - Certificate-replayed VCs: `SAT_CERT` axiom profile, `CertificateReplayed`

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::types::{AxiomProfile, Provenance, SourceSystem, TrustLevel};

// ════════════════════════════════════════════════════════════════════════════
// Errors
// ════════════════════════════════════════════════════════════════════════════

/// Errors raised during Dafny import operations.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum DafnyError {
    /// Failed to parse a Boogie verification condition.
    #[error("failed to parse Boogie VC: {reason}")]
    ParseError { reason: String },

    /// Error in the Boogie verification condition structure.
    #[error("Boogie VC error in `{vc_name}`: {reason}")]
    BoogieVcError { vc_name: String, reason: String },

    /// Certificate replay failed for a VC.
    #[error("certificate replay failed for `{vc_name}`: {reason}")]
    CertReplayError { vc_name: String, reason: String },

    /// Unsupported Dafny/Boogie feature encountered.
    #[error("unsupported Dafny feature: {feature}")]
    UnsupportedFeature { feature: String },
}

// ════════════════════════════════════════════════════════════════════════════
// Data types
// ════════════════════════════════════════════════════════════════════════════

/// A single Boogie verification condition extracted from Dafny compilation.
///
/// Each VC corresponds to one proof obligation generated by the Boogie pipeline
/// (e.g., a precondition check, postcondition check, loop invariant, or
/// termination proof).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DafnyVerificationCondition {
    /// VC identifier (typically `<method>::<check_kind>::<index>`).
    pub name: String,
    /// Dafny method or function this VC belongs to.
    pub method_name: String,
    /// Source `.dfy` file path, if known.
    pub source_file: Option<String>,
    /// Source line number, if known.
    pub source_line: Option<u32>,
    /// The VC assertion in SMT-LIB2 format.
    pub assertion: String,
}

/// Result of importing a Dafny verification session.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DafnyImportResult {
    /// Name of the Dafny module or file imported.
    pub name: String,
    /// Total number of verification conditions.
    pub vc_count: usize,
    /// Number of VCs successfully verified.
    pub verified_count: usize,
    /// Axiom profile for the imported result.
    pub axiom_profile: AxiomProfile,
    /// Trust level assigned to the imported result.
    pub trust_level: TrustLevel,
    /// Provenance record for the import.
    pub provenance: Provenance,
    /// Diagnostic messages from the import process.
    pub diagnostics: Vec<String>,
}

// ════════════════════════════════════════════════════════════════════════════
// Importer
// ════════════════════════════════════════════════════════════════════════════

/// Imports Dafny verification results into the Mathverse trust framework.
///
/// Dafny programs compile to Boogie, which generates SMT-LIB2 verification
/// conditions. This importer parses those VCs and tracks their verification
/// status through the trust pipeline.
pub struct DafnyImporter {
    /// Whether to attempt certificate replay (upgrades trust level).
    cert_replay_enabled: bool,
}

impl Default for DafnyImporter {
    fn default() -> Self {
        Self::new()
    }
}

impl DafnyImporter {
    /// Create a new Dafny importer with default settings.
    #[must_use]
    pub fn new() -> Self {
        Self {
            cert_replay_enabled: false,
        }
    }

    /// Enable certificate replay for upgraded trust.
    #[must_use]
    pub fn with_cert_replay(mut self, enabled: bool) -> Self {
        self.cert_replay_enabled = enabled;
        self
    }

    /// Import a single Boogie verification condition from SMT-LIB2 text.
    ///
    /// Parses the VC text and extracts the method name, source location, and
    /// assertion body. The VC text must contain at least an `(assert ...)` form.
    pub fn import_boogie_vc(
        &self,
        vc_text: &str,
    ) -> Result<DafnyVerificationCondition, DafnyError> {
        let trimmed = vc_text.trim();
        if trimmed.is_empty() {
            return Err(DafnyError::ParseError {
                reason: "empty VC text".to_string(),
            });
        }

        // Extract VC name from a `;; VC: <name>` comment line if present.
        let name =
            extract_comment_field(trimmed, "VC:").unwrap_or_else(|| "anonymous_vc".to_string());

        // Extract method name from `;; Method: <name>` comment.
        let method_name = extract_comment_field(trimmed, "Method:")
            .unwrap_or_else(|| "unknown_method".to_string());

        // Extract source file from `;; File: <path>` comment.
        let source_file = extract_comment_field(trimmed, "File:");

        // Extract source line from `;; Line: <n>` comment.
        let source_line =
            extract_comment_field(trimmed, "Line:").and_then(|s| s.parse::<u32>().ok());

        // The assertion body is the full text (including metadata comments).
        // In production, this would be validated as well-formed SMT-LIB2.
        let assertion = trimmed.to_string();

        Ok(DafnyVerificationCondition {
            name,
            method_name,
            source_file,
            source_line,
            assertion,
        })
    }

    /// Produce an import result from a set of parsed VCs and their verification status.
    ///
    /// - `name`: Name for the overall verification session (e.g., module name).
    /// - `vcs`: Parsed verification conditions.
    /// - `all_verified`: Whether the SMT solver reported all VCs as valid.
    #[must_use]
    pub fn import_dafny_result(
        &self,
        name: &str,
        vcs: &[DafnyVerificationCondition],
        all_verified: bool,
    ) -> DafnyImportResult {
        let vc_count = vcs.len();
        let verified_count = if all_verified { vc_count } else { 0 };

        let (axiom_profile, trust_level) = if all_verified && self.cert_replay_enabled {
            // Certificate replay upgrades from oracle trust to certificate trust.
            (AxiomProfile::SAT_CERT, TrustLevel::CertificateReplayed)
        } else {
            // Without cert replay, we trust the SMT solver as an oracle.
            (AxiomProfile::SMT_ORACLE, TrustLevel::TrustedOracle)
        };

        let mut diagnostics = Vec::new();
        if !all_verified {
            diagnostics.push(format!(
                "not all VCs verified: {verified_count}/{vc_count} passed"
            ));
        }
        if self.cert_replay_enabled && all_verified {
            diagnostics.push("certificate replay: enabled and successful".to_string());
        }

        // Collect source file from first VC with a known source.
        let source_file = vcs.iter().find_map(|vc| vc.source_file.clone());

        let provenance = Provenance {
            source: SourceSystem::Dafny,
            original_name: name.to_string(),
            source_file,
            axiom_profile,
        };

        DafnyImportResult {
            name: name.to_string(),
            vc_count,
            verified_count,
            axiom_profile,
            trust_level,
            provenance,
            diagnostics,
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Extended data types
// ════════════════════════════════════════════════════════════════════════════

/// A proof obligation generated by the Dafny/Boogie pipeline.
///
/// Proof obligations are finer-grained than verification conditions: a single
/// VC may contain multiple proof obligations (e.g., a method postcondition
/// generates one PO per `ensures` clause). Source location tracking enables
/// diagnostic mapping back to the original `.dfy` file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DafnyProofObligation {
    /// Unique identifier for this proof obligation.
    pub id: String,
    /// Kind of proof obligation.
    pub kind: DafnyPoKind,
    /// Enclosing method or function name.
    pub method_name: String,
    /// Source `.dfy` file path, if known.
    pub source_file: Option<String>,
    /// Source line number, if known.
    pub source_line: Option<u32>,
    /// Source column number, if known.
    pub source_column: Option<u32>,
    /// The assertion text in SMT-LIB2 format.
    pub assertion: String,
    /// Whether this PO was discharged.
    pub discharged: bool,
}

/// Kind of Dafny proof obligation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum DafnyPoKind {
    /// Method/function precondition check.
    Precondition,
    /// Method/function postcondition check.
    Postcondition,
    /// Loop invariant maintenance.
    LoopInvariant,
    /// Loop variant (termination measure) decrease.
    LoopVariant,
    /// Assert statement.
    Assertion,
    /// Array/sequence bounds check.
    BoundsCheck,
    /// Division by zero check.
    DivisionByZero,
    /// Object non-null check.
    NonNull,
    /// Other (unclassified) proof obligation.
    Other,
}

/// Statistics collected during a Dafny verification session.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct DafnyStatistics {
    /// Total number of VCs generated.
    pub vcs_total: usize,
    /// Number of VCs successfully proved.
    pub vcs_proved: usize,
    /// Number of axioms used across all VCs.
    pub axioms_used: usize,
    /// Number of unique methods verified.
    pub methods_verified: usize,
    /// Number of unique methods with at least one unproved VC.
    pub methods_with_errors: usize,
    /// Total solver time in milliseconds.
    pub solver_time_ms: u64,
}

impl DafnyStatistics {
    /// Compute statistics from a set of parsed VCs and their verification status.
    ///
    /// - `vcs`: Parsed verification conditions.
    /// - `all_verified`: Whether the SMT solver reported all VCs as valid.
    /// - `axiom_count`: Number of axioms used by the solver.
    #[must_use]
    pub fn from_vcs(
        vcs: &[DafnyVerificationCondition],
        all_verified: bool,
        axiom_count: usize,
    ) -> Self {
        let vcs_total = vcs.len();
        let vcs_proved = if all_verified { vcs_total } else { 0 };

        // Count unique methods.
        let mut method_names: Vec<&str> = vcs.iter().map(|vc| vc.method_name.as_str()).collect();
        method_names.sort_unstable();
        method_names.dedup();
        let methods_verified = if all_verified { method_names.len() } else { 0 };
        let methods_with_errors = if all_verified { 0 } else { method_names.len() };

        Self {
            vcs_total,
            vcs_proved,
            axioms_used: axiom_count,
            methods_verified,
            methods_with_errors,
            solver_time_ms: 0,
        }
    }

    /// Fraction of VCs proved, as a value in `[0.0, 1.0]`.
    ///
    /// Returns `1.0` if there are no VCs (vacuously true).
    #[must_use]
    pub fn success_rate(&self) -> f64 {
        if self.vcs_total == 0 {
            1.0
        } else {
            self.vcs_proved as f64 / self.vcs_total as f64
        }
    }
}

/// Parse a Boogie verification condition from SMT-LIB2 text.
///
/// This is a standalone function that performs the same parsing as
/// [`DafnyImporter::import_boogie_vc`] but without requiring an importer
/// instance. Useful for batch processing pipelines.
///
/// # Errors
///
/// Returns `DafnyError::ParseError` if the input is empty.
pub fn parse_boogie_vc(vc_text: &str) -> Result<DafnyVerificationCondition, DafnyError> {
    let trimmed = vc_text.trim();
    if trimmed.is_empty() {
        return Err(DafnyError::ParseError {
            reason: "empty VC text".to_string(),
        });
    }

    let name = extract_comment_field(trimmed, "VC:").unwrap_or_else(|| "anonymous_vc".to_string());
    let method_name =
        extract_comment_field(trimmed, "Method:").unwrap_or_else(|| "unknown_method".to_string());
    let source_file = extract_comment_field(trimmed, "File:");
    let source_line = extract_comment_field(trimmed, "Line:").and_then(|s| s.parse::<u32>().ok());
    let assertion = trimmed.to_string();

    Ok(DafnyVerificationCondition {
        name,
        method_name,
        source_file,
        source_line,
        assertion,
    })
}

/// Classify a Boogie VC name into a proof obligation kind.
///
/// Boogie VCs follow naming conventions like `<method>::precondition::0`,
/// `<method>::loop_invariant::1`, etc.
#[must_use]
pub fn classify_vc_kind(vc_name: &str) -> DafnyPoKind {
    let lower = vc_name.to_ascii_lowercase();
    if lower.contains("precondition") || lower.contains("requires") {
        DafnyPoKind::Precondition
    } else if lower.contains("postcondition") || lower.contains("ensures") {
        DafnyPoKind::Postcondition
    } else if lower.contains("loop_invariant") || lower.contains("invariant") {
        DafnyPoKind::LoopInvariant
    } else if lower.contains("variant") || lower.contains("decreases") {
        DafnyPoKind::LoopVariant
    } else if lower.contains("assert") {
        DafnyPoKind::Assertion
    } else if lower.contains("bounds") || lower.contains("index") {
        DafnyPoKind::BoundsCheck
    } else if lower.contains("division") || lower.contains("div_by_zero") {
        DafnyPoKind::DivisionByZero
    } else if lower.contains("non_null") || lower.contains("nonnull") {
        DafnyPoKind::NonNull
    } else {
        DafnyPoKind::Other
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════════════════

/// Extract a value from an SMT-LIB2 comment line: `;; <prefix> <value>`.
fn extract_comment_field(text: &str, prefix: &str) -> Option<String> {
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix(";;") {
            let rest = rest.trim();
            if let Some(value) = rest.strip_prefix(prefix) {
                let value = value.trim();
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
    }
    None
}

// ════════════════════════════════════════════════════════════════════════════
// Tests
// ════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    const MOCK_VC: &str = "\
;; VC: Increment::postcondition::0
;; Method: Increment
;; File: counter.dfy
;; Line: 42
(set-logic ALL)
(assert (=> (>= x 0) (> (+ x 1) 0)))
(check-sat)";

    #[test]
    fn test_import_boogie_vc_parses_metadata() {
        let importer = DafnyImporter::new();
        let vc = importer.import_boogie_vc(MOCK_VC).unwrap();

        assert_eq!(vc.name, "Increment::postcondition::0");
        assert_eq!(vc.method_name, "Increment");
        assert_eq!(vc.source_file.as_deref(), Some("counter.dfy"));
        assert_eq!(vc.source_line, Some(42));
        assert!(vc.assertion.contains("(assert"));
    }

    #[test]
    fn test_import_boogie_vc_anonymous() {
        let importer = DafnyImporter::new();
        let vc = importer.import_boogie_vc("(assert (= x x))").unwrap();

        assert_eq!(vc.name, "anonymous_vc");
        assert_eq!(vc.method_name, "unknown_method");
        assert!(vc.source_file.is_none());
        assert!(vc.source_line.is_none());
    }

    #[test]
    fn test_import_boogie_vc_empty_input_errors() {
        let importer = DafnyImporter::new();
        let result = importer.import_boogie_vc("");
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            matches!(err, DafnyError::ParseError { .. }),
            "expected ParseError, got {err:?}"
        );
    }

    #[test]
    fn test_import_result_all_verified_no_cert() {
        let importer = DafnyImporter::new();
        let vc = importer.import_boogie_vc(MOCK_VC).unwrap();
        let result = importer.import_dafny_result("counter", &[vc], true);

        assert_eq!(result.name, "counter");
        assert_eq!(result.vc_count, 1);
        assert_eq!(result.verified_count, 1);
        assert_eq!(result.axiom_profile, AxiomProfile::SMT_ORACLE);
        assert_eq!(result.trust_level, TrustLevel::TrustedOracle);
        assert_eq!(result.provenance.source, SourceSystem::Dafny);
        assert_eq!(result.provenance.original_name, "counter");
        assert_eq!(
            result.provenance.source_file.as_deref(),
            Some("counter.dfy")
        );
    }

    #[test]
    fn test_import_result_all_verified_with_cert() {
        let importer = DafnyImporter::new().with_cert_replay(true);
        let vc = importer.import_boogie_vc(MOCK_VC).unwrap();
        let result = importer.import_dafny_result("counter", &[vc], true);

        assert_eq!(result.axiom_profile, AxiomProfile::SAT_CERT);
        assert_eq!(result.trust_level, TrustLevel::CertificateReplayed);
        assert!(
            result
                .diagnostics
                .iter()
                .any(|d| d.contains("certificate replay")),
            "expected cert replay diagnostic"
        );
    }

    #[test]
    fn test_import_result_not_all_verified() {
        let importer = DafnyImporter::new();
        let vc = importer.import_boogie_vc(MOCK_VC).unwrap();
        let result = importer.import_dafny_result("counter", &[vc], false);

        assert_eq!(result.verified_count, 0);
        assert_eq!(result.trust_level, TrustLevel::TrustedOracle);
        assert!(
            result.diagnostics.iter().any(|d| d.contains("not all VCs")),
            "expected unverified diagnostic"
        );
    }

    #[test]
    fn test_import_result_empty_vcs() {
        let importer = DafnyImporter::new();
        let result = importer.import_dafny_result("empty_module", &[], true);

        assert_eq!(result.vc_count, 0);
        assert_eq!(result.verified_count, 0);
        assert!(result.provenance.source_file.is_none());
    }

    #[test]
    fn test_dafny_importer_default() {
        let importer = DafnyImporter::default();
        assert!(!importer.cert_replay_enabled);
    }

    #[test]
    fn test_extract_comment_field_missing() {
        assert!(extract_comment_field("(assert true)", "VC:").is_none());
    }

    #[test]
    fn test_extract_comment_field_present() {
        let text = ";; VC: my_vc\n(assert true)";
        assert_eq!(
            extract_comment_field(text, "VC:"),
            Some("my_vc".to_string())
        );
    }

    // -----------------------------------------------------------------------
    // DafnyProofObligation tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_dafny_proof_obligation_creation() {
        let po = DafnyProofObligation {
            id: "po_1".to_string(),
            kind: DafnyPoKind::Postcondition,
            method_name: "Increment".to_string(),
            source_file: Some("counter.dfy".to_string()),
            source_line: Some(42),
            source_column: Some(10),
            assertion: "(assert (> result 0))".to_string(),
            discharged: true,
        };
        assert_eq!(po.id, "po_1");
        assert_eq!(po.kind, DafnyPoKind::Postcondition);
        assert!(po.discharged);
        assert_eq!(po.source_column, Some(10));
    }

    #[test]
    fn test_dafny_po_kind_variants() {
        let kinds = [
            DafnyPoKind::Precondition,
            DafnyPoKind::Postcondition,
            DafnyPoKind::LoopInvariant,
            DafnyPoKind::LoopVariant,
            DafnyPoKind::Assertion,
            DafnyPoKind::BoundsCheck,
            DafnyPoKind::DivisionByZero,
            DafnyPoKind::NonNull,
            DafnyPoKind::Other,
        ];
        // Verify all kinds are distinct.
        for (i, a) in kinds.iter().enumerate() {
            for (j, b) in kinds.iter().enumerate() {
                if i == j {
                    assert_eq!(a, b);
                } else {
                    assert_ne!(a, b, "kinds at index {i} and {j} should differ");
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // DafnyStatistics tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_dafny_statistics_default() {
        let stats = DafnyStatistics::default();
        assert_eq!(stats.vcs_total, 0);
        assert_eq!(stats.vcs_proved, 0);
        assert_eq!(stats.axioms_used, 0);
    }

    #[test]
    fn test_dafny_statistics_from_vcs_all_verified() {
        let importer = DafnyImporter::new();
        let vc1 = importer.import_boogie_vc(MOCK_VC).unwrap();
        let vc2 = importer
            .import_boogie_vc(";; VC: Check2\n;; Method: Decrement\n(assert (< x 100))")
            .unwrap();
        let stats = DafnyStatistics::from_vcs(&[vc1, vc2], true, 5);

        assert_eq!(stats.vcs_total, 2);
        assert_eq!(stats.vcs_proved, 2);
        assert_eq!(stats.axioms_used, 5);
        assert_eq!(stats.methods_verified, 2); // Increment, Decrement
        assert_eq!(stats.methods_with_errors, 0);
    }

    #[test]
    fn test_dafny_statistics_from_vcs_not_verified() {
        let importer = DafnyImporter::new();
        let vc = importer.import_boogie_vc(MOCK_VC).unwrap();
        let stats = DafnyStatistics::from_vcs(&[vc], false, 0);

        assert_eq!(stats.vcs_total, 1);
        assert_eq!(stats.vcs_proved, 0);
        assert_eq!(stats.methods_verified, 0);
        assert_eq!(stats.methods_with_errors, 1);
    }

    #[test]
    fn test_dafny_statistics_from_empty_vcs() {
        let stats = DafnyStatistics::from_vcs(&[], true, 0);
        assert_eq!(stats.vcs_total, 0);
        assert_eq!(stats.methods_verified, 0);
    }

    #[test]
    fn test_dafny_statistics_success_rate() {
        let mut stats = DafnyStatistics::default();
        assert!((stats.success_rate() - 1.0).abs() < f64::EPSILON);

        stats.vcs_total = 10;
        stats.vcs_proved = 7;
        assert!((stats.success_rate() - 0.7).abs() < f64::EPSILON);

        stats.vcs_proved = 0;
        assert!((stats.success_rate() - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_dafny_statistics_duplicate_methods() {
        let importer = DafnyImporter::new();
        let vc1 = importer.import_boogie_vc(MOCK_VC).unwrap();
        // Second VC with same method name.
        let vc2 = importer
            .import_boogie_vc(
                ";; VC: Increment::loop_invariant::0\n;; Method: Increment\n(assert true)",
            )
            .unwrap();
        let stats = DafnyStatistics::from_vcs(&[vc1, vc2], true, 3);

        assert_eq!(stats.vcs_total, 2);
        assert_eq!(stats.methods_verified, 1); // Both are "Increment"
    }

    // -----------------------------------------------------------------------
    // parse_boogie_vc standalone function tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_parse_boogie_vc_standalone_parses_metadata() {
        let vc = parse_boogie_vc(MOCK_VC).unwrap();
        assert_eq!(vc.name, "Increment::postcondition::0");
        assert_eq!(vc.method_name, "Increment");
        assert_eq!(vc.source_file.as_deref(), Some("counter.dfy"));
        assert_eq!(vc.source_line, Some(42));
    }

    #[test]
    fn test_parse_boogie_vc_standalone_empty_errors() {
        let result = parse_boogie_vc("");
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_boogie_vc_standalone_whitespace_only_errors() {
        let result = parse_boogie_vc("   \n  \t  ");
        assert!(result.is_err());
    }

    // -----------------------------------------------------------------------
    // classify_vc_kind tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_classify_vc_kind_precondition() {
        assert_eq!(
            classify_vc_kind("Method::precondition::0"),
            DafnyPoKind::Precondition
        );
        assert_eq!(
            classify_vc_kind("requires_check"),
            DafnyPoKind::Precondition
        );
    }

    #[test]
    fn test_classify_vc_kind_postcondition() {
        assert_eq!(
            classify_vc_kind("Method::postcondition::1"),
            DafnyPoKind::Postcondition
        );
        assert_eq!(
            classify_vc_kind("ensures_check"),
            DafnyPoKind::Postcondition
        );
    }

    #[test]
    fn test_classify_vc_kind_loop_invariant() {
        assert_eq!(
            classify_vc_kind("Method::loop_invariant::0"),
            DafnyPoKind::LoopInvariant
        );
        assert_eq!(
            classify_vc_kind("invariant_maintenance"),
            DafnyPoKind::LoopInvariant
        );
    }

    #[test]
    fn test_classify_vc_kind_variant() {
        assert_eq!(
            classify_vc_kind("variant_decrease"),
            DafnyPoKind::LoopVariant
        );
        assert_eq!(
            classify_vc_kind("decreases_check"),
            DafnyPoKind::LoopVariant
        );
    }

    #[test]
    fn test_classify_vc_kind_assertion() {
        assert_eq!(classify_vc_kind("assert_check"), DafnyPoKind::Assertion);
    }

    #[test]
    fn test_classify_vc_kind_bounds() {
        assert_eq!(
            classify_vc_kind("array_bounds_check"),
            DafnyPoKind::BoundsCheck
        );
        assert_eq!(classify_vc_kind("index_range"), DafnyPoKind::BoundsCheck);
    }

    #[test]
    fn test_classify_vc_kind_division() {
        assert_eq!(
            classify_vc_kind("division_check"),
            DafnyPoKind::DivisionByZero
        );
        assert_eq!(
            classify_vc_kind("div_by_zero_guard"),
            DafnyPoKind::DivisionByZero
        );
    }

    #[test]
    fn test_classify_vc_kind_nonnull() {
        assert_eq!(classify_vc_kind("non_null_check"), DafnyPoKind::NonNull);
        assert_eq!(classify_vc_kind("nonnull_ref"), DafnyPoKind::NonNull);
    }

    #[test]
    fn test_classify_vc_kind_other() {
        assert_eq!(classify_vc_kind("some_random_check"), DafnyPoKind::Other);
        assert_eq!(classify_vc_kind(""), DafnyPoKind::Other);
    }

    // -----------------------------------------------------------------------
    // Serialization tests for new types
    // -----------------------------------------------------------------------

    #[test]
    fn test_dafny_statistics_serde_round_trip() {
        let stats = DafnyStatistics {
            vcs_total: 10,
            vcs_proved: 8,
            axioms_used: 3,
            methods_verified: 5,
            methods_with_errors: 1,
            solver_time_ms: 1500,
        };
        let json = serde_json::to_string(&stats).expect("serialize");
        let restored: DafnyStatistics = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, stats);
    }

    #[test]
    fn test_dafny_proof_obligation_serde_round_trip() {
        let po = DafnyProofObligation {
            id: "po_42".to_string(),
            kind: DafnyPoKind::LoopInvariant,
            method_name: "BinarySearch".to_string(),
            source_file: Some("search.dfy".to_string()),
            source_line: Some(100),
            source_column: None,
            assertion: "(assert (and (<= lo hi) (>= hi 0)))".to_string(),
            discharged: false,
        };
        let json = serde_json::to_string(&po).expect("serialize");
        let restored: DafnyProofObligation = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, po);
    }
}
