#!/usr/bin/env python3
# Copyright 2026 Andrew Yates
# Author: Andrew Yates <andrewyates.name@gmail.com>
# Licensed under the Apache License, Version 2.0
# SPDX-License-Identifier: Apache-2.0

"""Read-only release issue hygiene gate.

This script consumes the JSON shape emitted by:

    gh issue list --state open --limit 500 \
      --json number,title,url,labels,assignees,body,comments

It never edits GitHub issues. Use ``--input`` for offline tests or ``--fetch``
for a live read-only ``gh issue list`` call.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

WATCHED_LABELS = ("urgent", "P1", "blocked", "local-maximum")
GH_JSON_FIELDS = "number,title,url,labels,assignees,body,comments"
RELEASE_DECISION_RE = re.compile(r"\bRelease decision\b[\s*_`]*:", re.IGNORECASE)
OWNERSHIP_LABEL_RE = re.compile(r"^(?:W|R|M)\d+$|^prov\d+$", re.IGNORECASE)
BATCH_FILE_RE = re.compile(r"batch-\d{3}\.md")
DRAFT_BATCH_GENERATED_MARKER = (
    "Generated by `scripts/release_issue_hygiene.py --draft-comment-batches`."
)
ACTION_PLAN_GENERATED_MARKER = (
    "Generated by `scripts/release_issue_hygiene.py --action-plan`."
)
GAP_AUDIT_GENERATED_MARKER = (
    "Generated by `scripts/release_issue_hygiene.py --gap-audit`."
)
OWNER_ACTION = "assign a release owner or add Wn/Rn/Mn/provN"
RELEASE_DECISION_ACTION = "add a visible `Release decision:` note"


@dataclass(frozen=True)
class IssueSummary:
    number: int | str
    title: str
    url: str
    labels: tuple[str, ...]
    has_owner: bool
    has_release_decision: bool
    owner_evidence: tuple[str, ...] = ()
    release_decision_evidence: tuple[str, ...] = ()

    def reference(self) -> str:
        return f"#{self.number}: {self.title}" if self.title else f"#{self.number}"


@dataclass(frozen=True)
class HygieneReport:
    scanned: int
    counts: dict[str, int]
    release_impacting: tuple[IssueSummary, ...]
    missing_owner: tuple[IssueSummary, ...]
    missing_release_decision: tuple[IssueSummary, ...]
    warnings: tuple[str, ...] = ()

    @property
    def ready(self) -> bool:
        return not self.missing_owner and not self.missing_release_decision


def _label_name(label: Any) -> str:
    if isinstance(label, str):
        return label.strip()
    if isinstance(label, dict):
        name = label.get("name")
        return name.strip() if isinstance(name, str) else ""
    return ""


def label_names(issue: dict[str, Any]) -> tuple[str, ...]:
    raw_labels = issue.get("labels", [])
    if isinstance(raw_labels, dict):
        raw_labels = raw_labels.get("nodes", [])
    if not isinstance(raw_labels, list):
        return ()
    return tuple(name for label in raw_labels if (name := _label_name(label)))


def _assignee_names(issue: dict[str, Any]) -> tuple[str, ...]:
    raw_assignees = issue.get("assignees", [])
    if isinstance(raw_assignees, dict):
        raw_assignees = raw_assignees.get("nodes", [])
    if not isinstance(raw_assignees, list):
        return ()

    names: list[str] = []
    for assignee in raw_assignees:
        if isinstance(assignee, str) and assignee.strip():
            names.append(assignee.strip())
        elif isinstance(assignee, dict):
            for key in ("login", "name"):
                value = assignee.get(key)
                if isinstance(value, str) and value.strip():
                    names.append(value.strip())
                    break
    return tuple(names)


def _comment_bodies(issue: dict[str, Any]) -> tuple[str, ...]:
    comments = issue.get("comments", [])
    if isinstance(comments, dict):
        comments = comments.get("nodes", [])
    if not isinstance(comments, list):
        return ()

    bodies: list[str] = []
    for comment in comments:
        if isinstance(comment, dict):
            body = comment.get("body")
            if isinstance(body, str):
                bodies.append(body)
    return tuple(bodies)


def owner_evidence(issue: dict[str, Any], labels: tuple[str, ...]) -> tuple[str, ...]:
    evidence: list[str] = []
    evidence.extend(f"assignee:{name}" for name in _assignee_names(issue))
    evidence.extend(
        f"label:{label}" for label in labels if OWNERSHIP_LABEL_RE.fullmatch(label)
    )
    return tuple(evidence)


def has_release_decision(issue: dict[str, Any]) -> bool:
    return bool(release_decision_evidence(issue))


def release_decision_evidence(issue: dict[str, Any]) -> tuple[str, ...]:
    evidence: list[str] = []
    body = issue.get("body")
    if isinstance(body, str) and RELEASE_DECISION_RE.search(body):
        evidence.append("body")
    evidence.extend(
        f"comment:{index}"
        for index, text in enumerate(_comment_bodies(issue), start=1)
        if RELEASE_DECISION_RE.search(text)
    )
    return tuple(evidence)


def has_owner(issue: dict[str, Any], labels: tuple[str, ...]) -> bool:
    return bool(owner_evidence(issue, labels))


def _issue_number(issue: dict[str, Any]) -> int | str:
    number = issue.get("number", "?")
    if isinstance(number, (int, str)):
        return number
    return "?"


def _issue_title(issue: dict[str, Any]) -> str:
    title = issue.get("title", "")
    return title.strip() if isinstance(title, str) else ""


def _issue_url(issue: dict[str, Any]) -> str:
    url = issue.get("url", "")
    return url.strip() if isinstance(url, str) else ""


def summarize_issue(issue: dict[str, Any]) -> IssueSummary:
    labels = label_names(issue)
    owner_sources = owner_evidence(issue, labels)
    decision_sources = release_decision_evidence(issue)
    return IssueSummary(
        number=_issue_number(issue),
        title=_issue_title(issue),
        url=_issue_url(issue),
        labels=labels,
        has_owner=bool(owner_sources),
        has_release_decision=bool(decision_sources),
        owner_evidence=owner_sources,
        release_decision_evidence=decision_sources,
    )


def build_report(
    issues: list[dict[str, Any]],
    *,
    watched_labels: tuple[str, ...] = WATCHED_LABELS,
    limit: int | None = None,
) -> HygieneReport:
    counts = dict.fromkeys(watched_labels, 0)
    watched_set = set(watched_labels)
    release_impacting: list[IssueSummary] = []

    for issue in issues:
        summary = summarize_issue(issue)
        issue_label_set = set(summary.labels)
        for label in watched_labels:
            if label in issue_label_set:
                counts[label] += 1
        if watched_set & issue_label_set:
            release_impacting.append(summary)

    warnings: list[str] = []
    if limit is not None and len(issues) >= limit:
        warnings.append(
            f"scanned {len(issues)} issues, which reached --limit {limit}; "
            "increase --limit if the repository has more open issues"
        )

    missing_owner = [issue for issue in release_impacting if not issue.has_owner]
    missing_release_decision = [
        issue for issue in release_impacting if not issue.has_release_decision
    ]
    return HygieneReport(
        scanned=len(issues),
        counts=counts,
        release_impacting=tuple(release_impacting),
        missing_owner=tuple(missing_owner),
        missing_release_decision=tuple(missing_release_decision),
        warnings=tuple(warnings),
    )


def _extract_issues(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        items = payload
    elif isinstance(payload, dict):
        for key in ("issues", "items", "nodes"):
            value = payload.get(key)
            if isinstance(value, list):
                items = value
                break
        else:
            msg = "JSON input must be a list or object with issues/items/nodes"
            raise ValueError(msg)
    else:
        msg = "JSON input must be a list or object"
        raise ValueError(msg)

    if not all(isinstance(item, dict) for item in items):
        msg = "JSON issue entries must be objects"
        raise ValueError(msg)
    return list(items)


def load_issues(path: Path) -> list[dict[str, Any]]:
    if str(path) == "-":
        payload = json.load(sys.stdin)
    else:
        with open(path, encoding="utf-8") as f:
            payload = json.load(f)
    return _extract_issues(payload)


def fetch_issues(limit: int) -> list[dict[str, Any]]:
    cmd = [
        "gh",
        "issue",
        "list",
        "--state",
        "open",
        "--limit",
        str(limit),
        "--json",
        GH_JSON_FIELDS,
    ]
    result = subprocess.run(
        cmd,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (
            result.stderr.strip() or result.stdout.strip() or "gh issue list failed"
        )
        raise RuntimeError(detail)
    return _extract_issues(json.loads(result.stdout))


def _missing_field_ids(issue: IssueSummary) -> tuple[str, ...]:
    missing: list[str] = []
    if not issue.has_owner:
        missing.append("owner")
    if not issue.has_release_decision:
        missing.append("release_decision")
    return tuple(missing)


def _missing_field_display_names(issue: IssueSummary) -> tuple[str, ...]:
    display_names = {
        "owner": "owner",
        "release_decision": "Release decision",
    }
    return tuple(display_names[field] for field in _missing_field_ids(issue))


def _suggested_actions(issue: IssueSummary) -> tuple[str, ...]:
    actions: list[str] = []
    if not issue.has_owner:
        actions.append(OWNER_ACTION)
    if not issue.has_release_decision:
        actions.append(RELEASE_DECISION_ACTION)
    return tuple(actions)


def _issue_to_dict(issue: IssueSummary) -> dict[str, Any]:
    return {
        "number": issue.number,
        "title": issue.title,
        "url": issue.url,
        "labels": list(issue.labels),
        "has_owner": issue.has_owner,
        "has_release_decision": issue.has_release_decision,
        "missing_fields": list(_missing_field_ids(issue)),
        "suggested_actions": list(_suggested_actions(issue)),
        "owner_evidence": list(issue.owner_evidence),
        "release_decision_evidence": list(issue.release_decision_evidence),
    }


def report_to_json(report: HygieneReport) -> str:
    non_ready_issues = issues_needing_draft_comments(report)
    payload = {
        "ready": report.ready,
        "summary": {
            "scanned": report.scanned,
            "release_impacting": len(report.release_impacting),
            "non_ready": len(non_ready_issues),
            "counts": report.counts,
        },
        "non_ready_issues": [_issue_to_dict(issue) for issue in non_ready_issues],
        "missing_owner": [_issue_to_dict(issue) for issue in report.missing_owner],
        "missing_release_decision": [
            _issue_to_dict(issue) for issue in report.missing_release_decision
        ],
        "warnings": list(report.warnings),
    }
    return json.dumps(payload, indent=2, sort_keys=True)


def issues_needing_draft_comments(report: HygieneReport) -> tuple[IssueSummary, ...]:
    return tuple(
        issue
        for issue in report.release_impacting
        if not issue.has_owner or not issue.has_release_decision
    )


def _draft_issue_lines(issue: IssueSummary) -> list[str]:
    labels = ", ".join(issue.labels) or "-"
    lines = [
        f"## {issue.reference()}",
        "",
        f"- URL: {issue.url or '(missing URL)'}",
        f"- Watched labels: {labels}",
        "",
        "Suggested comment draft:",
        "",
    ]
    if not issue.has_owner:
        lines.append(
            "Owner: <assign a release owner, or add an ownership label such "
            "as Wn/Rn/Mn/provN>."
        )
    if not issue.has_release_decision:
        lines.append(
            "Release decision: <ship, defer, block, or document unsupported "
            "scope, with release-note impact>."
        )
    lines.append("")
    return lines


def draft_comments_to_text(report: HygieneReport) -> str:
    lines = [
        "# Release Issue Hygiene Draft Comments",
        "",
        "Generated by `scripts/release_issue_hygiene.py --draft-comments`.",
        "These are review drafts only; the script does not write to GitHub.",
        "",
    ]

    issues = issues_needing_draft_comments(report)
    if not issues:
        lines.extend(
            [
                "No draft comments needed.",
                "",
                "All watched release-impacting issues have an owner and a "
                "`Release decision:` note.",
            ]
        )
        return "\n".join(lines) + "\n"

    for issue in issues:
        lines.extend(_draft_issue_lines(issue))

    return "\n".join(lines)


def _chunks(
    issues: tuple[IssueSummary, ...],
    size: int,
) -> list[tuple[IssueSummary, ...]]:
    return [issues[index : index + size] for index in range(0, len(issues), size)]


def _batch_file_name(index: int) -> str:
    return f"batch-{index:03d}.md"


def _is_generated_draft_batch_file(path: Path) -> bool:
    if not BATCH_FILE_RE.fullmatch(path.name):
        return False
    try:
        return DRAFT_BATCH_GENERATED_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def _prune_stale_generated_draft_batches(
    output_dir: Path,
    active_batch_names: set[str],
) -> None:
    for stale_batch in output_dir.glob("batch-*.md"):
        if (
            stale_batch.name not in active_batch_names
            and _is_generated_draft_batch_file(stale_batch)
        ):
            stale_batch.unlink()


def write_draft_comment_batches(
    report: HygieneReport,
    output_dir: Path,
    *,
    batch_size: int,
) -> tuple[int, int]:
    issues = issues_needing_draft_comments(report)
    batches = _chunks(issues, batch_size)
    output_dir.mkdir(parents=True, exist_ok=True)
    active_batch_names = {
        _batch_file_name(batch_index)
        for batch_index, _batch_issues in enumerate(batches, start=1)
    }

    index_lines = [
        "# Release Issue Hygiene Draft Comment Batches",
        "",
        DRAFT_BATCH_GENERATED_MARKER,
        "These are review drafts only; the script does not write to GitHub.",
        "",
        f"- Non-ready watched issues: {len(issues)}",
        f"- Batch size: {batch_size}",
        f"- Batch files: {len(batches)}",
        "",
    ]

    if not batches:
        index_lines.extend(
            [
                "No draft comment batches needed.",
                "",
                "All watched release-impacting issues have an owner and a "
                "`Release decision:` note.",
            ]
        )
        (output_dir / "index.md").write_text(
            "\n".join(index_lines) + "\n",
            encoding="utf-8",
        )
        _prune_stale_generated_draft_batches(output_dir, active_batch_names)
        return (0, 0)

    index_lines.append("## Batches")
    index_lines.append("")
    for batch_index, batch_issues in enumerate(batches, start=1):
        batch_name = _batch_file_name(batch_index)
        first_ref = batch_issues[0].reference()
        last_ref = batch_issues[-1].reference()
        index_lines.append(
            f"- [{batch_name}]({batch_name}): {len(batch_issues)} issue(s), "
            f"{first_ref} through {last_ref}"
        )

        batch_lines = [
            f"# Release Issue Hygiene Draft Batch {batch_index:03d}",
            "",
            DRAFT_BATCH_GENERATED_MARKER,
            "These are review drafts only; the script does not write to GitHub.",
            "",
            f"Batch issue count: {len(batch_issues)}",
            "",
        ]
        for issue in batch_issues:
            batch_lines.extend(_draft_issue_lines(issue))
        (output_dir / batch_name).write_text(
            "\n".join(batch_lines),
            encoding="utf-8",
        )

    (output_dir / "index.md").write_text(
        "\n".join(index_lines) + "\n",
        encoding="utf-8",
    )
    _prune_stale_generated_draft_batches(output_dir, active_batch_names)
    return (len(issues), len(batches))


def _action_plan_row(issue: IssueSummary) -> str:
    labels = ", ".join(issue.labels) or "-"
    link = f"[#{issue.number}]({issue.url})" if issue.url else f"#{issue.number}"
    return (
        f"| {link} | {issue.title or '-'} | {labels} | "
        f"{', '.join(_missing_field_display_names(issue))} | "
        f"{'; '.join(_suggested_actions(issue))} |"
    )


def action_plan_to_text(report: HygieneReport) -> str:
    issues = issues_needing_draft_comments(report)
    lines = [
        "# Release Issue Hygiene Action Plan",
        "",
        ACTION_PLAN_GENERATED_MARKER,
        "This is a local, non-mutating remediation plan for watched issue hygiene failures.",
        "",
        "## Summary",
        "",
        f"- Open issues scanned: {report.scanned}",
        f"- Release-impacting watched issues: {len(report.release_impacting)}",
        f"- Non-ready watched issues: {len(issues)}",
        f"- Missing owner entries: {len(report.missing_owner)}",
        f"- Missing `Release decision:` entries: {len(report.missing_release_decision)}",
        f"- Status: {'READY' if report.ready else 'NOT READY'}",
        "",
    ]

    if report.warnings:
        lines.extend(["## Warnings", ""])
        lines.extend(f"- {warning}" for warning in report.warnings)
        lines.append("")

    if not issues:
        lines.extend(
            [
                "## Required Actions",
                "",
                "No action needed. All watched release-impacting issues have an owner and a `Release decision:` note.",
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            "## Required Actions",
            "",
            "| Issue | Title | Watched labels | Missing | Action |",
            "|-------|-------|----------------|---------|--------|",
        ]
    )
    lines.extend(_action_plan_row(issue) for issue in issues)
    lines.extend(
        [
            "",
            "## Completion Checklist",
            "",
            "- [ ] Assign a release owner or add an ownership label for every `owner` row.",
            "- [ ] Add a visible `Release decision:` note for every release-decision row.",
            "- [ ] Re-run `python3 scripts/release_issue_hygiene.py --fetch` or the same `--input` snapshot.",
            "",
        ]
    )
    return "\n".join(lines)


def _markdown_table_cell(value: object) -> str:
    return str(value).replace("\n", " ").replace("|", r"\|")


def _issue_link(issue: IssueSummary) -> str:
    return f"[#{issue.number}]({issue.url})" if issue.url else f"#{issue.number}"


def _joined_or_missing(values: tuple[str, ...]) -> str:
    return ", ".join(values) if values else "missing"


def _missing_field_names(issue: IssueSummary) -> str:
    return ", ".join(_missing_field_display_names(issue))


def _gap_audit_row(issue: IssueSummary) -> str:
    labels = ", ".join(issue.labels) or "-"
    cells = [
        _issue_link(issue),
        issue.title or "-",
        labels,
        _missing_field_names(issue),
        _joined_or_missing(issue.owner_evidence),
        _joined_or_missing(issue.release_decision_evidence),
    ]
    return "| " + " | ".join(_markdown_table_cell(cell) for cell in cells) + " |"


def _append_gap_audit_table(
    lines: list[str],
    issues: tuple[IssueSummary, ...],
    *,
    empty_message: str,
) -> None:
    if not issues:
        lines.extend([empty_message, ""])
        return

    lines.extend(
        [
            "| Issue | Title | Watched labels | Missing | Owner evidence | Release decision evidence |",
            "|-------|-------|----------------|---------|----------------|---------------------------|",
        ]
    )
    lines.extend(_gap_audit_row(issue) for issue in issues)
    lines.append("")


def gap_audit_to_text(report: HygieneReport, *, source: str) -> str:
    issues = issues_needing_draft_comments(report)
    lines = [
        "# Release Issue Hygiene Gap Audit",
        "",
        GAP_AUDIT_GENERATED_MARKER,
        (
            "This is a local, non-mutating audit artifact. It does not post, "
            "edit, label, close, or assign GitHub issues."
        ),
        "",
        "## Provenance",
        "",
        f"- Source: {source}",
        f"- Watched labels: {', '.join(report.counts)}",
        "- Watched label counts: "
        + ", ".join(f"{label}={count}" for label, count in report.counts.items()),
        f"- Open issues scanned: {report.scanned}",
        f"- Release-impacting watched issues: {len(report.release_impacting)}",
        f"- Non-ready watched issues: {len(issues)}",
        f"- Missing owner entries: {len(report.missing_owner)}",
        f"- Missing `Release decision:` entries: {len(report.missing_release_decision)}",
        f"- Status: {'READY' if report.ready else 'NOT READY'}",
        "",
    ]

    if report.warnings:
        lines.extend(["## Warnings", ""])
        lines.extend(f"- {warning}" for warning in report.warnings)
        lines.append("")

    lines.extend(["## Gap Matrix", ""])
    _append_gap_audit_table(
        lines,
        issues,
        empty_message=(
            "No owner or `Release decision:` gaps found for watched issues."
        ),
    )

    lines.extend(["## Owner Gaps", ""])
    _append_gap_audit_table(
        lines,
        report.missing_owner,
        empty_message="No owner gaps found for watched issues.",
    )

    lines.extend(["## Release Decision Gaps", ""])
    _append_gap_audit_table(
        lines,
        report.missing_release_decision,
        empty_message="No `Release decision:` gaps found for watched issues.",
    )

    return "\n".join(lines)


def _format_issue_list(title: str, issues: tuple[IssueSummary, ...]) -> list[str]:
    if not issues:
        return [f"{title}: none"]

    lines = [f"{title}: {len(issues)}"]
    for issue in issues:
        labels = ", ".join(issue.labels) or "-"
        suffix = f" ({issue.url})" if issue.url else ""
        lines.append(f"  - {issue.reference()} [{labels}]{suffix}")
    return lines


def _format_non_ready_issue_gaps(issues: tuple[IssueSummary, ...]) -> list[str]:
    if not issues:
        return ["Non-ready issue gaps: none"]

    lines = ["Non-ready issue gaps:"]
    for issue in issues:
        labels = ", ".join(issue.labels) or "-"
        suffix = f" ({issue.url})" if issue.url else ""
        missing = ", ".join(_missing_field_display_names(issue))
        actions = "; ".join(_suggested_actions(issue))
        lines.append(
            f"  - {issue.reference()} [{labels}] missing: {missing}; "
            f"action: {actions}{suffix}"
        )
    return lines


def report_to_text(report: HygieneReport, *, counts_only: bool) -> str:
    lines = [
        "Release issue hygiene",
        f"Open issues scanned: {report.scanned}",
        f"Release-impacting watched issues: {len(report.release_impacting)}",
        "Watched label counts:",
    ]
    lines.extend(f"  {label}: {count}" for label, count in report.counts.items())

    if report.warnings:
        lines.append("Warnings:")
        lines.extend(f"  - {warning}" for warning in report.warnings)

    if not counts_only:
        non_ready_issues = issues_needing_draft_comments(report)
        lines.append(f"Non-ready watched issues: {len(non_ready_issues)}")
        lines.extend(_format_non_ready_issue_gaps(non_ready_issues))
        lines.extend(_format_issue_list("Missing owner", report.missing_owner))
        lines.extend(
            _format_issue_list(
                "Missing Release decision",
                report.missing_release_decision,
            )
        )
        if report.ready:
            lines.append("Status: READY")
        else:
            non_ready = len(issues_needing_draft_comments(report))
            missing_fields = len(report.missing_owner) + len(
                report.missing_release_decision
            )
            lines.append(
                "Status: NOT READY "
                f"({non_ready} non-ready issue(s), {missing_fields} missing field(s))"
            )

    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Report release issue counts and verify read-only release-decision "
            "hygiene for urgent/P1/blocked/local-maximum issues."
        ),
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument(
        "--input",
        type=Path,
        help="Read mocked gh issue JSON from PATH, or '-' for stdin.",
    )
    source.add_argument(
        "--fetch",
        action="store_true",
        help="Run read-only gh issue list against the current repository.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=500,
        help="Maximum issues to fetch with --fetch (default: 500).",
    )
    parser.add_argument(
        "--counts-only",
        action="store_true",
        help="Only report watched label counts; do not fail on hygiene gaps.",
    )
    parser.add_argument(
        "--format",
        choices=("text", "json"),
        default="text",
        help="Output format (default: text).",
    )
    parser.add_argument(
        "--draft-comments",
        type=Path,
        metavar="PATH",
        help=(
            "Write non-mutating markdown draft guidance for missing owner or "
            "Release decision notes."
        ),
    )
    parser.add_argument(
        "--draft-comment-batches",
        type=Path,
        metavar="DIR",
        help=(
            "Write non-mutating markdown draft guidance batches for missing "
            "owner or Release decision notes under DIR."
        ),
    )
    parser.add_argument(
        "--action-plan",
        type=Path,
        metavar="PATH",
        help=(
            "Write a repeatable non-mutating markdown action plan for watched "
            "issue hygiene failures."
        ),
    )
    parser.add_argument(
        "--gap-audit",
        type=Path,
        metavar="PATH",
        help=(
            "Write a non-mutating markdown audit of watched issue owner and "
            "Release decision gaps."
        ),
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=25,
        metavar="N",
        help="Issues per --draft-comment-batches file (default: 25).",
    )
    return parser.parse_args(argv)


def source_description(args: argparse.Namespace) -> str:
    if args.fetch:
        return (
            "live read-only `gh issue list --state open "
            f"--limit {args.limit} --json {GH_JSON_FIELDS}`"
        )
    if str(args.input) == "-":
        return "stdin JSON snapshot"
    return f"input snapshot: {args.input}"


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    if args.limit <= 0:
        print("ERROR: --limit must be a positive integer", file=sys.stderr)
        return 2
    if args.batch_size <= 0:
        print("ERROR: --batch-size must be a positive integer", file=sys.stderr)
        return 2

    try:
        issues = fetch_issues(args.limit) if args.fetch else load_issues(args.input)
    except (OSError, ValueError, json.JSONDecodeError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    report = build_report(
        issues,
        limit=args.limit if args.fetch else None,
    )
    if args.draft_comments is not None:
        try:
            args.draft_comments.write_text(
                draft_comments_to_text(report),
                encoding="utf-8",
            )
        except OSError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Wrote draft comments: {args.draft_comments}", file=sys.stderr)
    if args.draft_comment_batches is not None:
        try:
            issue_count, batch_count = write_draft_comment_batches(
                report,
                args.draft_comment_batches,
                batch_size=args.batch_size,
            )
        except OSError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(
            "Wrote draft comment batches: "
            f"{args.draft_comment_batches} "
            f"({issue_count} issue(s), {batch_count} batch(es))",
            file=sys.stderr,
        )
    if args.action_plan is not None:
        try:
            args.action_plan.write_text(
                action_plan_to_text(report),
                encoding="utf-8",
            )
        except OSError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Wrote action plan: {args.action_plan}", file=sys.stderr)
    if args.gap_audit is not None:
        try:
            args.gap_audit.write_text(
                gap_audit_to_text(report, source=source_description(args)),
                encoding="utf-8",
            )
        except OSError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
        print(f"Wrote gap audit: {args.gap_audit}", file=sys.stderr)

    if args.format == "json":
        print(report_to_json(report))
    else:
        print(report_to_text(report, counts_only=args.counts_only), end="")

    if args.counts_only or report.ready:
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
